### ISSUE TITLE
Worker Count in Options is overridden and they are set to 0

### ISSUE THREAD

**Issue by Ironbell** [rebus-org/Rebus#1002]
Packages in Use

* Rebus Version=6.6.1
* Rebus.Microsoft.Extensions.Logging Version=2.0.0
* Rebus.Serilog Version=6.0.0
* Rebus.ServiceProvider Version=7.0.0
* Rebus.SqlServer Version=7.2.0

Framework: NET 6.0

-----------------------------------------

We just ported our project to .NET 6.0 and noticed that after the bus started, nothing was fetched from the queue. There were also no error messages. All we saw was what you would see with 0 workers:

![image](https://user-images.githubusercontent.com/9303244/146065086-039d6b08-cdaa-48f3-8aca-46a67940c461.png)

So I downloaded your project, referenced it directly instead from the nuget packages, set breakpoints here and there and saw that the worker count we set in the options was overridden to 0 in this method here
![image](https://user-images.githubusercontent.com/9303244/146063427-6f89509c-e354-4318-84d9-53c6e580ba53.png)

This is how we configure Rebus

![image](https://user-images.githubusercontent.com/9303244/146063632-5c08f0b1-ca23-4a97-a537-76251589d246.png)

The problem is that the set worker count from the options is set first and then the function inside the Create is called, leading to 0 workers. Are we configuring something in a wrong order, or is it a bug on your side? I could imagine that not many people upgraded to all these newest packages in this combination (DI, SQL Server and Rebus) and maybe it was just missed?

The workaround is to set the number of workers after the bus is created, here:

![image](https://user-images.githubusercontent.com/9303244/146064050-79abe5fc-f36c-49a6-be4b-a4431d159f4c.png)

But it is very ugly of course, as it should take the ones configured in the options.

Thanks for your response and thanks for your tool, we appreciate it.

**Comment by mookid8000** [comment]
It's because you need to call `.UseRebus()` on the `IServiceProvider` when you want the bus to start.

E.g. like
```csharp
host.Services.UseRebus();
```

The reason for this two-step procedure, is so you can control exactly when the bus is started. Of course it also means that you can forget to start it 🙂

**Comment by Ironbell** [comment]
Thanks for your help :)

That was it. It looks like we used it wrong for a very long time and it worked by just getting the service before,

as in host.Services.GetRequiredService<IBus>();

 as the Create() was called then. We didn't have to use UseRebus() at all before.  But that makes way more sense, much appreciated.
