### ISSUE TITLE
Newtonsoft.Json 13.0.1 dependency

### ISSUE THREAD

**Issue by kendallb** [rebus-org/Rebus#1005]
Is there a reason Rebus was upgraded to require the latest JSON library (13.0.1)? Not sure when it changed, but this will require everyone to upgrade to the latest (we are on 12.0.3). Probably not a big deal for us to upgrade, but wondering if this was intentional for some reason or if it can be reverted to what it was before (11.0.1)?

**Comment by kendallb** [comment]
System.Text.Json 5.0.0 => 6.0.0 also causes problems, because it then requires System.Runtime.CompilerServices.Unsafe 6.0.0 and for some whacky reason I always run into major problems trying to use 6.0.0 and get odd compiler warnings about bad resolving of 5.0.0. Can those both get reverted back?

**Comment by kendallb** [comment]
Looks like the depencies got changed trying to simplify things to .net standard 2.0 only, but that seems to bring in a ton of baggage for .net 4.5 and later (we are on 4.8 - cannot migrate off that yet due to not being able to migrate to asp.net core).

**Comment by mookid8000** [comment]
You're absolutely right 🙂 I've released Rebus 7.0.0-b02 now, where I've relaxed the nuggie dep requirements.

I can release a properly versioned Rebus as soon as we're sure this one works.

**Comment by kendallb** [comment]
Thanks!

**Comment by kendallb** [comment]
Ugh, any chance you can revert all the file scoped name changes and use of C# 10? We are still on VS 2019 and have not yet tested moving to 2022 so I cannot build the latest code :(
