### ISSUE TITLE
Writing Failures to the error queue

### ISSUE THREAD

**Issue by ikariw** [rebus-org/Rebus#1008]
Hi

We are handling retries manually, so have a config of
`
                    .Options(b => b.SimpleRetryStrategy(
                        errorQueueAddress: "Rebus_Errors",
                        maxDeliveryAttempts: 1,
                        secondLevelRetriesEnabled: true))
`

I then handle failed messages with a `public async Task Handle(IFailed<T> failedMessage)`  method, getting the defer count and working out whether to defer or whether it's reached our maximum number of tries for that message type.  if it's reached the maximum number of attempts then I can simply throw an exception from the `Handle(IFailed<T> failedMessage)` queue to write the message to the error queue.

However, according to https://github.com/rebus-org/Rebus/issues/858, instead of throwing an error, I should be able to `await _bus.Advanced.TransportMessage.Deadletter();` as of version 6.2.1.  We are using 6.4.1 but I do not get this option available.  Was this option removed and is throwing an exception the "correct" way to move a message to the error queue?

Thanks very much

**Comment by mookid8000** [comment]
Could you put a 
```csharp
using Rebus.Exceptions;
```
at the top of your file and see if it changes anything?

**Comment by ikariw** [comment]
> Could you put a
> 
> ```cs
> using Rebus.Exceptions;
> ```
> 
> at the top of your file and see if it changes anything?

Thank you - that's exactly what was needed :-)
