### ISSUE TITLE
Rebus Orchestrated with Datadog?

### ISSUE THREAD

**Issue by Claker** [rebus-org/Rebus#1009]
Hi,

Thanks for writing this amazing bus.

This is not an issue but I don't manage to find anything online about this and thought it would be a good place to ask.

I have 2 services talking through rebus+rabbitmq. All services and the messaging infrastructure(RabbitMq) are orchestrated using datadog. I want to trace a message end to end and so far I managed this 

Service1 => RabbitMQ.

I want to be able to trace this

Service1 => RabbitMq => Service2

Is there any example for this or do I need to do anything special to be able to push information from a Rebus Handler to Datadog? 
I know how to manually add tracing  for Datadog but but it simply doesn't work in rebus pipeline or handler. 

Thanks in advance,
Claudiu

**Comment by mookid8000** [comment]
Check out the wiki about [correlation IDs](https://github.com/rebus-org/Rebus/wiki/Correlation-ids) 🙂 

It means that all messages in the flow

Service1 => RabbitMq => Service2

will be automatically be provided with a correlation ID set to the message ID of each initial message from Service1.

Maybe you can put something together combined with this info about Rebus' message pipelines: https://github.com/rebus-org/Rebus/wiki/Extensibility#pipelines ?

**Comment by Claker** [comment]
Thanks ! 
In the meantime I started leveraging the middlewares in the pipeline but I didn't know about the first link with correlation IDs.
It is a great start and I am sure now that with some manual management of the ids also on datadog side I will be able to pass the ids and see what I need.
🥳

**Comment by mookid8000** [comment]
Would you be interested in reporting back here which results you end up with? If you're up for it, I'm thinking we could turn your work into an official Rebus.Datadog NuGet package?

**Comment by Claker** [comment]
Yes, I'll report back with all the details

**Comment by Claker** [comment]
Update.
I have found this example for RabbitMQ:
https://github.com/DataDog/dd-trace-dotnet/blob/master/tracer/samples/RabbitMQ.DistributedTracing/Send/Send.cs

I will try to convert this example to 1 IOutgoingStep and 1 IIncomingStep.

Question:
If I add a TransportMessage.Headers, Rebus in the background will convert the string to bytes right?

**Comment by Claker** [comment]
Ok, this is what I came up with.

```
[StepDocumentation("Adds datadog headers to outgoing messages")]
    public class DatadogTracingHeaderRebusStep : IOutgoingStep
	{
        private readonly string _exchangeName;
        private readonly string _rountingKey;

        public DatadogTracingHeaderRebusStep(string exchangeName, string rountingKey)
        {
            const string tagNotSetMessage = " not set for datadog tags";
            _exchangeName = string.IsNullOrWhiteSpace(exchangeName) ? tagNotSetMessage : exchangeName;
            _rountingKey = string.IsNullOrWhiteSpace(rountingKey) ? tagNotSetMessage : rountingKey;
        }

		public async Task Process(OutgoingStepContext context, Func<Task> next)
		{
			using (var scope = Tracer.Instance.StartActive("DatadogTracingHeaderRebusStep.Process"))
			{
				var message = context.Load<Message>();
				var headers = message?.Headers;
				var activeSpan = scope.Span;

				if (headers != null)
				{
					headers[HttpHeaderNames.TraceId] = activeSpan.TraceId.ToString();
					headers[HttpHeaderNames.ParentId] = activeSpan.SpanId.ToString();
					headers[HttpHeaderNames.SamplingPriority] = activeSpan.GetTag(Tags.SamplingPriority);

					activeSpan.ResourceName = "RebusDirect";
					activeSpan.SetTag(Tags.SpanKind, SpanKinds.Producer);
					activeSpan.SetTag("amqp.exchange", _exchangeName);
					activeSpan.SetTag("amqp.routing_key", _rountingKey);
				}

				await next().ConfigureAwait(false);
			}
		}
```


```
[StepDocumentation("Initializes end to end tracing for incoming messages")]
	public class DatadogTracingWrapperStep : IIncomingStep
	{
		public async Task Process(IncomingStepContext context, Func<Task> next)
        {
            var message = context.Load<TransportMessage>();

            if (message == null)
            {
                await next().ConfigureAwait(false);
                return;
            }

            var traceId = GetTraceId(message);

            if (traceId == null)
            {
                await next().ConfigureAwait(false);
                return;
            }

            SpanCreationSettings spanSettings = GenerateSpanSettings(message, traceId);

            using (var scope = Tracer.Instance.StartActive("DatadogTracingWrapperStep.HandlerWrapper", spanSettings))
            {
                await next().ConfigureAwait(false);
            }
        }

        private static SpanCreationSettings GenerateSpanSettings(TransportMessage message, ulong? traceId)
        {
            var spanId = GetSpanId(message);
            var samplingPriority = GetSamplingPriority(message);

            var spanSettings = new SpanCreationSettings()
            {
                FinishOnClose = true,
                Parent = new SpanContext(traceId, spanId, samplingPriority),
            };
            return spanSettings;
        }

        private static ulong GetSpanId(TransportMessage message)
        {
            var parentSpanIdExists = message.Headers.TryGetValue(HttpHeaderNames.ParentId, out string parentSpanId);
            if (parentSpanIdExists && ulong.TryParse(parentSpanId, out ulong parentSpanIdLong))
            {
                return parentSpanIdLong;
            }

            return GenerateSpanId(19);
		}

		private static ulong? GetTraceId(TransportMessage message)
		{
			var traceIdExists = message.Headers.TryGetValue(HttpHeaderNames.TraceId, out string traceId);
			if (traceIdExists && ulong.TryParse(traceId, out ulong traceIdLong))
			{
				return traceIdLong;
			}

			return null;
		}

		private static SamplingPriority? GetSamplingPriority(TransportMessage message)
		{
			var samplingPriorityExists = message.Headers.TryGetValue(HttpHeaderNames.SamplingPriority, out string samplingPriority);
			if (samplingPriorityExists && Enum.TryParse(samplingPriority, out SamplingPriority samplingPriorityType))
			{
				return samplingPriorityType;
			}

			return null;
		}

		private static ulong GenerateSpanId(int length)
		{
			var random = new Random();
			string s = string.Empty;
			for (int i = 0; i < length; i++)
				s = string.Concat(s, random.Next(10).ToString());
			return ulong.Parse(s);
		}
	}
```

**Comment by Claker** [comment]
By adding these 2 in the pipeline, they are being connected to each other so the Trace in the Datadog UI is showing them as 1 trace, 2 different spans. This is the first cut, it works but I did not do TDD unfortunately :)

**Comment by Claker** [comment]
We can inject a logger as well

**Comment by Claker** [comment]
By adding these 2 in the pipeline, the spans are being connected to each other so the Trace in the Datadog UI is showing them as 1 trace, 2 different spans. This is the first cut, it works but I did not do TDD unfortunately :)

We can inject a logger as well.

I now have 1 version for Datadog agent v1 and one for Datadog v2. Very similar to the above but a bit cleaned up and adapted to each Datadog agent version.

You can give your input and then I can put them in a class library?

So far I encountered 1 issue: Testability. The datadog tracer is statically accessible which makes unit testing a bit hard.

**Comment by Claker** [comment]
Hi @mookid8000 .

I have created a package with the 2 steps and published it to nuget (Haven't yet wrote the Readme and details but I will).

**Repo**
https://github.com/e-conomic/Rebus.Datadog.Tracing

**Nuget**
https://www.nuget.org/packages/Rebus.Datadog.Tracing/

- Added logging
- Added unit tests

It can still be cleaned a bit but from here on I am not sure how to go about it as you mentioned to possibly make it official package. Is that it? 

Claudiu

**Comment by Claker** [comment]
I added description too.
The package is .Net Standard 2 with support for Datadog agent `2.2.0` only (at the moment). If this ends up to be useful, I can add one version specific to each Datadog agent version
