### ISSUE TITLE
Feature suggestion - update failed message with an exception even before reaching maxDeliveryAttempts

### ISSUE THREAD

**Issue by xhafan** [rebus-org/Rebus#1011]
When a message handling is failing, and `maxDeliveryAttempts` is reached, the message is forwarded to the error queue and the exception message is added to the message. This is how I understand it works.

Now, I have two AWS ECS instances handling messages from AWS SQS, `maxDeliveryAttempts` set to 5, and a failing message is potentially handled 5x to 10x (more info why [here](https://stackoverflow.com/questions/61799579/rebus-with-sqs-a-failed-message-is-handled-by-2-consumers-more-times-than-numb)). When I configure a dead-letter queue in SQS with `Maximum receives` set to 5, a failing message is always handled maximum 5x, for example 3x by ECS instance 1 and 2x by ECS instance 2, and after that the message is moved to the dead-letter queue by SQS, but without the exception message as it didn't reach `maxDeliveryAttempts` by any ECS instance.

It would be handy to update the failed message by an exception message immediately after the first handling, so I would get maximum 5 handling attempts, and would get the exception message in a dead-letter queue. I understand this might not be possible due to various reasons - I can think of the exception message being added to the message only when forwarded to the error queue, but not possible to update it in the original queue, and one would also need to clear the exception message when the handling is successful.

**Comment by mookid8000** [comment]
> (..) It would be handy to update the failed message by an exception message immediately after the first handling, so I would get maximum 5 handling attempts (...)

Yes that would have been neat, but the problem is that the message is rolled back into the queue (i.e. it is NACKed) when it fails, and so it cannot have anything added to it.

The headers with the exception details are not added until the message is received the 6th time, and then it gets immediately forwarded to the dead-letter queue.

**Comment by xhafan** [comment]
Ok, cool I thought it might not be possible.
