### ISSUE TITLE
activator required for one way clients

### ISSUE THREAD

**Issue by riezebosch** [rebus-org/Rebus#1013]
Would it make sense to include an activator stub for one-way clients since you won't be activating anything?

```csharp
public class EmptyActivator : IHandlerActivator
{
    Task<IEnumerable<IHandleMessages<TMessage>>> IHandlerActivator.GetHandlers<TMessage>(TMessage message, ITransactionContext transactionContext) => 
        Task.FromResult(Enumerable.Empty<IHandleMessages<TMessage>>());
}
```

So you can do without disposing:
```csharp
Configure.With(new EmptyActivator())
    .Transport(t => t.UseRabbitMqAsOneWayClient(_container.ConnectionString))
    .Start();
```

**Comment by mookid8000** [comment]
Yeah, I guess that would be nice enough.

I mean, there's something about the `Configure.With(...)` thing that I've been wanting to change for a long time, but maybe it'll go away by itself because IoC containers seem to be converging towards extension methods as the preferred APIs, e.g. like

```csharp
// Microsoft DI
services.AddRebus(
    configure => configure
        .Transport(t => t.(...))
);

// Autofac
builder.RegisterRebus(
    configure => configure
        .Transport(t => t.(...))
);

// SimpleInjector
container.RegisterRebus(
    configure => configure
        .Transport(t => t.(...))
);
```

Maybe if it was possible to do something like 

```csharp
using var bus = Configure.Client()
    .Transport(t => t.UseAzureServiceBusAsOneWayClient(..))
    .Start();
```

and then have the configuration be validated somehow, to check that a one-way transport was in fact chosen in the `.Transport(...)` portion of the configuration.

**Comment by riezebosch** [comment]
One place I could use this is for a driver in integration and/or unit tests. I've seen you've done a decent job on abstractions and interfaces and testing support with the FakeBus in the testing library. But still, I may want to validate my assumptions in a real-world scenario. But I figured that having an activator stub would fit more scenarios where one-way clients are involved.

**Comment by mookid8000** [comment]
Rebus 7.0.0-b05 adds the ability to go
```csharp
var bus = Configure.OneWayClient()
    .Transport(t => t.Use(..)AsOneWayClient(...))
    .Start();
```
(including validation that the chosen transport was in fact configured to be a one-way client)

**Comment by riezebosch** [comment]
When released can update the samples:
* https://github.com/rebus-org/RebusSamples/blob/master/PubSub/PubSub.Publisher/Program.cs#L17

And the wiki:
* https://github.com/rebus-org/Rebus/wiki/Different-bus-modes#configuration-options-and-one-way-clients
* https://github.com/rebus-org/Rebus/wiki/How-to-create-integration-tests
