### ISSUE TITLE
hypothesist for integration tests

### ISSUE THREAD

**Issue by riezebosch** [rebus-org/Rebus#1014]
After developing the 3rd framework-specific implementation of a blocking test handler, I managed to abstract that into a dedicated library. On top of that, I added framework-specific adapters to make the future assertions lean, self-describing, and with nice error messages.

```csharp
var hypothesis = Hypothesis
    .For<TMessage>()
    .Any(m => m == ...);

using var activator = new BuiltinHandlerActivator()
    .Register(hypothesis.AsHandler);
```

```csharp
await hypothesis
    .Validate(TimeSpan.FromSeconds(2));
```

This would replace the `ManualResetEvent` logic described in the [wiki](https://github.com/rebus-org/Rebus/wiki/How-to-create-integration-tests).

Check out the [hypothesist library](https://github.com/riezebosch/hypothesist/) and the [Rebus adapter](https://github.com/riezebosch/hypothesist/tree/main/Rebus).

I'd be happy to incorporate it into the wiki and use it in an upcoming PR for a scenario I would like to suggest.

**Comment by mookid8000** [comment]
While this no doubt looks pretty neat, I am afraid it could add a layer of confusion to newcomers as to where the boundaries are between Rebus and not-Rebus.

It's a clear goal for Rebus to be welcoming to new users, and so I think it's very important that the code demonstrated relies mostly on Rebus combined with pure .NET BCL, and much less important that it's short.

If you like, you can add a mention and a link to Hypothesist to the wiki page above, but I'd like the example with `ManualResetEvent` to stay intact. 

I hope this makes sense to you. 🙂 

Sorry for taking so long to process this, btw.
