### ISSUE TITLE
Competing-Consumer pattern with Transport message forwarding technique

### ISSUE THREAD

**Issue by Aghlara** [rebus-org/Rebus#1029]
Hi,

I have been playing with sample "SqlScaleout" and trying to adapt the round-robin to multiple consumers (competing-consumer pattern) and cannot figure out how it can be done.

I am trying to create something like this
![image](https://user-images.githubusercontent.com/5187409/159201339-4854e060-c602-48b4-aff9-5319c20196df.png)

The above image is copied from https://stackoverflow.com/questions/50256664/how-to-implement-a-competing-consumer-patter-with-rebus-on-msmq)

I have done this on the producer app, but have no luck!
```C#
var consumerQueueNames = new [] {
    "worker1",
    "worker2",
    "worker3"
};

var currentConsumerIndex = 0;

Configure.With(...)
    .Transport(t => t.UseSqlServerAsOneWayClient(new SqlServerTransportOptions("server=.\\sqlexpress; initial catalog=rebus; integrated security=true")))
    .Routing(r => {
        r.AddTransportMessageForwarder(async transportMessage => {
            var index = Interlocked.Increment(ref currentConsumerIndex) 
                        % consumerQueueNames.Length;

            var destination = consumerQueueNames[index];

            return ForwardAction.ForwardTo(destination);
        });
    })
    .Start();
```

Is it possible to create a working application based on SqlScaleout, and identify which consumer is the best choice to process a message at runtime rather than statically biding please?

**Comment by mookid8000** [comment]
The configuration you posted above would be sitting in the Router (at least that's how I envisioned it). This way, the router's queue would be the one the producer(s) would send to to have their work processed.

And no, there's no "intelligent" way of selecting which worker to forward to. The implementation is simple round-robin forwarding, so it will distribute work evenly provided that the work contained in the messages is uniformly distributed.

Last thing though: SQL server as a transport is actually pretty good at handling the competing consumers pattern. Before building the more advanced routing solution, I suggest you try running with multiple consumer instances simply consuming messages off of the same queue. 🙂 

I hope that makes sense! 😁

**Comment by Aghlara** [comment]
I understand that is the producer model, thanks for confirming. Here is my producer model:
```C#
var consumerQueueNames = new[] {
    "worker1",
    "worker2",
    "worker3"
};
var currentConsumerIndex = 0;
using var bus = Configure.OneWayClient()
    .Logging(l => l.ColoredConsole(LogLevel.Warn))
    .Transport(t => t.UseSqlServerAsOneWayClient(new SqlServerTransportOptions("server=.\\sqlexpress; initial catalog=rebus; integrated security=true")))
    .Routing(r =>
    {
        r.AddTransportMessageForwarder(async transportMessage =>
        {
            var index = Interlocked.Increment(ref currentConsumerIndex) % consumerQueueNames.Length;

            var destination = consumerQueueNames[index];

            return ForwardAction.ForwardTo(destination);
        });
    })
    .Start();

var numberOfJobs = 10;
Console.WriteLine("Publishing {0} jobs", numberOfJobs);
var sendTasks = Enumerable.Range(0, numberOfJobs)
    .Select(i => new Job(i))
    .Select(job => bus.Send(job))
    .ToArray();

Task.WaitAll(sendTasks);
```

I removed the the `r.TypeBased().MapAssemblyOf<Job>(w);` from producer because I want to use `AddTransportMessageForwarder` and `ForwardAction.ForwardTo(destination)`. I need to resolve the destination at runtime, based on some business criteria. round-robin is just a simple example to achieve this destination resolving at runtime.

On the producer I get the exception below:
```
System.AggregateException: 'One or more errors occurred. (Cannot get destination for message of type Messages.Job because it has not been mapped! 
You need to ensure that all message types that you intend to bus.Send or bus.Subscribe to are mapped to an endpoint - it can be done by calling .Map<SomeMessage>(someEndpoint) or .MapAssemblyOf<SomeMessage>(someEndpoint) in the routing configuration.) (Cannot get destination for message of type Messages.Job because it has not been mapped! 
```
The exception makes sense, but don't know how to resolve it without mapping to a type and Send.

**Comment by mookid8000** [comment]
You can either
```csharp
await bus.SendLocal(...);
```
to send to the sender's own input queue, or you can specify the destination queue explicitly via the advanced API:
```csharp
await bus.Advanced.Routing.Send(queueName, message);
```
