### ISSUE TITLE
How to setup rebus to manage messages with no rebus specific headers and $type

### ISSUE THREAD

**Issue by sabbadino** [rebus-org/Rebus#1039]
context : ASB 
I would like to process messages send by an external system that does not put type info in headers or $type in body 

It's fine for me (obviously) to have IHandlemessage<> not know the type and provide me just the raw body payload (String or byte array) .. 
I read that I can subscribe to a topic directly with bus.Advanced.Topics.Subscribe("whatever");
but it's not clear to me how to implement a IHandlemessage<?> that gets the raw messages in that topic.
thanks

**Comment by sabbadino** [comment]
Definitely, thanks

**Comment by sabbadino** [comment]
Supposing i use the same bus setup for rebus compliant and rebus not compliant messages .. and i register my custom deserializer , how  can i "fall back" to built in deserializer if i see the message has the proper rebus headers ?

Thanks

**Comment by mookid8000** [comment]
You can decorate Rebus' default serializer by using the `Decorate<T>` method instead:

```csharp
services.AddRebus(
	configure => configure
		.(...)
		.Serializer(s => s.Decorate(c => new MyCustomSerializer(c.Get<ISerializer>())))
);
```
thus injecting Rebus' default serializer. This way, your decorator can delegate serialization/deserialization to the default serializer when it wants to.

**Comment by mookid8000** [comment]
Btw I recomment you wrap your Rebus customization code in an appropriate extension method, e.g. like
```csharp
public static class MyCustomSerializerConfigurationExtensions
{
	public static void EnableMyCustomSerializer(this StandardConfigurer<ISerializer> configurer)
	{
		configurer.Decorate(c => {
			var defaultRebusSerializer = c.Get<ISerializer>();
			
			return new MyCustomSerializer(defaultRebusSerializer)
		});
	}
}
```
and then your configuration code becomes pretty like this:
```csharp
services.AddRebus(
	configure => configure
		.(...)
		.Serializer(s => s.EnableMyCustomSerializer())
);
```
🤩

**Comment by sabbadino** [comment]
Fantastic, as always, thanks a lot
