### ISSUE TITLE
How to unsubscribe when the host is shutting down

### ISSUE THREAD

**Issue by EvgenyGrishnov** [rebus-org/Rebus#1040]
Good day! I have a question on how to unsubscribe Rebus instance from broker (rabbit mq, ...) when the service is shutting down. 

Use case: some service has CancellationToken.IsCancellationRequested from k8s to shut down gracefully and now it must unsubscibe itself from a broker and only finish processing buffered messages but do not take new ones from broker.

**Comment by mookid8000** [comment]
Since this is a rather uncommon use case, there's no built-in way for Rebus to do it. 

But since you're using RabbitMQ, you can use its "auto-delete queues" feature (see here: https://www.rabbitmq.com/queues.html ) to do it. You can enable that with Rebus by doing something like this:

```csharp
services.AddRebus(
	configure => configure
	   .Transport(t => t.UseRabbitMq(connectionString, "my-auto-delete-queue-name")
	        .InputQueueOptions(o => o.SetAutoDelete(autoDelete: true)))
	   .(...)
);
```


This will make the RabbitMQ broker delete the queue, when the subscriber shuts down.


I'm curious to know though, why you are using message queues with durable messages, but your subscriber doesn't care about messages enough to want those published while it's not running?

**Comment by EvgenyGrishnov** [comment]
Hmmmm...  Maybe I'am wrong but I thought that this use case is quite common. I give example of what I mean. There is one instance of service A and two instances of service B in k8s.  Service A is a publisher. The message can be processed by any of instances of service B. Single message processing time is about 5 minutes. Now one of instances of service B is going down for some reason (maybe will be moved to the other node). It means that instance of B can continue to process messages even though it is marked as "terminate your stuff" by k8s.  So there can be situation where message will be lost - that B instance will not have time to process it. Maybe there is an option like: "if message handler won't complete operation successfully then message is returned into queue and can be processed by other instance of Rebus"

**Comment by mookid8000** [comment]
If you simply deploy multiple instances of service B and they share an input queue (i.e. they're ["competing consumers"](https://www.enterpriseintegrationpatterns.com/CompetingConsumers.html)) then everything will work just fine, and work will be distributed evenly among them.

You will never (as in: never ever!) lose messages with Rebus!

Messages are only actually removed from a queue once they have been successfully processed. If something goes wrong during message processing - anything! - e.g. an exception, endpoint shutting down, etc etc - then messages that have not been fully handled(*) will not be ACKed and will eventually show up in the queue again.

---

(*) Rebus gives message handlers 1 minute to finish what they're doing when the bus is disposed. During this time, no new messages will be received, only message handlers currently at work will be doing something.

**Comment by mookid8000** [comment]
Did you figure this out? (closing for now - feel free to continue the talk in here if you like 🙂 )
