### ISSUE TITLE
Subscribe based on properties of a type

### ISSUE THREAD

**Issue by appcodr** [rebus-org/Rebus#1041]
Currently with Rebus we can subscribe to a message based on type.But we have a scenario where there are multiple different messages that has the type but has different commands inside of it. So is there an option with Rebus to subscribe based on a property inside message(like using a lambda) or a sub type?

`Configure.With(someContainerAdapter)
    .Logging(l => l.Serilog())
    .Transport(t => t.UseMsmq("myInputQueue"))
    .Routing(r => r.TypeBased().MapAssemblyOf<SomeMessageType>("anotherInputQueue"))
    .Start();`

**Comment by mookid8000** [comment]
No... but you can base your publish/subscribe logic on topics, which are strings that you have full control of.

E.g. a subscriber can
```csharp
var topics = bus.Advanced.Topics;

await topics.Subscribe("topic-a");
await topics.Subscribe("topic-b");
await topics.Subscribe("topic-c");
```

and then the publisher can
```csharp
var topics = bus.Advanced.Topics;

await topics.Publish("topic-a", new SomeMessageThatContainsA());
await topics.Publish("topic-a", new AnotherMessageThatContainsA());

await topics.Publish("topic-b", new SomeMessageThatContainsB());
await topics.Publish("topic-b", new AnotherMessageThatContainsB());
```

thus making it completely independent from the message type.

Maybe that could work for you? 🙂
