### ISSUE TITLE
Poison handling for stackoverflow exceptions

### ISSUE THREAD

**Issue by zlepper** [rebus-org/Rebus#1044]
I'm going to preface with that I know this is going to be a pain in the Butt to handle, and possibly impossible. 

Sometimes we write some bad code, that ends up causing a StackOverflow exception. Sadly this kind of exception causes the entire CLR process to abort, with no way to handle the exception. And the moment the process starts again, it gets the bad message, and promptly crashes. 

I don't have a really good idea for how to handle this, since it seems like it is not possible to mutate a message in RabbitMQ without putting it back as an entirely new message, in which case it would still be impossible to know if the message if it's because Rebus is retrying the message or if this is still the first time Rebus is attempting. 

Right now the only way we can recover a system that does this is by logging in to RabbitMQ, and removing the bad message manually.

Assume the following really extremely bad code:
```c#

public class Program
{
    
    public class MyMessage
    {

        public void CallSelf()
        {
            CallSelf();
        }
    }

    
    public static async Task Main(string[] args)
    {
        const string connectionString = "amqp://user:passw0rd@localhost/dev";

        var subscriberTask = Task.Run(async () =>
        {
            using var activator = new BuiltinHandlerActivator();
            activator.Handle<MyMessage>(m =>
            {
                Console.WriteLine("Got MyMessage message");
                m.CallSelf();
                return Task.CompletedTask;
            });

            var subscriber = Configure.With(activator)
                .Transport(t => t.UseRabbitMq(connectionString, "subscriber"))
                .Start();

            await subscriber.Subscribe<MyMessage>();

            Console.WriteLine("Subscriber started");
    
            Console.WriteLine("Press ENTER to quit");
            Console.ReadLine();
        });

        var publisherTask = Task.Run(async () =>
        {
            using var activator = new BuiltinHandlerActivator();
        
            var publisher = Configure.With(activator)
                .Transport(t => t.UseRabbitMq(connectionString, "publisher"))
                .Start();
        
            await publisher.Publish(new MyMessage());
            Console.WriteLine("Publisher started");
        });

        await publisherTask;
        await subscriberTask;

    }
}

```

**Comment by mookid8000** [comment]
Unfortunately, as you're already hinting at, [it's not possible for the CLR to catch a `StackOverflowException`](https://docs.microsoft.com/en-us/dotnet/api/system.stackoverflowexception?view=net-6.0#remarks).

The best you can do in that case is probably to detect the process crash, and then go correct the bug, or make the code behave differently somehow - e.g. by ignoring the problematic message by its ID and then carry out whichever manual work needs to be done.
