### ISSUE TITLE
thread names used by workers

### ISSUE THREAD

**Issue by AzizDZH** [rebus-org/Rebus#1047]
Hi
I'm using rebus 6.6.4.0, Rebus.RabbitMq 7.3.5.0
I'm trying to identify each thread in messagehandler by their names. I thought that they are always named by default as Rebus 1 worker 1, but in practice I see that many threads doesn't have names and as I understand threads got from thread pool which could have any ManagedThreadId and no name already. 
In my use case I want to identify one worker to allow it handle the message type while other workers do Failfast.
so is there is way to do that?

Thanks

**Comment by mookid8000** [comment]
Hi @AzizDZH , as you've correctly observed, Rebus will in most cases do most of the work on thread pool threads. It will initiate the initial receive operation on a dedicated, named Rebus worker thread, but after the first `await` – which is often the receive operation on the transport – work will continue on thread pool threads.

If you tell me more about your use case, then maybe I can help you.
