### ISSUE TITLE
Auto-correlation when doing request/reply from sagas

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#105]
When a saga sends a request that warrants a reply, a new header could attach the saga ID to the transport message. And then, if `bus.Reply` was smart enough, it would attach the header to the reply.

And then, if the saga lookup code was smart enough, it would be able to detect the header and do the saga lookup based on the header. That would be an awesome feature.

So, how do we detect when a saga wants to do request/reply?

Perhaps by implementing a new interface derived off of `IHandleMessages<TReply>`: `ICorrelateMessages<TRequest, TReply>` which would make Rebus automatically attach the saga id to sent messages of type `TReqest`.

That would actually be pretty elegang. Or maybe there's an even better way?

**Comment by rosieks** [comment]
@mookid8000 Does it still work in Rebus 3.0? I defer message from my saga and when it goes back I receive such exception: 

    System.ArgumentException: Could not find any correlation properties for message Rebus1.Timeout and saga data Rebus1.MySagaData`

**Comment by mookid8000** [comment]
unfortunately, no – you need to explicitly add a correlation property for the `Timeout` type
