### ISSUE TITLE
DataBus API streaming issue.

### ISSUE THREAD

**Issue by k-best** [rebus-org/Rebus#1053]
When i call 
var attachment = await bus.Advanced.DataBus.CreateAttachment(source);
it requires from me to pass stream inside. But if i generate data for this stream it means that i should have whole data loaded in memory at once. 
May be it is better to have additional CreateAttachment method that will return stream to pass data into (and it can pass it into storage in streaming manner)?

**Comment by mookid8000** [comment]
> it requires from me to pass stream inside. But if i generate data for this stream it means that i should have whole data loaded in memory at once.

There's many things one can misunderstand about streams, and I might be wrong about this... but shouldn't this work?

```csharp
using var source = File.OpenRead(pathToBigFile);

// now stream the big file into data bus storage and get a claim check for it
var attachment = await databus.CreateAttachment(source);

// do stuff with the attachment
```

**Comment by k-best** [comment]
Look, CreateAttachment method calls inside _dataBusStorage.Save, which expect that at this moment stream is fully completed. If we consider serialization scenario, that means whole data should be already serialized in memory instead of serializing in streaming manner directly into storage.
    Look at example with FileSystemDataBusStorage. Suppose i have some object of decent size. I want to put it into FileSystemDataBus. 
    How it works now:
    I have to open MemoryStream, serialize whole object into this stream and flush (at the moment i have whole serialized data in memory) and then call CreateAttachment, which open FileStream and copy my memory stream into it.
    What i suggest:
    I call some method, for example "StartCreateAttachment", that opens FileStream and return it to me. I serialize my object into this stream and call another method, for example "EndCreateAttachment", that close stream, do other work and return me instance of Attachment class to pass it into message.
In this case i don't have whole serialized object in memory.

**Comment by mookid8000** [comment]
> CreateAttachment method calls inside _dataBusStorage.Save, which expect that at this moment stream is fully completed. (...)

This is the part I don't understand – what do you mean when you say that it "expects that at this moment the stream is fully completed?"

Isn't it possible to pass a newly opened stream to it that has not had a single byte read yet, by doing what I am showing here?

```csharp
// get stream from somewhere 
using var source = File.OpenRead(pathToBigFile);
// or an Azure blob
await using var source = await blob.OpenReadAsync();

// now stream the big file into data bus storage and get a claim check for it
var attachment = await databus.CreateAttachment(source);

// do stuff with the attachment
```

Which kind of stream would you like to create an attachment out of?

**Comment by k-best** [comment]
Just try different thing: Create pretty large array of guids and put it into databus. You will see the problem.

**Comment by mookid8000** [comment]
Which kind of stream would you like to create an attachment out of?

**Comment by mookid8000** [comment]
Hi @k-best , I never understood what the problem was here.

Could you post some code that illustrates what you are trying to achieve?
