### ISSUE TITLE
Modifying headers with RebusBeforeMessageHandled

### ISSUE THREAD

**Issue by woeterman94** [rebus-org/Rebus#1061]
I'm trying to alter the headers of an incoming message with the RebusBeforeMessageHandled event:

```
        public void RebusBeforeMessageHandled(IBus bus, Dictionary<string, string> headers, object message, IncomingStepContext context, MessageHandledEventHandlerArgs args)
        {
            
            headers["my-test"] = "test";
        }
```

```
...
                }).Events(e =>
                {
                    e.BeforeMessageSent += rebusEventHandler.RebusBeforeMessageSent;
                    e.BeforeMessageHandled += rebusEventHandler.RebusBeforeMessageHandled;
                })
```

However when I look at my headers in my handler (messageContext.Headers) the header is gone.

How can we modify the headers in the RebusBeforeMessageHandled event?

**Comment by woeterman94** [comment]
I wanted to note that adding new headers with the BeforeMessageSent event works fine.


```
        public void RebusBeforeMessageSent(IBus bus, Dictionary<string, string> headers, object message, OutgoingStepContext context)
        {

             //…

            var messageIdentity = _mijnIdentityContext.CurrentIdentity;

            var messagingIdentityJson = JsonConvert.SerializeObject(messageIdentity);
            headers.Add("x-mijn -identity", messagingIdentityJson);
        }
```

**Comment by mookid8000** [comment]
OK I can see how this can be a little bit confusing!

The thing is this: When you access `IMessageContext`, you can access the headers of the incoming message in no less than three pretty obvious ways:

1. `messageContext.TransportMessage.Headers` (accesses the headers of the incoming transport message)
2. `messageContext.Headers` (probably the most obvious way, but it's just a shorthand for (1))
3. `messageContext.Message.Headers` 👈 this is the one!

The thing is this: While Rebus will in most cases deserialie the incoming message (the "transport message", i.e. just headers and a `byte[]`) into a .NET object for you to work with using the chosen serializer, this is not always the case.

Therefore, Rebus has a distinction between "transport message" (which is the opaque payload taken out of the queue, modeled as `(Dictionary<string, string>, byte[])`) and the much more friendly "logical message" (which is whatever .NET object Rebus' serializer makes out of the payload, comes as `(Dictionary<string, string>, object)`.

The headers passed to the `BeforeMessageHandled` event come from the logical message. They're **a copy** of the headers from the transport message, but depending on the steps in the incoming pipeline, they can be different (e.g. when you're using encryption, message compression, etc.)

Therefore, you'll need to explicitly go for the logical message headers in your handler, accessing them via `messageContext.Message.Headers`.

I know this might be a little bit confusing... I hope I made just a little bit of sense of myself 🙂
