### ISSUE TITLE
Test project will not compile as it depends on Hypothesist.Rebus?

### ISSUE THREAD

**Issue by kendallb** [rebus-org/Rebus#1065]
It references this package, which brings in Rebus from NuGet. So it will not work because the project already has a local project reference to the Rebus project? Not entirely sure how this is compiling for you?

https://www.nuget.org/packages/Hypothesist.Rebus/

**Comment by kendallb** [comment]
Ok odd. I removed the package and it failed to build just the OneWay.cs file. But then when I reverted all that it then worked? Seems like it works if it's been built or something? The lines in the project file are like this:

```
	<ItemGroup>
		<ProjectReference Include="..\Rebus\Rebus.csproj" />
		<ProjectReference Include="..\Rebus.Tests.Contracts\Rebus.Tests.Contracts.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Hypothesist.Rebus" Version="2.0.30" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.4.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
		<PackageReference Include="NUnit" Version="3.13.3" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.3.0" />
	</ItemGroup>
```

So the Rebus dependency from the Hypothesist.Rebus conflicts with the project reference. I am not sure why it builds for me now.

**Comment by kendallb** [comment]
Even did a full clean and it still builds? Odd.

**Comment by mookid8000** [comment]
I've removed the Hypothesist dependency, because as you've correctly observed, it creates a circular dependency.
