### ISSUE TITLE
Check options for delaying initialization

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#1068]
In some cases, it can be nice to be able to exert more control over when Rebus runs its initialization code.

E.g. when people are running RabbitMQ in dockerized environments, issues like this come up: https://github.com/rebus-org/Rebus.RabbitMq/issues/98

While it can be solved by disabling the transport's own initialization routine, this is suboptimal, as it puts more work on the developer. Therefore, it COULD be neat, if Rebus could somehow delay its initialization.

This might be doable in Rebus itself. Or maybe, because of the capabilities of "the old initializer"(1), it's only a problem when using Rebus.ServiceProvider (because of its tight integration with the generic host).

Figure out what's best 😉 

---
(1) Instead of calling `Start()` at the one, you can call `Create()` to get an `IBusStarter`, and THEN you can call `Start()` when you want. I'm just not sure whether `Create()` will actually connect to brokers in most cases anyway, which does not help solve this problem.

**Comment by zlepper** [comment]
Just fyi, the ServiceProvider integration only calls Create, however that is enough to cause the issue here :)

**Comment by mookid8000** [comment]
> Just fyi, the ServiceProvider integration only calls Create, however that is enough to cause the issue here :)

thanks...🙄 😅

**Comment by zlepper** [comment]
> > Just fyi, the ServiceProvider integration only calls Create, however that is enough to cause the issue here :)
> 
> thanks...🙄 😅 

Always happy to be the bearer of bad news ;)

**Comment by mookid8000** [comment]
> Always happy to be the bearer of bad news ;)

😆

**Comment by ldeluigi** [comment]
It would be useful to allow Rebus to be programmatically:
* created
* started
* paused
* resumed
* stopped

This would, on one hand, allow user to customize when Rebus runs its initialization code. On the other hand, it would be also possible to "pause" rebus between integration tests, so that there aren't ongoing background processes while a db reset script like [Respawn](https://github.com/jbogard/Respawn) is running.

**Comment by mookid8000** [comment]
After having had this issue float around for a while, I've come to the conclusion that you should start your message broker before you start the things that depend on the message broker.

Since this might not always be possible, you should also configure your (Rebus) containers to

```yaml
    restart: unless-stopped
```

or some variant of that, which should ensure that your (Rebus) container will eventually start up as it should.

Regarding this

> On the other hand, it would be also possible to "pause" rebus between integration tests, so that there aren't ongoing background processes while a db reset script like [Respawn](https://github.com/jbogard/Respawn) is running.

It's always been possible to pause Rebus bus setting number of workers to 0:

```csharp
bus.Advanced.Workers.SetNumberOfWorkers(0);
```

and then restart it again later with something like

```csharp
bus.Advanced.Workers.SetNumberOfWorkers(1);
```

**Comment by ldeluigi** [comment]
You can take our code, its MIT licensed, and we can integrate pausable background services into Rebus
