### ISSUE TITLE
 "TypeNameHandling.All" option in your "JsonSerializer.cs"

### ISSUE THREAD

**Issue by tititototutu** [rebus-org/Rebus#1078]
Hello,

I just want to warn you that it is dangerous to use the "TypeNameHandling.All" option in your "JsonSerializer.cs" file.
Do not deserialize your json datas with this option enabled.
I don't know if computer security is important in your project, but in case I warn you.

Enjoy

**Comment by mookid8000** [comment]
Why is it dangerous? Can you point to some additional resources on the subject?

**Comment by mookid8000** [comment]
Hi @tititototutu , could you maybe elaborate a little bit on why it is dangerous?

**Comment by mookid8000** [comment]
Ok @tititototutu , I assume you are thinking about using "TypeNameHandling.All" when deserializing JSON data in publicly exposed APIs.

Rebus is not usually used to process messages delivered from any kind of publicly exposed API.

Please get back to me and enlighten me, if you have some additional information about the subject.
