### ISSUE TITLE
Urgent need to cancel receive new messages

### ISSUE THREAD

**Issue by EvgenyGrishnov** [rebus-org/Rebus#1083]
Use case:

I am shutting down my service in k8s (IHostApplicationLifetime.ApplicationStopping become "true").
Now I need that my service instance shutdown gracefully: it is stop to take new messages and continued to handle already received (by prefetch setting) messages OR it is stop to take new messages and return all cached messages so other instance will handle them.

I can do this:

`   
 public void StopWorkers() => ((RebusBus)Bus).SetNumberOfWorkers(0);
`
 
But cached messages will be stuck and never handled

**Comment by mookid8000** [comment]
Rebus will attempt to shut down gracefully when it's disposed (which often happens as a consequence of disposing the IoC container).

It'll continue executing handlers which are currently being executed and let them finish, as long as they can do so within 1 minute (which is the [default worker shutdown timeout](https://github.com/rebus-org/Rebus/blob/master/Rebus/Config/Options.cs#L29))

If you can see "stuck" messages, I would say that either something did not shut down cleanly, OR it's an error.

Which transport are you using?

Which version of the NuGet packages are you using?

How do you actually see that messages aren't returned as they should have been?

**Comment by EvgenyGrishnov** [comment]
I use latest version of Rebus + latest RabbitMQ libs
I am not experimenting yet because I tried to clarify first how to shutdown services according to Rebus API.

I think that your answer should be in documentation then with a title like a "How Rebus stops his work gracefully" because I didn't find clear information you said and had a doubts)

**Comment by mookid8000** [comment]
You are absolutely right. I made this page that describes in more detail the different aspects of starting up/shutting down: https://github.com/rebus-org/Rebus/wiki/Startup-shutdown

Let me know if you think something is missing 🙂
