### ISSUE TITLE
Choosing handler based on header rather than message type

### ISSUE THREAD

**Issue by htxryan** [rebus-org/Rebus#1090]
We have a situation where we have a single message type coming from multiple sources. Based on a custom header value, we want to route these messages to different handlers. So say if a message has a "handle-me" header value of "x", HandlerX would be invoked; and if a message has a "handle-me" header value of "y", HandlerY would be invoked. In each instance, the deserialized type would be the same (in our case they are actually just strings).

Is this possible?

The only workaround I can think of to accomplish this would be to use a custom ISerializer implementation that inspected the header value and forced a deserialization to a custom type that mapped to the handler (like a simple type wrapping the actual string message body). This would work ok, I think, but it feels a bit hacky. I'm curious if there's a different, more straightforward way to handle this configuration.

**Comment by GMacAussie** [comment]
I have not looked at the deserializer aspect of Rebus but it does seem it would be a pretty low level change.

Not the same as your situation but maybe useful: we have fan-in/fan-out messages where we take a message type, process it and then generate other ongoing message types.

In your case, a single message handler would 'route' the message to the correct message type - you could use a constructor for say MessageX that takes that single message type to copy data and then that MessageX would be sent using say SendLocal()...?

**Comment by mookid8000** [comment]
I can think of several ways of implementing what you ask for. The simplest IMO would be to simply have two handlers for your message in the container. Rebus will resolve both of them and dispatch the message to both of them, but they would each do a simple check to see if the message was supposed to be processed there – e.g. like this:

```csharp
public class SomeKindOfHandler : IHandleMessages<string>
{
	readonly IMessageContext _messageContext;

	public SomeKindOfHandler(IMessageContext messageContext) => _messageContext = messageContext;

	public async Handle(string message)
	{
		var headers = _messageContext.Headers;

		if (!ShouldHandleMessageBasedOnHeaders(headers)) return;

		// handle message here
	}

	bool ShouldHandleMessageBasedOnHeaders(Dictionary<string, string> headers)
	{
		// determine stuff here
		return true;
	}
}
```
It should be fairly easy to move the logic of determining whether the message should be handled to an application service with a transient lifestyle, which may then be injected, thus removing the need to inject `IMessageContext` into your handlers.

IMO this would be a pretty simply and understandable implementation with very few surprises. 🙂 

If filtering matching handlers by looking at headers is a thing you're going to be doing a lot, you could decorate Rebus' `IHandlerActivator` interface, which is the thing that is responsible for looking at the incoming message and determining which handlers are suitable.

I just made an example on how to do that here: https://github.com/rebus-org/Rebus.ServiceProvider/blob/master/Rebus.ServiceProvider.Tests/Examples/FilterMessageHandlersDependingOnMessageHeaders.cs

Hopefully, this gave you inspiration on how you can come up with an elegang solution to your problem. 🙂
