### ISSUE TITLE
Using Decorator with DI in ASP.NET Core/NET5-7

### ISSUE THREAD

**Issue by kostazol** [rebus-org/Rebus#1092]
Hello!
Some times ago I started to use a decorator for ITransport  with your helps ( https://github.com/rebus-org/Rebus/issues/985 )
Now I have some dependencies that I need to use in the TransportDecorator class. 
I have the extension for Rebus configuration:
```
services.AddRebus(
				rebus => rebus
					.Logging(l => l.Serilog())
					.Transport(t => t.UseAmazonSQS(credentials, _sqsConfig, queueName))
					.Options(t =>
					{
						t.SimpleRetryStrategy(errorQueueAddress: busSettings.ErrorQueueName);
						t.SetNumberOfWorkers(1);
						t.SetMaxParallelism(1);
						t.Decorate<ITransport>(c =>
						{
							var transport = c.Get<ITransport>();

							return new TransportDecorator(transport, isPriorityQueue, instancesSynchronizer);
						});
					}));

```

Can I initialize the TransportDecorator with some decency from DI using with constructor injection or using service locator? I want to avoid changing this code on adding or removing dependency for the TransportDecorator.

**Comment by mookid8000** [comment]
Yes you can, but since Rebus' main bus instance (and everything contained in it, e.g. the transport implementation) is a singleton, please be sure that your dependency is also registered as a singleton!

Injecting stuff is easy, just use the `AddRebus` overload that passes `IServiceProvider` to the configuration function:

```csharp
services.AddRebus(
	(rebus, provider) => rebus
		.Logging(l => l.Serilog())
		.Transport(t => t.UseAmazonSQS(credentials, _sqsConfig, queueName))
		.Options(t =>
		{
			t.SimpleRetryStrategy(errorQueueAddress: busSettings.ErrorQueueName);
			t.SetNumberOfWorkers(1);
			t.SetMaxParallelism(1);
			t.Decorate<ITransport>(c =>
			{
				var transport = c.Get<ITransport>();

				// 👇
				var whatever = provider.GetRequiredService<IWhatever>();

				return new TransportDecorator(transport, isPriorityQueue, instancesSynchronizer);
			});
		}));
```
