### ISSUE TITLE
Pub/Sub and typerouting - Azure Service Bus

### ISSUE THREAD

**Issue by NWessel** [rebus-org/Rebus#1097]
P.S, kommer gerne forbi med en øl :D

I have what might be a weird bug? Maybe it is my configuration..

I have a .net 7 api where I'm doing some testing with Rebus and Azure Service Bus.
It took some time, but I figured out the general workings. That if you want to listen to messages it HAS to be from queues, but you can publish messages to topics. You can also subscribe to a topic, which will setup a subscription that forwards messages to said queue.

https://github.com/NWessel/SimpleRebus
I have this code, and by comment you can see what works and what doesn't.
I thought that when I had setup typebased routing that I would be able to just call _bus.Publish and _pub.Subscribe - But it only works when i go into _bus.Advanced.Topics. ETC
I put it all in the same place for readability
```csharp
public class TestingController : ControllerBase
{
    private readonly IBus _bus;

    public TestingController(IBus bus)
    {
        _bus = bus;
    }

    [HttpPost(Name = "SendMessage")]
    public async System.Threading.Tasks.Task SendMessage([FromBody] Project project)
    {
        try
        {
            //Doesn't work
            await _bus.Publish(project);

            //works
            await _bus.Advanced.Topics.Publish("project", project);


            //Doesn't work
            await _bus.Subscribe<Project>();

            //works
            await _bus.Advanced.Topics.Subscribe("project");
        }
        catch (Exception e)
        {
        }
        
    }
}
```

I get the following message in my exception from those marked as not working

**The specified HTTP verb (GET) is not valid. To know more visit https://aka.ms/sbResourceMgrExceptions. . TrackingId:8007a571-1b5e-4a32-8bae-9b8210e310de_G2, SystemTracker:ndwtest:Queue:simplerebus, Timestamp:2023-06-29T18:57:50
Status: 400 (Bad Request)

Content:
<Error><Code>400</Code><Detail>The specified HTTP verb (GET) is not valid. To know more visit https://aka.ms/sbResourceMgrExceptions. . TrackingId:8007a571-1b5e-4a32-8bae-9b8210e310de_G2, SystemTracker:ndwtest:Queue:simplerebus, Timestamp:2023-06-29T18:57:50</Detail></Error>**

This is my program.cs file with the typebased routing
```csharp
using Rebus.Config;
using Rebus.Routing.TypeBased;
using SimpleRebus.Incoming;
using SimpleRebus.Models;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddRebusHandler<ProjectHandler>();
builder.Services.AddRebus(configure => configure
    .Transport(t => t.UseAzureServiceBus(builder.Configuration["AzureServiceBusConnectionString"], "teamplanner"))
    .Logging(l => l.ColoredConsole(Rebus.Logging.LogLevel.Debug))
    .Routing(r => 
        r.TypeBased()
            .Map<Project>("project")
            .Map<Resource>("resource")
            .Map<SimpleRebus.Models.Task>("task"))
);



var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
```

**Comment by mookid8000** [comment]
Hi @NWessel , sounds pretty weird!

Initially, I though that that endpoint mappings (`r.TypeBased().Map<...>(...)` etc) could somehow interfere with the transport's mapping of .NET types to topic names, but that does not seem to be the case.

I coded this in my attempt to reproduce the odd behavior: https://github.com/rebus-org/Rebus.AzureServiceBus/blob/master/Rebus.AzureServiceBus.Tests/Bugs/EndpointMappingsDoNotInterfereWithPubSub.cs

Could you maybe take a look at it and see in what ways your code differs from the example?

**Comment by mookid8000** [comment]
> P.S, kommer gerne forbi med en øl :D

Det er sgu pænt af dig! 🙂 men jeg har øl nok 🤠 

![IMG_5395](https://github.com/rebus-org/Rebus/assets/32968/4ab7122e-d45b-4450-a916-c34d11667001)

(har en ølbutik med 168 forskellige øl på hylden...)

**Comment by NWessel** [comment]
Going to look at your code now - And for good measures, just adding the stacktrace of the error I got

   at Azure.Messaging.ServiceBus.Administration.HttpRequestAndResponse.<ThrowIfRequestFailedAsync>d__7.MoveNext()
   at Azure.Messaging.ServiceBus.Administration.HttpRequestAndResponse.<SendHttpRequestAsync>d__14.MoveNext()
   at Azure.Messaging.ServiceBus.Administration.HttpRequestAndResponse.<GetEntityAsync>d__11.MoveNext()
   at Azure.Messaging.ServiceBus.Administration.ServiceBusAdministrationClient.<TopicExistsAsync>d__48.MoveNext()
   at Rebus.AzureServiceBus.AzureServiceBusTransport.<EnsureTopicExists>d__28.MoveNext()
   at Rebus.AzureServiceBus.AzureServiceBusTransport.<>c__DisplayClass86_0.<<GetTopicClient>b__1>d.MoveNext()
   at Rebus.AzureServiceBus.AzureServiceBusTransport.<GetTopicClient>d__86.MoveNext()
   at Rebus.AzureServiceBus.AzureServiceBusTransport.<>c__DisplayClass35_0.<<GetOutgoingMessages>g__SendOutgoingMessagesToDestination|3>d.MoveNext()
   at Rebus.AzureServiceBus.AzureServiceBusTransport.<>c__DisplayClass35_1.<<GetOutgoingMessages>g__SendOutgoingMessages|1>d.MoveNext()
   at Rebus.Transport.TransactionContext.<InvokeAsync>d__32.MoveNext()
   at Rebus.Transport.TransactionContext.<Complete>d__27.MoveNext()
   at Rebus.Bus.RebusBus.<InnerSend>d__43.MoveNext()
   at Rebus.Bus.RebusBus.<InnerPublish>d__34.MoveNext()
   at SimpleRebus.Controllers.TestingController.<PublishSimple>d__5.MoveNext()

**Comment by NWessel** [comment]
I deleted all topics and queues and started the solution and now it is working - 
I also removed the routing with typebased().map and everything also runs smoothly.
I thought I knew what that route mapping did, but now I'm unsure :D 
Could you give a few words on what the routing solves then? I thought it would use that mapping when publishing a message, and use that as topic name. But that doesn't seem to be the case

**Comment by mookid8000** [comment]
When you 

```csharp
await bus.Send(new SomeKindOfMessage());
```

Rebus will look up the destination queue in its endpoint mappings. So if you have

```csharp
.Routing(r => r.TypeBased().Map<SomeKindOfMessage>("some-queue")
```

it will send the message to the queue "some-queue".

Since Azure Service Bus has native support for topic-based routing (i.e. "pub/sub messaging"), the endpoint mappings don't have any effect or relevance for pub/sub messaging.

If you want to customize the topic names, one way to do that is to register a custom [`ITopicNameConvention`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Topic/ITopicNameConvention.cs), which is what Rebus uses to get topic names for different message types.

**Comment by NWessel** [comment]
Seems like I'm not allowed to register a new one
![image](https://github.com/rebus-org/Rebus/assets/9061380/702f9c74-a2e6-4a85-9138-e0ef31bc8ef8)

**Comment by mookid8000** [comment]
Oh yes you are, but there can be only one primary `IBus` in the container (which will be the bus instance injected into MVC controller, etc).

As the error message says 😁 : You'll need to register additional bus instances with `isDefaultBus: false`.
