### ISSUE TITLE
Different sagas sharing correlation id

### ISSUE THREAD

**Issue by epgeroy** [rebus-org/Rebus#1098]
Hi there, we are experimenting with `Sagas` with a retail-related scenario.

Our `CorrelateMessages` function ends up looking like this:
```
config.Correlate<Price>(price => price.Id, data => data.PriceId);
config.Correlate<Product>(product => product.Id, data => data.ProductId);
config.Correlate<Store>(store => store.Id, data => data.StoreId);
```

Meaning that, there can be multiple sagas at the same time with the same `ProductId` or the same `StoreId` but not with the same `PriceId` (PriceId is a composite key with the `StoreId` and the `ProductId`)

1. When we try to publish, let's say, a store that already exists in another saga we get this error
```
Rebus.Exceptions.ConcurrencyException: Correlation property 'StoreId' has value 'XXXXXXXX' in existing saga data with ID XXXX
```

2. When we try to remove the correlation instruction from the `Product` and the `Store` we get the error saying that 

```
Could not find any correlation properties for message.
```

We checked this [StackOverflow question](https://stackoverflow.com/questions/67569777/rebus-multiple-sagas-handling-same-message-or-best-practice-for-request-reply) where using the `rbs2-corr-id` header is suggested, but currently, we don't have a way to match our messages since this is not a request/response scenario.

We are not sure if this problem can be addressed using sagas or if we are just doing something wrong.
Thanks in advance

**Comment by epgeroy** [comment]
On further investigation, I found this:
```
        //
        // Summary:
        //     Override this to be given an opportunity to resolve the conflict when a Rebus.Exceptions.ConcurrencyException
        //     occurs on an update. If a conflict cannot be resolved, feel free to bail out
        //     by throwing an exception.
        [AsyncStateMachine(typeof(Saga<>.<ResolveConflict>d__7))]
        protected virtual Task ResolveConflict(TSagaData otherSagaData);
```
I made a dummy override to understand how it worked, but upon debugging looks like the function is not being triggered after the `Rebus.Exceptions.ConcurrencyException` for this case.

Hope it helps
Thanks

**Comment by mookid8000** [comment]
Not sure if I understand this correctly, but if I do, please understand that a saga instance's correlation properties must be unique.

E.g. if you're using SQL Server to store your saga data, the saga index will have a unique constraint on the correlation property name + the correlation property value.

This is to ensure that at most one saga instance can be found when handling a message.

I think you should be able to make the correlation properties nullable, and then just store NULL in the irrelevant correlation properties.

I hope this helps 🙂 

(or if I misunderstood your problem, please let me know)

**Comment by mookid8000** [comment]
Ah yes, now I understand. And sorry no, having multiple instances of your saga data with the same store ID will not be possible.

If you can live without being able to correlate on the store ID, then you could remove that. But then if two stores had the same product ID, then you would have the same problem. If you could live with removing that too, then the correlation ID would simply be your composite `<store-id>/<product-id>`. Would that be sufficient for your use case?

If not, then I'm afraid that Rebus' sagas are too limited for what you are trying to achieve. 😐
