### ISSUE TITLE
Preventing duplicate publishes when deferring inbound messages

### ISSUE THREAD

**Issue by mattwcole** [rebus-org/Rebus#1099]
When deferring an inbound message, how can we prevent outbound messages from being sent multiple times?

```csharp
public async Task Handle(InboundMessage message)
{
    try
    {
        using var dbTransaction = TransactionScopeFactory.CreateReadCommitted();

        await DoWork();
        await _bus.Publish(new OutboundMessage { Body = "I should only every be published once!" });
        await DoMoreWork();

        dbTransaction.Complete();
    }
    catch (MyException)
    {
        await _bus.Advanced.TransportMessage.Defer(TimeSpan.FromSeconds(5));
    }
}
```

In the example above `OutboundMessage` will be published multipile times if `InboundMessage` is deferred. I tried to prevent this by aborting the Rebus transaction in the catch block, but this doesn't seem to work.

**Comment by mookid8000** [comment]
If I understand this correctly, you'll need to change your logic somehow.

You could e.g. include an additional header when deferring the message, which you could then detect in subsequent deliveries:

```csharp
var headers = new Dictionary<string, string> {["i-have-seen-you-before"] = "yes"};
await _bus.Advanced.TransportMessage.Defer(TimeSpan.FromSeconds(5), optionalAdditionalHeaders: headers);
```

and then when handling the (possibly deferred) message:

```csharp
if (!_messageContext.Headers.ContainsKey("i-have-seen-you-before"))
{
    await _bus.Publish(new OutboundMessage { Body = "I should only every be published once!" });
}
```

Let me know if it doesn't work 🙂

**Comment by mattwcole** [comment]
Thanks for the suggestion. If we take that approach, we publish the outbound message before we have successfully processed the inbound one. Ideally I want to prevent the outbound messages being sent in the catch block.

It seems like message deferral is not the correct approach here.  I want all the behaviour of an unhanded exception (roll back the transaction, retry the message) but with a delay before the next retry.

**Comment by mookid8000** [comment]
Oh, now I get it.

The easiest way then would probably be to manage the Rebus transaction scope manually:

```csharp
public async Task Handle(InboundMessage message)
{
    try
    {
        using var scope = new RebusTransactionScope(); //< 👈 !! 😁 
        using var dbTransaction = TransactionScopeFactory.CreateReadCommitted();

        await DoWork();
        await _bus.Publish(new OutboundMessage { Body = "I should only every be published once!" }); //< will be enlisted in the scope
        await DoMoreWork();

        dbTransaction.Complete();

        // commit the scope 🚀 
        await scope.CompleteAsync();
    }
    catch (MyException)
    {
        await _bus.Advanced.TransportMessage.Defer(TimeSpan.FromSeconds(5));
    }
}
```

This way you'll be in full control of what gets committed and when.

**Comment by mattwcole** [comment]
Fantastic thank you, I will give this a go!
