### ISSUE TITLE
Handling classes that use generics that implement interfaces

### ISSUE THREAD

**Issue by labeled** [rebus-org/Rebus#1103]
We have this event
``` 
public class DomainEvent<T> where T : ICommand
{
    public T Command { get; set; }
}
```
That we want to handle via rebus
```
public class FreezeBatchCommandHandler : MessageHandlerBase, IHandleMessages<FreezeBatchCommand>
```
But we cannot get the routing to work without using a fallback
```
.Routing(
    r => r.TypeBased()
        .MapAssemblyNamespaceOf<DomainEvent<ICommand>>(settings.CommandBusQueue) // doesn't work
        .MapFallback(settings.CommandBusQueue))); // works
```

Using the fallback we can get our handlers to succesfully work. However, we cannot handle the IFailed messages.
This does not work unless we change ICommand to object and do a switch with type casting which feels dirty.
```
public class ErrorHandler : IHandleMessages<IFailed<DomainEvent<ICommand>>>
```
Is it possible to do something like this?

**Comment by mookid8000** [comment]
Regarding endpoint mapping: What does the log say? IIRC Rebus will output all mapped message types and their mapped destinations to the log.

Regarding message dispatch: I'm afraid the level of contravariance required to properly look up `IFailed<DomainEvent<ICommand>>` from the IoC container is not supported. Even though you feel it's dirty, if it works, I recommend you accept `IFailed<DomainEvent<object>>` and do the type casting. And please remember to create proper integration tests (using the in-mem transport) to ensure that your assumptions about the behavior continue to hold.

**Comment by labeled** [comment]
Thank you for the quick response mookid8000, much appreciated. Awesome software btw :)
