### ISSUE TITLE
Could not anymore write a new worker outside of Rebus assembly.

### ISSUE THREAD

**Issue by antpata** [rebus-org/Rebus#1104]
Private ITransactionContextWithOwningBus and/or TransactionContextWithOwningBus prevents writing a new worker outside of Rebus assembly. Writing a new worker outside of the Rebus assembly was possible earlier and there are all required plugin mechanisms but a worker must be capable of constructing  a new transaction context that need to implement both ITransactionContext and ITransactionContextWithOwningBus interfaces but ITransactionContextWithOwningBus is private.
Also it would be nice to be able to use TransactionContextWithOwningBus class without re-implementing it.

**Comment by mookid8000** [comment]
You are right about this. I'll address it one of the following days.

**Comment by antpata** [comment]
Fyi,

Similar issue exists on reply step implementation outside of Rebus tree. ManualDeadletterCommand and ICanEagerCommit types are needed for a proper reply step implementation but they are private.
