### ISSUE TITLE
Rebus8 DefaultRetryStep cannot recover from a message that causes OOM

### ISSUE THREAD

**Issue by antpata** [rebus-org/Rebus#1113]
Rebus8 DefaultRetryStep runs an error tracker after an actual message handler, which has obvious benefits, but it causes severe issues to out of memory (OOM) handling. Older versions of the Rebus run an error tracker before a handler, which makes possible to write an error tracker that can detect poisonous message that constantly causes OOM. For example using Redis or underlying queue technology to track message execution count. On Rebus8 one must also replace DefaultRetryStep and evaluate all the consequences that changing the execution order of error tracker and handler will cause to be able to recover from OOM. 

Background:
On containerized setup CLR is typically configured so that on OOM the process just crashes and OutOfMemoryException is never thrown to the application. This is because of the fact that if the CLR would be configured to throw OutOfMemoryException then the container would easily end up to be a zombie if there is some sort of memory leak. Zombie meaning that a container environment would not kill the container but it cannot do any meaningful work either because any real action will lead to an OOM. So it better to let process crash and let the container environment to restart it that take a risk of creating zombie containers that needs a human interventions to recover. This setup has one mandatory requirement from the message error tracker: It must be able count poisonous OOM messages and remove them from the queue after couple of retries.

**Comment by mookid8000** [comment]
I never thought of that, but I guess you are absolutely right: Rebus 8 will not (out-of-the-box) be able to guard against repeated deliveries of a message that causes the process to get an OOME.

While this might seem unfortunate, positioning the error handling last in the pipeline has the very obvious benefit that no resources are wasted doing preemptive tracking of messages in the sunshine scenario.

If you need preemptive tracking of messages (or if you would like to switch to using the transport's built-in dequeue counter if it has such thing), I suggest you insert your own preemptive pipeline step, which can then do what you require before invoking the rest of the pipeline. Don't you think that would work for you?

**Comment by antpata** [comment]
Yep, I will get it working.
Most probably ending up to replacing whole DefaultRetryStep, that is little bit sad, but if an OOM message happens then it is a showstopper if it is not automatically handled.
RabbitMQ is so widely different in behavior than for example SqlServer that in the end the same reply step probably won't work for both of them. For example starting from the fact that SqlServerTransport delivers  retries almost always to the same container replica where RabbitMq delivers retries almost always to different container replicas. So In-memory tracking does not work very well  with RabbitMQ .
FYI: Our existing SW runs on Rebus4 and heavily relays that also FailFastExceptions end up to a second level error handler. So an another thing to put pressure to replace DefaultRetryStep

**Comment by antpata** [comment]
But now I have an issue that both ManualDeadletterCommand and ICanEagerCommit types are private and proper reimplementation of the retry step is not possible. This use case does not really need those but still I need to disable some features due to protection issues.

**Comment by antpata** [comment]
Fyi,
Replacing the DefaultReplyStep with a transport specific one and adapting the old logic from a SimpleReplyStep lead to quite optimal solution this time. But still these two interface (ManualDeadletterCommand and ICanEagerCommit) are needed for a proper reply step implementation.
