### ISSUE TITLE
.NET 8 + System.Text.Json 8.0.0 Support

### ISSUE THREAD

**Issue by mathiash98** [rebus-org/Rebus#1121]
Seems like the restriction in the project file:
https://github.com/rebus-org/Rebus/blob/99d97045441aeec4a5eec3e1d2f840e1df223f05/Rebus/Rebus.csproj#L34

`system.text.json" Version="[5,8)"` is more "Yes we know it works with version 5 -> text.json 7.x.x".
- Is there a good reason for setting the upper limit?
- Maybe using `system.text.json" Version="[5,)"` is more appropriate and then introduce upper limit if any error occurs in the future. So far it seems like there are no breaking changes that affects Rebus

**Comment by mookid8000** [comment]
Rebus 8.0.0 is out now with .NET 8 support 🙂
