### ISSUE TITLE
Question about getting a message header

### ISSUE THREAD

**Issue by dazinator** [rebus-org/Rebus#1131]
I am in a saga, processing an incoming message.

```
  public async Task Handle(ExecuteWorkflowCommandMessage message)
    {

```

I'd like to grab the sender's address so I can reply later on in the saga back to this sender.
So I think I just need to grab the senders address at this point from the incoming message and set it in saga state. Then later I can use it at the end of the saga with the ReplyTo capability.

My question is, how do I access this incoming messages header for the senders address?

**Comment by hjalle** [comment]
Inject "IMessageContext" and get the sender from the headers perhaps?
`_messageContext.Headers.TryGetValue(Headers.SenderAddress, out var sender)`

**Comment by dazinator** [comment]
Thank you.
