### ISSUE TITLE
Is there any way to implement transport initialization asynchronously?

### ISSUE THREAD

**Issue by glazkovalex** [rebus-org/Rebus#1134]
In Apache Kafka, rebalancing when connecting consumers is difficult and time-consuming. It can consist of several asynchronous operations and last for minutes or longer. Now I have to initialize inside the [RegisterSubscriber ](https://github.com/rebus-org/Rebus/blob/41be260945fbec97c968083e4e0a7f8911cf3dfd/Rebus/Subscriptions/ISubscriptionStorage.cs#L20C10-L20C28)and delay the start of [receiving messages](https://github.com/rebus-org/Rebus/blob/41be260945fbec97c968083e4e0a7f8911cf3dfd/Rebus/Transport/ITransport.cs#L25C28-L25C35) until it is completed.
Is there any way to implement [transport initialization](https://github.com/rebus-org/Rebus/blob/41be260945fbec97c968083e4e0a7f8911cf3dfd/Rebus/Bus/IInitializable.cs#L12) asynchronously?

**Comment by mookid8000** [comment]
> Is there any way to implement [transport initialization](https://github.com/rebus-org/Rebus/blob/41be260945fbec97c968083e4e0a7f8911cf3dfd/Rebus/Bus/IInitializable.cs#L12) asynchronously?

Yes - by starting it during initialization and the letting it run in the background. 

You'll of course have to implement the proper synchronization mechanisms to ensure that the first call to e.g.

```csharp
await bus.Subscribe<Whatever>();
```

blocks asynchronously (e.g. on an `AsyncManualResetEvent` from [Nito.Asyncex](https://github.com/StephenCleary/AsyncEx)) so it will actually not send anything before the transport has been initialized.

It will of course also lose the ability to fail fast during initialization, if something is not right - so. e.g. if the connection string to Kafka points to an invalid hostname, you'll have to monitor your logs to find out.

**Comment by mookid8000** [comment]
By the way: Kafka is very different from queue-based message brokers in many ways, and I've never felt that it would be a good Rebus transport. 

When I needed "a Rebus, but for Kafka" myself, I built [Topos](https://github.com/mookid8000/topos), which basically wraps Kafka and makes it pleasant to work with and has a little bit of the Rebus feeling when you configure it.

As a bonus, it can also run in "embedded mode", using [Microsoft FASTER](https://microsoft.github.io/FASTER/) (the WAL part) as an embedded, file-based event store.

I'm not saying it can't be done - but you'll probably meet friction in various places (as you are now).
