### ISSUE TITLE
Empty session ID header added on retry

### ISSUE THREAD

**Issue by NickHedgesAE** [rebus-org/Rebus#1139]
Hi, 

Something weird has started happening recently that I do not have a solution for. I am using Rebus for Azure Service Bus messaging and  the retry approach I am using is simply if a message fails to be handled, place it on an _error_ queue. Sometimes errors do happen of course, and when messages appear in the error queue they suddenly have an extra header that wasn't present in the original message. Below screenshot was taken in Azure Service Bus Explorer. The _Message custom properties_ section is normally reserved for headers specific to Rebus, but suddenly it also includes the built-in _SessionId_ after retries. Since my implementation never uses _SessionId_ this value is empty, which is not allowed for custom properties. The issue lies in the fact that replaying these messages is impossible without removing this header manually from the custom properties. This is a hassle, as I have to do this one-by-one. 

![Screenshot 2024-02-06 100206](https://github.com/rebus-org/Rebus/assets/91309219/c415dd61-2577-41b0-8cbf-e0e29594e9cc)

Is there a setting that I missed somewhere?

**Comment by mookid8000** [comment]
Turned out that some of Rebus' header gymnastics would accidentally pull in a "SessionId" header, even though the ASB message had an empty session ID.

It's fixed in Rebus.AzureServiceBus 10.1.1, which is on NuGet.org now 🙂
