### ISSUE TITLE
How to mock MessageContext.Current in outgoing step?

### ISSUE THREAD

**Issue by andrescardenash** [rebus-org/Rebus#1143]
I'm facing a challenge with mocking `MessageContext.Current` in an outgoing step in Rebus. I have a piece of code that looks like this:

```csharp
    public class NewRelicTraceSend : IOutgoingStep
    {
        public async Task Process(OutgoingStepContext context, Func<Task> next)
        {
            var messageContext = MessageContext.Current;
            var transaction = NewRelic.GetAgent().CurrentTransaction;

            if (messageContext?.Headers != null)
            {
                transaction.InsertDistributedTraceHeaders(messageContext.Headers, (dictionary, key, value) =>
                {
                    dictionary.Add(key, value);
                });
            }

            try
            {
                await next();
            }
            catch (Exception error)
            {
                Log.Error(error, "Fatal error sending message.");
                NewRelic.NoticeError(error, messageContext.Headers);

                throw;
            }
      }
```

I've tried to follow the steps to create tests for incoming and outgoing steps([link](https://github.com/rebus-org/Rebus/wiki/How-to-test-incoming-and-outgoing-steps)), but I'm still unable to mock MessageContext.Current successfully. Can you provide guidance or examples on how to properly mock MessageContext.Current in this context? the idea is to create a test to validate some additional headers that InsertDistributedTraceHeaders is appending but MessageContentext.Current is always null.

Test:

```csharp
        [TestMethod]
        public async Task Process_WithMessageContextHeaders_AddsHeadersToTransaction()
        {
            using (var activator = new BuiltinHandlerActivator())
            {
                var step = new NewRelicTraceSend();
                var network = new InMemNetwork();
                var bus = Configure
                            .With(activator)
                            .Transport(t => t.UseInMemoryTransport(network, "test-rebus-queue"))
                            .Options(o =>
                                        o.Decorate<IPipeline>(c =>
                                        {
                                            var pipeline = c.Get<IPipeline>();

                                            return new PipelineStepInjector(pipeline)
                                                .OnSend(step, PipelineRelativePosition.Before, typeof(SendOutgoingMessageStep));
                                        })
                                    )
                            .Options(o => o.LogPipeline(verbose: true))
                            .Start();

                network.CreateQueue("test-rebus-queue");

                await bus.Advanced.Routing.Send("test-rebus-queue", "testing.com");
            }
        }
```

**Comment by mookid8000** [comment]
Hi @andrescardenash , sorry for taking so long to get back to you.

Your problem is valid, ~but there's no built-in way in Rebus to fake the current message context. It's available via the static `Current` property on `MessageContext`, but it's actually instantiated every time it gets requested from the current ambient transaction context, IF the ambient transaction context~ and I just figured out how easy it was for me to help you 😉 

With [Rebus.TestHelpers](https://www.nuget.org/packages/Rebus.TestHelpers) 9.1.0 (which is on NuGet.org now!) you can do this:

```csharp
var transportMessage = new TransportMessage(headers, body);
using var scope = new FakeMessageContextScope(transportMessage);

// this will now be available 🎉
var messageContext = MessageContext.Current;
```

It should make it very easy for you (and anyone else with similar problems) to write proper unit tests of their pipeline steps.

Thanks for directing my attention to the fact that this was missing.

**Comment by andrescardenash** [comment]
Thank you so much!!
