### ISSUE TITLE
Question: Kafka transport ? 😢

### ISSUE THREAD

**Issue by st3no** [rebus-org/Rebus#1150]
Is official support for Kafka transport planned ? Thanks 😊

**Comment by mookid8000** [comment]
No. Check out [Topos](https://github.com/mookid8000/topos) if you like Rebus but want to use Kafka.

Everything in Rebus revolves around queue-based messaging (and therefore: messages as fairly independently processable units), so it's really bad at processing streams (like you want to do when using Kafka).
