### ISSUE TITLE
Dotnet 9 support

### ISSUE THREAD

**Issue by ChrisonSimtian** [rebus-org/Rebus#1183]
Hey,

I just branched off one of my projects and upgraded to Dotnet 9 and it seems like one of your libraries restricts **Microsoft.Extensions.Logging.Abstractions** to < 9.0.0

Do you think you can open up that restriction in **Rebus.Microsoft.Extensions.Logging** ?
Not sure if there are any breaking changes but I'd be happy to test that in the next couple of weeks as we've put dev time aside to evaluate the latest dotnet version anyway :-)

```
Version conflict detected for Microsoft.Extensions.Logging.Abstractions. Install/reference Microsoft.Extensions.Logging.Abstractions 9.0.0 directly to project BestStart.Common.EventBus to resolve this issue. 
 BestStart.Common.EventBus -> BestStart.Common -> Microsoft.Extensions.Logging.Abstractions (>= 9.0.0) 
 BestStart.Common.EventBus -> Rebus.Microsoft.Extensions.Logging 5.0.0 -> microsoft.extensions.logging.abstractions (>= 6.0.0 && < 9.0.0).
```

**Comment by ChrisonSimtian** [comment]
And found another one in Rebus.ServiceProvider for Microsoft.Extensions.DependencyInjection :-)
```
Version conflict detected for Microsoft.Extensions.DependencyInjection. Install/reference Microsoft.Extensions.DependencyInjection 9.0.0 directly to project BestStart.Clients.Chris21API.Tests to resolve this issue. 
 BestStart.Clients.Chris21API.Tests -> BestStart.Common.Tests -> BestStart.Common -> Microsoft.Extensions.Logging 9.0.0 -> Microsoft.Extensions.DependencyInjection (>= 9.0.0) 
 BestStart.Clients.Chris21API.Tests -> BestStart.Common.Tests -> BestStart.Common.EventBus -> Rebus.ServiceProvider 10.2.0 -> Microsoft.Extensions.DependencyInjection (>= 8.0.0 && < 9.0.0).
```

**Comment by ChrisonSimtian** [comment]
https://learn.microsoft.com/en-us/dotnet/core/compatibility/9.0

Just for reference, I don't think there are any breaking changes in those libraries so probably safe to upgrade?

**Comment by mookid8000** [comment]
Rebus.ServiceProvider, Rebus.Microsoft.Extensions.Logging, and Rebus.Microsoft.Extensions.Configuration are all out in versions that accept v9.* of their respective Microsoft.Extensions.* dependencies, mostly thanks to @ronaldbarendse. 🙂
