### ISSUE TITLE
HTTP Gateway hosted on IIS

### ISSUE THREAD

**Issue by hagbarddenstore** [rebus-org/Rebus#149]
Looked at the HTTP gateway that exists now and found out that it's a self-hosted application. In scenarios where there's already an existing infrastructure setup for HTTP traffic over port 80 (Or some other port) it might be beneficial to reuse that existing infrastructure to host the Rebus HTTP gateway, IE in IIS.

A related idea is to have some sort of filter as well, so we can restrict which messages are accepted on the receiving endpoint.

**Comment by mookid8000** [comment]
if the new Rebus2 gateway will be implemented as an OWIN middleware, it can easily be hosted anywhere you want :)
