### ISSUE TITLE
Optimizing SQL Server transport even further

### ISSUE THREAD

**Issue by improvedk** [rebus-org/Rebus#187]
Just hit me you might actually be able to optimize the transport even further...

Right now you do something like this:
* Begin tran
* Select & lock available message from queue [DB roundtrip]
* Process message
* Delete locked message from queue [DB roundtrip]
* Commit tran [DB roundtrip]

Instead you should be able to do:
* Begin tran
* Delete available message from queue - using the OUTPUT clause you can get the deleted row back to the client [DB roundtrip]
* Process message
* Commit tran [DB roundtrip]

That way you only have *one* DML statement instead of selecting & deleting separately. In your non-transactional mode you could simply delete the message outright and just hope the client processes it, though that probably won't satisfy the once-or-more constraint as it'll be zero-or-one. But then again, as most will probably be transactional, you could have the optimized version only for the transactional version.

**Comment by mookid8000** [comment]
I'm parking this one for now :)
