### ISSUE TITLE
New build script

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#204]
Create a new build script, possibly using Fake, that parses the changelog and gets the version number from there.

Should be able to compile the version number into all assemblies.

Should be able to pack & push properly versioned packages to NuGet.org

**Comment by mookid8000** [comment]
Rebus2 has a new build script, which is based on the immensely awesome normcore build technology known among friends as "MSBuild"

"If you need more from your build script than MSBuild provides, YDIW." (- Anonymous, after half a bottle of Chianti)

**Comment by asgerhallas** [comment]
I now believe he was right. But the syntax :,(
