### ISSUE TITLE
Ability to automatically store originating endpoint in saga data

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#211]
Add to `ISagaData`:

    public interface ISagaDataWithOriginator : ISagaData
    {
        string Originator { get; set; }
    }

and make sure it is set to `messageContext.ReturnAddress` when the saga data is initially created.

**Comment by CasperTDK** [comment]
How about persisting messageContext on each revision? That is a messageContext history for the saga.
Or perhaps just save messageContext for the originator (IAmInitializedBy Message)? 

This could easily be done outside the rebus framework - any particular reason you want it built-in?

**Comment by mookid8000** [comment]
Well.... the message context is not really meant to be persisted, and so it may contain stuff that can't readily be serialized - e.g. when using `AzureServiceBusMessageQueue`, the message context has an `Action` in it that can be used to renew the lease for the message currently being handled.

Also, I don't know if it makes that much sense to build it into Rebus - as you correnctly say, these things can easily be achieved outside of Rebus, so why bother :)

I'll close this issue now
