### ISSUE TITLE
Use native JSON storage type in PostgreSQL saga persister

### ISSUE THREAD

**Issue by hagbarddenstore** [rebus-org/Rebus#236]
What the title says. Easier to maintain and closer to what MongoDb is doing.

**Comment by mookid8000** [comment]
This one is not as trivial as it sounds - Postgres' JSONB type does not preserve the order of the fields inside objects, which means that Newtonsoft's reliance on having the `$type` property come first in every object causes it to fail during deserialization.

In [Cirqus](https://github.com/d60/Cirqus) we had this problem too, and at one point I solved it by first deserializing to a `JObject` and then recursively ensure that all objects have the `$type` property come first, and THEN deserialize to the real object, which was a clunky solution.

I'm closing this issue for now - we'll see if it gets asked for in the future :)
