### ISSUE TITLE
Subscribe to all messages handlers from current assembly

### ISSUE THREAD

**Issue by pruiz** [rebus-org/Rebus#248]
Hi,

I cant seem to find an existing method to subscribe to all IHandleMessage implementations from an assembly (or from the current one). So I normally use something like:

	public static class SubscriptionExtensions
	{
		private static MethodInfo _busSubscribeMethod = typeof(IBus).GetMethod("Subscribe");

		private static IEnumerable<Type> GetMessagesHandledBy(Assembly assembly)
		{
			return assembly
					.ExportedTypes
					.SelectMany(x => x.GetInterfaces())
					.Where(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IHandleMessages<>))
					.Select(x => x.GetGenericArguments()[0])
					.ToArray();
		}

		public static void SubscribeFrom(this IBus bus, params Assembly[] assemblies)
		{
			foreach (var assembly in assemblies)
			{
				foreach (var msg in GetMessagesHandledBy(assembly))
				{
					var _subscribeMethod = _busSubscribeMethod.MakeGenericMethod(msg);
					_subscribeMethod.Invoke(bus, new object[] { });
				}
			}
		}

		public static void SubscribeFromCurrentAssembly(this IBus bus)
		{
			bus.SubscribeFrom(Assembly.GetCallingAssembly());
		}
	}

Would it make sense to add this methods to Rebus's core? I can send a pull-req if so.

Regards
Pablo

**Comment by mookid8000** [comment]
Assembly scanning can be had now (since 0.76.0) - it's in the `Rebus.Extensions` package :) 

(allows you to go `bus. SubscribeByScanningForHandlers(anAssembly)`)
