### ISSUE TITLE
Transport message sent event handler

### ISSUE THREAD

**Issue by jasperdk** [rebus-org/Rebus#252]
I need a hook for accessing the correlation id when sending messages outside message handlers to track all changes related to a command, e.g. a command initiated as Web Api action.

What do you think of adding a TransportMessageSentEventHandler that will be called in "internal void InternalSend(string destination, List<object> messages)" after all headers has been handled?

It is not important for me whether it is possible to modify the actual transport message beeing sent.

**Comment by jpierson** [comment]
I don't see an `Events` method on `RebusConfigurer` in the newest 2.0.0.0. Has the API been deprecated?

**Comment by jpierson** [comment]
Ok, so I may have found the answer myself.
https://github.com/rebus-org/Rebus/issues/538
