### ISSUE TITLE
Error on Advanced.Routing.Send using RabbitMq

### ISSUE THREAD

**Issue by madstt** [rebus-org/Rebus#257]
I'm using Rebus.RabbitMq 0.71.

I am using the _bus.Advanced.Routing.Send(_queue, message) option. When I dispose the bus, I get this error:
"RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted"

The queue has a number of bindings.

If I roll-back to version 0.63 of both Rebus.RabbitMq and Rebus, I don't get this error. There seems to have been introduced a bug somewhere with regard to the RabbitMq integration.

**Comment by mookid8000** [comment]
I guess nothing more happened on this one - closing it for now, please reopen if you still think there's an issue
