### ISSUE TITLE
Discussing SimpleInjectorAdapter

### ISSUE THREAD

**Issue by dotnetjunkie** [rebus-org/Rebus#260]
Hi guys,

I'm one of the developers of Simple Injector and one of our users brought the [SimpleInjectorAdapter](https://github.com/rebus-org/Rebus/blob/master/src/Rebus.SimpleInjector/SimpleInjectorAdapter.cs) to my attention and I like to present my feedback to the implementation. Obviously, since there's not much code in there (always a good thing), there's not that much to discuss, but perhaps my feedback can make things even better.

Simple Injector contains a generic **GetAllIntances** method and this allows the **GetHandlerInstancesFor** implementation to be simplified to the following:

``` c#
return container.GetAllInstances<IHandleMessages<T>>().ToArray();
```
This snippet removes the `Cast<T>` method and the generic **GetAllInstances** method has better performance, since the non-generic overload has to build a generic type under the covers. But perhaps more importantly, this simplification is just much nicer :-).

There's one important detail of Simple Injector you should  be aware about. Simple Injector is the only DI container that handles returned `IEnumerable`s as streams. What this means is that the instance that **GetAllInstances** returns is a singleton, but every time you iterate the enumerable, the container is asked to resolve instances. In a sense you can see an IEnumerable as a collection of factories and this allows to original lifestyles to be preserved even if you keep a reference to that enumerable. So individual registrations within that collection could all have different lifestyles and Simple Injector ensures that you always get the right instance according to the lifestyle.

I'm bringing this up, because it might influence the implementation of the SimpleInjectorAdapter. You might already be aware of this, because you are explicitly calling `ToArray()`. ToArray obviously forces all instances of the collection to be resolved and copied into the array. Of course, iterating the array will not cause new instances to be resolved.

Calling ToArray might precisely be what you need in this case, but perhaps it can be beneficial to remove ToArray. The advantage of the stream behavior is that Simple Injector resolves items within the collection lazily (truly as a stream). So in case the collection is big and you're not always processing the complete collection (and are just iterating that collection once), returning a stream might give better performance. Take the following example for instance:

``` c#
var handlers = container.GetAllInstances<IHandleMessages<T>>();

var handlerToUse = handlers.First(someCondition);
```
In this case the `Enumerable.First` extension method stops iterating the collection directly after the `someCondition` returns true and this means that Simple Injector stops resolving types. Simple Injector is extremely fast in building up object graphs and resolving instances, so in many cases the performance improvement might not be very significant, but when the collections get big, this might be different.

I hope this information gives you more knowledge to decide whether the use of ToArray is the good approach or not.

The other thing I'd like to comment on is the **Release** method. I'm not familiar with Rebus, but it looks like any collection that is resolved with **GetHandlerInstancesFor** is passed to the **Release** method afterwards.

Of course, if the **GetHandlerInstancesFor** returns an stream instead of an array, iterating the collection again in the **Release** method will cause new instances to be created and disposed. The original instances are not disposed.

I think however that it is better to keep this method empty. As I see it, it is not the job of this **Release** method to call dispose. Since the DI container is in control of creating handlers, it should be in control of disposing them if needed. 

By default however, transient registrations are not disposed in Simple Injector. So if the user registers some disposable handlers as transient, they won't get disposed. But this still doesn't seem a concern of the **Release** method, more more a concern of the way handlers are registered.

But perhaps the most important argument for leaving the **Release** method empty is that this method has no clue whether or not those handlers should be disposed or not. What if there's a handler that is registered as singleton? You surely don't want to dispose that one, because the application will stop working directly after that.

Usually, disposing of instances happens on the boundaries of a 'request'. A request can be anything, depending on the application type, but for a web application it's quite obvious what a request is. In Simple Injector you define a scope (most often implicitly) on the boundaries of that request and this allows you to dispose instances when that scope is disposed. Perhaps this is a model that can be used for Rebus as well, but I have no idea how Rebus defines a request. Depending on how the **GetHandlerInstancesFor** method is used, you might even be able to start and finish the scope using the returned enumerable as follows:

``` c#
public IEnumerable<IHandleMessages<T>> GetHandlerInstancesFor<T>() {
    Scope scope = this.container.BeginLifetimeScope();

    try {
        var handlers = container.GetAllInstances<IHandleMessages<T>>();
        foreach (var handler in handlers) {
            yield return handler;
        }
    }
    finally {
        scope.Dispose();
    }
}
```
This allows the scoped lifestyle to be started when the enumerable is iterated and automatically disposes the scope afterwards. You can just do this:

``` c#
foreach (var handler in adapter.GetHandlerInstancesFor<MyMessage>()) [
    handler.Handle(message);
}
```
I hope this helps.

Steven

**Comment by mookid8000** [comment]
Simple Injector is supported in Rebus2 which will soon be available
