### ISSUE TITLE
samples

### ISSUE THREAD

**Issue by kiquenet** [rebus-org/Rebus#275]
Any sample console applications (Client and Server) for testing issues about MSMQ private queues ?

Console application in Client to send message and read message from/to private queue in Server.

Console application in Server to send message and read message from/toprivate queue.

Client send Message A to private Queue in Server

Server read Message A from private queue

Server sendMessage B to private queue

Client read Message B from private queue.

Console Application EXE is more easy. anyways, EXE can be installed like Windows Service in Server.

any full source code sample in github?

IMHO, the key important are good patterns and practices, and full source code samples using it 

Any final solution with full source code sample application ? IMHO, better samples for minimize learning curve are real applications with full source code and good patterns.

**Comment by mookid8000** [comment]
Thanks for your suggestions - I'll keep them in mind going forward with [the existing Rebus samples](https://github.com/rebus-org/RebusSamples)
