### ISSUE TITLE
Azure Service Bus only returns one message at a time

### ISSUE THREAD

**Issue by seankearon** [rebus-org/Rebus#285]
When using Azure Service Bus and when there is more message in the error queue, then using return to source queue will only process one message at a time.

It seems that having the [transaction scope](https://github.com/rebus-org/Rebus/blob/master/src/Rebus.ReturnToSourceQueue.AzureServiceBus/Program.cs#L242) around the message processing is stopping receipt of any further messages.

I was thinking of changing this to transaction for each message but still allow the console process all messages.  Does that seem sensible?

**Comment by mookid8000** [comment]
I guess that sounds sensible... but I wonder why it's possible to only receive one message at a time - do you know why that is?

**Comment by seankearon** [comment]
Nope - no idea why!  Will do some looking and see what I can find.

**Comment by mookid8000** [comment]
probably not relevant anymore (Rebus2 is out - things are different now)
