### ISSUE TITLE
Async overloads of all IBus methods that send messages

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#291]
E.g. so you can

```
await bus.SendAsync(someMessage);
```
and
```
await bus.Defer(5.Minutes(), someMessage);
```
etc.

**Comment by DixonD-git** [comment]
Hi @mookid8000! I started working on this in feature-send-async branch in my fork. However, I need advice. I've got a bit stuck on ITransactionContext.DoCommit when there are both synchronous and  asynchronous operations in the transaction scope now. Should it become ```event Func<Task> DoCommit;``` ? What's about AmbientTransactionContext.Commit, for instance, should it become async?

**Comment by mookid8000** [comment]
Hi @DixonD-git - I don't understand what you're saying :) but I'd like to check out your branch when I have the time. Could you maybe open a PR and then we'll keep the discussion in there?

**Comment by asgerhallas** [comment]
If you send a message async, does that mean that it will be sent before the transaction is committed? If not, is it then just for serialization and a bit of queue IO to be parallized?

(I moved this comment here, as I find it is more related to the feature as such)

**Comment by mookid8000** [comment]
good point - right now afaik there's only two transport layers that support async: SQL Server and Azure Service Bus.

SQL Server could work because there's a transaction and every message is actually sent to the server when you call `bus.Send` - therefore, `bus.SendAsync` would end up in an `await sqlCommand.ExecuteNonQueryAsync()` or something like that.

Azure Service Bus, however, does not have transactions - therefore, to avoid messages "escaping" the current unit of work, sent messages are just put in a list of outgoing messages. And then, when the transaction commits, the messages are sent.

I realize now that the async send would be nicer if we can both `await bus.SendAsync()` (which the user would have to remember to do) and `await transactionContext.CommitAsync();` (which would just be the way Rebus would do it).

**Comment by mookid8000** [comment]
closing this one for now - `async` / `await` will be first-class citizens in Rebus2 :)

**Comment by asgerhallas** [comment]
I'm so excited :) when will be on Rebus2 nuget?

**Comment by asgerhallas** [comment]
= when will Rebus2 be on nuget? :)

**Comment by dalager** [comment]
Ah. That sounds nice!
await Rebus2 then.
