### ISSUE TITLE
Async request/response handling in same handler

### ISSUE THREAD

**Issue by asgerhallas** [rebus-org/Rebus#294]
Elaborating on the async trend, I wonder if it would be an idea to support "minisagas" using async, having something like this:

```
public void Handle(InitMessage init)
  {
    var response = await bus.RequestAsync(new Request());
    response.DoSomething()

    var nextResponse = await bus.RequestAsync(new NextRequest());
    nextResponse.DoSomething(response)
  }
```

Each continuation would work as a standalone handler action, having a separate tx scope. Correlation could be handled automatically. 

Retries could be harder to do, but not impossible. The closure could be persisted and rehydrated on failure recovery or if the saga is really long running as a kind of automatic saga data.

**Comment by mookid8000** [comment]
Can you persist a continuation? If so: like what?

**Comment by mookid8000** [comment]
Interesting idea btw! :D

**Comment by IanYates** [comment]
HangFire seems to have accomplished persistence of continuations pretty well.  Worth looking there for inspiration/knowledge :)

**Comment by asgerhallas** [comment]
@IanYates Great reference, thanks! That looks like a cool project. I don't think they persist async/awaits though, but they do a lot of other neat stuff I need to check out :)

@mookid8000 it seems doable. You can get access to the state machine when implementing an awaiter. The state machine's fields has local vars and stacks and such. And I've seen examples of it being serialized/deserialized and reinvoked later. It could work, though it's a little evil.

The real problem lies in that it's not really an async handler invocation, in that it needs to commit the tx and the other stuff right after the await, and start a new tx for the next step. I'm trying it out right now for fun, and right now struggle with mixing Task-awaitables with my special awaitable and exception-handling. But it kinda works :)

**Comment by cellistlondon** [comment]
Actually the best place to look for inspiration might be the Durable Task Framework which is actually a Microsoft project: https://github.com/affandar/durabletask

**Comment by mookid8000** [comment]
@cellistlondon wow that looks really interesting!

**Comment by Plasma** [comment]
>  The closure could be persisted and rehydrated on failure recovery or if the saga is really long running as a kind of automatic saga data.

This is certainly a cool idea, but one caveat I can think of is your access to local variables and other in memory state. If the intention is an async/await will schedule a continuation command on the bus and another worker thread on another computer picks it back up, some state variables (eg db connection or other reference types) won't be restored

**Comment by asgerhallas** [comment]
Yes, that is a problem. My first thought was that is was the same Rebus instance that would pick up the task, and the continuation would not really be sent on the bus, but rather persisted locally. But the problems remain - but can be fixed by following some conventions eg injecting all "unserializable" dependencies in the handler ctor, and then have the handler newed up again from with fresh dependencies from the container or the like when the continuation is run. The handlers Handle-method will not be run again, but it will serve as context for the saved continuation. All "serializable" local vars and fields are still accessible in the continuation.

I have made a prototype a while back (on the old Rebus) where that worked, almost :) I don't know if it'll make the feature less usable. 

One thing that is actually pretty hard is knowing when a continuation should be continued in the same handler instance (eg like web service calls and other tasks that does not send new messages and commits the tx) and when it should and the tx and continue in a new tx and with a new handler instance.

**Comment by mgibas** [comment]
Isn't it defeating whole asynchronous/messages model ?

**Comment by mookid8000** [comment]
While this is a funny idea, I'm closing it for now 😄 if anyone needs something like this, we can definitely continue the discussion in here.
