### ISSUE TITLE
Allow for competing due timeouts consumers

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#295]
has already been implemented with SQL Server since 0.79.0, using a row-level update lock and readpast

something similar ought to work with Postgres

MongoDB should use findAndModify to obtain a "lease" on the due timeout

Not sure about RavenDB, though - I wonder if it's even possible

**Comment by CasperTDK** [comment]
Could you elaborate what you mean by 'lease' regarding mongoDB?
I can't see a way to avoid removing the timeout documents untill 'MarkAsProcessed' unless you do something like http://docs.mongodb.org/manual/tutorial/perform-two-phase-commits/

I've tried submitting a solution. What do you think?

**Comment by CasperTDK** [comment]
I guess you could expand the update statement to add a timestamp = now+ 100 ms - to avoid multiple consumers for a message
This would cause issues if the process hangs and not just crashes though

**Comment by mookid8000** [comment]
A common way to implement "receiving" something from MongoDB as if it was a message queue, is to use FindAndModify where you update the found document by setting a time stamp on it, which would function as a lease for, say, 1 minute or something like that.

The receiving process will then have one full minute to turn it into a timeout reply and then delete the document to complete the transaction so to speak. 



Sendt fra min iPhone

**Comment by CasperTDK** [comment]
Ah, that is what my solution did (see commits in this thread). I will make
a pull request soon

On Fri, Mar 20, 2015 at 4:26 PM, Mogens Heller Grabe <
notifications@github.com> wrote:

> A common way to implement "receiving" something from MongoDB as if it was
> a message queue, is to use FindAndModify where you update the found
> document by setting a time stamp on it, which would function as a lease
> for, say, 1 minute or something like that.
>
> The receiving process will then have one full minute to turn it into a
> timeout reply and then delete the document to complete the transaction so
> to speak.
>
>
>
> Sendt fra min iPhone
>
> > Den 20/03/2015 kl. 07.12 skrev Casper Thygesen <notifications@github.com
> >:
> >
> > I guess you could expand the update statement to add a timestamp = now+
> 100 ms - to avoid multiple consumers for a message
> > This would cause issues if the process hangs and not just crashes though
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rebus-org/Rebus/issues/295#issuecomment-84048905>.
>



-- 
Med venlig hilsen
Casper

**Comment by mookid8000** [comment]
Cool!

(I'm on a mini-vacation for the extended weekend, so I'm just replying to GitHub's notifications:))

Sendt fra min iPhone

> Den 20/03/2015 kl. 16.45 skrev Casper Thygesen <notifications@github.com>:
> 
> Ah, that is what my solution did (see commits in this thread). I will make
> a pull request soon
> 
> On Fri, Mar 20, 2015 at 4:26 PM, Mogens Heller Grabe <

**Comment by mookid8000** [comment]
this is solved in Rebus2 :)
