### ISSUE TITLE
Adding support for SQS transport

### ISSUE THREAD

**Issue by jasperdk** [rebus-org/Rebus#296]
Using the Amazon Cloud stack it could be great to have a Amazon SQS transport implementation for Rebus.

**Comment by jasperdk** [comment]
Has anybody looked at this before? Especially I would like to hear if someone think SQS doesn't fulfill the requirements for being a Rebus transport mechanism. Delivered at least once and no guarantee for ordered delivery shouldn't be an issue for Rebus or I am wrong?

**Comment by mookid8000** [comment]
I'd be very surprised if SQS did not support everything that Rebus needs to function correctly.

There's a differences in how the various queueing systems handle "transactions" - some use transactions, some use a lease on a received message that can be used to acknowledge having handled the message.

Rebus does not have any requirements wrt ordering.

**Comment by jasperdk** [comment]
Cool. SQS use a lease on the received message.

**Comment by mookid8000** [comment]
There is Amazon SQS support in Rebus 2 ;)

**Comment by mookid8000** [comment]
(which is not available yet (as of June the 7th 2015) but it will be soon..)

**Comment by romanych** [comment]
Hi @mookid8000. Do you have any estimate in Rebus 2 publishing?

**Comment by mookid8000** [comment]
unfortunately, no - but if you are willing to be an early alpha tester, you can have a bunch of packages to play around with.... would you be interested in trying it out?
