### ISSUE TITLE
Azure ServiceBus connection string in *.config file

### ISSUE THREAD

**Issue by mgibas** [rebus-org/Rebus#298]
It would be nice to handle servicebus connection string stored in *.config file and use only it name:

```csharp
.Transport(t => t.UseAzureServiceBusInOneWayClientMode("myEndpointConnectionString")
```

**Comment by mookid8000** [comment]
Rebus2 does not provide app.config support out of the box because of the planned port to dnxcore that doesn't have app.configs

Maybe something can be worked out later, but for now I'll close this one
