### ISSUE TITLE
More functional Unity container for Rebus

### ISSUE THREAD

**Issue by nykkel** [rebus-org/Rebus#303]
We wanted to use our present unity container using Rebus. The current implementation in Rebus.Unity does not allow resolving handlers that implement the IHandleMessages<> interface unless you explicitly register the interface since Unity does not drill down the inheritence chain. 

for any handler implementing IHandleMessages<>
Register<THandler>()

for inline implementations..
Handle<TMessage>(Action<TMessage> handler)

.. just as the BuiltInContainerAdapter.

If there are others that need this behaviour of a Rebus adapter for Unity here is the implementation.

    public class UnityContainerAdapter : IContainerAdapter, IDisposable
    {   
        public IBus Bus { get; internal set; }
        
        private readonly IUnityContainer _unityContainer;
        private readonly IHandlerRegistrator _handlerRegistrator;

        public UnityContainerAdapter(IUnityContainer unityContainer)
        {
            _unityContainer = unityContainer;

            _handlerRegistrator = _unityContainer
                .AddNewExtension<AllThatImplements>()
                .Configure<IHandlerRegistrator>();
        }

        public IEnumerable<IHandleMessages> GetHandlerInstancesFor<T>()
        {
            return _unityContainer.ResolveAll<IHandleMessages<T>>();
        }

        public void Release(IEnumerable handlerInstances)
        {
            foreach (IDisposable disposable in handlerInstances.OfType<IDisposable>())
                disposable.Dispose();
        }

        public void SaveBusInstances(IBus bus)
        {
            Bus = bus;
            _unityContainer.RegisterInstance(typeof(IBus), bus);
            _unityContainer.RegisterType<IMessageContext>(new InjectionMember[1]
            {
                new InjectionFactory(c => (object) MessageContext.GetCurrent())
            });
        }

        public UnityContainerAdapter Register<THandler>()
        {
            _handlerRegistrator.RegisterImplementingType<THandler>(typeof(IHandleMessages<>));
            return this;
        }

        public UnityContainerAdapter Handle<TMessage>(Action<TMessage> handler)
        {
            _unityContainer.RegisterType<IHandleMessages<TMessage>, HandlerMethodWrapper<TMessage>>(Guid.NewGuid().ToString(), new InjectionConstructor(handler));
            return this;
        }

        internal class HandlerMethodWrapper<T> : IHandleMessages<T>
        {
            private readonly Action<T> _action;

            public HandlerMethodWrapper(Action<T> action)
            {
                _action = action;
            }

            public void Handle(T message)
            {
                _action(message);
            }
        }

        public void Dispose()
        {
            _unityContainer.Dispose();
        }

        #region - Unity Extionsion -
        internal class AllThatImplements : UnityContainerExtension, IHandlerRegistrator
        {
            protected override void Initialize() { }

            public void RegisterImplementingType<T>(Type implementationToLookFor)
            {
                var closedType = typeof(T);

                closedType.GetInterfaces()
                          .Where(x => x.IsGenericType)
                          .Where(x => x.GetGenericTypeDefinition() == implementationToLookFor)
                          .ToList()
                          .ForEach(x => Container.RegisterType(x, closedType, Guid.NewGuid().ToString()));
            }
        }

        internal interface IHandlerRegistrator : IUnityContainerExtensionConfigurator
        {
            void RegisterImplementingType<T>(Type inheritedTypeToLookFor);
        }
        #endregion
    }

/Nykkel

**Comment by mookid8000** [comment]
I'm sorry, but to be honest I don't really understand what this one is about - if you're still working with Rebus and Unity, could you maybe check out Rebus2 (versions 0.90.* and onwards) and its Unity container adapter to see if it still lacks something?
