### ISSUE TITLE
ActiveMQ transport

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#309]

**Comment by P47Phoenix** [comment]
Are there any plans to create an ActiveMQ transport

**Comment by mookid8000** [comment]
No concrete plans at the moment 😞 

Are you using ActiveMQ yourself? Would you be interested in helping with building an ActiveMQ transport for Rebus?

**Comment by P47Phoenix** [comment]
I would be interested in making a provider for ActiveMQ. I am hearing of plans o use ActiveMQ at work and would like to use Rebus for the solution.

**Comment by mookid8000** [comment]
🙌 

It's not easy to get right, but it's not hard either 😃 

It's basically about implementing [`ITransport`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Transport/ITransport.cs), but with some subtleties around transactions. 

If you're interested in getting started, I can set up a repository that you can fork, and then we can collaborate on making this happen. What do you say about that?

**Comment by P47Phoenix** [comment]
Sounds good.

**Comment by mookid8000** [comment]
As a starting point, I suggest you start looking at how the RabbitMQ transport is implemented: https://github.com/rebus-org/Rebus.RabbitMq/

You can include Rebus' contract tests by including the [`Rebus.Tests.Contracts`](https://www.nuget.org/packages/Rebus.Tests.Contracts/5.0.0-b06) package, and then all of the contract tests can be brought in and executed like this: https://github.com/rebus-org/Rebus.RabbitMq/blob/master/Rebus.RabbitMq.Tests/RabbitMqTransportBasicSendReceive.cs

I suggest you start out simple, though, and then implement some simple request/reply tests.
