### ISSUE TITLE
Rebus.AzureStorageQueues 0.90.0 nuget error

### ISSUE THREAD

**Issue by torangel** [rebus-org/Rebus#310]
*Unable to find a version of 'Microsoft.Data.Edm' that is compatible with 'Microsoft.Data.OData 5.6.4 constraint: Microsoft.Data.Edm (= 5.6.4)', 'Rebus.AzureStorageQueues 0.90.0*

To reproduce:
VS2015=>new console app (net 4.5.2)

PM> install-package rebus.AzureStorageQueues
Attempting to gather dependencies information for package 'rebus.AzureStorageQueues.0.90.0' with respect to project 'ConsoleApplication5', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'rebus.AzureStorageQueues.0.90.0' with DependencyBehavior 'Lowest'
install-package : Unable to find a version of 'Microsoft.Data.Edm' that is compatible with 'Microsoft.Data.OData 5.6.4 constraint: Microsoft.Data.Edm (= 5.6.4)', 'Rebus.AzureStorageQueues 0.90.0 constraint: Micro
soft.Data.Edm (≥ 5.6.2 && < 5.6.3)'.
At line:1 char:1
+ install-package rebus.AzureStorageQueues
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by mookid8000** [comment]
Argh, bummer! NuGet.org had trouble accepting me push the packages, and I must have forgotten to manually re-push 0.90.1 of Rebus.AzureStorageQueues...

[I have pushed it now](http://www.nuget.org/packages/Rebus.AzureStorageQueues/) - it should be available as soon as NuGet's indexer comes by or you explicitly update to 0.90.1

Thanks for reporting it! :+1:

**Comment by torangel** [comment]
Successfully installed 'Rebus.AzureStorageQueues 0.90.1' to ConsoleApplication5

:)

**Comment by mookid8000** [comment]
:+1:
