### ISSUE TITLE
Add support for Azure Service Bus subscriptions

### ISSUE THREAD

**Issue by DixonD-git** [rebus-org/Rebus#319]
Currently only simple queues are supported. It would be great if subscriptions for topics are supported as well

**Comment by mookid8000** [comment]
You are right, it would be great.

I'll see if I can figure out a nice way to do this - would be pretty nice with RabbitMQ topics as well

**Comment by DixonD-git** [comment]
I don't know about RabbitMQ, but as for Service Bus subscriptions, they can be identified by path like (SomeTopic)/Subscriptions/(SomeSubscription). So in AzureServiceBusTransport, we can just check the format of the queue name provided and use proper Service Bus API then. What do you think?

**Comment by mookid8000** [comment]
are you thinking that the input queue would simply be specified as some subscription then?

**Comment by DixonD-git** [comment]
Yes, something like that. I think it is a kind of the easiest way since we don't need to change Rebus API in this case.

**Comment by mookid8000** [comment]
I'm sure it can be done without changing the Rebus API - I think I have a plan, I'll elaborate tomorrow :)

-
Sendt fra min iPhone

**Comment by mookid8000** [comment]
I'm thinking that the current transport could be augmented with special handling of `bus.Subscribe`, `bus.Ubsubscribe`, and `bus.Publish` by

- [ ] hooking up an implementation of `ISubscriptionStorage` that claims to be centralized, which will then create an ASB subscription on `bus.Subscribe`
- [ ] extend the `AzureServiceBusTransport` to receive messages from its input queue AND all of its subscriptions at the same time (basically just extend the existing prefetch mechanism)
- [ ] hook into `bus.Publish` by having the implementation of `ISubscriptionStorage` return one recognizable address as the subscriber address - e.g. something like `subscriptions/<topic>`
- [ ] make the `AzureServiceBusTransport` use `TopicClient` to publish on a topic when the destination address has the `subcriptions/<topic>` format

This way, "legacy mode" could be kept, and the ASB topic-based mode could be optionally enabled (or the other way around)

**Comment by mookid8000** [comment]
oh, it's going to be simpler than that if [auto-forwarding](https://msdn.microsoft.com/en-us/library/azure/jj687471.aspx) is used...

i.e. `bus.Subscribe` would ensure the topic exists, create a subscription, and then configure auto-forwarding from that subscription to the endpoint's own input queue

**Comment by mookid8000** [comment]
if you're interested, you can try out the new topic-based Azure Service Bus transport in version 0.90.8

**Comment by DixonD-git** [comment]
I guess, this won't work if the application lacks permissions to create queues e.g. it has permissions to read from specific subscription only and nothing else. I'm mentioning this, because that the case for me:)

**Comment by mookid8000** [comment]
Oh, I see... well ... having learned from my previous experiences with the RabbitMQ transport, I don't think the current Azure Service Bus transport should be augmented to support that pretty specific scenario.

I suggest you create your own Azure Service Bus transport for this scenario, possibly by simply copying the code of the existing transport and then adding a few modifications to instantiate it with the name of a topic and a subscription instead of the current input queue.

I will be happy to help you if you're interested :)
