### ISSUE TITLE
Return to source queue tools

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#322]
should be command line tool - would be nice if there was one for each transport available

- [x] MSMQ
- [x] RabbitMQ
- [x] Azure Service Bus
- [x] Azure Storage Queues

**Comment by mookid8000** [comment]
Simple MSMQ flavored forklift added.... more to come!

**Comment by mookid8000** [comment]
bam!

**Comment by jpierson** [comment]
What about MS SQL Server?

**Comment by mookid8000** [comment]
I've used SQL Server Management Studio myself to do this, simply by updating the `recipient` .. I thought it was so easy that I could not imagine that anyone would need something else. 

Is there anything in particular that you would like to be able to do?

Sendt fra min iPhone

**Comment by jpierson** [comment]
Without knowing how the information in the message header is affected by returning to source queue, I suppose I made the assumption that there was more to it. I suppose knowing the source queue would at least require that some funky T-SQL to pull it out or to do it on the side that is issuing the request by reading the message manually and deserializing the header.

**Comment by mookid8000** [comment]
Oh yes, you are absolutely right. 

The headers do not have to be changed when returning to source queue, so that's not a problem.

But if you want to be able to return a bunch of messages to their respective source queues based on the source queue information from the headers, then yes - you would have to write some pretty funky SQL.

I don't know if the upcoming [JSON support](https://msdn.microsoft.com/en-us/library/dn921897.aspx?f=255&MSPPError=-2147217396) can help with that.

If you really really want a CLI app to help you with the messages, I suggest you take a look at the existing [CLI app for Azure Service Bus](https://github.com/rebus-org/Rebus/tree/master/Rebus.Forklift.AzureServiceBus) - it doesn't take that many lines of code to activate one of Rebus' transport implementations (`SqlServerTransport` in this case) and make the CLI app work with that.

Let me know if you need any further hints 😄

**Comment by jpierson** [comment]
Thanks I've forked in preparation for creating a forklift implementation for SQL Server but in the immediate term I'm going to take the shortcut of updating the recipient as mentioned because we are interested in being able to cherry pick messages to return to source queue.
