### ISSUE TITLE
Migration from 0.84

### ISSUE THREAD

**Issue by mgibas** [rebus-org/Rebus#325]
Is there any instruction/help for 0.84 => 0.9X migration ?

**Comment by mookid8000** [comment]
well... you should be able to upgrade your endpoints one at a time to 0.92.3, if you configure it to

    .Options(o => o.EnableLegacyCompatiblity())

which will cause version >= 0.92.3 endpoints to receive/send messages in the old format.

I haven't tested this thoroughly though, so please be careful and do some testing before you start upgrading a production environment.

(PS: the legacy compability only works with JSON serialization and might be broken if you've customized too many things - therefore, please do your testing :))

**Comment by mookid8000** [comment]
I'd be grateful if you would tell be about your experiences migrating, and also please don't hesitate to get in touch if you need help

**Comment by mgibas** [comment]
First, I have problem with compilation :)
I saw that many namespaces and interfaces changed and some I can fix without any problem but still have issues with those:

- Can not find  ```IStartableBus```
- Does not compile: ```configurer.Serialization(s => s.UseJsonSerializer())```
- Does not compile: ```configurer.Transport(t => t.UseTheFileSystemAndGetInputQueueNameFromAppConfig(...))```
- Does not compile: ```configurer.MessageOwnership(m => m.FromRebusConfigurationSection())```
- Does not compile: ```configurer.Subscriptions(c => c.StoreInXmlFile(Path.Combine(... , ...)))```

**Comment by mookid8000** [comment]
`IStartableBus` is not there anymore - if you need to separate building the configuration and starting the bus, you can hold on to the `RebusConfigurer` instance and then just call `Start()` on it when you're ready.

No need to configure JSON serialization - that's the default :)

New Rebus unfortunately does not have a file system transport (yet). I suggest you use MSMQ or a local SQL Server instead. 

Message ownership can be configured in code by doing something like this:

    .Routing(r => r.TypeBased()
                   .MapAssemblyOf<SomeMessage>(someEndpoint)
                   .MapAssemblyOf<AnotherMessage>(anotherEndpoint))

in the configuration API, or - if you want to keep doing the mapping in XML in your app.config, you can bring in the [`Rebus.XmlConfig`](https://www.nuget.org/packages/Rebus.XmlConfig/) package which adds the ability to

    .Routing(r => r.TypeBased().AddEndpointMappingsFromAppConfig())

although you're required to change the assembly name and the namespace of the configuration section declaration at the top (don't worry, Rebus XmlConfig will help you ;))

Last thing: If you want to store subscriptions in a file, Rebus can store them in a JSON file now - just go

    .Subscriptions(s => s.UseJsonFile(someFilePath))

**Comment by mgibas** [comment]
Thanks, this is basically what I was looking for. ```FileSystemTransport``` is crucial for our project, so we would need to wait for that one. Any plans/ideas when it should be migrated from old src?
