### ISSUE TITLE
Update to Official C# driver for MongoDB 2.0.1

### ISSUE THREAD

**Issue by kevbite** [rebus-org/Rebus#326]
The new MongoDB driver supports TPL to stop IO blocking. I've forked the repository to have a little dig in to a solution and doesn't seem that hard.

http://docs.mongodb.org/ecosystem/drivers/csharp/

Once I've got it all working i could submit a pull request.

Cheers,

Kev

**Comment by mookid8000** [comment]
awesome! :+1: :sunglasses:

**Comment by mookid8000** [comment]
let me know if you need help or anything

**Comment by mookid8000** [comment]
release in 0.93.0 - thanks :+1:
