### ISSUE TITLE
Running Rebus in the cloud

### ISSUE THREAD

**Issue by seankearon** [rebus-org/Rebus#333]
I'm looking to get rid of having to have a VM around to run the bus and have been wondering if there are any examples of how to run Rebus in some kind of cloud based compute facility?  Something like Azure Websites would be ideal if that's (1) possible and (2) sensible.  Failing that, whatever makes sense really!

PS: I've not upgraded yet, but Rebus2 is looking awesome! :)

**Comment by mookid8000** [comment]
I've run Rebus in a couple of Azure Web Sites myself, and it is a) possible, b) sensible, and c) pretty cool! 

Just remember to flick on the "Always On" switch (only available on the Standard tier), or create a scheduler that pings your site periodically.

**Comment by mookid8000** [comment]
Moreover, you should of course remember to shut down the bus properly (either by disposing the `IBus` instance or the container holding it) when the application shuts down.

You know what, I'll write a blog post about it tomorrow :)

**Comment by seankearon** [comment]
You know what - you're a star - thanks :)

**Comment by mookid8000** [comment]
I've written [this blog post](http://mookid.dk/oncode/archives/4008) now - please let me know if you think something is missing :)

**Comment by seankearon** [comment]
Nice one, thanks very much for that.  I'll be giving that a try pretty soon and ditching my VM!  Nothing is missing that I can see.  Will post back if I find anything when implementing it. :)

**Comment by torangel** [comment]
It is also possible to host rebus inside a azure webjob.
https://azure.microsoft.com/en-us/documentation/articles/web-sites-create-web-jobs/

You can then benefit from autoscaling features (cpu, queuelength, etc). Since a azure-webjob can be a simple console-program it is also easy to test the job locally before deploying to azure.

(Remember to use the "always on" feature of the website and mark the job to run "continously")

**Comment by mookid8000** [comment]
@torangel true :) I do like the ability to git-deploy my backend along with the web site, though, which was not possible with webjobs the last time I used them

**Comment by seankearon** [comment]
@torangel - so, are you saying that the webjob does not need to be triggered by a queue entry or http call, and that can be configured to be constantly running?  Am I right in thinking that the Rebus bus inside that webjob is then just a "normal" bus as if I was running it locally in a console app?

**Comment by mookid8000** [comment]
Rebus running inside a continuous webjob instance would be just as normal as Rebus running inside the web process.

In fact, webjobs are running inside the IIS - this fact can be verified if you visit the Kudu SCM portal associated with your website.

If you host your Rebus endpoint inside a webjob, please be sure to set up a background timer that watches for the existence of a file at the path specified by the environment variable `WEBJOBS_SHUTDOWN_FILE` and properly disposes the container holding the bus.

**Comment by seankearon** [comment]
Nice - that sounds like another good option.  Especially as it looks like you can FTP deploy webjobs (from Octopus in my case).  Thanks for the tip on the shutdown file too. :)

**Comment by torangel** [comment]
@mookid8000 `WEBJOBS_SHUTDOWN_FILE` was new to me. Thanks :+1:

**Comment by mattwhetton** [comment]
I'd love to see an example of using rebus in a webjob if anybody has one

**Comment by mookid8000** [comment]
I recently needed to run Rebus in a webjob, which made me finish Topper: https://github.com/rebus-org/Topper

Topper was originally meant to be a wrapper for Topshelf, which would allow me to host an arbitrary number of services(*) and not bother with the Topshelf configuration every time, and then I extended it to be able to run as a proper Azure webjob too.

---
(*) A "service" in Topper is just an object that implements `IDisposable` – i.e. you would probably just use the ctor to initialize an IoC container and start a bus instance, and then use the `Dispose` method to dispose the container.

**Comment by mattwhetton** [comment]
I had literally just found Topper and was spinning up a sample - great!

**Comment by mookid8000** [comment]
Super 😁 let me know how it works out for you

**Comment by mattwhetton** [comment]
Topper has worked painlessly so far - I've got the conitnuous web job runnning handling events and commands from an azure storage queue. Automatically deploying via VSO. Works really well!

**Comment by mookid8000** [comment]
I'm happy to hear that 😄
