### ISSUE TITLE
Seemingly random IIS crashes

### ISSUE THREAD

**Issue by sniffdk** [rebus-org/Rebus#336]
We are running Rebus v. 0.98.2 on a web project, and for some reason we experience that the IIS is crashing rather often at seemingly random times.
I've checked the Windows event log and found the following:

```
Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
Stack:
   at System.Data.ProviderBase.DbConnectionInternal.PrePush(System.Object)
   at System.Data.ProviderBase.DbConnectionPool.PutObject(System.Data.ProviderBase.DbConnectionInternal, System.Object)
   at System.Data.ProviderBase.DbConnectionInternal.CloseConnection(System.Data.Common.DbConnection, System.Data.ProviderBase.DbConnectionFactory)
   at System.Data.SqlClient.SqlConnection.Close()
   at Rebus.Persistence.SqlServer.DbConnectionWrapper.Dispose(Boolean)
   at Rebus.Persistence.SqlServer.DbConnectionWrapper.Finalize()
```

We are initializing Rebus like this:

```
Configure.With(new AutofacContainerAdapter(container))
    .Logging(l => l.Serilog(Log.Logger))
    .Transport(t => t.UseSqlServer("Project.Aux", "RebusMessages", "Web"))
    .Routing(r => r.TypeBased().MapAssemblyOf<StartImportMessage>("default"))
    .Options(o => o.SetNumberOfWorkers(1))
    .Start();
```

Hopefully this means something to you :)
If you need me to provide any more info, just let me know, I'd be happy to help.

Cheers
Mads

**Comment by mookid8000** [comment]
Jesus! I'll see if I can figure out what's happening... stay tuned :)

**Comment by sniffdk** [comment]
Thanks, much appreciated :)

**Comment by mookid8000** [comment]
As far as I can tell, the process crashes because the connection is closed from a finalizer - I've realized that it's actually wrong to implement disposal this way, because the finalizer must only release _unmanaged_ resources.

I've made Rebus' disposal of stuff more consistent across the board - hopefully that solves this problem. If not, I'll have to investigate further.

**Comment by mookid8000** [comment]
(PS: my build server is running the tests now - if they're good, I'll push 0.98.3 to NuGet.org in a few minutes...)

**Comment by sniffdk** [comment]
awesome, thanks !
I'll be sure to report back :)

**Comment by mookid8000** [comment]
0.98.3 is on NuGet.org now - I'm looking forward to hearing how it goes.... :)

**Comment by sniffdk** [comment]
Great, thanks a lot :)
I'll be attending coldfrontconf.com tomorrow and Thursday, but i'll report back as soon as I have the chance.

**Comment by sniffdk** [comment]
So, since we updated to 0.98.3 we haven't had a single IIS crash, thanks a lot !! :+1: :smile:

**Comment by mookid8000** [comment]
excellent! thanks for reporting the issue in the first place!
