### ISSUE TITLE
Trying to upgrade to 0.98.3 from 0.84 and have som problems

### ISSUE THREAD

**Issue by Sumomannen** [rebus-org/Rebus#338]
In 0.84 i wrote like this:

			Configure.With(new WindsorContainerAdapter(container))
					.Logging(l => l.NLog())
					.Transport(t => t.UseMsmqAndGetInputQueueNameFromAppConfig())
					.Timeouts(t => t.StoreInMemory())
					.Subscriptions(t => t.Use(new RavenDbSubscriptionStorage(RavenStore.DocumentStore, "RebusSubscriptions")))
					.Sagas(t => t.Use(new RavenDbSagaPersister(StatsStore.DocumentStore)))
					.MessageOwnership(d => d.FromRebusConfigurationSection())
					.CreateBus().Start();

and trying to do the same in 0.98.3 and think it's something like this:

			Configure.With(new CastleWindsorContainerAdapter(container))
					.Logging(l => l.NLog())
					.Transport(t => t.UseMsmq("InQueueName"))
					//.Timeouts(t => t.StoreInMemory())
					.Subscriptions(t => t.StoreInRavenDb(RavenStore.DocumentStore))
					//.Sagas(t => )
					.Routing(r => r.TypeBased()
					.MapAssemblyOf<StartSession>("AnOtherQueueName"))
					.Start();

but how should Timeouts and Sagas be now? I want my Sagas to use another RavenDb Store. Can you guide my in the right direction.

**Comment by Sumomannen** [comment]
One more question, on this page it says that I should use:
if(!IsNew) return;

https://github.com/rebus-org/Rebus/wiki/Coordinating-stuff-that-happens-over-time

but in 0.98.3 I can't find the property IsNew in Saga, we don't need it anymore?

**Comment by mookid8000** [comment]
I'm sorry, but there's no RavenDB saga storage yet - the timeout and subscription storages were contributed, but unfortunately they didn't come with a saga storage too.

And you are right that `IsNew` does not exist in Rebus 2 yet - I'll see to it that it gets re-introduced.

**Comment by Sumomannen** [comment]
Oh okey thanks for the quick answer!.

How far away is an implementation of "RavenDb saga storage"? Is it a big job?

**Comment by mookid8000** [comment]
yeah well, kind of - I haven't personally looked at it yet, but if I get the time I can take a look later today.

**Comment by mookid8000** [comment]
0.98.4 will be available on NuGet.org shortly with `IsNew` :) thanks for requesting that one :+1: 

I've created #340 to bring back the RavenDB saga storage

**Comment by Sumomannen** [comment]
:+1: Awesome
