### ISSUE TITLE
Bring back RavenDB saga storage

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#340]
just do it

**Comment by Sumomannen** [comment]
1 vote up for this one =)

**Comment by bjomi** [comment]
Is something happening with this?

**Comment by mookid8000** [comment]
it's not done - I did mess around a little bit in the [ravendb-sagas branch](https://github.com/rebus-org/Rebus/tree/feature/ravendb-sagas)... don't remember why I stopped though

If anyone is interested in helping out, it would be awesome :)

**Comment by bjomi** [comment]
Okay, thanks for fast reply. I would really need this. Ideally done by somebody else though :) Any problems you can recall?

**Comment by mookid8000** [comment]
Only "problem" is RavenDB's missing ability to have proper unique constraints on values within a document, which calls for using a separate collection to store correlation property documents.

It can be done though, it just requires more manual labor than when using other databases.

**Comment by bjomi** [comment]
Yeah, but the UniqueContraints bundle works great. Removes all the manual stuff, the bundle does all the booking keeping.

**Comment by mookid8000** [comment]
true - but I don't think Rebus should depend on having any bundles enabled on the server - isn't that bad RavenDB client style?

**Comment by bjomi** [comment]
Hmmm... might depend on who you ask. UniqueConstraints is a official bundle. It's in the Ravendbs official documentation so if you ask me I wouldn't call it an external dependency.

http://ravendb.net/docs/article-page/3.0/csharp/server/bundles/unique-constraints

**Comment by mookid8000** [comment]
Added the "up-for-grabs" label because it is

* is probably a few hours of work for one who knows RavenDB well
* is not depended upon by core logic or other critical things (just yet :wink: )
* is pretty well-described

As mentioned previously in this thread, I did some work in the [feature/ravendb-sagas](https://github.com/rebus-org/Rebus/tree/feature/ravendb-sagas/) branch, creating the necessary tests + added a skeleton for the saga persister.

I don't know enough about RavenDB to finish this task at the moment, and I am not going to use the persister myself anytime soon.

**Comment by mookid8000** [comment]
I guess I can close this one, [now that it has been added](https://github.com/rebus-org/Rebus/blob/master/CHANGELOG.md#09922) :+1: 

Excellent work!
