### ISSUE TITLE
Extensible, pluggable, and flexible retry strategies

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#342]
No matter how #341 ends, it would be neat if Rebus could

- [ ] when a message fails for the first time (*): based on the message context and the caught exception, decide on a `RetryStrategy` to apply
- [ ] persist the chosen `RetryStrategy` in a tracker (can be persistent somewhere centralized, allowing errors to be tracked among multiple workers)
- [ ] leave it to the `RetryStrategy` implementation to decide what to do whenever a new error occurs
- [ ] instanced derived from `RetryStrategy` should be serializable, allowing for keeping a persistent instance per message that is currently undergoing an intelligent retry workflow

The API could be shaped similarly to how the transport message forwarder works, i.e. by providing a function that gets context + info and returns some kind of `RetryAction` - an imaginary implementation could look like this:

```
public class ExponentialBackoffRetryStrategy : RetryStrategy
{
    static readonly TimeSpan[] DefaultBackoffTimes = {
        TimeSpan.FromSeconds(1),
        TimeSpan.FromSeconds(2),
        TimeSpan.FromSeconds(4),
        TimeSpan.FromSeconds(8),
        TimeSpan.FromSeconds(16)
    };

    public int NextBackoffIndex { get; set; }
    public TimeSpan[] BackoffTimes { get; set; }

    public override void Initialize(IMessageContext context)
    {
        BackoffTimes = DefaultBackoffTimes;
        NextBackoffIndex = 0;
    }

    public override RetryAction GetAction(IMessageContext context, Exception caughtException)
    {
        var index = NextBackoffIndex++;

        if (index < BackoffTimes.Length)
        {
            var deferTime = BackoffTimes[index];
            return RetryAction.Defer(deferTime);
        }

        return RetryAction.MoveToErrorQueue;
    }
}
```

---
(*) or maybe not until the 1st level retries are over? dunno....

**Comment by MrMDavidson** [comment]
I'd definitely agree with moving the retry logic into an interface people can override / extend. The current mechanism of just trying again means that transient errors often end up as fatal errors.

Also in our implementation we have 2 worker queues. We have the `Input` which has its error queue set as `Error`. We then have the `Error` queue which has its error queue set to `Poison`. Additionally we insert an `ErrorTransformStep` into the `Error` queue's receive pipeline. What that does is transform the message from a `TMessage` to an `Error<TMessage>`;

```C#
public class Error<TMessage> {
  public TMessage Original { get;set; }
  // For some applications it might be useful to include the last exception, too
  //public Exception LastException { get; set; }
}
```

What this means is that non-transient errors can have application level hooks. Imagine something like;

```C#

public class ChargeCreditCardHandler : IHandleMessages<ChargeCreditCardCommand>, IHandleMessages<Error<ChargeCreditCardCommand>> {

  public Task Handle(ChargeCreditCardCommand command) {
    // Do something with an external system which might throw if the remote system is down
  }

  public Task Handle(Error<ChargeCreditCardCommand> command) {
    OrderService.CancelOrder(command.Original.OrderNumber);
  }
}
```

Really powerful technique as we need to worry less about retry / exception handling at the application level and instead just have truly exceptional cases handled by the `Error<TMessage>` handler.

```C#
[StepDocumentation("Transforms the message from type TMessage to Error<TMessage> so handlers can react to fatal errors")]
public class ErrorTransformStep : IIncomingStep {
	private static readonly MethodInfo WrapMethodInfo;
	private static readonly ConcurrentDictionary<Type, MethodInfo> MethodCache = new ConcurrentDictionary<Type, MethodInfo>();

	static ErrorTransformStep() {
		WrapMethodInfo = typeof(ErrorTransformStep).GetMethod("Wrap", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly);
		if (WrapMethodInfo == null) {
			throw new Exception("Could not find Wrap method.");
		}
	}

	/// <summary>
	/// Carries out whichever logic it takes to do something good for the incoming message :)
	/// </summary>
	public Task Process(IncomingStepContext context, Func<Task> next) {
		Message oldMessage = context.Load<Message>();
		object oldBody = oldMessage.Body;
		
		TransportMessage transportMessage = context.Load<TransportMessage>();
		if (transportMessage == null)
		{
			throw new Exception("Pipeline misconfigured");
		}

		object newBody = WrapAsError(oldBody);
		Message newMessage = new Message(oldMessage.Headers, newBody);
		newMessage.Headers[Headers.Type] = newBody.GetType().GetSimpleAssemblyQualifiedName();

		context.Save(newMessage);

		return next();
	}

	public object WrapAsError(object inner) {
		Type type = inner.GetType();
		MethodInfo cacheCall = MethodCache.GetOrAdd(
			type,
			t => WrapMethodInfo.MakeGenericMethod(t)
		);

		return cacheCall.Invoke(this, new object[] { inner, null });
	}

	private Error<TMessageType> Wrap<TMessageType>(TMessageType message, Exception ex) {
		return new Error<TMessageType>(message, ex);
	}
}
```

**Comment by mookid8000** [comment]
I love it!

I love the idea of using `Error` as a type amplifier for messages!

I'm thinking that this must be usable somehow - just like you're doing it, but without the extra queue.... the really simple (but maybe too simple) thing to do would be to `Error`-wrap the message after the first initial failed delivery attempts to see if there was a handler that wanted to do something about it before moving it to the error queue.

This could actually be how you would customize the retry strategy - instead of the very specialized (and thus constrained) solution I sketched above, one could imagine a customized retry strategy like this:

```
public class HandleSomeSpecificError : IHandleMessages<Error<SomethingWeCareAbout>> {
	readonly IBus _bus;

	public HandleSomeSpecificError(IBus bus) {
		_bus = bus;
	}	

	public async Task Handle(Error<SomethingWeCareAbout> error) {
		if (error.Exception is ConcurrencyException) {
			await _bus.Advanced.TransportMessage.Defer(TimeSpan.FromSeconds(5));
			return;
		}

		await _bus.Advanced.TransportMessage.ForwardToErrorQueue();
	}
}
```

and even more advanced stuff that works in distributed scenarios and does other interesting things could be implemented simply as a saga that correlates with the ID of the failed message.

I'll think some more about this .... I've got a feeling that we're on to something cool :grin:

**Comment by mookid8000** [comment]
PS: There's no `bus.Advanced.TransportMessage` API yet :) don't know if that's how it's going to be, but there should be an API for doing stuff with the raw transport message some time in the future

**Comment by MrMDavidson** [comment]
I would say you'd want to requeue the `Error<T>` message into the queue after initial failure but as to if it goes to an Error queue or back to the Input queue (with counters, id, etc, reset) would probably depend on the application. One advantage of having it in a specific Error queue is that (hopefully!) that's much less heavily used than the input queue so you get quicker notification of those errors at the application level. I'd suggest either making it a config option on the error handling where "errored" messages go or providing an easy wrapped up way for people to transform a message to an `Error<TMessage>` (which might require the context of the original message as you may want to keep the correlation id / set the correlation id to the original message's id) and then choose their own queue in their error handler like you provided.

The other thing I'd recommend is even if the error selection stuff is implemented as a plain `IHandleMessages<...>` handler for developer discover-ability maybe create a marker interface;

```C#
public interface IDetermineWhatHappensToErrorsOf<TMessage> : IHandleMessages<Error<TMessage>> {
}
```

(But with a far more sensible name! Heh)

**Comment by mookid8000** [comment]
For now (in 0.98.7) I've made it so that you can

    Configure.With(...)
        .(...)
        .Options(o => o.SimpleRetryStrategy(secondLevelRetriesEnabled: true))
        (...)

which will cause failed messages to be tracked on two levels - first, the ordinary retries, and then an equal number of delivery attempts as a `Failed<TMessage>`.

ATM there's not really anything interesting in this besides the 2nd level delivery attempts, which enables you to e.g. forward the message or defer it.

Let's see if there's something missing - I'll close this one for now :)
