### ISSUE TITLE
How can i implement unit of work for message handlers?

### ISSUE THREAD

**Issue by oguzhaneren** [rebus-org/Rebus#346]
The old version of Rebus had Unit of work manager. How can i implement unit of work for message handlers? (Enlist with current rebus queue transaction)

**Comment by mookid8000** [comment]
Thanks for asking :) I've added some more info to the wiki: https://github.com/rebus-org/Rebus/wiki/Unit-of-work 

and I've created a sample that demonstrates how it can be done: https://github.com/rebus-org/RebusSamples/tree/master/UnitOfWork

Some time in the future I may build an API around handling the unit of work pattern, which will use the approach described on the wiki and in the sample underneath the covers.
