### ISSUE TITLE
Bring back FileSystem transport

### ISSUE THREAD

**Issue by mgibas** [rebus-org/Rebus#347]
Please :heart_eyes:

**Comment by mookid8000** [comment]
Try going
```
Configure.With(...)
    .Transport(t => t.UseFileSystem(pathToSharedDirectory, "myQueueName"))
    .Start();
```

Not sure if anyone is using it (or even if anyone has tried it ;))

**Comment by mgibas** [comment]
We are using it in our company :) It has many pros:
- efficient (SSD...)
- super easy to setup
- convenient way of taking a look at message
- convenient way to replay failing messages
- 0 configuration when installing on clients computers - no extra infrastructure.

If I only need to message through single machin/network there is no point of using anything else :) Please don't event think about dropping it!

**Comment by mookid8000** [comment]
cool! :+1: :grin:
