### ISSUE TITLE
Missing SubscribeByScanningForHandlers in 9.X

### ISSUE THREAD

**Issue by mgibas** [rebus-org/Rebus#348]
Is there any 9.XX equivalent ?

**Comment by mookid8000** [comment]
You are right that there's no assembly scanning since >= 0.90.0. 

I'm not sure I want to add it because it's so little, and I believe it's going to be removed again when I port Rebus to .NET core.

This should work for most scenarios:

```
var assemblyToScan = Assembly.GetExecutingAssembly();

var handledMessageTypes = assemblyToScan
    .GetTypes()
    .SelectMany(t => t.GetInterfaces()
        .Where(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof (IHandleMessages<>))
        .Select(i => i.GetGenericArguments().Single()))
    .Distinct()
    .ToList();

foreach (var messageType in handledMessageTypes)
{
    bus.Advanced.Topics.Subscribe(messageType.GetSimpleAssemblyQualifiedName());
}
```

**Comment by mgibas** [comment]
Does it mean that I would need to configure bus using topics ?

**Comment by mookid8000** [comment]
No - there's topics underneath it all, no matter what you do - the `GetSimpleAssemblyQualifiedName()` is how the type-based router gets a topic out of a type :)

**Comment by mgibas** [comment]
Thats great - thanks
