### ISSUE TITLE
Azure Service Bus serialization interop support

### ISSUE THREAD

**Issue by Meyce** [rebus-org/Rebus#349]
Use Streams for the ser/deserialization of the TransportMessage to BrokeredMessage and vice versa.  This will improve the interop support between different platforms/languages.  NServiceBus has a similar issue due to the usage of BrokeredMessage.  See the referenced link for more detail.

https://github.com/Particular/NServiceBus.AzureServiceBus/issues/49

I've cloned the repo and made an update to the AzureServiceBusTransport and switching to Streams works fine, but making a change would have impact to production systems.  If you have any thoughts on how to work around this please let me know.

**Comment by mookid8000** [comment]
PR as fast as you can ;)

no, seriously - Rebus2 has not stabilized so much yet that I see this as a problem, so I will happily accept your pull request right away!

**Comment by Meyce** [comment]
I'll try to get a PR done this afternoon.

**Comment by mookid8000** [comment]
:+1: :smiley:

**Comment by Meyce** [comment]
I'm getting a 403 trying to publish a branch with the changes.

**Comment by mookid8000** [comment]
Did you fork the repository?

**Comment by Meyce** [comment]
No I branched.  I'll fork it.  Sorry, first time contributing.

**Comment by mookid8000** [comment]
no problem :) let me know if you need any more assistance

**Comment by Meyce** [comment]
Will do.

**Comment by Meyce** [comment]
update released in 99.
