### ISSUE TITLE
ThreadWorkers doesn't handle LogicalContext as expected

### ISSUE THREAD

**Issue by AndreaCuneo** [rebus-org/Rebus#352]
Hi,

migrating to new version of Rebus, I've incurred in quite a big problem.

What happens is that if I use LogicalCallContext to track of the correlation-id in NLog across Tasks, it doesn't work. 
This currently works on old Rebus where I set the correlationID as per Log4Net.

I suppose it is dependent on the custom syncronization context used by ThreadWorkers but my knowledge on that is a bit limited atm. 
Maybe you could help me figuring it out. I think ExecutionContext need to be used.

Scenario:
- Before a Send() I set a variable in the LogicalCallContext (using NLog.MappedDiagnosticsLogicalContext).
- This variable is picked by a custom pipeline outgoing step that put that into the correlation-id.
- On receiving a message, a custom pipeline incoming step put the correlation-id in the MappedDiagnosticsLogicalContext.
- Therefore I expect the correlation-id flow through all out application message pipeline.

I've configured NLog to log the variable set in the MappedDiagnosticsLogicalContext on each log.

I've prepared a sample test application based on AzureServiceBus, but you can replicate it with other transports.

http://filebin.ca/2ICWseXVa8oh

Each message contains the expected correlation-id in it's body. I've logged in the Trace.log file:
1) the correlation ID from the LogicalCallContext handled by the pipeline
2) the correlation ID from the LogicalCallContext setted by the IMessageHandler as first statement using the one taken from the message
3) the correlation ID saved in the body of the message

Format:    date          - ThreadID - CorrelationFromPipeline - CorrelationFromMessage -        MsgX[CorrelationFromMessage]
2015-10-06 15:22:34.8642 -    7     -           8             -           8            - DEBUG: Msg1[8]: After send await

I expect the three correlation values to always be equals, but they are not. The correlationID flows through messages correctly, the only issue is with the LogicalContext to be tampered.

**Comment by mookid8000** [comment]
Hi Andrea - I'm sorry, but I am pretty tired right now and I have not completely read & understood what you wrote.... I'll revisit it tomorrow when my brain is up to the task :)

One thing did strike me as sounding like it was overly complicated - iirc NLog has a way of providing "ambient" information into each log event... can't remember it completely, but I remember it as something similar to Serilog's [event enrichers](https://github.com/serilog/serilog/wiki/Enrichment).

With Serilog, I could do it like this:

    public class RebusCorrelationIdEnricher : ILogEventEnricher
    {
        public void Enrich(LogEvent logEvent, ILogEventPropertyFactory factory)
        {
            var correlationid = MessageContext.Current?
                .TransportMessage.Headers
                .GetValueOrNull(Headers.CorrelationId);

            if (correlationid == null) return;

            logEvent.AddOrUpdateProperty(factory.CreateProperty("CorrelationId", correlationid));
        }
    }


as in: just get called for each log line, and add the context if it's present.

But again: I'm very tired, didn't understand all you wrote - I'll get back to you tomorrow :)

**Comment by mookid8000** [comment]
Oh, I just did this: Added a [Serilog log event enricher](https://github.com/rebus-org/Rebus/blob/master/Rebus.Serilog/RebusCorrelationIdEnricher.cs) that does what I described, and [a neat configuration extension](https://github.com/rebus-org/Rebus/blob/master/Rebus.Serilog/SerilogConfigurationExtensions.cs#L28-L35) that hooks into Serilog's configuration syntax and allows for enabling it.

You would call it like this:

    // create static global base logger
    Log.Logger = new LoggerConfiguration()
        .Enrich.WithRebusCorrelationId("CorrelationId")
        .CreateLogger();

    // inside each class:
    static readonly ILogger Logger = Log.ForContext<EachClass>();

Maybe something similar could be devised for NLog? and possibly including some configuration smoothness....?

**Comment by mookid8000** [comment]
now I'm going to bed :zzz: :crescent_moon:

**Comment by AndreaCuneo** [comment]
Hi Mogens,

first, have a good night! :)

Thanks for looking into this. My idea is more or less like Serilog, done
via a custom NLog step only in the incoming pipeline.
The rest I've described has been done to test why was not working.

The NLog "way" for logging the correlation-id in each message is to put
that in the logical call context so that I can format any log from any
logger using that. Like ThreadLocal for Log4Net but the follow the async
flow. And for this I use a NLog extension that do so. This is more or less
the same way the Identity is flown across async calls in Asp.Net etc. And
this works in Rebus 1 (for the record, done with a decorator). The problem
is that the LogicalCallContext is not preserved in Rebus 2 and this
actually brings me also other problems since my application use that to
flow across async calls some "stuff" (nothing critical, mostly diagnostic
contexes for metrics).

In the test code you'll find a NLogStep class for pipeline. Actually only
the IncomingStep is needed for integrating with Rebus 2.
All the rest was a way to understand where the logical context was getting
tampered.

For this I've:
1) Generated the correlation-id myself (just an int)
2) Put that in the body of a pipeline of 3 messages: Msg1 => Msg2 => Msg3
3) Set the outgoing correlation-id using an outgoing step in the pipeline
(this could have been done in many other ways, I know)
4) As first statement of each Handle, I take the correlation-id from the
body of the message and put it manually in another item of the
LogicalCallContext.

This way I've two variables I can log in each log that have been inserted
in the LogicalCallContex in different moments of the async state machine.
Plus the correlation-id from the body of the message that I log directly in
the log message.

The expected output is that both the variable in the LogicalCallContext are
equals to the one logged in the string. Instead they are different an they
both change at a different rate. This means that the LogicalCallContext is
tampered multiple times else both the variables would have been always the
same value.

As you can see from the code, I've also tried to both use
ConfigureAwait(false) or not, to see if something was fishy with the
captured synchronization context. No luck.

My idea is that your custom synchronization context doesn't restore the
ExecutionContext when processing the Posted callback from the bag.

P.S Yes, I'm sure I could have written a better test project, but I was
banging my head on this for too long to have something clean after all. :)






On Wed, Oct 7, 2015 at 10:31 PM Mogens Heller Grabe <
notifications@github.com> wrote:

> now I'm going to bed [image: :zzz:] [image: :crescent_moon:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rebus-org/Rebus/issues/352#issuecomment-146319253>.
>
-- 
_____________________________________
*Andrea Cuneo*
*Energy & Asset Management Practice*

cell (Italy): +39 3470837612 website: http://www.ark-energy.it Nel rispetto
e per gli effetti del D. Lgs 196/2003, Vi informiamo che il contenuto della
presente è riservato esclusivamente al destinatario, restando a chiunque
altro interdetto trattenerlo, copiarlo, diffonderlo od altrimenti
utilizzarlo. Vi segnaliamo che, qualora il destinatario voglia eliminare
dal nostro archivio il Suo indirizzo e-mail, è invitato a darcene notizia.
The information contained in this message is confidential and may be
legally privileged. It is intended solely for the addressee. Access to this
message by anyone else is unauthorized. If you are not the intended
recipient, any disclosure, copying or distribution of this message, or any
action or omission taken by you in reliance on it, is prohibited and may be
unlawful.Please immediately contact the sender if you have received this
message in error.

**Comment by mookid8000** [comment]
I'm not an expert on the call context things, but I do know that `CallContext.LogicalGetData` and `CallContext.LogicalSetData` can be used to flow things to continuations. This is the mechanism that Rebus relies on in order to have the `ITransactionContext` flow properly.

I've dug a little bit into NLog, and I've created a `RebusCorrelationIdLayoutRenderer` which is an NLog `LayoutRenderer` that picks up the current correlation ID if possible.

It's included in Rebus 0.99.1, which is on NuGet.org right now, and it can be used by configuring the ordinary NLog stuff:

    Configure.With(...)
        .Logging(l => l.NLog()) //< registers the layout renderer if it has not been registered already
        .(...)

and then having something like this in your app.config:

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog"/>
  </configSections>
  <nlog>
    <targets>
      <target name="f" type="file" fileName="${basedir}/logs/logfile.log"
              layout="${longdate}|${level}|${logger}|${rebus-correlation-id}|${message}"  />
    </targets>
    <rules>
      <logger name="*" minLevel="Info" appendTo="f"/>
    </rules>
  </nlog>
</configuration>
```

Could you try out that one and see if it works as it should?

(PS: If you do your NLog configuration in code, you might need to register the layout renderer manually before you come too far in your configuration - you can do that with `RebusCorrelationIdLayoutRenderer.Register()`)

**Comment by AndreaCuneo** [comment]
Hi Mogens,

thanks, I'll test the renderer asap and let you know.

But maybe I was not clear: NLog is not the problem, it's the symptom. If I
use the LogicalCallContext at the start of any Handle to set a variable so
that I can flow that through the async calls (metric counters / identity /
application transaction context), that doesn't work. I've seen that in NLog
at first, but is not only NLog related.

Thanks,
Andrea
*_____________________________________*
*Andrea Cuneo*
Lead Technical Architect

<http://www.ark-energy.eu/>

cell (Italy): +39 348 750 7841
website: http://www.ark-energy.eu

The information contained in this message is confidential and may be
legally privileged. It is intended solely for the addressee. Access to this
message by anyone else is unauthorized. If you are not the intended
recipient, any disclosure, copying or distribution of this message, or any
action or omission taken by you in reliance on it, is prohibited and may be
unlawful.Please immediately contact the sender if you have received this
message in error.

Nel rispetto e per gli effetti del D. Lgs 196/2003, Vi informiamo che il
contenuto della presente è riservato esclusivamente al destinatario,
restando a chiunque altro interdetto trattenerlo, copiarlo, diffonderlo od
altrimenti utilizzarlo. Vi segnaliamo che, qualora il destinatario voglia
eliminare dal nostro archivio il Suo indirizzo e-mail, è invitato a darcene
notizia.

On Thu, Oct 8, 2015 at 10:52 PM Mogens Heller Grabe <
notifications@github.com> wrote:

> I'm not an expert on the call context things, but I do know that
> CallContext.LogicalGetData and CallContext.LogicalSetData can be used to
> flow things to continuations. This is the mechanism that Rebus relies on in
> order to have the ITransactionContext flow properly.
>
> I've dug a little bit into NLog, and I've created a
> RebusCorrelationIdLayoutRenderer which is an NLog LayoutRenderer that
> picks up the current correlation ID if possible.
>
> It's included in Rebus 0.99.1, which is on NuGet.org right now, and it can
> be used by configuring the ordinary NLog stuff:
>
> Configure.With(...)
>     .Logging(l => l.NLog()) //< registers the layout renderer if it has not been registered already
>     .(...)
>
> and then having something like this in your app.config:
>
> <?xml version="1.0" encoding="utf-8" ?>
> <configuration>
>   <configSections>
>     <section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog"/>
>   </configSections>
>   <nlog>
>     <targets>
>       <target name="f" type="file" fileName="${basedir}/logs/logfile.log"
>               layout="${longdate}|${level}|${logger}|${rebus-correlation-id}|${message}"  />
>     </targets>
>     <rules>
>       <logger name="*" minLevel="Info" appendTo="f"/>
>     </rules>
>   </nlog>
> </configuration>
>
> Could you try out that one and see if it works as it should?
>
> (PS: If you do your NLog configuration in code, you might need to register
> the layout renderer manually before you come too far in your configuration
> - you can do that with RebusCorrelationIdLayoutRenderer.Register())
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rebus-org/Rebus/issues/352#issuecomment-146681795>.
>
-- 
_____________________________________
*Andrea Cuneo*
*Energy & Asset Management Practice*

cell (Italy): +39 3470837612 website: http://www.ark-energy.it Nel rispetto
e per gli effetti del D. Lgs 196/2003, Vi informiamo che il contenuto della
presente è riservato esclusivamente al destinatario, restando a chiunque
altro interdetto trattenerlo, copiarlo, diffonderlo od altrimenti
utilizzarlo. Vi segnaliamo che, qualora il destinatario voglia eliminare
dal nostro archivio il Suo indirizzo e-mail, è invitato a darcene notizia.
The information contained in this message is confidential and may be
legally privileged. It is intended solely for the addressee. Access to this
message by anyone else is unauthorized. If you are not the intended
recipient, any disclosure, copying or distribution of this message, or any
action or omission taken by you in reliance on it, is prohibited and may be
unlawful.Please immediately contact the sender if you have received this
message in error.

**Comment by mookid8000** [comment]
oh, sorry - but the thing is that I don't think `LogicalCallContext` is the way to go if you want stuff to flow across `await`s

`CallContext.LogicalSetData`/`CallContext.LogicalGetData` is, as far as I know, the only thing that works the way we want it to work in this case.

But, as I said: I'm not an expert on this. I've just observed through trial and error that `CallContext.LogicalSetData`/`CallContext.LogicalGetData` was the only thing that I could use to flow Rebus' transaction context properly.

**Comment by mookid8000** [comment]
I'll just close this one for now - please reopen if it was not fixed... thanks for reporting the issue by the way, Rebus' NLog logging got better :)

**Comment by AndreaCuneo** [comment]
oh, now I understand the misunderstanding. LogicalCallContext ==
CallContext.Logical{G,S}etData.

The LogicalCallContext is managed internally by the CallContext. And the
Nlog extension I mentioned use the CallContext like Rebus, but somehow in a
wrong way. (stores a dictionary in the context).

I've traced the problem to NLog.MappedDiagnosticsLogicalContext. The
strange thing is that it was working fine in the old version of Rebus, for
that I presumed it was related to the change in the worker factory.
Something in the new version of Rebus triggers a bug in
MappedDiagnosticsLogicalContext.

Well, I'll open a bug to NLog. Thanks a lot for you patience!

Btw: Rebus.NLog links NLog 4.1 but the nuget package dependency is still
[3,4).


Thanks,
Andrea
*_____________________________________*
*Andrea Cuneo*
Lead Technical Architect

<http://www.ark-energy.eu/>

cell (Italy): +39 348 750 7841
website: http://www.ark-energy.eu

The information contained in this message is confidential and may be
legally privileged. It is intended solely for the addressee. Access to this
message by anyone else is unauthorized. If you are not the intended
recipient, any disclosure, copying or distribution of this message, or any
action or omission taken by you in reliance on it, is prohibited and may be
unlawful.Please immediately contact the sender if you have received this
message in error.

Nel rispetto e per gli effetti del D. Lgs 196/2003, Vi informiamo che il
contenuto della presente è riservato esclusivamente al destinatario,
restando a chiunque altro interdetto trattenerlo, copiarlo, diffonderlo od
altrimenti utilizzarlo. Vi segnaliamo che, qualora il destinatario voglia
eliminare dal nostro archivio il Suo indirizzo e-mail, è invitato a darcene
notizia.

On Fri, Oct 9, 2015 at 10:06 PM Mogens Heller Grabe <
notifications@github.com> wrote:

> I'll just close this one for now - please reopen if it was not fixed...
> thanks for reporting the issue by the way, Rebus' NLog logging got better :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rebus-org/Rebus/issues/352#issuecomment-146974742>.
>
-- 
_____________________________________
*Andrea Cuneo*
*Energy & Asset Management Practice*

cell (Italy): +39 3470837612 website: http://www.ark-energy.it Nel rispetto
e per gli effetti del D. Lgs 196/2003, Vi informiamo che il contenuto della
presente è riservato esclusivamente al destinatario, restando a chiunque
altro interdetto trattenerlo, copiarlo, diffonderlo od altrimenti
utilizzarlo. Vi segnaliamo che, qualora il destinatario voglia eliminare
dal nostro archivio il Suo indirizzo e-mail, è invitato a darcene notizia.
The information contained in this message is confidential and may be
legally privileged. It is intended solely for the addressee. Access to this
message by anyone else is unauthorized. If you are not the intended
recipient, any disclosure, copying or distribution of this message, or any
action or omission taken by you in reliance on it, is prohibited and may be
unlawful.Please immediately contact the sender if you have received this
message in error.

**Comment by mookid8000** [comment]
Oh sorry, I'll fix the nuspec right away

-
Sendt fra min iPhone

> Den 12. okt. 2015 kl. 16.13 skrev AndreaCuneo <notifications@github.com>:
> 
> oh, now I understand the misunderstanding. LogicalCallContext ==
> CallContext.Logical{G,S}etData.
> 
> The LogicalCallContext is managed internally by the CallContext. And the
> Nlog extension I mentioned use the CallContext like Rebus, but somehow in a
> wrong way. (stores a dictionary in the context).
> 
> I've traced the problem to NLog.MappedDiagnosticsLogicalContext. The
> strange thing is that it was working fine in the old version of Rebus, for
> that I presumed it was related to the change in the worker factory.
> Something in the new version of Rebus triggers a bug in
> MappedDiagnosticsLogicalContext.
> 
> Well, I'll open a bug to NLog. Thanks a lot for you patience!
> 
> Btw: Rebus.NLog links NLog 4.1 but the nuget package dependency is still
> [3,4).
> 
> 
> Thanks,
> Andrea
> *_____________________________________*
> *Andrea Cuneo*
> Lead Technical Architect
> 
> <http://www.ark-energy.eu/>
> 
> cell (Italy): +39 348 750 7841
> website: http://www.ark-energy.eu
> 
> The information contained in this message is confidential and may be
> legally privileged. It is intended solely for the addressee. Access to this
> message by anyone else is unauthorized. If you are not the intended
> recipient, any disclosure, copying or distribution of this message, or any
> action or omission taken by you in reliance on it, is prohibited and may be
> unlawful.Please immediately contact the sender if you have received this
> message in error.
> 
> Nel rispetto e per gli effetti del D. Lgs 196/2003, Vi informiamo che il
> contenuto della presente è riservato esclusivamente al destinatario,
> restando a chiunque altro interdetto trattenerlo, copiarlo, diffonderlo od
> altrimenti utilizzarlo. Vi segnaliamo che, qualora il destinatario voglia
> eliminare dal nostro archivio il Suo indirizzo e-mail, è invitato a darcene
> notizia.
> 
> On Fri, Oct 9, 2015 at 10:06 PM Mogens Heller Grabe <

**Comment by mookid8000** [comment]
I've fixed the NLog dependency now - thanks for pointing it out :)
