### ISSUE TITLE
How do i implement Custom topic exchange in RabbitMQ Rebus2?

### ISSUE THREAD

**Issue by dotnetdude** [rebus-org/Rebus#354]
I am trying to implement something similar to [stackoverflow question](http://stackoverflow.com/questions/14772877/how-to-make-rebus-play-nice-with-a-custom-topic-exchange-in-rabbitmq ) asked long time before. The suggested answer is not going to work for me as the solution supports rebus 1. How do I implement the same on Rebus 2?

**Comment by mookid8000** [comment]
What what you like to be able to do? And why?

(just asking so I can understand, and maybe suggest some way of making it work with Rebus2....)

**Comment by dotnetdude** [comment]
In my scenario, I need to send message to different subscribers. At run time, the publisher will decide  where to send the message. I can able to implement easily with different routing key using rabbitmq client. But i am trying to use the Rebus framework to achieve the same.

**Comment by mookid8000** [comment]
Could you give an example with some concrete values that you might use, as in some concrete topics and routing keys?

**Comment by dotnetdude** [comment]
I am trying to implement the following topic exchange example explained in this [blog post](https://lostechies.com/derekgreer/2012/03/28/rabbitmq-for-windows-exchange-types/) 
![GitHub Logo](http://lostechies.com/derekgreer/files/2012/03/TopicExchange2.png) 
In my case, the producer need to send message to different stores. it only knows at run time which store to send the message. if the publisher routing key contains store1.store2 the message will be processed by store1 and store2. if the publisher routing key contains store1.store3, the message will be processed by store 1 and store 3.

**Comment by mookid8000** [comment]
I think you can use Rebus2's advanced topics API to do that - check out [the RabbitMQ topics sample I just made](https://github.com/rebus-org/RebusSamples/tree/master/RabbitTopics)

In the sample I

    await bus.Advanced.Topics.Subscribe("mercedes.#");

which subscribes the endpoint to messages published on the `mercedes.bmw.vw` topic like so:

    await bus.Advanced.Topic.Publish("mercedes.bmw.vw", "This one should be received by all!");

Do you think that could work?

**Comment by dotnetdude** [comment]
Thanks a lot for your code and sample example. But I need slightly different routing keys. 

    subscriber1.Bus.Advanced.Topics.Subscribe("mercedes.#").Wait();
    subscriber2.Bus.Advanced.Topics.Subscribe("*.mitsubishi.*").Wait();
    subscriber3.Bus.Advanced.Topics.Subscribe("*.*.honda").Wait();


    topicsApi.Publish("mercedes.mitsubishi.honda", "This one should be received by all!").Wait();
    topicsApi.Publish("mercedes.mitsubishi.car", "This one should be received by 1 & 2").Wait();
    topicsApi.Publish("mercedes.car.honda", "This one should be received by 1 & 3").Wait();

The same routing keys working fine in rabbitmq client and working as expected. But not in Rebus. Am i doing anything wrong?

By looking at the pub/sub model with wildcard routing keys, looks like it will be hard to for me to add another car model, with out changing all the routing keys. Instead stick with pub sub model and if Honda receives a Mitsubishi message and ignores it. Whats your suggestion to design a messaging system that has to send a message to different subscribers at run time? 

Thanks for your help.

**Comment by mookid8000** [comment]
If you've tried using the wildcars keys both with Rebus and with RabbitMQ directly, could you try and compare the bindings in the management console?

E.g. when I run the RabbitMqTopics sample on my machine, the bindings for `endpoint2` look like this:

![image](https://cloud.githubusercontent.com/assets/32968/10863457/a97854c2-7fce-11e5-95c6-136c739c4c8e.png)

I'm not an expert on RabbitMQ, but may Rebus' "hack" with prepending `subscription/` to all topics is somehow interfering with your wildcards?

**Comment by dotnetdude** [comment]
yeah looks like prepending "subscription/"  in the routing key is messing with the messaging. the same example i tried with rabbitmq client directly doesn't have "subscription/" in the routing key. 

Is there any way to override the default "subcription/" hack? 

Any reason why you choose Topic exchange for Pub/sub model? RabbitMQ suggest to use Fanout Exchange for Pub/Sub Model which doesn't need any hacking.

**Comment by mookid8000** [comment]
??? As far as I know, RabbitMQ fanout exchange does not use routing keys for anything, as they "fan out" all messages to all queues.....

**Comment by dotnetdude** [comment]
sorry for the confusion.  my third line was general question about rebus implementation.

In my scenario, I definitely need Topic exchange which uses bus.advanced. I need to somehow to override the default "subscription/" behavior to make it work.

 But when I go through the rebus code implementation for general pub/sub model without need for any wildcard characters, it uses topic exchange. instead of fan out exchange. May I know why?

**Comment by mookid8000** [comment]
Oh yeah, sure - Rebus uses RabbitMQ with a topic exchange because I basically want to support two modes of operation:

* 1-to-1 sending
* 1-to-n publishing

which I do by having each endpoint create its own input queue and then make appropriate bindings.

"Appropriate bindings" in this case is

* one binding to a topic of the same name as the input queue (which is then used to address this particular endpoint only)
* one binding per subscription (with the `subscription/` prefix, to be sure that it's not mixed up with the direct 1-to-1 binding)

As I'm writing this, I think I'm realizing that it should be switched around, so that the direct binding should somehow be the one that stands out, and then "proper" bindings (and corresponding topics) can be used for the pub/sub type messaging.

Don't you think that sounds sensible?

**Comment by dotnetdude** [comment]
you come up with this model, because you are trying to achieve both direct and pub-sub model with single [exchange name](https://github.com/rebus-org/Rebus/blob/master/Rebus.RabbitMq/RabbitMqTransport.cs#L24)? 

why not create rebus 1-1 exchange rebus-direct with the exchange type direct and create another rebus exchange 1-n exchange rebus-pubsub with the exchange type fanout and advanced will support any other rabbitmq message type. I am assuming following the rabbitmq implementation documentaiton will improve performance with out any routing key for pub/sub model (never tested performance over rabbitmq fanout vs rabbitmq topic with routing keys) .

I am sure the customer who is implementing, will only care about how the 1-1 and 1-n system works without any issue and perform well, when they replace some other bus with RabbitMQ. I never worked with other message buses, but I assuming the common pattern will be 1-1 and 1-n .

Sorry I am also new to the messaging system, I am just asking these questions to understand the rebus better and thanks for your quick responses.

**Comment by mookid8000** [comment]
That is actually an excellent idea! Thank you for asking these questions, it will definitely lead to a much better design.

I'll do exactly what you propose: Create two separate exchanges, one for 1-to-1, and one for pub/sub.

**Comment by dotnetdude** [comment]
Thanks. :smile: 

For 1-1 queue name and routing key can be [same](https://github.com/rebus-org/Rebus/blob/master/Rebus.RabbitMq/RabbitMqTransport.cs#L62) and for 1-n routing key will be empty. it will make the logic simple and I hope will improve the performance as well. 

you can allow users to use bus,advanced to implement  complex scenarios that may not be replaced by any other bus.

**Comment by mookid8000** [comment]
hello again mr. @dotnetdude , would you be interested in trying out a custom-built Rebus.RabbitMq NuGet package that I built just for you? :)

**Comment by mookid8000** [comment]
oh well, I could not upload a .nupkg file here, so I pushed it to NuGet.ord as 0.99.9 - I would be happy if you would try it out and see if you can make it work :)

**Comment by dotnetdude** [comment]
sure. I will give it  a try and let you know. Cheers. :+1:

**Comment by dotnetdude** [comment]
When i tried the new nuget package, the custom topic based [rabbitmq example](https://github.com/rebus-org/RebusSamples/tree/master/RabbitTopics) working fine as i expected. However, I noticed that queues are subscribed to both RebusDirect and RebusTopics. I expect that to be subscribed to Topics Only? 

![rabbit_subscribed_two_exchange](https://cloud.githubusercontent.com/assets/1378633/11031844/3ed1b7e6-86cf-11e5-88ea-dfac841d12e3.png)

so the publisher uses both exchange to send message? sorry. its really confusing me now.

**Comment by mookid8000** [comment]
It's because Rebus still supports the direct way of sending a message. 

When you `bus.Send`, the message will be published on the Direct exchange, allowing you to target one specific recipient.

When you `bus.Publish`, the message will be published on the Topic exchange, allowing you to target Rabbit-style subscriptions.

**Comment by dotnetdude** [comment]
UseRabbitMqAsOneWayClient(connectionString) => create the exchange rebusdirect and rebustopic


    UseRabbitMq(connectionString,"subscriber1") => creates the queue 


    adapter.Bus.Subscribe<T>().Wait();  subscribe to the queue.


    bus.send => send message through rebusdirect exchange.


    bus.publish => send message through redbustopic exchange.

Direct uses QueueName as routing key, pub/sub uses "message type,Message name" as routing key. Advanced uses the user's routing key.


I played with direct and pub sub and Advanced examples. All working fine. Thanks for your quick reply and quick fixes.

**Comment by mookid8000** [comment]
Excellent - good to hear that it worked out for you! 😊

Thanks for your help in making this change, which I believe has lead to a much improved design.
