### ISSUE TITLE
Better SQL transport

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#357]
The current transport has some issues with locking.

It doesn't really work that well if it takes some time to handle a message, and it looks like it's because of the transaction that is kept open for the entire duration of handling the message.

A new, improved SQL transport could use the ringbuffer approach described in [Kejser's blog post](http://kejser.org/implementing-message-queues-in-relational-databases/) and simply receive a message by taking a lease on it.

It should then automatically renew the lease in the background, like the Azure Service Bus transport does it.

And then it should commit by `null`ing the recipient column or something.

**Comment by mookid8000** [comment]
@hdrachmann you have been assigned ;)

**Comment by jeffreyabecker** [comment]
Would you be open to a Sql Server service bus implementation?

**Comment by mookid8000** [comment]
Service Broker?

Yeah sure - is it something you would like to use?

**Comment by jeffreyabecker** [comment]
I used the 'old' rebus in an app and the client is complaining about the polling on the queue table. I could probably just use msmq but it might be an interesting exercise in figuring out service broker.

**Comment by mookid8000** [comment]
Yes, definitely 😄 let me know if you need any hints to get started

**Comment by jeffreyabecker** [comment]
If IsCentralized = true on the SubscriptionStorage, will the subscribers get registered before any messages are sent to them?

**Comment by mookid8000** [comment]
It means that subscribers will register themselves directly in the subscription storage instead of sending a subscription request to the publisher (which is the default mechanism).

And yes, that could potentially avoid some funny race conditions happening when the subscribe/publish order gets mixed - since the `await bus.Subscribe<SomeMessage>()` registers the subscriber immediately, the publisher will (provided that no caching has been introduced) immediately include the subscriber when publishing events.

You can read more on [the wiki page about subscription storage](https://github.com/rebus-org/Rebus/wiki/ISubscriptionStorage).

**Comment by jeffreyabecker** [comment]
Okay. Would you want this in the main rebus package or as a separate package?

**Comment by mookid8000** [comment]
> Okay. Would you want this in the main rebus package or as a separate package?

Sorry, I'm a little confused - do you mean whether I want a SQL Server Service Broker transport in main or in a separate package?

If that is the case, I would prefer to have it in a separate package to begin with.

Later on, when it has proven its worth and it has been stabilized, we could move it into core (because it depends on good old ADO.NET only...)

**Comment by jeffreyabecker** [comment]
My first pass at a SqlServiceBroker transport is [Here](https://github.com/jeffreyabecker/Rebus/tree/SqlServiceBus). It doesn't currently support sending deferred messages so an external timeout manager is required. Adding support is possible but involves a side-table that holds the delayed messages.

**Comment by mookid8000** [comment]
Supporting it should be pretty easy because we can just enable the built in `SqlServerTimeoutStorage`

I would love to take a look at your code! I'm currently on vacation, but I think I can find time to play around with it tomorrow.

**Comment by SvenVandenbrande** [comment]
That's a long tomorrow. :)

**Comment by mookid8000** [comment]
Wow I completely forgot about this - I am so sorry!!

I am in my bed now - I will get back to this one tomorrow (not kidding - I will 😁🙄)

**Comment by SvenVandenbrande** [comment]
No problem for me. Just that we can close the issue. :)

**Comment by loneshark99** [comment]
Tomorrow never comes 😁

**Comment by mookid8000** [comment]
It has now become completely obvious to anyone watching this thread that there is something wrong with me.

@jeffreyabecker Are you using the service broker-based transport? Has it been working good for you?

**Comment by mookid8000** [comment]
(I have created [this issue](https://github.com/rebus-org/Rebus.SqlServer/issues/2) now where the work can continue... the SQL transport is no longer part of Rebus core)

**Comment by mookid8000** [comment]
PS @loneshark99 : thanks for pinging this thread once again... I needed that 😁
