### ISSUE TITLE
Readthedocs

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#359]
Check it out and see if the docs can somehow be put there

**Comment by mclausen** [comment]
Hi Mookid

We are thinking about taking the rebus bus for a ride on the current project that iam sitting at, Yay! However i cant seem to find Documentation for pub/sub scenario for azure service bus topic based routing. Could you point me in the right direction or write a little wiki page on it?

**Comment by mookid8000** [comment]
That is a decision I can get behind 👍 😁 

There really isn't anything special about pub/sub with Rebus on Azure Service Bus.... it should work the same way as when you are working with MSMQ, RabbitMQ, etc., although you will NOT need to configure a subscriptions storage (the `.Subscriptions(s => ...)` thing) and you will only have to set up endpoint mappings for messages that you intend to `await bus.Send(...)`.

**Comment by mookid8000** [comment]
But please do let me know if there is something specific that you feel is missing 😄

**Comment by mclausen** [comment]
Maybe i was thinking of a more general notion on how the pub/sub mechanism actually worked :)

I got it up and working with a `.Transport(y => y.UseAzureServiceBusAsOneWayClient(connectionString))` and then a subscribing consumer.. It's almost too easy :smile:.  Then again. I dont know if this needs to fleshed out abit more in a document?

**Comment by mclausen** [comment]
The "publish" method on the bus is not written down anywhere, so maybe its not transparent that this feature is part of the frameswork?

**Comment by zabulus** [comment]
There is lack information about configuring MSMQ to use it in pub\sub scenario on different PCs.  Requirements to subscription storage, queue names, etc.

**Comment by mookid8000** [comment]
You guys are absolutely right of course 😁

**Comment by mookid8000** [comment]
I've started working on a few pages [here](https://github.com/rebus-org/Rebus/wiki/Configuration-requirements). Let me know if you think something is missing

**Comment by mookid8000** [comment]
I think making the documentation from comments in the codebase and from the GitHub wiki would be pretty awesome, but I will probably not do anything about it myself in the near future. If anyone knows a cool way of achieving this, it would be awesome to hear about it.

**Comment by zabulus** [comment]
I like how it is done in the autofac library:
https://github.com/autofac/Documentation

**Comment by mookid8000** [comment]
For now, I have decided that the docs are fine on the GitHub wiki. I might change my mind in the future, though – especially if someone ports (at least a great portion of) the docs for me.
