### ISSUE TITLE
FileSystem Message Queue

### ISSUE THREAD

**Issue by SvenVandenbrande** [rebus-org/Rebus#362]
According to this topic on stackoverflow.
http://stackoverflow.com/questions/25690737/rebus-filesystemmessagequeue

This is already available? If not, you can see this as a backlog item. :)

**Comment by mookid8000** [comment]
[It is already available](https://github.com/rebus-org/Rebus/blob/master/Rebus/Transport/FileSystem/FileSystemTransport.cs) - just go

    Configure.With(...)
       .Transport(t => t.UseFileSystem(@"C:\data\messages", "my-input-queue"))
       .(...)

to use files in directories beneath `C:\data\messages` to communicate

**Comment by mookid8000** [comment]
Thanks for you suggestion though :) I think it's pretty funny that the file system-based transport actually started out as a fun piece at a user group meeting (where I used a shared Dropbox folder to sync files between machines) but has turned to actually be used by people for real stuff.

**Comment by SvenVandenbrande** [comment]
I am not using it. :) But i saw it on stackoverflow. And i didn't saw it in the documentation. That's why i mentioned it. :)

BTW: You saw my last mail?

**Comment by mookid8000** [comment]
yeah, sorry - I've sent you an answer :)

(short version: endpoints only create their own input queues, and there's good reasons for that - therefore, you should start the server first)
