### ISSUE TITLE
Sample ASP MVC with invoice approval

### ISSUE THREAD

**Issue by patagoniahiker** [rebus-org/Rebus#365]
Hello, can you please add an ASP MVC 4.6 sample to show how you do invoice approvals

**Comment by mookid8000** [comment]
Could you be a little more specific in your request?

I would love to provide samples for things that are of interest to the general Rebus user base.

**Comment by patagoniahiker** [comment]
Sure, :+1: I am trying to implement a scenario with a simple list (mailbox for the users), where a purchase order is requested, then approved by a manager, and routed to another dept called fulfillment.

1.  There is purchase request from an employee (fills some form)
2.  This requested need to be routed to a manager, and a role (all people in that role) - so this shows up in their invoice (can you please explain what types of sagas / design /name is this called in rebus, everyone seems to have their own names and its hard for us to follow)
3.  After approval, it goes to the designated employees, and shows up in their inboxes
4.  Views to monitor the state of the various sagas, for cleanup, or restart if hung etc

thanks

**Comment by mookid8000** [comment]
To be honest, this sounds pretty much like a very specific assignment. It you would like me to help you do that, I will happily do that if you contact my employer [d60](http://www.d60.dk/), who will be delighted to set you up with an agreement.

If you can express your problem in a more general form, I can help you right here (or by providing a sample project in the [RebusSamples](https://github.com/rebus-org/RebusSamples) repository.

**Comment by patagoniahiker** [comment]
hmm, lets see, I started with a general sample on approvals (commands) *as a sample or design pattern*; you asked that I get specific and now you complain I'm too specific. I am not sure how exactly those 4 lines would make up a commercial application unless it was homework!

Let me try another avenue, and if this does not work, no worries!

My question is, using your component **how does one orchestrate *durable* commands** and **how does one monitor the health of that orchestration**? 

Pardon me, I  am new to buses, is this a design pattern, or something custom, everyone seems to call it something different, a courier, a slip?? do you have one, or can show a sample on how this can be done.

**Comment by seankearon** [comment]
Commands are durable in Rebus by virtue of being stored in the [transport mechanism](https://github.com/rebus-org/Rebus/wiki/Transport) of your choice.

For orchestration of long running workflows, take a look at Rebus' [Sagas](https://github.com/rebus-org/Rebus/wiki/Coordinating-stuff-that-happens-over-time).

There is no built-in support for monitoring the progress (of sagas).  However, it would be easy enough to write those stats out to a table as your saga progresses.  There is also a [timeout manager](https://github.com/rebus-org/Rebus/wiki/Timeout-Manager) if that suits your needs.

Hope that helps!
