### ISSUE TITLE
Is there anyway to execute messages synchronously?

### ISSUE THREAD

**Issue by oguzhaneren** [rebus-org/Rebus#370]
Hi,

I want to replace my messaging system with Rebus but I need to execute some messages synchronously. 
 
Or do you have any idea how can I implement this?

Thanks,

**Comment by CasperTDK** [comment]
You could set your worker count to 1?
This will make sure only one message is processed from your input queue at a time.
I can show you the syntax if it is needed.

**Comment by oguzhaneren** [comment]
@CasperTDK thanks for response but this is not solution for me.

My webapi controller needs to wait until all handlers to complete.


Client -> Controller -> Bus (Tx1 Begin -> Handler1 - Handler2 -> Tx1 Complete) -> Http.OK

**Comment by CasperTDK** [comment]
Okay, then I would not recommend rebus to get involved here.
It sounds much more like you need a state between your workers (rebus) and the webcall.

I would let the Handlers write to a db storage that your webrequest monitors. So the webrequest will fire-and-forget rebus message(s) and then monitor the db. 

Solving it through rebus would require a quite complex request-reply setup.

**Comment by CasperTDK** [comment]
Also I know @mookid8000 prefers stackoverflow.com for questions, so please create a ticket (tag: rebus) there if we should proceed with this question :smile:

**Comment by oguzhaneren** [comment]
http://stackoverflow.com/questions/34018494/is-there-anyway-to-execute-messages-synchronously

**Comment by mookid8000** [comment]
:+1: thanks (already answered the question on SO)
