### ISSUE TITLE
Simple Injector Verify Issuee

### ISSUE THREAD

**Issue by oguzhaneren** [rebus-org/Rebus#374]
Hi,

My configuration like this:

     _container = new Container();
     _rebusBus = Configure.With(new SimpleInjectorContainerAdapter(_container))
                                     .Logging(l => l.NLog())
                                     .Transport(sc =>
                                     {
                                         var connectionString = _config.Get("Bus.Transport.ConnectionString");
                                         var tablename = "rebus-queue";
                                         var inputQueueName = "main-queue";
                                         sc.UseSqlServer(connectionString, tablename, inputQueueName);
                                     })
                                     .Subscriptions(ss =>
                                     {
                                         var connectionString = _config.Get("Bus.Subscriptions.ConnectionString");
                                         var tablename = "rebus-subscriptions";
                                         ss.StoreInSqlServer(connectionString, tablename);
                                     })
                                     .Start();
                                     
    _container.Verify();

When I call <pre>_container.Verify();</pre>, Rebus throw exception

<pre>
An exception of type 'System.InvalidOperationException' occurred in SimpleInjector.dll but was not handled in user code

Additional information: The configuration is invalid. Creating the instance for type IMessageContext failed. The registered delegate for type IMessageContext threw an exception. Attempted to inject the current message context from MessageContext.Current, but it was null! Did you attempt to resolve IMessageContext from outside of a Rebus message handler?
</pre>

**Comment by mookid8000** [comment]
The exception is caused by the fact that `MessageContext.Current` returns `null` when called outside of a Rebus handler.

As it turns out, [there is an easy solution to this issue](http://stackoverflow.com/a/21601811/6560), which I've implemented in Rebus 0.99.19 which will be on NuGet.org as soon as the build server has finished munching through the tests.

**Comment by mookid8000** [comment]
Thanks for reporting this issue btw :+1: :smiley:
