### ISSUE TITLE
Exception not included in SimpleRetryStrategy

### ISSUE THREAD

**Issue by bjomi** [rebus-org/Rebus#376]
Hi,

we're trying to implement a strategy for retrying failed messages. The thing is that we programatically, based on what exception that was thrown, need to decide if we should retry or not. But, the Failed<TMessage> class does not include the exception, just the stack trace (or some version there of). Is there a good reason for this? We were discussing implementing our own retry strategi, but there are quite a few interfaces to implement and the simple strategy implementation does the job except for the missing exception. Please advise about what to do.

@jsvahn

**Comment by mookid8000** [comment]
from 0.99.67, `IFailed<TMessage>` will have an `Exceptions` property, which is an `IEnumerable<Exception>` 😄

**Comment by bjomi** [comment]
Awesome! Great job.

On Fri, Jul 1, 2016 at 7:21 AM, Mogens Heller Grabe <
notifications@github.com> wrote:

> from 0.99.67, IFailed<TMessage> will have an Exceptions property, which
> is an IEnumerable<Exception> 😄
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rebus-org/Rebus/issues/376#issuecomment-229856286>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAYmzc1OLuvmfkYE8or-gV3APl2Jg0v8ks5qRKPMgaJpZM4Gx878>
> .
>



-- 
*Björn Milton*, CEO & Founder

bjorn@roombler.com
Phone: +46 702 35 54 35
Twitter: @bjomi <http://twitter.com/bjomi>
Facebook: facebook.com/roombler

Strandgatan 1
621 57 Visby
