### ISSUE TITLE
Could not load file or assembly 'RabbitMQ.Client, Version=3.5.4.0, Culture=neutral, PublicKeyToken=89e7d7c5feba84ce'

### ISSUE THREAD

**Issue by houwenlong789** [rebus-org/Rebus#379]
I create a web project and I use following package:

  package  id="RabbitMQ.Client" version="3.5.6" targetFramework="net451" 
  package id="Rebus" version="0.99.20" targetFramework="net451"
  package id="Rebus.Castle.Windsor" version="0.99.20" targetFramework="net451" 
  package id="Rebus.RabbitMq" version="0.99.20" targetFramework="net451" 

But error occur:
Could not load file or assembly 'RabbitMQ.Client, Version=3.5.4.0, Culture=neutral, PublicKeyToken=89e7d7c5feba84ce' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by houwenlong789** [comment]
I find the problem.
Rebus.RabbitMq use  RabbitMQ.Client  whice is  version of 3.5.4 . But I use version of  3.5.6.

**Comment by mookid8000** [comment]
If you use NuGet to manage your packages, it should automatically maintain the necessary binding redirects in your application configuration file.

I've sometimes tried that it messes it up, so sometimes I've found it necessary to do a

    update-packages <some-package> -reinstall

**Comment by mookid8000** [comment]
Let me know if you continue having problems :)

**Comment by gertjvr** [comment]
Just run add-bindingredirects just add the binding redirects into your cofig file. Worked for me :)

**Comment by houwenlong789** [comment]
@gertjvr  Thank you for good advise.
