### ISSUE TITLE
AzureServiceBusConfigurationExtensions fails to use Connectionstring from config file

### ISSUE THREAD

**Issue by AggeKA** [rebus-org/Rebus#382]
This is just a minor bug:
[the line](https://github.com/rebus-org/Rebus/blob/master/Rebus.AzureServiceBus/Config/AzureServiceBusConfigurationExtensions.cs#L142-142) should be ```return connectionStringSettings.ConnectionString;```

**Comment by mookid8000** [comment]
[it's been fixed](https://github.com/rebus-org/Rebus/blob/master/Rebus.AzureServiceBus/Config/AzureServiceBusConfigurationExtensions.cs#L137) - thanks :wink:
