### ISSUE TITLE
Publish on no existing subscriptions in subscriptionstorage

### ISSUE THREAD

**Issue by rasmuschristensen** [rebus-org/Rebus#384]
Hi,

In Rebus/Rebus/Persistence/SqlServer/SqlServerSubscriptionStorage.cs -> GetSubscriberAddresses called during publish, there is no "warning/error" if there is no subscriptions. Is this by design?

**Comment by mookid8000** [comment]
yes :)

Generally you will use pub/sub messaging when the publisher does not care whether there are any subscribers, thus providing a high degree of decoupling.

You can say that it is the responsibility of the subscribers to ensure that they're correctly subscribed.

With that said - I can easily understand why you in some cases would like a warning about this situation. You can do that, but only in those cases where Rebus manages the subscriptions - e.g. with RabbitMQ and Azure Service Bus, Rebus has no (easy) way of knowing whether anyone were subscribed to a message that was published.

**Comment by mookid8000** [comment]
If you want to be sure that someone is processing some particular message, I suggest you `await bus.Send(...)` it instead

**Comment by rasmuschristensen** [comment]
Thanks! Will migrate to send!

**Comment by mookid8000** [comment]
I can recommend that you always keep a clear distinction between _commands_ and _events_.

Commands are usually named in the imperative, e.g. "SendEmail", "ProcessOrder", etc. You will always `bus.Send` these.

Events are named in the past tense, e.g. "InvoicePaid", "ItemShipped", etc. You will always `bus.Publish` these.

If you do this, natural order will follow :+1:
