### ISSUE TITLE
Routing automap

### ISSUE THREAD

**Issue by replaysMike** [rebus-org/Rebus#385]
I was looking for a good way to decouple the message classes when using a single queue - and thought about adding the ability to automatically default route messages to a queue without explicitly naming the types.

I don't know if it already exists, or if there's a reason this might not be a good idea but it might look something like:

```
config
    .Transport(t => t.UseMsmq(thisQueue))
    .Routing(r => r.TypeBased()
        .MapAssemblyOf<TestMessageReques1t>(queueName));
        .MapAssemblyOf<TestMessageRequest2>(queueName));
        .MapAssemblyOf<TestMessageRequest3>(queueName));
```

could read more like:
```
config
    .Transport(t => t.UseMsmq(thisQueue))
    .Routing(r => r.TypeBased()
    .MapAll(queueName));
```

**Comment by mookid8000** [comment]
It doesn't exist (yet) in Rebus, but it could definitely be supported.

By default, the router will throw an exception if an unmapped message type is sent. I'm thinking that your function could be thought of as a "catch-all mapping", a fallback that kicks in if no explicit mapping was found?

This way, the configuration could be 

    .Routing(r => r.TypeBased()
        .MapAssemblyOf<SomeMessageAssembly>("somequeue")
        .Map<SomeParticularMessageType>("anotherqueue")
        .MapAll("fallbackqueue"))

What do you think?

Maybe the name "`MapAll`" is not so good then, although I'm not sure I can come up with a better name :)

**Comment by IanYates** [comment]
`.MapFallback()`, `.MapDefault()` or even `.MapOtherwise()`

Probably fallback is a good one since you used the word yourself in the example queue name for `.MapAll()`

**Comment by IanYates** [comment]
Probably worth writing out a log event at an information (or even warning?) level whenever a fallback mapping is used so, if it wasn't desired, it can still be noticed.  Although I suppose then that the developer just shouldn't use the catch all mapping :)

**Comment by mookid8000** [comment]
I would not log a warning because the developer, as you said, did explicitly go and configure a fallback

**Comment by mookid8000** [comment]
but I think this `MapWhatever("somequeue")` method would make a nice addition to the routing API

**Comment by replaysMike** [comment]
yea I think your suggestions make sense. It would really be nice for those of us using a single queue, just being able to map them all without specifying an explicit mapping and having to worry about wiring it all up when adding additional handlers. Using Windsor it's already possible to autoregister the handlers in the assembly, it would be nice to continue that pattern with routing.

**Comment by mookid8000** [comment]
In Rebus 0.99.48 you will be able to

    .Routing(r => r.MapFallback("wherever"))

It will be available on NuGet.org one of the following days.
