### ISSUE TITLE
Not all extension methods for OptionsConfigurer return OptionsConfigurer

### ISSUE THREAD

**Issue by xenoputtss** [rebus-org/Rebus#386]
In the master branch some extension methods for "OptionsConfigurer" do not return OptionsConfigurer .  This breaks the fluent configuration when using those extension methods.  The methods that fall into this category are:

* EnableMessageAuditing
* SimpleRetryStrategy
* EnableLegacyCompatibility
* EnableIdempotentSagas
* EnableSynchronousRequestReply

Easy there a reason why these should not return OptionsConfigurer?

**Comment by mookid8000** [comment]
Well.... sorry about the inconsistency :smiley: 

I think it's the other way around - I intended for the methods to return void except when that particular configuration method should lead to more stuff, like e.g. the saga auditing configuration

    .Options(o => {
        o.EnableSagaAuditing()
            .UseJsonFile(@"sagas/audit.jsonl");
    })

but then I must have been confused somehow when I made the threading configuration:

    .Options(o => {
        o.SetNumberOfWorkers(1)
            .UseExternalTimeoutManager("anotherQueue")
            .SetMaxParallelism(1);
        
        o.SetMaxParallelism(1)
            .UseExternalTimeoutManager("anotherQueue")
            .SetNumberOfWorkers(1);
    })

but I guess the short version of the story is that I can't really decide which fluent style should be supported.

I guess the good question is whether one style leads to more confusion and accidentally erronous configurations than the other.

## void style

	.Options(o => {
		o.EnableThis();
		o.EnableThat();

		o.ConfigureSomething()
		    .ThatHasItsOwnOptions();
	})

## super-fluent style

	.Options(o => o.EnableThis()
		.EnableThat()
		.EnableYetAnotherThing())

## my conclusion

I think I like "void style" best. And I think "super-fluent style" falls short if one of `OptionConfigurer`'s extensions is a fluent configuration builder itself, although that could maybe be changed into an action-style configuration builder:

	.Options(o => o.EnableThis()
		.EnableThat()
		.ConfigureThingWithOptions(o => o.ThisIsAThingOption("blah"))
		.EnableYetAnotherThing())

what do you think?

**Comment by IanYates** [comment]
The very last one reminds me of the Castle Windsor registration DSL, which works well imho.

**Comment by xenoputtss** [comment]
Now that you mention that your intention was to go "return void" I can convince myself that I like that way also.  By returning void we are then explicitly saying that "this method alters the object state" where as when returning itself could be misinterpreted as "this method does not alter object state, but returns another object with the changes you requested"

I would prefer to go with your idea of making everything return void.  
or
If you wanted to go super-fluenty, we make the extension methods idempotent and return a new object with the changes applied

**Comment by xenoputtss** [comment]
Let me know which way you would like to go, I can make the changes.

**Comment by mookid8000** [comment]
since you agree with me that returning void is the best, I must have made my case well :) return void it is!

**Comment by mookid8000** [comment]
sorry, wrong button - if you send PR I will merge it

**Comment by xenoputtss** [comment]
https://github.com/rebus-org/Rebus/pull/387

**Comment by mookid8000** [comment]
merged - will be out in 0.99.25 :)
