### ISSUE TITLE
OWIN host

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#395]
Add option to start a HTTP listener that can have OWIN middelware installed in it, this way providing a way to trivially add HTTP-enabled request/reply capability to any Rebus endpoint

In a separate package of course

**Comment by mookid8000** [comment]
available from 0.99.32 via the [Rebus.Owin](https://www.nuget.org/packages/Rebus.Owin/) package

**Comment by seankearon** [comment]
Wow - what an awesome feature! :)

**Comment by mookid8000** [comment]
thanks :)

**Comment by mookid8000** [comment]
this is how to do it:

    Configure.With(activator)
        .Logging(l => l.ColoredConsole(minLevel: LogLevel.Info))
        .Transport(t => t.UseInMemoryTransport(new InMemNetwork(), "owintest"))
        .Options(o =>
        {
            o.AddWebHost("http://localhost:3000", app =>
            {
                // go OWIN-crazy in here
                app.Map("/test", a => a.Use(async (context, next) =>
                {
                    await context.Response.WriteAsync("hello there!");
                }));
            });
        })
        .Start();

and then you can do this:

![image](https://cloud.githubusercontent.com/assets/32968/12944771/89caaede-cfe9-11e5-9333-25a0eb741baa.png)

**Comment by seankearon** [comment]
Very pretty indeed!

**Comment by mookid8000** [comment]
I've added the [OwinWebHost sample](https://github.com/rebus-org/RebusSamples/tree/master/OwinWebHost) to demonstrate this feature
