### ISSUE TITLE
Missing 0.84.0 tag

### ISSUE THREAD

**Issue by chilversc** [rebus-org/Rebus#398]
I can't find the tag for the 0.84.0 release, it looks like it was probably commit d6f12a1fa058ea8bffd30989f4a77159f2d8d089

**Comment by mookid8000** [comment]
wow thanks for pointing that out!

how did you figure out which commit it was?

**Comment by chilversc** [comment]
I used annotate on the change log, compared the notes for 0.84 with the commit message then checked the commits before/after that one. Though only inspected in github's commit history view.

**Comment by mookid8000** [comment]
I've pushed a 0.84.0 tag, assuming that d6f12a1 was the right point in time. It looked right when I checked it out.
