### ISSUE TITLE
Make saga data serializer configurable

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#401]
and default to JSON.NET as usual, but allow for customizing this aspect too

**Comment by mookid8000** [comment]
If the saga data serializer could be configured, it would also be trivial to implement compression and [encryption](http://stackoverflow.com/questions/34986605/encrypt-saga-data-in-rebus) as serializer decorators.

**Comment by mookid8000** [comment]
Change persisters to use raw bytes as their storage format - preferably in a way that is backwards-compatible and doesn't break when running on data stored in the old format:

- [ ] `InMemorySagaStorage`
- [ ] `PostgreSqlSagaStorage`
- [ ] `SqlServerSagaStorage`
- [ ] `MongoDbSagaStorage`
- [ ] `RavenDbSagaStorage`

**Comment by jeffreyabecker** [comment]
One thing to note: If the AzureStorage module is accepted it will need the serializer to expose the content type of the resulting data and the appropriate text encoding if applicable.

**Comment by mookid8000** [comment]
Is this because you are filling out the `Content-Type` property of the blob?

Another way to do this would be similar to how the existing message serializer works - it transforms tuples of `(headers, bytes)` to/from tuples of `(headers, object)`, and in that process it can add/remove headers as needed.

The Azure Storage-based saga persister could pass a tuple of (properties, ISagaData) to the saga data serializer, which would then return (properties, bytes).

This way, the requirements of this particular blob storage will not leak into the surface API of the saga data serializer (which does not even exist yet 😉 )

**Comment by mookid8000** [comment]
The saga data serializer might be configurable, but it has to be an option provided by the chosen saga data persister.

E.g. if MongoDB is chosen for persisting saga data, the data will be serialized using the Mongo driver's built-in BSON serializer.

With Postgres, the saga data should probably be saved as a JSON string into a proper JSON column.

And in future SQL Server versions it might become interesting to do something similar.

I'm closing this issue for now.
