### ISSUE TITLE
Proper way to wire up a logger in a message handler?

### ISSUE THREAD

**Issue by donig** [rebus-org/Rebus#402]
I'm a bit confused reading the documentation for logging...it says that the proper way to wire up logging is:
```
class MyClass
{
    static ILog log;

    static MyClass()
    {
        RebusLoggerFactory.Changed += f => log = f.GetCurrentClassLogger();
    }
}
```

But in Rebus V2, it doesn't appear to work this way. How is this supposed to work in Rebus V2

**Comment by mookid8000** [comment]
Thanks for pointing my attention to this - this piece of documentation is clearly outdated.

The docs come from a time where I wasn't totally clear about this too - I will go and update it immediately :)

**Comment by mookid8000** [comment]
I don't have time to finish [the wiki page](https://github.com/rebus-org/Rebus/wiki/Logging) right now.... it'll be done in a couple of hours....
