### ISSUE TITLE
AmazonSqs Purge has hardcoded region setting.

### ISSUE THREAD

**Issue by gertjvr** [rebus-org/Rebus#404]
https://github.com/rebus-org/Rebus/blob/master/Rebus.AmazonSQS/AmazonSQSTransport.cs#L113

**Comment by mookid8000** [comment]
thanks for pointing that out - it has been fixed

**Comment by mookid8000** [comment]
the fix has been released in 0.99.30 on Nuget.org just now - thanks for finding this issue :smile:
