### ISSUE TITLE
Multiple queues

### ISSUE THREAD

**Issue by paulmarshall** [rebus-org/Rebus#410]
In a pipes and filter architecture, what is the "best practice" for implementing multiple filters?

In the context of Rebus, where we use ".Transport(t=>t.UseMsq(...)), this denotes the "input" queue. But in a P&F architecture, there will be many input queues.

Basically, can I call ".Transport(t=>t.WhatEver)" multiple times within the same process i.e console app?

**Comment by mookid8000** [comment]
"Best practice" (I love that word!) is to have one input queue per Rebus endpoint. That is also the only thing that is possible at the moment :)

You are free to host as many Rebus endpoints within the same process as you like, though, which can be a perfectly fine way to host endpoints that don't have to be independently updated.

**Comment by mookid8000** [comment]
PS: It is NOT possible to call

    .Transport(t => ...)

multiple times - you should get an error and an explanation if you do so.

**Comment by paulmarshall** [comment]
"You are free to host as many Rebus endpoints within the same process as you like"

**Comment by mookid8000** [comment]
static readonly List<IDisposable> _stuffToDisposeWhenApplicationShutsDown = new List<IDisposable>();

	public static void Main()
	{
		ConfigureBus("bus1");
		ConfigureBus("bus2");
		ConfigureBus("bus3");

                Console.WriteLine("Press ENTER to quit");
                Console.ReadLine();

                _stuffToDisposeWhenApplicationShutsDown.ForEach(d => d.Dispose());
	}

	public static void ConfigureBus(string inputQueueName)
	{
		var container = new WindsorContainer();

		// install everything:
		container.Install(FromAssembly.This());

		Configure.With(new CastleWindsorContainerAdapter(container))
			.Transport(t => t.UseMsmq(inputQueueName))
			.Start();

		_stuffToDisposeWhenApplicationShutsDown.Add(container);
	}

**Comment by mookid8000** [comment]
....assuming Castle Windsor in the example above :)

General approach is: Have an IoC container instance per **logically** separate process and just keep them in the process as a list of disposables to dispose when the application shuts down.

This way you can start out by hosting all the endpoints within the same process and easily move them out one by one as your wishes to update/scale them independently start creeping in (or not ;))
