### ISSUE TITLE
About Rebus.MultipleSagaHandlersFoundException:

### ISSUE THREAD

**Issue by Uma19** [rebus-org/Rebus#413]
Hey,

I am facing one exception related with saga handlers. Please find the description below :
 could be handled by multiple saga handlers: x, y. 
This is an error because it would require that multiple saga instances could be updated atomically, which is not possible with all saga persisters.

I have seen 1 of your blog for implementing ICanUpdateMultipleSagasAtomically using IStoreSagaData as a solution.
But could you guid me how to proceed with the same?

**Comment by mookid8000** [comment]
Unfortunately, the `ICanUpdateMultipleSagasAtomically` is not my invention, and it is not present in the current version of Rebus.

The current version of Rebus does not prevent you from executing multiple saga handlers though, so if you upgrade you should not have that problem.

**Comment by Uma19** [comment]
okay you mean to say rebus 2 right ?

**Comment by mookid8000** [comment]
Yes :)

Sendt fra min iPhone

**Comment by Uma19** [comment]
thank you. one last question from my end. Is rebus 2 is stable to use ?

**Comment by mookid8000** [comment]
Yes :)

Sendt fra min iPhone

**Comment by Uma19** [comment]
Thank you (y)
