### ISSUE TITLE
Rebus.Async nuspec file missing

### ISSUE THREAD

**Issue by czuares** [rebus-org/Rebus#414]
It appears the Rebus.Async nuspec file is missing from the project directory. As a result, this library is not getting built or deployed to NuGet. Due to this, the latest version of the Rebus.Async NuGet package is quite old and incompatible with the current version of Rebus.

**Comment by mookid8000** [comment]
Thanks for bringing it to my attention :+1: 

The reason there was no nuspec was that the async package lacked a few stability features, namely

1. the ability to throw a `TimeoutException` if an `await`ed reply never shows (or arrives too late), and
1. the ability to clean up abandoned replies in the background (replies that arrived too late or came back to a requestor that was gone)

I've fixed these things, and I'll push it in 0.99.34 as soon as the build server has run the tests :smile:

**Comment by czuares** [comment]
Awesome, thanks for the quick reply. Cheers! :smile:

**Comment by mookid8000** [comment]
[`Rebus.Async`](https://www.nuget.org/packages/Rebus.Async/) is available now :)

**Comment by mookid8000** [comment]
btw if you've use the inline async thing before - this one is new, and it uses `async`/`await` do to its thing - you use it like this:

    var reply = await bus.SendRequest<MyReply>(new MyRequest());

    // do what you want with reply here....
