### ISSUE TITLE
AzureServicebus transport option to not create queue / check if queue exists

### ISSUE THREAD

**Issue by runes83** [rebus-org/Rebus#415]
Today if the transports checks if via namespacemanager if the queue exists, this requires the client to have manage rights to the servicebus.

We want to be able to have clients that only have read access to a single queue, but this does not work as the bus checks if the queue exists/and creates it when it starts. Would it be possible to add an option to not checking the existence of the queue when starting?

**Comment by mookid8000** [comment]
hmm, I can see that that can be a problem..... and yes, it would certainly be possible to tack some extra information on Azure Service Bus configuration builder, it already supports setting a few options by building on the returned [AzureServiceBusTransportSettings](https://github.com/rebus-org/Rebus/blob/master/Rebus.AzureServiceBus/Config/AzureServiceBusTransportSettings.cs), e.g. like so:

    Configure.With(...)
        .Transport(t => t.UseAzureServiceBus(connStr, queue)
                             .EnablePartitioning()
                             .AutomaticallyRenewPeekLock()
                             .EnablePrefetching(100))

so something like

    Configure.With(...)
        .Transport(t => t.UseAzureServiceBus(connStr, queue)
                             .DoNotCreateQueues())

ought to do the trick

**Comment by torangel** [comment]
If  the readonly instance of Rebus configured with `t.UseAzureServiceBus` is provided with a readonly SAS for it's own "readonly" queue (and not for the namespace) it will not be able to send messages to other queues in the namespace. Would it be better with the folowing configuration to clearly indicate that this bus-instance will never be able to send messages (except to itself)?:

`Configure.With(...)
    .Transport(t => t.UseAzureServiceBusReadOnly(connStr, queue)
                        )`

**Comment by torangel** [comment]
Could this work?
#417

**Comment by mookid8000** [comment]
hi @torangel ,

I am sorry, but it's not clear to me what this does?

Or maybe it's the naming that is confusing me....

If I understand correctly, SAS is a tailored connection string (similar to a JWT/SWT/etc), i.e. basically an encrypted set of claims that can be used to give granular access rights to something.

In this case - and this is where it becomes unclear to me - you're calling `UseAzureServiceBusReadOnly` with a SAS connection string that grants the endpoint the right to RECEIVE and SEND on its own queue only, right?

Or how do you use the SAS connection strings?

**Comment by torangel** [comment]
Sorry for being unprecise with the naming here. My apologies.

 This commit simply makes it possible to start an instance of rebus using azureservicebus configured with a connectionstring containing a "SharedAccessKey/KeyName" which is configured to only have read permission on the queue.

In queue-config =>shared access policies=>
Endpoint=sb://../;SharedAccessKeyName=reader;SharedAccessKey=nL5......../Aw=

The class `BasicReadOnlyAzureServiceBusTransport` makes sure it is not possible to send messages (beacuse the bus will only have access to its own queue) and it also does not try to create the bus's own inputqueue.

**Comment by mookid8000** [comment]
and it will not be able to send messages to anyone, not even itself?

**Comment by torangel** [comment]
That is correct - would that introduce problems - not being able to send to itself?

**Comment by mookid8000** [comment]
not really.... but as a receiver, it should be possible for the endpoint to send a message to the error queue...

although this makes me think whether the Azure Service Bus transport ought to take advantage of ASB's built-in poison message handling....

I will have to think about this :)

**Comment by torangel** [comment]
Should I close my pullrequest and fall back to an implementation like this one
```
Configure.With(...)
    .Transport(t => t.UseAzureServiceBus(connStr, queue)
                         .DoNotCreateQueues())
```

which in effect solves the "readonly" problem?

**Comment by mookid8000** [comment]
Hi @torangel , sorry for taking so long to think about it :grin: 

I guess you have struck something here which I haven't really considered... I have always just used a raw, admin connection string when I have used Azure Service Bus, but I can definitely see how it is much prettier, security-wise, to issue SAS tokens for the endpoints.

For now, I think I prefer the `DoNotCreateQueues` solution.... it doesn't ruin the nice symmetry whereby all transports have exactly two `Use*` methods - one that goes `Use<the transport>`, and one that goes `Use<the transport>AsOneWayClient`.

**Comment by mookid8000** [comment]
If you will adapt your PR, I will see if I can get the time to review your code and merge it today.

**Comment by DixonDs** [comment]
@mookid8000 
> I have always just used a raw, admin connection string when I have used Azure Service Bus

Just want to mention that restricted access in production environment seems to be a pretty common scenario. It reminds me the issue I posted a while ago: https://github.com/rebus-org/Rebus/issues/319 In that scenario I had only access to specific subscription, no access for creating error queues or anything else. So in the end, for a simple case I had it was easier just to use `SubscriptionClient` directly than customizing Rebus for my needs, but I can imagine similar scenarios could be quite common for other people.

**Comment by mookid8000** [comment]
@DixonDs thanks for chiming in 😃 

Yes - you are probably right that using SAS keys with Azure Service Bus can be pretty common... and I would have loved to support it with the existing transport implementation if it could be done without interfering too much with it. 

But I am afraid that the seemingly simple scenario of just receiving from one single subscription deviates too much from all of the "niceness" that Rebus want to provide, like forwarding to an error queue of your choice, automatically setting everything up according to your configuration, etc.

So you probably made the right choice in choosing the raw `SubscriptionClient` instead of pulling in a full framework just for handling a couple of messages 👍

**Comment by mookid8000** [comment]
I'm closing this one because the main issue of skipping queue creation has been fixed – it is now possible to do this

    Configure.With(...)
        .Transport(t => {
			t.UseAzureServiceBus(connStr, queue)
             .DoNotCreateQueues();
        })
        .(...)
