### ISSUE TITLE
Regarding Publishing Message to Multiple Subscriber

### ISSUE THREAD

**Issue by Uma19** [rebus-org/Rebus#421]
Hi Guys,

I have a question regarding publishing message to multiple subscriber.
So right now I am facing the issue as, the Publish component is publishing the message but the subscriber component are taking time to react to that message. So can you tell me what all things needs to be taken care here ? or in which area I should look to improve this performace

**Comment by mookid8000** [comment]
Could you maybe show me your Rebus configuration code and, possibly, any other bit you may find relevant?

**Comment by Uma19** [comment]
Hi,
Thanks for replying. Here is the below 

Rebus configuration for the server component (who plays the role of Publisher and Subscriber) is as follows :
for rebus is as following :
 log4net.Config.XmlConfigurator.Configure();
            Configure.With(new WindsorContainerAdapter(container))
          .Logging(l => l.Log4Net())
          .Transport(t => t.UseMsmqAndGetInputQueueNameFromAppConfig())
          .Serialization(x => x.UseJsonSerializer())
          .MessageOwnership(m => m.FromRebusConfigurationSection())
          .Sagas(m => m.StoreInNDb())
          .Subscriptions(m => m.StoreInNDb())
          .Timeouts(m => m.StoreInMemory())
          .Events(e =>
          {
              e.MessageSent += (advancedbus, destination, message) =>
              {
                  var timeToBeReceived = ConfigurationManager.AppSettings["TimeToBeReceived"];
                  if (string.IsNullOrEmpty(timeToBeReceived))
                      timeToBeReceived = "00:00:30";
                  if (timeToBeReceived != "-1")
                  {
                      advancedbus.AttachHeader(message, Headers.TimeToBeReceived, timeToBeReceived);
                      advancedbus.AttachHeader(message, Headers.Express, "rebus-express");
                  }
              };
          })
          .CreateBus()
          .Start();
        }

Apart from the above configurations:
The webconfig file for publisher component contains :
 <rebus inputQueue="xyz" errorQueue="error" workers="1" maxRetries="5" />

The webconfig file for subscriber component contains :
   <rebus inputQueue="yud" errorQueue="error" workers="10" maxRetries="1">

So mainly we have assigned workers threads also 1 and 10 as per publisher and subscriber components :

**Comment by mookid8000** [comment]
What does the `StoreInNDb` extension method look like?

**Comment by Uma19** [comment]
This means we are using SQL server for storing subscription information.

**Comment by mookid8000** [comment]
Right - but the thing is, whenever Rebus needs to publish a message, it will look up the queue names of the subscribers of that message from the current `IStoreSubscriptions` (since you're using Rebus 1, it's called `ISubscriptionStorage` in Rebus 2)

If that lookup takes a long time to complete, it will take a while before the message is actually published.

Moreover, endpoints use an [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff)-like strategy to avoid thrashing whichever queue they are receiving from, so if an endpoint has not received anything for a while, it may take up to a few seconds (iirc) before the endpoint polls the queue and finds the event.

**Comment by Uma19** [comment]
Thanks for giving me the inside working on the same.
Will check this and get back to you for more details :)
I request you not to close this chain of issue for 2-3 days. So that I can contact if I have any query

**Comment by mookid8000** [comment]
Sure :)

btw you can check if it's the backoff strategy by enabling low-latency backoff

    Configure.With(...)
        .(...)
        .Behavior(b => b. SetLowLatencyBackoffBehavior())
        .(...)

This will poll the queues more often, thus allowing for much lower latency even when events are not so frequent.

**Comment by Uma19** [comment]
:) thanks. but I am not getting this option as "SetLowLatencyBackoffBehavior" when I try to add in the configuration.

The only setting which I get are : "HandleMessagesInsideTransactionScope" and "SetMaxRetriesFor"

And we are using Rebus 1.
Is it also available with the same ?

**Comment by mookid8000** [comment]
which version are you using? the latest "Rebus 1" version is 0.84.0....

**Comment by Uma19** [comment]
We are using Rebus 1 version 1.0.0.0
I mean File Version (1.0.0.0) and Product Version (1.0.0.0)
Actually I am new to this, that why getting confused in this

**Comment by mookid8000** [comment]
oh - all of the assemblies are "1.0.0.0".... you need to check your "packages.config" file to see which version got included :smile:

**Comment by Uma19** [comment]
okay :) actually . This rebus dll was already downloaded sometimes ago and had stored in some folder.
Right now we are not referring from nuget but directly from they physical location. and from there I am not getting the idea of which version it is.

But one thing I can say that. If I check teh direct rebus.configuration. Then they are exposing only following methods. So what does this means then ?
namespace Rebus.Configuration
{
    public class RebusBehaviorConfigurer : BaseConfigurer
    {
        public RebusBehaviorConfigurer HandleMessagesInsideTransactionScope();
        public RebusBehaviorConfigurer SetMaxRetriesFor<TException>(int maxRetriesForThisExceptionType) where TException : Exception;
    }
}

**Comment by mookid8000** [comment]
It's still possible for `SetLowLatencyBackoffBehavior` to be implemented as an extension method...

**Comment by Uma19** [comment]
oh okay nice

**Comment by mookid8000** [comment]
Do you know what I mean? 

I mean that `SetLowLatencyBackoffBehavior` is probably implemented somewhere else.... did you try ant type it in and see if Visual Studio offers to import another namespace for you?

**Comment by Uma19** [comment]
Firstly I have the entire rebus project whose dll which we are using. So in that I didnt found any such kind of method. 
So trying above thing which you have mentioned

**Comment by mookid8000** [comment]
I just checked with the old Rebus codebase - the `SetLowLatencyBackoffBehavior` method turned out to be an ordinary method on the `RebusBehaviorConfigurer` - you can see it [here](https://github.com/rebus-org/Rebus/blob/master/old/src/Rebus/Configuration/RebusBehaviorConfigurer.cs#L91-L95) if you like.

I think you are using a very old version of Rebus. I suggest you update to 0.84.0 when you can if you want to stay with "Rebus 1".

The future is with "Rebus 2", though (versions >= 0.90.0), but that's a slightly bigger update than just going to 0.84.0.

**Comment by Uma19** [comment]
yes true saw that. and about to ask you the same. whether we can update to 0.84.0 and stay with Rebus1.
I think thats the good idea . And I think there will be not much change in the configuration which I had mentioned in the top I guess ?

**Comment by mookid8000** [comment]
I don't think updating to 0.84.0 will require anything other than rebuilding your project.... depending on how old your current version is though :grin:

**Comment by Uma19** [comment]
perfect :)

**Comment by Uma19** [comment]
Hey ,

I am again facing one more issue related to same.
I have refered rebus , Rebus.Castle.Windsor and Rebus.Log4net of version 0.84.0
But when I downloaded from package , its not strongly named.
So I made it strongly named by using our snk key
but then after doing that, its thowing compilation error for the below statement

"
log4net.Config.XmlConfigurator.Configure();
            Configure.With(new WindsorContainerAdapter(container))
          .Logging(l => l.Log4Net())
"

Error	CS0012	The type 'IContainerAdapter' is defined in an assembly that is not referenced. You must add a reference to assembly 'Rebus, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.	
The version is of 1.0.0.0

can you guide me here?

**Comment by mookid8000** [comment]
Did you strong-name ALL of the Rebus assemblies?

The `PublicKeyToken=null` part of the thrown exception suggests that the thrower is not expecting its `Rebus` dependency to be strong-named, although it should actually be impossible for a strong-named assembly to depend on somethat that was not strong-named too.

**Comment by Uma19** [comment]
yes for the above dll's which I have mentioned ("rebus , Rebus.Castle.Windsor and Rebus.Log4net ") ,
I made them all strong name.
And if I dont make them strong name , then run time exception is thrown that rebus has to be strongly named

**Comment by mookid8000** [comment]
Ok - but the exception indicates that `Rebus.Log4net` is built against a `Rebus.dll` which is NOT strongly named (which should not be possible).

Do you really have to strong-name your own code?

**Comment by Uma19** [comment]
Finally I made it

What I did is downloaded the entire source code of 0.84.0 of rebus. 
To that project I added our snk key and singed that project.
then complied it and generated the required above 3 dll's
and now its done :) :) :)

**Comment by mookid8000** [comment]
Good to hear you made it work :)

**Comment by Uma19** [comment]
(y). Now I will try with this version. And hopefully it will solve the actual problem :)

**Comment by Uma19** [comment]
Hello,
I am back :). The issue which I have discussed above still persist :(. find the senario below :

Senario :
I have updated our code with latest rebus 1 version i.e 0.84.0
And also added that "SetLowLatencyBackoffBehavior" while configuring

2 projects 
Project 1 (publisher) 
Project 2 (subscriber)

Now when I added some logs to the rebus code then 
I could able to detect that the lag is while executing** async Task DoTry() method 
Exactly before "await (Task)dispatchMethod.Invoke(dispatcher, parameters);" code**


So the issue could be the time subscriber taking for receiving the request message.
Can you guide us regarding the same ?

One more thing with each request , we are appending rebus-express. So it makes it express message which I thing should improve the performance .

**Comment by mookid8000** [comment]
You are correct that the `rebus-express` header will speed things up a little bit. In case you're familiar with MSMQ, [you can see what it does here](https://github.com/rebus-org/Rebus/blob/master/old/src/Rebus/Transports/Msmq/RebusTransportMessageFormatter.cs#L68-L69).

If I understand your problem correctly, you are experiencing a delay between the publisher publishing an event and the event being received by the subscribers - is that correct?

How long is that delay?

Can you reproduce the problem with a small working code sample that you can ZIP and send to me?

**Comment by Uma19** [comment]
The delay is for 20 secs. And yes will try that only now, creating a sample code and then check.
if any difficulty, then will send the zip and check :)

**Comment by Uma19** [comment]
Hey,

Thanks for your support. The issue got resolved. Com firmed yesterday. It was related with customer's environment on which I have deployed this project.
So now with rebus 1 (latest version) its working fine.

No delay and getting response in few secs (5-6)
Thank you once again :) :+1:

**Comment by mookid8000** [comment]
Excellent! :+1:  Thank you for getting back to me :smiley:
