### ISSUE TITLE
Add Azure table storage saga persister

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#424]
just do it

**Comment by mookid8000** [comment]
except... I don't know how to efficiently be able to look up a saga instance from an arbitrary correlation property, since the table storage is indexed on partitionkey/rowkey only

**Comment by seankearon** [comment]
If it's not querying against partition/row keys then it will always effectively doing a full scan of the table.  Don't think there's any way around that.  What about constraining the correlation to use just those - the saga name and UID perhaps?

**Comment by runes83** [comment]
I think @seankearon is right here. If using table storage the lookup could be limited to only the saga id. 
It's a limitation on the functionality but still using table storage make Rebus much more scalable running in the cloud (and cheaper). So it's worth it for those who would accept the limitation.

**Comment by mookid8000** [comment]
I agree totally 👍

**Comment by jeffreyabecker** [comment]
What about keeping multiple rows in a SagaIndex table with divergent schemas and keys? For the Find operation the correlation property / value can be packed into the RowKey. In order to update or delete records you'd also need to keep an entry which allows you to look up the other keys by SagaType/Id/Revision.  When you think about it, this isnt all that different from how the indexes in the SqlServer storage work.  

Would you be open to a PR implementing this?

**Comment by mookid8000** [comment]
If I understand you correctly, you are proposing persisting sagas in table storage by using two tables with the following columns:

### Index table

* PartitionKey: (whatever?)
* RowKey: Concatenated string consisting of saga data type, property name, and property value
* Saga ID

### Data table

* PartitionKey: (whatever?)
* RowKey: Saga ID
* Row keys of all entries in the index currently pointing to this instance
* Data (possibly by using the ["fat entity"](https://github.com/Lokad/lokad-cloud-storage/blob/master/Source/Lokad.Cloud.Storage/Azure/FatEntity.cs) approach

It could definitely work, but I am a little bit worried about race condition-type bugs in it because it is not possible to update both the data table and the index table in one atomic operation.

I would definitely accept any PRs that could implement this 😁

**Comment by jeffreyabecker** [comment]
Not quite, I intend on only having the single Index table and storing the serialized saga in Blob storage. That would let me take leases on the blob for concurrency and keep revision as an attribute of the blob.
As for the index table, I was using the saga data type name as the partition key. From there each saga data gets several rows with divergent schemas using [DynamicTableEntity](https://msdn.microsoft.com/library/azure/microsoft.windowsazure.storage.table.dynamictableentity.aspx).  Each saga gets one row which consists of:

- PartitionKey: Saga data type Name
- RowKey: SagaId_Revision
- Dictionary of Property name/values 

And then for each property there is a row:

- PartitionKey: Saga data type Name
- RowKey: PropertyName_PropertyValue
- SagaId

**Comment by mookid8000** [comment]
Ah, I see! Well that actually sounds pretty brilliant 👍 

There's still some things around concurrency that worries me, since this will require multiple pieces of data that cannot be updated atomically to be in sync. But I guess my worries come mostly from not being able to predict everything, so it's probably not a problem.

**Comment by jeffreyabecker** [comment]
So, I got concurrency working, or at least passing the tests, but I had to resort to taking out distributed locks on the saga blob. My branch is [here](https://github.com/jeffreyabecker/Rebus/tree/jb-azure). This contains a full set of the storage interfaces for Azure. Let me know if you'd like a PR.

**Comment by mookid8000** [comment]
I would love a PR 😄 it will take a few days before I have time to check it out though..

**Comment by jeffreyabecker** [comment]
Do you have any guidance on how to deal with issue #401 here? There's some blatant copy-pasta from SqlServerSagaStorage in there.

**Comment by mookid8000** [comment]
Just copy/paste for now - if you use the same serializer, it will be easy to switch to an injected saga data serializer later on.

**Comment by mookid8000** [comment]
fixed by #476  which is out in 0.99.66
