### ISSUE TITLE
Max message size handling question

### ISSUE THREAD

**Issue by replaysMike** [rebus-org/Rebus#425]
I've gone through all the docs and couldn't find an answer.

Is there any particular strategy to dealing with large messages with Rebus? I have switched to ProtoBuf and turned on compression but am still dangerously close to Amazon SQS 256kb limit.

I could roll my own solution using a central database, however I'm wondering if Rebus has a mechanism already for this (like nHibernate's data channels)

**Comment by mookid8000** [comment]
Rebus does not have any way of handling this at the moment.

I will add a "databus" feature to Rebus some day though, similar to what NServiceBus can do, thus allowing for using a file share, Azure blobs, S3, etc. to store large payloads.

Unfortunately I cannot give you any time horizon on this task though.

**Comment by mookid8000** [comment]
I've opened #426 for the databus feature

**Comment by xhafan** [comment]
I enabled compression for Rebus messages: https://github.com/rebus-org/Rebus/wiki/Message-compression-and-encryption#message-compression . I set the body size compression threshold to 64000 (EnableCompression(64000)) bytes, as SQS bills each 64kb of data as one request (64000 to make sure the whole message including any Rebus data overhead would be smaller than 65536 bytes).

**Comment by mookid8000** [comment]
If you did this:
```csharp
Configure.With(...)
    .(...)
    .Options(o => o.EnableCompression(bodySizeThresholdBytes: 64000))
    .(...)
```
then it means that Rebus will automatically GZIP message bodies when the body size exceeds 64000 bytes. This is probably not what you want🙂 because then you would need to exceed (or get very near to) the maximum message size to have it kick in, and then you'd have the databus kick in anyway.

It's much more fun to configure it with something like
```csharp
Configure.With(...)
    .(...)
    .Options(o => o.EnableCompression(bodySizeThresholdBytes: 2048))
    .(...)
```
which will GZIP all messages that exceed 2kB in size.

**Comment by xhafan** [comment]
> then it means that Rebus will automatically GZIP message bodies when the body size exceeds 64000 bytes. This is probably not what you wantslightly_smiling_face

This is what I wanted. To compress only messages which would exceed 64kb, to save on SQS billing. I don't really care about small message being compressed, we need CPU for web request handling and not for compressing messages :smile:
