### ISSUE TITLE
FakeBus should offer a method to clear events

### ISSUE THREAD

**Issue by oliverhanappi** [rebus-org/Rebus#430]
It would be nice to have an option for clearing all events recorded by the FakeBus. This can be useful when reusing a FakeBus instance between multiple tests.

**Comment by mookid8000** [comment]
filed under "too nice to ever consider not doing" :+1: :grin:

**Comment by mookid8000** [comment]
[it has it](https://github.com/rebus-org/Rebus/blob/master/Rebus/Testing/FakeBus.cs#L50-L57) (since 0.99.45)
