### ISSUE TITLE
Ensure non-awaited async stuff runs to end

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#435]
When inside a message handler, if you

```
bus.Send(yourMessage);
```

your message might not be properly sent because the continuation ends up being run AFTER the queue transaction has ended (note the lack of an `await`)

MassTransit magically "captures" the started tasks somehow, ensuring that they are run to end before ending the queue transaction. It would be neat if Rebus could do the same.

**Comment by colin-higgins** [comment]
Seeing as you have control over the sending methods, can't you just add the `Task` for the Enqueue action to a shared context? You can await those Tasks after the handler method finishes.

**Comment by mookid8000** [comment]
Dude!! 👏👌👍 that's actually pretty brilliant! I can't believe I did not consider doing that... whenever I thought about this issue, I kept focusing on the synchronization context, but you are absolutely right. 

This will of course only work with Rebus' own tasks... but that's also the most important part in this context. 

Sendt fra min iPhone

**Comment by colin-higgins** [comment]
That's where my mind first went as well... Like.... 
"how the hell could they be capturing tasks internal to a method... Maybe some IL weaving magic??? Wait a second... that's not even necessary."

I guess the nice part about doing this is if users don't "want" to use async, which I understand... but then it's just programming by coincidence.
In other words, the user might expect that the messages will be queued before the rest of their code executes, but that's just not true.

But it does remove blame from Rebus for "losing" messages.

Are you going to go ahead with it?

**Comment by mookid8000** [comment]
I am contemplating making a little spike, yes 😁

**Comment by mookid8000** [comment]
are you asking because you would be interesting in doing it?

**Comment by colin-higgins** [comment]
I'll spike this, yeah.

**Comment by JornWildt** [comment]
I would rather not have this happening magically somewhere/sometime. I would rather see a `WaitAll()` somewhere for the application to call when it is ready.

**Comment by mookid8000** [comment]
I'm closing this one for now, because I don't see how it can be done. Feel free to revive this issue if you have anything to add 😄
