### ISSUE TITLE
Bus.Publish take about 30 Milliseconds and it take so much time

### ISSUE THREAD

**Issue by houwenlong789** [rebus-org/Rebus#436]
I use Rebus.RabbitMq, and use await IBus.Publish() method. I test the method, and the publish method take about 30 miliseconds.
Compare to RabbitMQ.Client, I use BasicPublish method,it just take about  1 Milliseconds.

Can you tell me how to solve this problem.

**Comment by mookid8000** [comment]
Can you show me the code you are using to compare the performance of publishing to RabbitMQ with and without Rebus?

**Comment by houwenlong789** [comment]
Here is Rebus Code:

 using (var activator = new BuiltinHandlerActivator())
            {
                IBus bus = Configure.With(activator)
                .Logging(i => i.ColoredConsole())
                .Transport(t => t.UseRabbitMqAsOneWayClient("amqp://admin:admin@10.16.35.62"))
                .Start();

                Stopwatch stopwatch = new Stopwatch();
                stopwatch.Start();
                Stopwatch stopwatch2 = new Stopwatch();
                stopwatch2.Start();
                var number = 100;
                StringBuilder sb = new StringBuilder();
                for (var i = 0; i < number; i++)
                {
                    stopwatch.Restart();
                    await bus.Publish(new EmailTemplateMessage()
                    {
                        TemplateCode = "111001",
                        UseTemplateAddressee = true
                    });
                    stopwatch.Stop();
                    sb.Append(string.Format("{0} ", stopwatch.ElapsedMilliseconds));
                 
                   
                }
                _output.WriteLine(sb.ToString());
                stopwatch2.Stop();
                _output.WriteLine("avarage time is " + (double)stopwatch2.ElapsedMilliseconds / number);

            }


Test output  as follow:
238 7 5 6 7 11 4 12 11 4 11 10 19 10 10 9 7 15 9 14 9 46 15 13 5 24 24 23 6 7 16 24 14 19 21 16 5 13 15 11 9 659 30 22 11 21 16 29 5 30 21 9 6 11 17 12 7 10 13 9 9 4 18 10 10 644 8 7 43 23 4 34 39 21 10 20 19 11 16 7 6 14 6 11 11 12 10 15 12 623 24 6 20 9 6 18 14 7 16 21 
avarage time is 35.64

**Comment by houwenlong789** [comment]
RabbitMq.Client Code as follow:

 var factory = new ConnectionFactory()
           {
               HostName = "10.16.35.62",
               UserName ="admin",
               Password ="admin"
           };

           using (var connection = factory.CreateConnection())
           {
               using (var channel = connection.CreateModel())
               {
                   channel.ExchangeDeclare(exchange: "topic_logs", type: "topic");
                   var routingKey = "mytest.red";



                  var pro= channel.CreateBasicProperties();
                   pro.Headers =new Dictionary<string, object>();
                   pro.Headers.Add("rbs2-audit-handlequeue", "TimeJob");
                   pro.Headers.Add("rbs2-msg-id", Guid.NewGuid().ToString());

                   var message = new EmailTemplateMessage()
                   {
                       TemplateCode = "111001",
                       UseTemplateAddressee = true
                   };
                   var emailTemplate = JsonConvert.SerializeObject(message);
                   var body = Encoding.UTF8.GetBytes(emailTemplate);

                    Stopwatch stopwatch = new Stopwatch();
                    Stopwatch stopwatch2 = new Stopwatch();
                    stopwatch2.Start();
                    stopwatch.Start();
                   var countNumber = 100;
                    StringBuilder sb = new StringBuilder();
                    for (var i = 0; i < countNumber; i++)
                   {
                        stopwatch.Restart();
                    
                        channel.BasicPublish(exchange: "topic_logs",
                                 routingKey: routingKey,
                                 basicProperties: pro,
                                 body: body);
                        stopwatch.Stop();
                       sb.Append(string.Format("{0} ", stopwatch.ElapsedMilliseconds));
                    }
                    _outputHelper.WriteLine(sb.ToString());
                    stopwatch2.Stop();
                  _outputHelper.WriteLine("avarage time is"+((double)stopwatch2.ElapsedMilliseconds/countNumber).ToString());



Test ouput is:

6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
avarage time is 0.08

**Comment by houwenlong789** [comment]
I check Rebus source code, and find the life of IBus is  transient. So every time call IBus.Publish
it will create a new Rabbit.Client`s IModel. Time is been cost on create and dispose IModel.
From the first test result, some time,Rebus cost** over 600 milliseconds** that`s  not reasonable.Hope you can solve this.
I have another question,Why not design IBus as  singletion? It will save creation IModel time.

**Comment by mookid8000** [comment]
>> the life of IBus is transient

?? what do you mean?

>> So every time call `IBus.Publish` it will create a new Rabbit.Clients `IModel`

This is intentional. The instance will be cached for the duration of the transaction, however, so if you want to test Rebus in a way that is more true to how you are using RabbitMQ in your code, you can do this:

	using(var context = new DefaultTransactionContext())
	{
		AmbientTransactionContext.Current = context;

		// run Rebus code in here

		await context.Complete();
	}

**Comment by houwenlong789** [comment]
I see. Every defaultTransactionContext, the instance is created.I change my code as follow:

![qq 20160408183212](https://cloud.githubusercontent.com/assets/9875294/14381336/3c8672d2-fdb8-11e5-94f6-6c6c03dbd35a.png)

output result is:
![qq 20160408183317](https://cloud.githubusercontent.com/assets/9875294/14381371/7395faa4-fdb8-11e5-94ff-75d90d5221ed.png)

**Comment by mookid8000** [comment]
moreover, Rebus always uses durable messages - if I recall correctly, you will have to set `Persistent` to true on the `props` that you pass on when sending the message..

alternatively, you can add the `[Express]` attribute to the message class, like so:

    [Express]
    public class EmailTemplateMessage 
    {
          ....
    }

which will make Rebus accelerate the message by making it non-durable

**Comment by houwenlong789** [comment]
Thank you so much for answering my question. All my questions are solved!
Rebus really help me so much!

**Comment by mookid8000** [comment]
so did it bring down the time to publish to an acceptable level?

**Comment by houwenlong789** [comment]
Express Attribute seems no effect on publishing time. But  if I sleep current thread for a while(30 Milliseconds )  after publish a message,almost no time  cost to publish a message.
In real sinario, message is published one by one,not continuelly publish messages.

**Comment by houwenlong789** [comment]
I will continue read rebus source code to find out why cost so much if messages are published without break situation.

**Comment by mookid8000** [comment]
>> In real sinario, message is published one by one,not continuelly publish messages.

It seems to me that it would make much more sense then to test these scenarios:

	// raw RabbitMQ client
	using(var model = connection.CreateModel())
	{
		// publish single message in here
	}

	// Rebus
	await bus.Publish(yourMessage);

**Comment by mookid8000** [comment]
I'll close this issue for now because it's not really an issue. Please let me know if Rebus is not fast enough for you 😄

**Comment by boskjoett** [comment]
Although this issue has been closed years ago I experience the same issue. I also use RabbitMQ transport.
The time to complete bus.Publish() varies between a few millisecs to 600 ms. With random occurrence of the message delivery delay spikes.
I have tried to use these headers in Publish:

```
    _headers = new Dictionary<string, string> {
       { RabbitMqHeaders.DeliveryMode, "1" },     // 1 = non-persistent, i.e. messages are not persisted by RabbitMQ
       { Headers.Express, "" }                    // Deliver messages as fast as possible
    };
```
but that did not help.

I also tried to add the [Express] attribute to my message classes, but I could find out which Rebus NuGet package that implements this attribute. I searched the Rebus source but could find any ExpressAttribute class definition.

Conclusion is that this issue seems to persist.

**Comment by mookid8000** [comment]
> I have tried to use these headers in Publish: (.....) but that did not help.

What do you mean it didn't help? Did it not have any effect at all?

> I also tried to add the [Express] attribute to my message classes, but I could find out which Rebus NuGet package that implements this attribute. I searched the Rebus source but could find any ExpressAttribute class definition.

OK I actually though that attribute still existed, but apparently I removed it from Rebus a long time ago 🙄 you can define your own though like this:
```csharp
public class ExpressAttribute : HeaderAttribute
{
    public ExpressAttribute() : base(Headers.Express, "") {}
}
```
and since `HeaderAttribute` are picked up by Rebus, so will this. 🙂 

I am sorry to hear your latency varies so much. Is there anything in the logs that could give you an indication about what is happening?

**Comment by boskjoett** [comment]
No, using Headers.Express has no significant effect.
I have made a performance test setup that runs a simple test in docker-compose.
RabbitMQ is part of the docker-compose stack.
It runs 10 publishers and 10 subscribers that publishes messages between random publishers and subscribers and with random delays between each message publishing. When a subscriber receives a message it returns the message to the publisher using bus.Reply().
The test output is logged to console. 
The source code can be found in this Github repo
[https://github.com/boskjoett/rebus-performance-test](https://github.com/boskjoett/rebus-performance-test)

**Comment by boskjoett** [comment]
Using an [Express] attribute on message classes, using the header Header.Express, and setting PublisherConfirms to false like this

```
    .Transport(t => t.UseRabbitMq(rabbitMqConnectionString, _inputQueueName)
                     .SetPublisherConfirms(false))
```

is that just 3 different ways to achieve the same?

**Comment by mookid8000** [comment]
The express header is a Rebus feature that can be interpreted by the transport as "if it's possible to give up some reliability and get increased speed in return, then do it!". 

Different transports have different ways of increasing the speed, but with RabbitMQ that can be done by skipping the wait for publisher confirms, so that's how the RabbitMQ transport does it.

So yes, when you call `.SetPublisherConfirms(false)` you get the same behavior as if you had added the express header to all send/published messages.
