### ISSUE TITLE
Generic wiring of subscriptions

### ISSUE THREAD

**Issue by stevengopmo** [rebus-org/Rebus#437]
Is there a simple way to wire all the messages my application must respond to?  I'm using Sub/Pub and I want my application to subscribe to quite a few messages.  Currently I do 

`bus.Subscribe<MyMessage>()`

Nothing wrong with this of course other than just tedious.    I'm using SimpleInjector as my container.

I would also like to subscribe to all messages that inherit from an interface but that interface is not in the same assembly as the messages.  I'm able to subscribe to the interface but never get any messages in my handler for that interface.  I'm doing that by 

`.Routing(r => r.TypeBased().MapAssemblyOf<IDomainEvent>("publisher"))`

then
`bus.Subscribe<IDomainEvent>()`

This saves the subscription but then I never get any messages even though all implement this interface.

I guess what I really want to do is say, "Subscribe to all the messages in this assembly and if you don't find a handler, treat it as an object.".  Is that possible?

**Comment by mookid8000** [comment]
Well.... as you have correctly discovered, you need to subscribe to all concrete types of messages that you wish to receive.

E.g. something like

    await bus.Subscribe<OneDomainEvent>();
    await bus.Subscribe<AnotherDomainEvent>();
    //...

does the trick - this will ensure that the subscriber endpoint gets these particular event types in its input queue.

The subscriber can then handle the events in several ways, where one is to simply implement `IHandleMessages<IDomainEvent>` and let [polymorphic dispatch](https://github.com/rebus-org/Rebus/wiki/Polymorphic-message-dispatch) do its thing.

If you want to be sure that your subscriber always subscribes to all domain event types, I suggest you execute something like this at startup:

    var assembliesToScan = new []
    {
        typeof(IDomainEvent).Assembly,
        typeof(OneDomainEvent).Assembly
    };

    var domainEventTypes = assembliesToScan
        .SelectMany(a => a.GetTypes())
        .Where(i => !i.IsInterface && !i.IsAbstract)
        .Where(t => t.GetInterfaces().Any(i => i == typeof(IDomainEvent)));

    await Task.WhenAll(domainEventTypes.Select(t => bus.Subscribe(t)));

thus automatically figuring out which concrete event types exist and subscribing to them all.
