### ISSUE TITLE
Scatter / Gather

### ISSUE THREAD

**Issue by paulmarshall** [rebus-org/Rebus#438]
I have a requirement to a batch a number of web service calls on the receipt of a single message appearing in a single MSMQ. 

Is "sagas" the way to go?

The interaction with the 3rd party web service is further complicated because I need to call it once, then poll subsequently for an acknowledgement with a correlation id, returned in the reply to the initial call to the web service.

**Comment by mookid8000** [comment]
Excellent question 👍 can I make you go to [StackOverflow](http://stackoverflow.com/questions/tagged/rebus) and ask the question instead? I'll answer your question as quickly as I can then 😄
