### ISSUE TITLE
Don't back off too much

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#439]
It turns out that this is painfully slow:

    class TakeTimeHandler : IHandleMessages<string>
    {
        readonly IBus _bus;

        public TakeTimeHandler(IBus bus)
        {
            _bus = bus;
        }

        public async Task Handle(string message)
        {
            for (var counter = 0; counter < 100; counter++)
            {
                await _bus.Publish(new
                {
                    Text = $"This is message {counter}"
                });
            }
        }
    }

when using 1 single worker thread and a subscription storage that is `async`....

It is most likely caused by a subtle timing issue that causes the worker thread to very quickly decide to back off after having kicked off the `await _bus.Publish(...)` bit, even though the continuation becomes available to run almost immediately.

**Comment by mookid8000** [comment]
Closing it, because recent timing tweaks seem to have reduced the impact of this issue

**Comment by colin-higgins** [comment]
Had you tried the `ExecuteSynchronously` hint?

**Comment by mookid8000** [comment]
The new thread pool-based workers solves this problem completely, as workers no longer need to try to balance message receiving and continuation execution.

Rebus workers now only receive messages and execute the pipeline until the first `await`, after which the rest runs on the thread pool. This way, back-off can be configured to use even very long intervals, while not affecting continuation execution at all.
