### ISSUE TITLE
PubSub sample

### ISSUE THREAD

**Issue by bnogueira** [rebus-org/Rebus#440]
Greetings,

I downloaded the samples and started to experiment them.

In the PubSub sample, when the publisher publishes a TimeStamp the Subscriber1 receives it as a string instead of a TimeStamp.

Thank you.

**Comment by mookid8000** [comment]
oh - it must be because a JSON-serialized `TimeStamp` becomes a `string` which is then just a `string` in the receiving end.

I'll fix the sample - thanks for telling me 👍 😄

**Comment by mookid8000** [comment]
I've fixed the sample and updated to the latest Rebus now 😄

**Comment by bnogueira** [comment]
Thank you! :+1:
