### ISSUE TITLE
Rabbitmq transport based on EventingBasicConsumer

### ISSUE THREAD

**Issue by Hangsolow** [rebus-org/Rebus#441]
The current rabbitmq transport hits the rabbitmq server with a lot of get requests even when there is no messages to be fetched since it is using BasicGet. 

I'm thinking to create a rabbitmq transport based on EventingBasicConsumer in order to be a bit nicer to the rabbitmq server since that will push messages to Rebus when there is one, which will be a little  bit better on rabbitmq server, especially if there are extended periods of time when there is no messages to fetch on the server.

Can you think of a reason not to do an rabbitmq transport based on EventingBasicConsumer or should I just dive into it?
/Alex

**Comment by mookid8000** [comment]
That would be extremely cool! - in fact I think the existing transport could easily be changed to use this way of getting messages.

For inspiration, you might want to look at how Rebus' Azure Service Bus transport can [use a prefetch queue](https://github.com/rebus-org/Rebus/blob/master/Rebus.AzureServiceBus/AzureServiceBusTransport.cs#L64) to store prefetched messages in a `ConcurrentQueue<T>`. I am thinking that this approach could be easily transferred to the RabbitMQ transport.

Would you be interested in changing the existing `RabbitMqTransport` to work this way?

Please let me know if you need any hints or have any questions 😄

**Comment by Hangsolow** [comment]
Well my plan was to copy RabbitMqTransport to have a starting point anyway so I have no problem with adding the functionality to it instead :wink:  

I will give it a look and get back to you if I have any questions :smiley:

**Comment by mookid8000** [comment]
👌

**Comment by Hangsolow** [comment]
Hi again

I have done a little work on this and I think it is pretty much done.
Can you have a look and see if you can find any problems with it? 

[https://github.com/Hangsolow/Rebus/compare/7493964a53...c1f3d07ca4 ](https://github.com/Hangsolow/Rebus/compare/7493964a53...c1f3d07ca4)

**Comment by mookid8000** [comment]
I'm not an expert on RabbitMQ... but isn't `EventingBasicConsumer` supposed to be used by creating it once at startup?

From your code it seems like it is created every time `Receive` is called by Rebus....

**Comment by mookid8000** [comment]
Actually, I think `QueueingBasicConsumer` seems like a better fit for doing non-blocking RabbitMQ message receive as it provides a thread-safe in-mem queue for received message out of the box

**Comment by Hangsolow** [comment]
EventingBasicConsumer is 'cheap' to create since all the heavy lifting is done by the model which creates and maintains the channel to the rabbitmq server, although I just realized that the model currently gets disposed after each message which is not optimal and something I need fix.  

That said I think your right that QueueingBasicConsumer might be a better fit here since that will allow messages to be prefetched and thus reducing the roundtrips to the  rabbitmq server. 
I do a little refactoring with QueueingBasicConsumer  and see how it goes  :wink:

**Comment by mookid8000** [comment]
cool :)

It would be natural to initialize the `QueueingBasicConsumer` in the `Initialize` method, and then `Receive` would simply just pull the next message from the queue

Let me know if you need any further pointers 😄

**Comment by Hangsolow** [comment]
Hi again

I have refactored the code to use `QueueingBasicConsumer ` and it seems to work quite well!

I have added a optional parameter to the `RabbitMqTransport` constructor: `maxMessagesToPrefetch` with a default value of 50, I'm thinking that should be configurable but I will leave that to you if and where that should happen :wink: . 

Have a look and talk me if you think there is anything missing!. :smile:   

[https://github.com/rebus-org/Rebus/compare/master...Hangsolow:master](https://github.com/rebus-org/Rebus/compare/master...Hangsolow:master)

**Comment by mookid8000** [comment]
Cool 👍 😄  would you mind opening up a PR?

**Comment by Hangsolow** [comment]
Done :smile:

**Comment by mookid8000** [comment]
This feature will be released in 0.99.56.
