### ISSUE TITLE
Saga does not work with IFailed<TMessage> types

### ISSUE THREAD

**Issue by jinhong-** [rebus-org/Rebus#442]
As the title says, the Saga code does not handle IFailed messages well

**Comment by mookid8000** [comment]
what happens?

**Comment by jinhong-** [comment]
The Saga would complain that the message that it is unable to correlated the message.

In the CorrelatedMessage method i would register it like so:
config.Correlate<IFailed<TMessage>>(m => m.Message.CorrelationId, d => d.CorrelationId);

But when the Message fails, the fail handler will not fire, instead exception would be logged
"Could not find any correlation properties for message  Rebus.Retry.Simple.FailedMessageWrapper`1[<Omitted>] and saga data <Omitted>".

Which makes sense when you look at the method ForMessage in SagaDataCorrelationProperties.cs. It only caters for base types but not interfaces

**Comment by mookid8000** [comment]
I think I recall having fixed this recently - which version of Rebus are you using?

Since 0.99.37 Rebus has had [polymorphic correlation](https://github.com/rebus-org/Rebus/blob/master/CHANGELOG.md#09937) which has got to be what you are missing....

**Comment by jinhong-** [comment]
I am using 0.99.50. Like i mentioned, the problem is that the polymorphic correlation handles only base classes. It does not take into account interfaces. IFailed is an interface so it will not be captured

**Comment by mookid8000** [comment]
Right 😄 I'll see if I can fix it right away

**Comment by mookid8000** [comment]
I've fixed it in 0.99.53 which will be out as soon that the build server has finished crunching.

**Comment by mookid8000** [comment]
0.99.53 is on NuGet.org now - thanks for reporting this issue 👍 😁

**Comment by jinhong-** [comment]
Wow cool that's really fast of you to fix it
