### ISSUE TITLE
Customizable worker finish timeout

### ISSUE THREAD

**Issue by Rzpeg** [rebus-org/Rebus#443]
Hello,
Currently the ThreadWorker has 1 minute timeout to finish processing active handlers, when signaled to stop. 

Is there any way to customize the value?
I have a few long running handlers that take more than 1 minute to process, and I don't want to interrupt them.

**Comment by mookid8000** [comment]
There is no way at the moment. Generally, you should probably try to avoid having handlers run for that long, although I realize that that might not always be possible.

I will think about how this could be made. I'm thinking that it would be natural to put it in a place where different kinds of low-lever technical things could be configured. There's also several poll intervals and stuff like that that one might want to customize.

**Comment by Rzpeg** [comment]
Thanks for the response.
I know, but the few long running handlers contain some legacy code that was moved from the main app and that won't be refactored anytime soon.

I will fork Rebus and try implement the option to set custom timeout using options, similar to how MaxParallelism is implemented. I will then make a pull-request.

Thanks! Rebus is awesome :)

**Comment by mookid8000** [comment]
Oh, but I am not sure that I think that that particular setting belongs on the existing options! 

I'm thinking that there should be another place for low-level settings like that... you can definitely fork&implement so you can make your stuff work

**Comment by Rzpeg** [comment]
I don't think it's any more low level setting, than DefaultDueTimeoutsPollInterval, that's why I am planning on implementing it by side. 

Eventually such settings may be moved to another place, if there will be needs for more low-level customizations.

**Comment by mookid8000** [comment]
You are absolutely right

Sendt fra min iPhone

**Comment by Rzpeg** [comment]
I have implemented this extra option and made related tests (both unit tests of ThreadWorker and integration tests against the new option.).

**Comment by Rzpeg** [comment]
I think you can close the issue for now :smile:

**Comment by mookid8000** [comment]
excellent! 👍

**Comment by Rzpeg** [comment]
Might be useful to add this feature to the changelog https://github.com/rebus-org/Rebus/blob/master/CHANGELOG.md.
I guess it was published in v 0.99.54 ?

**Comment by mookid8000** [comment]
oh yeah, thanks for reminding me 😄 I've added it to 0.99.55
