### ISSUE TITLE
Turn off/ignore encryption  for types of messages or endpoints

### ISSUE THREAD

**Issue by runes83** [rebus-org/Rebus#451]
Make it possible to send messages that are not encrypted, while still having encryption on.

Scenario:
Have an endpoint that we do not want to share our encryption key with and that only should handle on type of messages. If it was possible to turn off encryption for this type, then this endpoint would not have to know the encryptionkey to handle messages of that type.

**Comment by mookid8000** [comment]
Great idea 😄 

It could be easily achieved if the outgoing step that encrypts the message body could spot a special `do-not-encrypt-this-message` header and just leave the body alone.

This way your not-so-secret messages could look like this:

    [Header("do-not-encrypt")]
    class NotSecret { ... }

**Comment by runes83** [comment]
Yes and just make a constant or something for the header name, so the same header name are used everywhere. 
The in going step should also read the header an not try to decrypt?

**Comment by mookid8000** [comment]
The incoming only decrypts if it sees a `rbs2-content-encryption` header: [DecryptMessagesIncomingStep](https://github.com/rebus-org/Rebus/blob/master/Rebus/Encryption/DecryptMessagesIncomingStep.cs#L30-L46), so it would never have tried to decrypt an unencrypted message anyway

**Comment by zabulus** [comment]
Off topic: configuration doesn't allow to specify custom encryption, is this intentional?

**Comment by mookid8000** [comment]
Yeah well... - I guess the actual encryption/decryption could have been abstracted away in a way that allows for customizing it, but I guess I didn't feel it was necessary.

Originally, it was only meant as a simple scrambling of the message contents that meant that you had to work hard (pretty hard, actually) to "accidentally" see the contained information. This way, you could pass payroll information and other sensitive-but-not-that-sensitive messages around.

Do you have any specific requirements with regards to how the data is encrypted?

**Comment by zabulus** [comment]
I think extracting interface of Encryptor class is enough to provide custom encryption. And using the interface instead Encryptor in configuration, of course.

**Comment by zabulus** [comment]
Filled separate issue for discussion: https://github.com/rebus-org/Rebus/issues/452

**Comment by mookid8000** [comment]
this one will be out in 0.99.67 when the build server has finished munching
