### ISSUE TITLE
Provide interface for custom encryption scheme

### ISSUE THREAD

**Issue by zabulus** [rebus-org/Rebus#452]
Extract interface from Encryptor class and replace with it all using of Encryptor

**Comment by mookid8000** [comment]
At the moment there is a header on an encrypted message that says `rijndael` because that's the encryption algo cyrrently used. This header should probably be set accordingly when alternative algorithms can be plugged in.

**Comment by zabulus** [comment]
> This header should probably be set accordingly when alternative algorithms can be plugged in.

I'll add it to the new interface as read-only property.

**Comment by mookid8000** [comment]
release in 0.99.56 - awesome work 👍
