### ISSUE TITLE
Azure Service Fabric Host

### ISSUE THREAD

**Issue by SvenVandenbrande** [rebus-org/Rebus#453]
Rebus can be hosted on Service Fabric?

**Comment by mookid8000** [comment]
You might want to read [this answer](http://stackoverflow.com/a/37268471/6560)

**Comment by SvenVandenbrande** [comment]
Ok. It was just something I wanted to mention. If it was not yet possible. That it probably could be something that people wanted.

Good to include in the documentation. :)
Did you already created a "ReadTheDocs", so we can add it?

**Comment by mookid8000** [comment]
no... I don't know how that ReadTheDocs thing work... haven't had time to look at it

**Comment by SvenVandenbrande** [comment]
See as example Simple Injector

The ReadTheDocs page
http://simpleinjector.readthedocs.org/

The documentation hosted on github & editable by other people.
https://github.com/simpleinjector/Documentation

**Comment by mclausen** [comment]
Well we after some hasel we actually went in a bit different direction, because we had some issues with stateful services. We are in the midst of rewriting the code execute Rebus from the run block, but thats still work in progress. Ill post something as soon as our results goes from "working" to "awesome" 😄

**Comment by mikanyg** [comment]
I have added a comment to the Stackoverflow post that @mookid8000 refers too http://stackoverflow.com/questions/37163990/message-handler-not-activating/37268471#37268471

Basically it can be done, but be mindfull whether Rebus is being hosted in a Stateless or Statefull Service as described in the comment.

**Comment by mookid8000** [comment]
👍 😄
