### ISSUE TITLE
Rebus keeps on trying receiving messages after being signaled to dispose (ASB)

### ISSUE THREAD

**Issue by Rzpeg** [rebus-org/Rebus#461]
After one of the recent updates (@ 56 I think) I started noticing that, when I have a lot of worker threads (10, for the example, with MaxParallelism 50 ) after being signaled to Dispose(), Rebus continue trying to call ReceiveBrokeredMessage. The call is, however, not coming from directly invoking
`Task<TransportMessage> Receive(ITransactionContext context)` (That's logically, because ThreadWorker sets canTryToReceiveNewMessage to false when signaled to stop.) but yes from using 
```
(await _bottleneck.Enter()){
..
}
```

Inside, which calls ReceiveBrokeredMessage(...) which, again awaits for ReceiveAsync and so on (all this after signaling rebus to Dispose).

Seems like the AsyncBottleneck is not cancellation-aware.
I'll be doing some tests and will see what can be done here.

**Comment by Rzpeg** [comment]
The approach I am taking atm is refactoring ITransport contract from:
`Task<TransportMessage> Receive(ITransactionContext context)`
to: `Task<TransportMessage> Receive(ITransactionContext context, CancellationToken cToken = default(CancellationToken))`, where token is passed by the ThreadWorker, we'll where it goes :)

**Comment by Rzpeg** [comment]
Ok, I am able to terminate the waiting of bottleneck using the token from ThreadWorker, and the handlers that started processing aren't interrupted. The issue I haven't got around yet is cancelling QueueClient ReceiveAsync without breaking the active transaction context (pre-mature dispose).

**Comment by mookid8000** [comment]
it is awesome that you're doing this 👍 😁

**Comment by Rzpeg** [comment]
Cool to contribute to one of my favorite projects on github! :smile:
P. S.  What's the purpose of the AsyncBottleneck for azure and sql transports anyway?

**Comment by mookid8000** [comment]
The purpose of `AsyncBottleneck` is to avoid having too many parallel attempts to try to receive messages.... if there was no limit to the number of concurrent receive operations, one single thread could quickly consume all available resources, while attempting to receive messages when the receive API supports `async`, because the thread would `await` on the receive operation and then the thread would become available to start yet another receive operation immediately, which would then `await` on the next receive operation and so forth.

**Comment by Rzpeg** [comment]
Oh, got it now. Thanks :)
I was thinking about finding a way to use ASB's `Task OnMessage` instead of pooling for ReceiveAsync, simiiar to how it's done in [MassTransit](https://github.com/MassTransit/MassTransit/blob/develop/src/MassTransit.AzureServiceBusTransport/Receiver.cs) but I am afraid the current Rebus architecture won't support it. At the moment I am toying with something like this:
 
```

           public Task<TransportMessage> Receive(ITransactionContext context, CancellationToken cToken = new CancellationToken())
           {
               var client = QueueClient.CreateFromConnectionString("connString", "input", ReceiveMode.PeekLock);
               var tcs = new TaskCompletionSource<TransportMessage>();
               client.OnMessageAsync(async asbMsg =>
               {
                  // simulate work
                   await Task.Delay(TimeSpan.FromMinutes(1));
                   var rebusMessage = new TransportMessage(null, null);
                   tcs.SetResult(rebusMessage);
   
               });
   
               cToken.Register(async () =>
               {
                   await client.CloseAsync();
                   tcs.SetCanceled();
               });
   
               return tcs.Task;
           }

```

**Comment by mookid8000** [comment]
this is solved by your cancellation token PR, right?

assuming that it is, closing it now 😁 

PS: absolutely awesome work 👍

**Comment by Rzpeg** [comment]
Yeah, it's working for preventing new receives in ASB when cancellation is requested, but still I have no solution to cancel a client that's already awaiting on Receive. The example I gave is not working because ASB's OnMessageAsync can trigger multiple times inside the single Rebus Receive call, and that breaks things :confused:
