### ISSUE TITLE
Generic type arguments for IHandleMessages aren't handled?

### ISSUE THREAD

**Issue by replaysMike** [rebus-org/Rebus#464]
Hey guys.. I ran into an issue when trying to use a handler with a generic type argument. Any messages sent to it aren't picked up, is this a known limitation?

```
public class FooHandler : IHandleMessages<Foo<Bar>>
{
}

bus.Send<Foo<Bar>>(new Foo<Bar>());
```

I also noticed they aren't picked up by a default handler either `IHandleMessages<object>`.

**Comment by mookid8000** [comment]
I just tried [this program](https://gist.github.com/mookid8000/9c3decf3d7e59fe35951841cc1f8ec3f) which yields this on my machine:

![image](https://cloud.githubusercontent.com/assets/32968/15802790/5f6bbf6c-2abf-11e6-943f-ab4c78804eaf.png)

which was pretty much what I expected 😄 

Could you try and either 1) `await` the call to `bus.Send`, or 2) `Wait()` at the end of it?

I suspect that the message does not even get sent, which probably explains why you are not receiving it 😁

**Comment by replaysMike** [comment]
My code uses await/async and does await the send. If I literally change the message type the message is sent and received (and they are both declared in the handler mappings). I'll take a closer peek at that app and see if it's a configuration problem I haven't been able to identify.

**Comment by mookid8000** [comment]
Sure 😄  if it keeps tricking you, and if you can reproduce it in something you can send to me, please do - I'll be happy to debug it.

**Comment by Rzpeg** [comment]
Just to note, we had the similar problem that had to do with the IoC we are using (StructureMap v2), as well as with the resolution of IFailed<TMessages> and we had to code a new adapter internally to make it work. The Autofac-based application is working great by the way... Try changing the IoC container for your app.

P.S.  @mookid8000 here is the IFailed resolution code we had to add to make SM2 work:

```
....
 if (typeof(TMessage).IsConstructedGenericType)
            {
                var genericArg = typeof(TMessage).GetGenericArguments().ElementAt(0);
                var failedType = typeof(IFailed<>).MakeGenericType(genericArg);
                if (failedType.IsAssignableFrom(typeof(TMessage)))
                {
                    var iHandleFailedGeneric = typeof(IHandleMessages<>).MakeGenericType(failedType);
                    var failedHandlers = container.GetAllInstances(iHandleFailedGeneric);
                    var castedHandlers = failedHandlers.Cast<IHandleMessages<TMessage>>();
                    return Task.FromResult(castedHandlers.AsEnumerable());
                }
            }
...
```

**Comment by mookid8000** [comment]
@Rzpeg that's weird! Did you try and see if your StructureMap container was capable of resolving all of `IFailed<TheMessage>`?

**Comment by replaysMike** [comment]
yea sorry for the delay, busy project. I'm going to double check and reproduce with a test app, I think it's an issue with using Windsor/the way we are mapping handlers as we don't use the BuiltInHandlerActivator, but rather the following:

```
/// <summary>
    /// Automatic registration of all defined Handlers in the assembly (using Castle Windsor)
    /// </summary>
    public class HandlerInstaller : IWindsorInstaller
    {
        public void Install(IWindsorContainer container, IConfigurationStore store)
        {
            // register all types that handle IHandleMessages<>
            container.Register(Classes.FromThisAssembly()
                .BasedOn<IHandleMessages>()
                .WithService.AllInterfaces()
                .LifestyleTransient());
        }
    }
```

I'll post a full test app once I get a few extra min..

**Comment by replaysMike** [comment]
a side note, though I hate them, we also ran into a really weird handler mapping situation where one handler message was inheriting from a base class which was also mapped, and it caused a message loop. I'll pop that on a separate thread as it might be interesting to look at (we just restructured the class layout to prevent it)
