### ISSUE TITLE
MSMQ permissions

### ISSUE THREAD

**Issue by zabulus** [rebus-org/Rebus#467]
Is there API to set permissions for an MSMQ?

**Comment by mookid8000** [comment]
Not readily, no. But I can definitely see that it would be nice to be able to specify default permissions for queues created by Rebus.

What would you like to be able to do?

**Comment by zabulus** [comment]
We've ran to issue where pub/sub scenario didn't work as expected. After research I've found out that there is no permission for anonymous logon user to send. And because queues were created as no authentication all messages were sent to dead letter queues with access denied status.
I'd like to have possibility to create either authenticated queue or add send permission to anonymous logon.

**Comment by mookid8000** [comment]
I've been thinking about this feature for some days now.... I am not sure that I would know how it should be done.

My initial thought was to provide some kind of extra options on the `UseMsmq(...)` configuration extensions, e.g. like so:

	Configure.With(...)
		.Transport(t => {
			t.UseMsmq(...)
				.DoSomeExtraStuffHere();
		})
		.Start();

which could e.g. then be used to assign/change the rights of the endpoint's own input queue, e.g. by doing something like this:

	t.UseMsmq(...)
		.SetPermission("Everyone", MessageQueueAccessRights.GenericWrite)
		.SetPermission("someParticularUser@your_directory", MessageQueueAccessRights.Generic);

Do you have any ideas on how it could look?

**Comment by zabulus** [comment]
Proposed API is enough for me, but I think it is better to duplicate ```SetPermission``` surface from MSMQ

**Comment by mookid8000** [comment]
I've added a hook that allows for customizing newly created queues. For instance, to give `Everyone` full access, you can now (from 0.99.65) do this:

    t.UseMsmq(InputQueueName)
        .OnCreated(queue =>
        {
            var user = new SecurityIdentifier(WellKnownSidType.WorldSid, null)
                .Translate(typeof(NTAccount))
                .ToString();

            queue.SetPermissions(user, MessageQueueAccessRights.FullControl);
        });

This way it should be possible to e.g. grant other domain accounts proper send rights to an endpoint's input queue, etc.

You can register as many callbacks as you like. 

The callbacks will be invoked in order, AFTER the default permissions have been set - this means that calling `queue.ResetPermissions();` as the first thing allows you to discard the defaults completely.

The callbacks will ONLY be called for newly created queues.

**Comment by zabulus** [comment]
Great! thanks
