### ISSUE TITLE
subscription broken

### ISSUE THREAD

**Issue by stevengopmo** [rebus-org/Rebus#469]
Hi,

I'm having a very strange problem this morning with my subscriptions.  I get this message in my log

`Rebus.Exceptions.RebusApplicationException: Message with ID 26b7fcc6-a66b-4322-846b-bcb03ba30a8f and type Rebus.Messages.Control.SubscribeRequest, Rebus could not be dispatched to any handlers
   at Rebus.Pipeline.Receive.DispatchIncomingMessageStep.<Process>d__1.MoveNext()`

My webapi (owner of the incoming subscriptions) is configured like so

`            var jsonSubcriptionStorage = Path.Combine(appDataPath + @"\subscriptions.json");
            Configure
                .With(adapter)
                .Options(o=> o.LogPipeline(true))
                .Logging(l => l.Serilog(Serilog.Log.Logger))
                .Transport(t => t.UseMsmq("myMessages"))
                .Subscriptions(s => s.UseJsonFile(jsonSubcriptionStorage))
                .Start();
`

my windows service that is subscribing to the messages is configured like

`            var bus = Configure
                .With(adapter)
                .Options(o => o.LogPipeline(true))
                .Serialization(s =>
                {
                    var settings = new JsonSerializerSettings();
                    settings.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);
                    s.UseNewtonsoftJson(settings);
                })
                .Logging(l => l.Serilog(Serilog.Log.Logger))
                .Transport(t => t.UseMsmq("myService"))
                .Routing(r => r.TypeBased().MapAssemblyOf<ProjectProposed>("myMessages"))
                .Start();
`

This used to work, I have the subscriptions.json to prove it, but when I deleted the subscriptions file to try something I get the error above.

**Comment by stevengopmo** [comment]
Found the issue, it was because I overrode the default JsonSerializerSettings for my subscriber.  It would be nice to be able to access the current settings some way so as only to replace or tweak the settings I need to work with (NodaTime in this case).

In any case this can be closed

**Comment by mookid8000** [comment]
Oh, but you CAN get access to the settings - it's thus the _default JSON serializer_ that is sealed off - if you want to customize things, go ahead and pull in [Rebus.NewtonsoftJson](https://www.nuget.org/packages/Rebus.NewtonsoftJson/), and then you can hand your custom `JsonSerializerSettings` to it 😄

**Comment by stevengopmo** [comment]
but, I can't get a ref to your DefaultSettings so I'm not overwriting a setting that rebus expects.  That's what happened in this case.  I didn't realize that not using TypeNameHandling = TypeNameHandling.All would cause my subscriptions to fail.

**Comment by mookid8000** [comment]
oh sorry - didn't understand you fully there 😁
