### ISSUE TITLE
message mutators

### ISSUE THREAD

**Issue by stevengopmo** [rebus-org/Rebus#470]
Hi,

I'm looking for the simplest way to mutate outgoing messages with a header.  I read a post here (http://mookid.dk/oncode/archives/3930) about one way was to decorate ISerializer.  Are there other ways?  I believe previous versions used an event (#122), but I don't see that now.

**Comment by mookid8000** [comment]
An [outgoing message step](https://github.com/rebus-org/Rebus/wiki/Outgoing-messages-pipeline) is the way to go 😄 

You can read more [here](http://mookid.dk/oncode/archives/3938) on how to inject steps in the pipeline, and see how to figure out where to place the step.

Rebus has a few steps already that add headers to the message - you can e.g. take a look at [`AssignTypeHeaderStep`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Pipeline/Send/AssignTypeHeaderStep.cs) for inspiration.

**Comment by stevengopmo** [comment]
I'm probably making this way more difficult than needed but...  How do I get reference to the existing Injectionist in order to reference the IPipeline?  Doing a search of the source for AssignTypeHeaderStep I see that it's registered during the Start method of the RebusConfigurer to the _injectionist internal variable.  

I can new up an Injectionist, but how do I think assign it to the RebusConfigurer?

**Comment by mookid8000** [comment]
oh, sorry - try and take a look at how saga auditing is enabled in [`SagaAuditingConfigurationExtensions`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Auditing/Sagas/.cs#L17-L34) - here it can be seen how an extension method mounts itself on `OptionsConfigurer`, decorating `IPipeline` by wrapping whichever pipeline is already configured inside a `PipelineStepInjector`, which can be configured to inject steps into both the incoming and outgoing pipelines.

If you want to get an overview of what is in your pipelines, Rebus can be configured to [output the pipeline steps](https://github.com/rebus-org/Rebus/wiki/Log-message-pipelines) into the log when it starts... this can help you figure out which step to choose as the "anchor" for positioning your own step.

I hope that makes it clear 😄

**Comment by mookid8000** [comment]
I can understand why these things might be slightly intimidating at first.... but once you get into working with the Injectionist and the principle of dependency injection in combination with decorators, it turns out to be a really powerful and flexible mechanism (I promise! 😁 )

**Comment by stevengopmo** [comment]
yeah we use the concepts of decorators alot in our code (a fundamental design principle for us), it's just a little different figuring out how to do it in conjunction with Rebus.  I like the idea very much.  I think this is correct?

````
.Options(o =>
                {
                    o.Register<IPipeline>(c =>
                    {
                        var pipeline = c.Get<IPipeline>();
                        return new PipelineStepInjector(pipeline).OnSend(new TenantIdOutgoingMutator(),
                            PipelineRelativePosition.Before, typeof(SerializeOutgoingMessageStep));
                    });
````

**Comment by mookid8000** [comment]
When you `o.Register<IPipeline>` you are registering a _primary_ implementation of `IPipeline`. This will cause Rebus to skip installing its own default (which is what you saw in [`RebusConfigurer`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Config/RebusConfigurer.cs#L198-L221)). Conclusion: This is not what you want 😄 

You want to `o.Decorate<IPipeline>` - so if you cange `Register` into `Decorate`, then it should work 😃

**Comment by stevengopmo** [comment]
Oh yeah! I mean I knew that, I was just testing you. :)

**Comment by mookid8000** [comment]
you got me then! 😉
