### ISSUE TITLE
There should be a way to route every message to a single queue.

### ISSUE THREAD

**Issue by jeffreyabecker** [rebus-org/Rebus#474]
I often rebus in a website to send processes off into the background. When I do this I configure single receiving queue. There should be a simple way to set this up.

**Comment by mookid8000** [comment]
More simple than:

    var bus = Configure.With(...)
        .(...)
        .Routing(r => r.TypeBased().MapFallback("gets_all_the_messages"))
        .Start();

    // ....
    
    await bus.Send("here you go!");

or is that not what you meant?

**Comment by jeffreyabecker** [comment]
Basically just some syntax sugar around that. If you're open to a PR.

**Comment by mookid8000** [comment]
I'm always open to PRs 😄 

Rebus does not have a place yet for things that are basically shortcuts to other stuff that already exists. There's a solution folder called "convenience" though, which is for things that are slightly out-of-band.

Could we start out by adding a new project to the "convenience" folder? Don't know what it should be called.... I just thought about something like `Rebus.Recipes` or something like that - what do you think?

**Comment by jeffreyabecker** [comment]
I like that.
