### ISSUE TITLE
RabbitMQ failover with multiple connection strings

### ISSUE THREAD

**Issue by nicemd** [rebus-org/Rebus#483]
In Rebus.RabbitMQ v0.82 you could comma separate RabbitMQ connection strings and Rebus would handle failover to next instance in case of a failure.

t => t.UseRabbitMq("amqp://guest:guest@docker.local:5672,amqp://guest:guest@docker.local:5673", queue))

If I do that now in v0.99.67 I get a System.UriFormatException.

Is that going to be supported again?

/Niclas

**Comment by mookid8000** [comment]
Yes 😁

**Comment by mookid8000** [comment]
will be available in 0.99.68 😄 

please let me know if it works for you as it should

**Comment by nicemd** [comment]
Thanks a lot! It seems to work ok!
I found one error I failed a new issue for. Actually I think this bug was also in v0.82.
