### ISSUE TITLE
Methods missing

### ISSUE THREAD

**Issue by takinosaji** [rebus-org/Rebus#490]
He Rebus team!
Currently have update set of libraries for messaging in a project: Rebus/Rebus.RabbitMQ/Rebus.Castle.Windsor/Rebus.Log4Net/Castle.Windsor to latest versions. I was very confused when found that some of very convenient old methods are absend in that versions.

I have the following rebus configuration code:

 Configure.With(new WindsorContainerAdapter(container))
        .Logging(l => l.Log4Net())
        .Transport(t => t.UseRabbitMqAndGetInputQueueNameFromAppConfig(connectionString)
        .ManageSubscriptions().SetPrefetchCount(5))
        .MessageOwnership(d => d.FromRebusConfigurationSection())
        .Serialization(s => s.Use(new MySerializer()))
        .CreateBus()
        .Start();
These methods are absent in the new version:

UseRabbitMqAndGetInputQueueNameFromAppConfig
ManageSubscriptions in RabbitMqOptionsBuilder
MessageOwnership in RebusConfigurer
Log4Net extension methods is present in library not even recognized by VS
The Rebus documentation though still has references on old methods and scenarios in many places.

Also i used  ISerializeMessages and JsonMessageSerializer for building my own seriaizer. Do you have any replacement for them?

What has been done with old convenient methods? Could anybody give me a hint what apis to use in the current version (0.99.67) for existing way of configuring a client.

**Comment by mookid8000** [comment]
I've posted an [answer to your question on StackOverflow](http://stackoverflow.com/a/38387930/6560) 😄 

To reiterate: You either want to update to Rebus 2 (which requires that you update everything), or just update to Rebus 0.84.0 (which is the last "Rebus 1" version).

Here are some reasons why you might want to go through the hassle of updating to Rebus 2:

* it is `async` all the way, i.e. it is capable of utilizing CPU and memory in a very efficient manner
* it has integration libraries that are up-to-date with their dependencies
* it has a data bus
* it has a much improved extensibility model

Please let me know if you have any further questions 😄

**Comment by takinosaji** [comment]
Thank you for a answer. I am new to Rebus and messaging. Could you give me a hint where to read about what and how should i use instead of old methods Also is it still possible to use something in new Rebus instead of UseRabbitMqAndGetInputQueueNameFromAppConfig - to read queue name from rebus config, what should i use instead of ManageSubscriptions and MessageOwnership(d => d.FromRebusConfigurationSection()

Thank you in advance!!!

**Comment by mookid8000** [comment]
Rebus 2 unfortunately does not provide a way to pick up queue names from app.config because it is expected that it will be ported to .NET Core some time soon, and the way .NET applications are configured is going to change with that.

`ManageSubscriptions` is no longer necessary, as Rebus 2's RabbitMQ transport will always use proper RabbitMQ topics to do pub/sub.

`MessageOwnership` is replaced by `Routing`. Rebus can pick up endpoint mappings from app.config if you add the [`Rebus.XmlConfig`](https://www.nuget.org/packages/Rebus.XmlConfig/) package and go

	Configure.With(...)
		.(...)
		.Routing(r => r.TypeBasedRoutingFromAppConfig())
		.Start();

Generally, porting your code from Rebus 1 to Rebus 2 should be pretty straightforward - just remember to `await` those `async` methods 😉

**Comment by takinosaji** [comment]
Thank you! Also i used `ISerializeMessages` and `JsonMessageSerializer` for building my own serializer and     `.Serialization(s => s.UseJsonSerializer())` for bus configuration. Do you have any replacement for them?

**Comment by mookid8000** [comment]
Leave the serializer configuration out, and it will default to use a pretty tolerant JSON serializer based on Newtonsoft.

If you want to customize serialization, you can bring in the [`Rebus.NewtonsoftJson`](https://www.nuget.org/packages/Rebus.NewtonsoftJson/) package which allows for providing your own `JsonSerializerSettings` - then you can do anything! 😁

**Comment by takinosaji** [comment]
I very appreciate your help. Could you give me one more hint please? How can i now set error queue for rebus.rabbitmq. Previously i have set it in config file in Rebus section.

**Comment by mookid8000** [comment]
Use `.Options(o => o.SimpleRetryStrategy(errorQueue: "whatever"))`

Sendt fra min iPhone

**Comment by takinosaji** [comment]
Thank you. Could you help me with other matters of configuration?

I have such a bus initialization code:
`            var busConfigurer = Configure.With(new BuiltinHandlerActivator())
                                .Logging(l => l.Log4Net())
                                .Transport(t => t.UseRabbitMqAsOneWayClient(connection)
                                    .Prefetch(5))
                                .Options(b => b.SimpleRetryStrategy(errorQueue));
                                new ConfigureRebusRoutesCommand(busConfigurer).Execute();`
where ConfigureRebusRoutesCommand does next:
` .Map<Message<Entity>>(
                    "My.Queue.In.my.Exchange")
                    .........`

The problem is that now client created two excnahges "RebusDirect" and "RebusTopic" then creates a new queue with name My.Queue.In.my.Exchange. And send messages there. I need to send messages in exchange with name Rebus for existing queue as we had using rebus1. Could you help me with it please?

**Comment by mookid8000** [comment]
Unfortunately Rebus 2 and Rebus 1 are not compatible!

In other words: You cannot just send from Rebus 2 to Rebus 1.

**Comment by takinosaji** [comment]
But i am sending to rabbit mq - is it no way to configure exchange name for rabbit?

**Comment by mookid8000** [comment]
You can customize the exchange names used by Rebus 2 by attaching `ExchangeNames(...)` in the configuration builder, like so:

    Configure.With(...)
        .Transport(t => t.UseRabbitMqAsOneWayClient(connectionString)
                         .ExchangeNames("CustomDirect", "CustomTopics"))
        .(...)

but if you succeed in sending to your Rebus 1 endpoint you will just realize that the message headers cannot be understood by Rebus 1.

**Comment by takinosaji** [comment]
Yes I thought I could make rebus1 on one site and rebus2 on the other side friends:).

But if it is impossible i should probably return to rebus1 everywhere.
And it is impossible - have i caught your point right?

**Comment by mookid8000** [comment]
"Impossible" is a pretty harsh word, it's just not really support 😉 

If your usage scenario is very simple, and if you are willing to do some thorough testing, you can actually make Rebus 2 attempts to send Rebus 1-compatible messages by going

    .Options(o => o.EnableLegacyMode())

but that is not really something I recommend that you use... the purpose is to allow for migrating an endpoint at a time, and then when all endpoints are running Rebus 2 - probably one night, when nobody cares - you can stop all endpoints and remove legacy mode from them.

**Comment by takinosaji** [comment]
Al right. I will try proceed with your advice now.

**Comment by takinosaji** [comment]
I have set `.ExchangeNames("CustomDirect", "CustomTopics"))` as you advisedand yeah it doesnt create new exchange anymore but my mapped messages are going to direct queue instead of topic.  Is there a way to configure them to use topic queue?

**Comment by mookid8000** [comment]
Well... the reason `TopicBased` is going away, is because of the confusion it has caused.... just to be absolutely clear: All routing is based on message queues, and then Rebus implements some kind of topic-based routing on topic of that.

The reason it is called `TypeBased`, is because topics are automatically inferred from message types (by default).

This means that when you

    await bus.Publish(new SomethingHappened(..));

with RabbitMQ, the topic is inferred from the `SomethingHappened` type thus resulting in publishing the message with the routing key `Messages.SomethingHappened, Messages` on the configured topic exchange (`RebusTopics` by default, `CustomTopics` in your case).

If you want to be in full control over the used routing key, you can use

    await bus.Advanced.Topics.Publish("my-custom-topic", new SomethingHappened(...));

to publish the message with the `my-custom-topic` routing key, and

    await bus.Advanced.Topics.Subscribe("my-custom-topic");

in the subscriber's end to subscribe to that topic.

**Comment by mookid8000** [comment]
and yes, I meant `EnableLegacyCompatibiliy`! Thanks for clearing that up 😄

**Comment by takinosaji** [comment]
In obsolete attribute you are pointing on `.Routing(r => r.Default().Map(...))` where r.Default - doesn't exist at least without any additional libraries that was confusing reference. Thank you for explanation i will try!

**Comment by takinosaji** [comment]
`await bus.Advanced.Topics.Publish("my-custom-topic", new SomethingHappened(...));`

as far as i am using this method i see that it sends messages to a topic which is set in bus configuration, and "my-custom-topic" appears to be a routing key for rabbit actually. Is it correct? if yes it means i should set routing key explicitly every time in code (when in rebus1 all this bindings were set in config file in rebus section being inserted into message automatically) ?

I am sorry i am confused you definitions a bit

**Comment by takinosaji** [comment]
Hopefully the last my problem is that my receiving Rebus bus is looking on a wrong queue. I have a 'Rebus' topic exchange and 'MyQueue' queue with binding in this exchange. I am seting the bus with next way 
`  var busConfigurer = Configure.With(new CastleWindsorContainerAdapter(_container))
                .Logging(l => l.Log4Net())
                .Transport(t => t.UseRabbitMq(_connectionString, _inputQueue).ExchangeNames("RebusDirect", "Rebus")
                    .Prefetch(5))
                .Options(o => {
                    o.SimpleRetryStrategy(_errorQueue);
                    if (_enableLegacyCompatibility)
                    {
                        o.EnableLegacyCompatibility();
                    }
                })
                .Serialization(s => s.Decorate(c => new XmlMessageSerializer()));

            return busConfigurer.Start();`

and it creates new 'MyQueue' for RebusDirect exchange and listenes it instead of my queue in tiopic exchange. Is it possible to tell rebus to listen my old queue?
