### ISSUE TITLE
Is Id generally unique for MS SQL Server transport?

### ISSUE THREAD

**Issue by jpierson** [rebus-org/Rebus#491]
I've noticed that since the primary key for the *Messages* table when using the MS SQL Server transport is a composite key comprised of `Id`, `Recipient`, and `Priority` that it makes it slightly cumbersome to deal with when manually inspecting and [manually manipulating the queue](https://github.com/rebus-org/Rebus/issues/322#issuecomment-232736890). Without reviewing the internal implementation it's not clear whether Id should conventionally be unique or not although based on the fact that it is an Identity column one could guess that it probably is and take a short cut as using it as a reasonable candidate key. If this is the case is there any danger in terms of performance of placing a unique constraint on the Id column to make it more explicit?

**Comment by mookid8000** [comment]
The `[Id]` column is unique, and a constraint can definitely be added to it to make it explicit.

The PK is as it is for historic reasons I guess.... initially, the table had only this single, clustered index.

Over time, the SQL transport has had expiration and message deferral capabilities added to it, so I don't think the index has to be like that anymore.

Why do you think the composite PK makes it cumbersome to work with?

**Comment by jpierson** [comment]
The composite key hasn't seemed to cause us much grief but when creating support tooling based on the SQL Transport we just wanted to make sure we had some firm understanding of the intentions with uniqueness of the [Id] column.
