### ISSUE TITLE
When does it really make sense to use a project like Rebus vs Hangfire?

### ISSUE THREAD

**Issue by markalanevans** [rebus-org/Rebus#494]
Our immediate need is background processing.
Both provide this, however management is full featured(built in UI) and deployment is simpler with Hangfire, but a service bus does seem like it could be more robust.

Aside from sending emails and post processing data. What are some pretty common examples that make using a Service Bus the right choice over http://hangfire.io/ when dealing with large web application?

**Comment by mookid8000** [comment]
> but a service bus does seem like it could be more robust

I wonder what you mean by this?

> What are some pretty common examples that make using a Service Bus the right choice over http://hangfire.io/ when dealing with large web application?

I don't know that much about Hangfire, and as an author of a service bus I'm probably biased 😁 but if your needs go beyond simple background processing, I would recommend that you go with a service bus.

I suggest you read a little bit about [scenarios where a bus can be used](https://github.com/rebus-org/Rebus/wiki#scenarios) for inspiration 😄 

If you're certain that the ability to queue up work in the background is the only thing you're after, my guess is that it will be easier for you to go with Hangfire. I don't have any experience with it, but my impression is that it is really neat.

**Comment by markalanevans** [comment]
By more robust, I probably should have said it could allow me both background processing as well as offering solutions to better scale my infrastructure. 

Currently I only need background workers. So i'm probably going Hangfire until it makes sense to switch since it solves my current requirements.

Thanks again.

**Comment by mookid8000** [comment]
Excellent 😄 👍
