### ISSUE TITLE
Databus encryption

### ISSUE THREAD

**Issue by runes83** [rebus-org/Rebus#496]
The databus looks very promising, is there any plans to add encryption to it?
When using Azure blob storage for example there are regulation / client demands that the data is encrypted.

It would be a nice feature to add both symmetric and asymmetric encryption to these files.

**Comment by mookid8000** [comment]
You are absolutely right 😄 

Encryption and compression are clear-cut candidates for decorators of the [`IDataBusStorage`](https://github.com/rebus-org/Rebus/blob/master/Rebus/DataBus/IDataBusStorage.cs) abstraction.

Let's create some tasks 😄
