### ISSUE TITLE
Data bus data compression

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#498]
Support compression via an `IDataBusStorage` decorator

**Comment by mpaul31** [comment]
if i get some free time here it could be cool to create a SqlFileStreamDataBusStorage implementation that uses SqlServer's new(ish) FileStream feature.

**Comment by mookid8000** [comment]
Data bus compression will be out in 0.99.73

It can be enabled like this:

    Configure.With(activator)
        (...)
        .Options(o =>
        {
            o.EnableDataBus()
                .UseCompression(DataCompressionMode.Always)
                .(...);
        })
        .Start();

where `DataCompressionMode.Always` means that data will always be compressed.

If `DataCompressionMode.Explicit` is specified instead, data will only be compressed if the metadata passed along with the attachment has the `MetadataKeys.ContentEncoding` key and the corresponding value is `gzip` - e.g. like so:

    var metadata = new Dictionary<string, string>
    {
        {MetadataKeys.ContentEncoding, "gzip"}
    };

    var attachment = await bus.Advanced.DataBus.CreateAttachment(source, metadata);

    await bus.Send(new MessageWithAttachment(attachment));
