### ISSUE TITLE
Create a Legacy sagadata provider (suggestion)

### ISSUE THREAD

**Issue by runes83** [rebus-org/Rebus#499]
There are a number of Saga providers for Rebus, and the one that is chosen when the project is started is not necessary the optimal one.

If it was possible to add a second sagaprovider as "LegacyProvider" witch is read read only when the primary does not find the saga. And then copies the saga data and index over to the primary provider.

This would make it easier to switch sagadata provider without a huge manual copy process that most likely would be painful.

**Comment by mookid8000** [comment]
An interesting experiment could be to simply register an implementation of `ISagaStorage` which would use two real saga storage implementations to do what you are asking for.

**Comment by runes83** [comment]
Yes, when there is no hit for main saga provider, try the old one, maybe cache the result, and then slowly retire the old one.

**Comment by mookid8000** [comment]
This could definitely be a fun experiment to pull, but I don't think it belongs in Rebus core – at least not yet.

I'll close this issue for now. If someone feels like taking a stab at it, I suggest it be added to a separate project similar to [`Rebus.Recipes`](https://github.com/rebus-org/Rebus.Recipes) (but not necessarily there)
