### ISSUE TITLE
MSMQ SubscribeRequest messages getting stuck

### ISSUE THREAD

**Issue by MGillett** [rebus-org/Rebus#500]
I am using Rebus and seeing an issue where SubscribeRequest and UnsubscribeRequest messages seem to be getting "stuck" in MSMQ.

The messages that my application publishes then obviously get stuck because nothing has subscribed to them. Restarting the application just results in more messages backing up in the queue, but if I manually clear the queue and then restart, the problem goes away.

Any idea what could be causing this issue? Or about what information I should be looking for in order to further investigate?

**Comment by mookid8000** [comment]
When a message is "stuck", is it just sitting there and can be seen in Computer Management? (or are you using another tool to inspect the queues?)

Are multiple machines involved? Are they on the same domain?

**Comment by MGillett** [comment]
I used Rebus.Snoop to see the stuck message.

There is only one machine involved.

**Comment by mookid8000** [comment]
Have you only experienced "stuck messages" with `SubscribeRequest` and `UnsubscribeRequest`?

**Comment by MGillett** [comment]
Only with SubscribeRequest.

**Comment by mookid8000** [comment]
Are you capable of manually sending messages to your publisher? E.g. by using the explicit routing API

    await bus.Advanced.Routing.Send("publisher", someMessage);

?

**Comment by MGillett** [comment]
We can get messages into the publisher's queue, but since the SubscribeRequests are also still in the queue, they just sit there.

**Comment by mookid8000** [comment]
Is there something in the log in the publisher's end?

**Comment by MGillett** [comment]
Nothing in the Event Log. It just sits there doing nothing.

**Comment by mookid8000** [comment]
Can you reproduce the issue in a small app and send it to me?

Sendt fra min iPhone

**Comment by MGillett** [comment]
Will work on that and get back to you.

**Comment by mookid8000** [comment]
Hi @MGillett , did you have a chance to look any further on this one?

**Comment by MGillett** [comment]
I have not. Given that the issue does not happen very often and there is a workaround (manually clear the queue and then restart), it is not my top priority. I will keep you posted on when I am able to make progress.

**Comment by mookid8000** [comment]
Please let me know if you run into more issues with this one. Since I have never had any reports of similar behavior, I assume that it is more likely that you are experiencing some kind of MSMQ hiccups than it is a sign that something is wrong with Rebus.

I may be wrong though, so please just reopen the issue if you keep having problems 😄
