### ISSUE TITLE
High CPU consumption on idle

### ISSUE THREAD

**Issue by zabulus** [rebus-org/Rebus#501]
My cluster node doesn't do anything, but consumes over 70% of i5 CPU.
I've profiled this issue and found that main CPU consumer is following execution path:

Function Name|Module Name|Inclusive Samples|Exclusive Samples|Inclusive Samples %|Exclusive Samples %
-------------|-----------|-----------------|-----------------|-------------------|-------------------
Rebus.Workers.ThreadBased.ThreadWorker.ThreadStart|Rebus.dll|103,661|38|100.00|0.04
Rebus.Workers.ThreadBased.ThreadWorker.DoWork|Rebus.dll|103,623|65|99.96|0.06
Rebus.Workers.ThreadBased.ThreadWorker.TryReceiveNewMessage|Rebus.dll|103,473|77|99.82|0.07
System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start|mscorlib.dll|103,270|251|99.62|0.24
Rebus.Workers.ThreadBased.ThreadWorker+<TryReceiveNewMessage>d__16.MoveNext|Rebus.dll|103,019|77|99.38|0.07
Rebus.Threading.ParallelOperationsManager.TryBegin|Rebus.dll|101,190|63|97.62|0.06
System.Threading.SemaphoreSlim.Wait|mscorlib.ni.dll|101,060|101,060|97.49|97.49

Part of rebus configuration:
```
                             .Options(x =>
                             {
                                 x.SetMaxParallelism(4);
                                 x.SetNumberOfWorkers(4);
                             })
```

**Comment by zabulus** [comment]
IMHO it is relates to my earlier issue:
https://github.com/rebus-org/Rebus/issues/484
WDYT?

**Comment by zabulus** [comment]
I think following code:
```
            using (var operation = _parallelOperationsManager.TryBegin())
            {
                // if we didn't get to do our thing, let the OS decide what to do next.... we don't hog the processor
                if (!operation.CanContinue())
                {
                    Thread.Yield();
                    return;
                }
```
Doesn't make much sense. IMHO better to wait on semaphore inside ```_parallelOperationsManager``` instead yielding and wasting CPU in work cycle.

**Comment by mookid8000** [comment]
well.... I am not sure what to do about this... the way things work atm is where each worker basically executes the following pseudocode:

	start:
		get next available continuation c
		if c is not null:
			execute c
			goto start

		get next available message m
		if m is not null:
			handle m
			goto start

The problem is that putting a timeout on either `get next available *` will basically [dos](https://en.wikipedia.org/wiki/Denial-of-service_attack) the other one - therefore, they are both equipped with very short timeouts.

I may have an idea though on a way to address that though. Stay tuned 😄

**Comment by runes83** [comment]
I too experience high cpu and traced it back to 
Rebus.Threading.ParallelOperationsManager.TryBegin-> System.Threading.SemaphoreSlim.Wait

Using AzureServiceBus and latest Rebus 0.99.68. 
I've got a Visual studio dianostics report I could send you if you need it.

![image](https://cloud.githubusercontent.com/assets/7079276/17343281/1d25f994-58fd-11e6-9be0-0adb4048c1d5.png)

**Comment by mookid8000** [comment]
@runes83 thanks for chiming in - the just helps to confirm that the current worker design is not optimal

I have some ideas on how to address this issue - I will get back to you guys soon 😄

**Comment by gertjvr** [comment]
We have found mixing different versions of rebus and transport packages also leads to high CPU, which could be a sign of a memory leak. We have reverted all our packages back to 0.99.61 found them to be the most stable.

**Comment by runes83** [comment]
I have to use the lastest 0.99.68+ to get the fix for multiple buses. But if @mookid8000 you are on the case i recon it will we solved soon :-)

**Comment by mookid8000** [comment]
I have pushed Rebus 0.99.71 to NuGet.org just now.

It has an experimental entirely new worker factory based on the thread pool, which can be enabled by going

    .Options(o => {
        o.UseThreadPoolMessageDispatch();
    })

In other words: Completely opt-in for now, but definitely meant to replace the existing worker factory later on.

This is quite a big change in how Rebus does its work. The new worker factory only uses worker threads to actually do the initial RECEIVE of a message, which it then dispatches to be handled on the thread pool.

As far as I can tell, it actually improves the performance across the board quite a lot, and hopefully you will experience much lower CPU usage during idle periods.

Would you guys care to take it for a spin? 

I would be really grateful if you could report back to me any issues and/or oddities you might encounter.

**Comment by mookid8000** [comment]
I have done a little bit of testing myself, and on one hand it looks kinda promising – here showing an endpoint with 10 workers running first for two minutes on the old model (maxing out the CPU), taking a break for one minute, and then running for two minutes on the new model.

![image](https://cloud.githubusercontent.com/assets/32968/17376617/a31cf76e-59b6-11e6-926f-a39bd69970c5.png)

It is pretty clear that the CPU does not seem to sweat quite as hard with the new model – and I haven't even built in any kind of backoff strategy in yet (the old one had that and it's really easy to add to the new model).

However, on the other hand, something seems to be a little bit weird – with the old model, starting 10 endpoints with 10 workers each feels pretty lightweight, and they just start/stop right away. With the new model, starting endpoints becomes slower and slower, and it pretty much ends up freezing my application.

I will do some more investigation 😄 feel free to try it out and let me know all of the ways in which it is broken 😁

**Comment by mookid8000** [comment]
A preliminary conclusion of mine is that it seems the new model can do about as much work as the old model using half the number of threads.

It still worries me that having 10 endpoints with 10 workers each seemed to bog my CPU so much down. It's possible that implementing a tiny increasing backoff could remedy that though.

**Comment by runes83** [comment]
@mookid8000 it helped, but still using more cpu than excepted from a service that does "nothing" when no messages are thrown at it. 

Any plans for improvements here?

**Comment by mookid8000** [comment]
@runes83 yes, I will add the backoff behavior from the previous workers... stay tuned, 0.99.72 will be out in about an hour or so...

**Comment by runes83** [comment]
@mookid8000 thanks for a quick response.

**Comment by mookid8000** [comment]
0.99.72 (which is out now) looks even better in my test – check this out.... here's 

* two minutes old-style idle running
*  a one-minute chill-down period
* two minutes new-style idle running

![image](https://cloud.githubusercontent.com/assets/32968/17417170/3ad9f1f2-5a92-11e6-9a2c-12334f11032b.png)

Looks like running idle now can almost not be discerned from not doing anything at all.

The new default backoff strategy (which is only available with the new thread pool-based workers) will pause for 100 ms between polling the queues the first 10 seconds where it doesn't receive anything, and then it will poll the queues every 250 ms after that.

@runes83 I would be happy if you will take 0.99.72 for a spin 😄

**Comment by zabulus** [comment]
Will this add pauses for fast message processing?

**Comment by mookid8000** [comment]
It will increase the max possible latency when sending to an endpoint that is running idle to 250 ms. 

Each time a message is received, the backoff is reset, and messages will be retrieved continuously.

**Comment by runes83** [comment]
@mookid8000 we have deployed 0.99.72 into our test environment now, so far it looks very good. CPU dropped from 100% to below 10.

**Comment by mookid8000** [comment]
@runes83 sounds good 😄 

I've been meaning to change the worker implementation for a while now, because having two responsibilities for each worker (receive message/execute continuation) turned out to be hard to manager – it was simply impossible to achieve a sensible prioritization of queue polling backoff vs. super-fast execution of continuations.

I have a feeling that the new model is far superior in almost every aspect.

**Comment by mookid8000** [comment]
One last trick that I have in my sleeve (but haven't tried implementing yet) is auto-scaling.... imagine something like this:

    Configure.With(activator)
        (...)
        .Options(o =>
        {
            o.AutoSetNumberOfWorkers(min: 1, max: 10);
        })
        .Start();

which would then dynamically remove workers during slow periods and then add them again when it made sense to do so.

**Comment by zabulus** [comment]
Now it is default behavior? UseThreadPoolMessageDispatch is not needed anymore?

**Comment by Rzpeg** [comment]
Auto-scaling seems interesting and I would probably use it in at least half of rebus projects I currently have.
By the way, does this new behavior respect worker shutdown timer?

**Comment by mookid8000** [comment]
Yes it does :)

Sendt fra min iPhone

**Comment by mookid8000** [comment]
You can see the code [here](https://github.com/rebus-org/Rebus/blob/master/Rebus/Workers/ThreadPoolBased/ThreadPoolWorkerFactory.cs#L82-L113) - I would almost call it beautiful 😁 because it turned out to be so simple

**Comment by mookid8000** [comment]
Yes it does :)

You can see the code [here](https://github.com/rebus-org/Rebus/blob/master/Rebus/Workers/ThreadPoolBased/ThreadPoolWorkerFactory.cs#L82-L113) - I would almost call it beautiful 😁 because it turned out to be so simple

**Comment by Rzpeg** [comment]
You can make **WaitForContinuationsToFinish** an Awaitable Task then await Task.Delay instead of hard blocking the thread :)

**Comment by mookid8000** [comment]
@Rzpeg that wouldn't really accomplish anything, as the purpose of it all is to block the calling thread until all continuations have finished running... i.e. when the application shuts down, this happens:

    bus.Dispose(); 

    // all continuations must be finished by now

**Comment by runes83** [comment]
@mookid8000 I like the idea of minimum and maximum number of workers, so that the endpoint do not use more threads/resources than needed.

**Comment by mookid8000** [comment]
Have anyone experienced any kind of problem using the new threading model?

(it's still opt-in via the `.UseThreadPoolMessageDispatch()` on the options configurer)

**Comment by zabulus** [comment]
Haven't tested yet. I'll post results till the end of this week.

**Comment by runes83** [comment]
We have it our test environment and have not experienced anything yet.

**Comment by zabulus** [comment]
I've tested this. Looks good. Today answer from qa should arrive. I'll let you know if something happens

**Comment by Rzpeg** [comment]
WIll this become a new "defaut" anytime soon?

**Comment by mookid8000** [comment]
@Rzpeg yes :)

**Comment by mookid8000** [comment]
no, seriously – if you guys haven't had any issues with it (and I haven't either), I think it should be safe to make the switch.... It'll most likely be the default from 0.99.74

**Comment by SeniorMunch** [comment]
I think there still is a issue. In our project on my machine (core i7), this is low cpu when idle: 
```
o.UseThreadPoolMessageDispatch();
o.SetNumberOfWorkers(10);
o.SetMaxParallelism(7);
```
and this is ~12% cpu when idle
```
o.UseThreadPoolMessageDispatch();
o.SetNumberOfWorkers(10);
o.SetMaxParallelism(6); //<--changed
```

**Comment by mookid8000** [comment]
@SeniorMunch thanks for reporting this – I'll investigate

**Comment by mookid8000** [comment]
@SeniorMunch I figured it out now!

If you take a look at your configuration, it doesn't make that much sense: You are running with a higher number of threads than your degree of parallelism allows!

Check this out – here, I have made a test that runs idle for 1 minute at a time, with 10 threads all the time, reducing the parallelism for each run from 10, 9, 8, ..., 4

![image](https://cloud.githubusercontent.com/assets/32968/17736773/fbbd2abe-6489-11e6-96f8-9635d2b96c10.png)

As you can see, CPU usage starts out very low, but makes a drastic increase around reducing the parallelism from 7 to 6 (as you have also discovered).

I bet the explanation is the increasing contention around the parallelism lock, which is implemented by using a `SemaphoreSlim`.

If I recall correctly, this type of semaphore uses a spin lock for a short while each time it tries to decrement the semaphore, leading to high CPU usage if there is contention.

When there is no contention, there is no problem.

Generally, you should always set the parallelism at least as high as the worker count. No matter how high you set the number of workers, the max parallelism will work as a global upper limit of how many things can happen concurrently.

**Comment by SeniorMunch** [comment]
Yes, it doesn't make any sense with less workers than parallelism. 

We ran into it, because we where just setting number of workers (to 10) without adjusting parallelism (thereby using the default 5). 
And this wasn't a problem when running an older Rebus version.

btw: Great product! :-)

**Comment by mookid8000** [comment]
In 0.99.74 it will automatically limit number of workers to the max parallelism :)

Thanks :)

Sendt fra min iPhone
