### ISSUE TITLE
Real versions of libraries

### ISSUE THREAD

**Issue by zabulus** [rebus-org/Rebus#502]
Do you plan to use versions in assembly names?
We can't determine if assembly was successfully updated during our update.

**Comment by mookid8000** [comment]
I should probably do that, yes :) I'll make this a task, then you can follow its progress

**Comment by mookid8000** [comment]
- [ ] Rebus
- [ ] Rebus.AmazonSQS
- [ ] Rebus.Async
- [ ] Rebus.Autofac
- [ ] Rebus.AzureServiceBus
- [ ] Rebus.AzureStorage
- [ ] Rebus.CastleWindsor
- [ ] Rebus.DryIoc
- [ ] Rebus.Jil
- [ ] Rebus.LightInject
- [ ] Rebus.Log4net
- [ ] Rebus.MongoDb
- [ ] Rebus.MsgPack
- [ ] Rebus.NLog
- [ ] Rebus.NewtonsoftJson
- [ ] Rebus.Ninject
- [ ] Rebus.Owin
- [ ] Rebus.PostgreSql
- [ ] Rebus.RabbitMq
- [ ] Rebus.RavenDb
- [ ] Rebus.Protobuf
- [ ] Rebus.Recipes
- [ ] Rebus.Serilog
- [ ] Rebus.ServiceProvider
- [ ] Rebus.SimpleInjector
- [ ] Rebus.StructureMap
- [ ] Rebus.TransactionScopes
- [ ] Rebus.UnitOfWork
- [ ] Rebus.Unity
- [ ] Rebus.Wire
- [ ] Rebus.XmlConfig

**Comment by mookid8000** [comment]
All repos now invoke [Aversion](https://github.com/rebus-org/Aversion) somehow as a pre-build step, replacing `$token$` from `AssemblyInfo.cs` with an appropriate .NET-compatible version, storing the result in `AssemblyInfo_Patch.cs`.
