### ISSUE TITLE
Restarting bus using the same DI container.

### ISSUE THREAD

**Issue by takinosaji** [rebus-org/Rebus#503]
I have singleton windsor container in application and i need to open several buses.
The second time i am trying to configure bus i receive and receive an exception:

`Component Rebus.Bus.RebusBus could not be registered. There is already a component with that name. Did you want to modify the existing component instead? If not, make sure you specify a unique name.`

Code:

```
            var busConfigurer = Configure.With(new CastleWindsorContainerAdapter(_container))
                .Logging(l => l.Log4Net())
                .Transport(t => t.UseRabbitMq(_connectionString, _inputQueue).ExchangeNames("RebusDirect", "Rebus")
                    .Prefetch(5))
                .Options(o => {
                    o.SimpleRetryStrategy(_errorQueue);
                    if (_enableLegacyCompatibility)
                    {
                        o.EnableLegacyCompatibility();
                    }
                })
                .Serialization(s => s.Decorate(c => new XmlMessageSerializer()));

            busConfigurer.Start();
```

Could you give a hint how to properly launch buses in consequent times with such a container?

**Comment by mookid8000** [comment]
Yes - treat each bus instance as a separate "application" and give it its own container instance.
