### ISSUE TITLE
Log4Net logging in rebus 2.0

### ISSUE THREAD

**Issue by takinosaji** [rebus-org/Rebus#505]
I am trying to migrate from Rebus1 to Rebus2. Previously in earlier versions of log4net and rebus in configuration file of application we have been using such a configuration 
`<log4net>
    <root>
      <level value="DEBUG" />
      <appender-ref ref="LogFileAppender" />
    </root>
    <appender name="LogFileAppender" type="log4net.Appender.RollingFileAppender, log4net">
      <file type="log4net.Util.PatternString" value="С:\Log\Rebus\Rebus..log" />
      <datePattern value="yyyyMMdd" />
      <preserveLogFileNameExtension value="true"/>
      <staticLogFileName value="false" />
      <appendToFile value="true" />
      <rollingStyle value="Date" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%d{yyyy-MM-dd HH:mm:ss} %-5level %logger: %message%newline" />
      </layout>
    </appender>
  </log4net>`

After upgrading and using such bus configuration: 
` var busConfigurer = Configure.With(new CastleWindsorContainerAdapter(_container))
                .Logging(l => l.Log4Net())...`

rebus doesn't make logs.

**Comment by mookid8000** [comment]
Did you initialize Log4Net?

I don't remember if Rebus 1 initialized it, but I am sure that Rebus 2 does not (since it will attempt to mess as little as possible with how you are configuring other things).

My guess is that you are missing an

    XmlConfigurator.Configure();

as the first thing when your application starts up.

**Comment by takinosaji** [comment]
Yeah exactly! Thank you very much!
