### ISSUE TITLE
Sql Server Saga Storage -- deserialization errors

### ISSUE THREAD

**Issue by jeffreyabecker** [rebus-org/Rebus#510]
When using the sql server saga storage I'm getting the following error:
`Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'Rebus.Sagas.ISagaData' `
in the Find method.  

I've tested and I am able to deserialize the data in the column using Json.Net. Any other ideas on what could be causing this?

**Comment by jeffreyabecker** [comment]
nevermind the data was wonky.

**Comment by mookid8000** [comment]
That's weird!

If you look [here](https://github.com/rebus-org/Rebus/blob/master/Rebus/Persistence/SqlServer/SqlServerSagaStorage.cs#L28) you can see that SQL Server saga storage uses "typename handling = all" to serialize/deserialize saga data – this means that each object in the saga data aggregate gets a `$type` field in addition to all of the ordinary fields.

JSON.NET – funnily enough – always serializes the `$type` field as the first field in each object, _and it requires that the field is still the first it encounters when deserializing each object_.

Could it be that the order of the fields has somehow been changed?

**Comment by mookid8000** [comment]
wonky data...... we all know data like that 😁

**Comment by jeffreyabecker** [comment]
Someone put in a migration which converted the underlying data into UTF-16.

**Comment by mookid8000** [comment]
Ah... that explains why stuff is not working then... someone better put in a migration that converts data back to UTF8 then 😁
