### ISSUE TITLE
Rebus.Tests NuGet package

### ISSUE THREAD

**Issue by NKnusperer** [rebus-org/Rebus#511]
I'am currently implementing a container adapter for our custom dependency injection.
To do so it would be nice to have access to stuff like ContainerTests via NuGet, currently I just copy-paste the required types. This way is is also easy to stay in sync with the latest version.

**Comment by mookid8000** [comment]
I guess that would be pretty neat, actually. That would also serve well later on when integration projects get moved to their own repositories.

I'll convert this on into a task right away 😁

**Comment by NKnusperer** [comment]
Any schedule when you will do this?

**Comment by mookid8000** [comment]
@NKnusperer can't really promise anything

**Comment by mookid8000** [comment]
I have published `Rebus.Tests.Contracts` in version `2.0.0-a1` to NuGet.org. 

Furthermore, I have migrated [the Amazon SQS transport](https://github.com/rebus-org/Rebus.AmazonSQS) and [the Wire serializer](https://github.com/rebus-org/Rebus.Wire) to use the package.

The two projects are pretty good reference examples on how an integration library can then be structured.
