### ISSUE TITLE
TransactionScope.EnlistRebus() to throw optionally when already enlisted

### ISSUE THREAD

**Issue by margusbirk** [rebus-org/Rebus#532]
Currently when enlisting Rebus in a nested transaction an exception is thrown. Would it be possible to have an API similar to this?

Instead of:

```csharp
using (var tx = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
{
     tx.EnlistRebus();
     using (var nestedTx = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
     {
           //this throws
           nestedTx.EnlistRebus();
      }
}
```

When `AmbientTransaction.Current != null && throwWhenAlreadyEnlisted == false`  TransactionScopeExtensions returns immediately instead of throwing.

Something like this:

```csharp
using (var tx = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
{
      //rebus is enlisted
      tx.EnlistRebus(throwWhenAlreadyEnlisted:false);
      using (var nestedTx = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
      {
          //rebus is previously enlisted. no exception is thrown
          nestedTx.EnlistRebus(throwWhenAlreadyEnlisted:false);
      }
}
```

Would there be any issues with such approach?

**Comment by mookid8000** [comment]
Well.... I don't know 😁 

Looking at the example you posted, I am wondering how nested transactions are supposed to work. Consider this slightly modified snipped of what you posted:

	using (var tx = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
	{
	      //rebus is enlisted
	      tx.EnlistRebus(throwWhenAlreadyEnlisted:false);

	      await _bus.Send("a message");

	      using (var nestedTx = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
	      {
	          nestedTx.EnlistRebus(throwWhenAlreadyEnlisted:false);

		      await _bus.Send("another message");

		      // throw new HypotheticalException("-----1----");

		      nestedTx.Complete();
	      }
	
	      // throw new HypotheticalException("-----2----");

	      tx.Complete();
	}

I can think of the following scenarios:

1. No exceptions are thrown
1. Hypothetical exception 1 is thrown
1. Hypothetical exception 2 is thrown

In (1) both `a message` and `another message` will be sent – that one is obvious.

In (2), no messages will be sent, as neither `tx` nor `nestedTx` are completed.

But what about (3)? `nestedTx` is completed, but the outer `tx` was NOT completed. Did `another message` get sent?

**Comment by margusbirk** [comment]
In case of 3 I would expect both messages not to be sent even though nestedTx completed. And it is the behaviour that I'm witnessing:

```c#
[Test]
public async Task When_outer_transaction_not_complete_no_messages_are_published()
{
      var transientDb = RequestDb(GetQueueName());

      CreateDatabase(transientDb);

      var bus = GetOneWaySqlTransportBus(transientDb);

     using (var tx = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
    {
         tx.EnlistRebus();

         using (var nestedTx = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
         {
              await bus.Send(new CustomerCreatedEvent());
              await bus.Send(new CustomerCreatedEvent());

               //act
              nestedTx.Complete();
           }
          await bus.Send(new CustomerCreatedEvent());

          //act - dont complete outer tx
      }
        AssertNoRowsInQueue(transientDb);
}
```

**Comment by mookid8000** [comment]
If none of the messages get sent in (3), how does it differ from just having one transaction scope for the two send operations?

**Comment by margusbirk** [comment]
It's correct that when using the default `TransactionScopeOption.Required` it shouldn't be any different than just a single transactionscope. 

I needed to integrate Rebus into an existing solution where nested transactions are created by existing components, having Rebus not throw when enlisting in a child scope would have been a quick fix but after reading more about txscopes I see that the current solution is misusing txscopes, indeed a single scope would suffice.

This can be closed.

**Comment by mookid8000** [comment]
I am happy to hear that 😄
