### ISSUE TITLE
One-way transport configuration

### ISSUE THREAD

**Issue by yan-oreshchenkov** [rebus-org/Rebus#534]
Hi there!
Thank you for the great job! We use Rebus on a set of projects - it's perfect.
But I faced with one little issue, maybe I don't understand something... I'm trying to start one-way outgoing bus with MSMQ:

```
var bus = Configure.With(new BuiltinHandlerActivator())
                .Logging(l => l.ColoredConsole())
                .Transport(t => t.UseMsmqAsOneWayClient())
                .Routing(x => x.TypeBased().Map<PushMessage>("agave.push"))
                .Start()

// Send a message
 bus.Publish(new PushMessage { });
```

When I run it I see that bus.Publish() fails with "no destination" log message:

```
Rebus.Routing.TypeBased.TypeBasedRouter INFO (Thread #1): Mapped Model.PushMessage -> agave.push
Rebus.Transport.Msmq.MsmqTransport INFO (Thread #1): Initializing one-way MSMQ transport
...
Rebus.Bus.RebusBus INFO (Thread #1): Starting bus 1
Rebus.Bus.RebusBus INFO (Thread #1): Started
Rebus.Config.RebusConfigurer+<>c DEBUG (Thread #1): Sending Model.PushMessage -> <no destinations>
```

What is wrong? Why rebus doesn't send the message right to "agave.push" as it's mapped in routing?

**Comment by mookid8000** [comment]
It's simply – when you `await bus.Publish(anEvent)`, the event gets delivered to those two subscribed to the type of the event by doing this: `await bus.Subscribe<EventType>()`.

In order for that to work, you need to EITHER a) configure a central subscription storage (e.g. a SQL Server that all publishers and subscribers can share), or b) configure an endpoint mapping in the subscriber's end.

BUT in this case, it looks like you are sending some kind of command to one single receiver. The endpoint mapping is correct in that case, you simply need to

    await bus.Send(new PushMessage { ... });

when will then cause the message to be sent to the `agave.push` queue.

**Comment by yan-oreshchenkov** [comment]
Thanks a lot, the puzzle is almost completed! :)
