### ISSUE TITLE
Add nice API for common events

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#538]
Rebus 1 had the `Events` configurer where you could do stuff like this:

```
Configure.With(...)
    .(...)
    .Events(e => {
        e.MessageSent += message => {
            message.Headers["good day"] = "sir";
        };
    })
```

which (as exemplified by the solution to #537 ) is more involved in Rebus 2.

It would be nice to add something similar to Rebus 2.

**Comment by mookid8000** [comment]
and no... this is not part of 2.0.1 – but it can be added as a small non-breaking change, maybe in a separate `Rebus.Events` library

**Comment by jpierson** [comment]
We are using the IBus.Advanced.Routing.Send API to send messages. Should we be able to use the optionalHeaders parameter to set a correlation id/sequence? I haven't found any examples doing as such and I'm getting ready to experiment with it.

**Comment by mookid8000** [comment]
yes – pass something like `new Dictionary<string, string> {{Headers.CorrelationId, "whatever"}}` to it, and then it should work

**Comment by mookid8000** [comment]
It's currently being added [here](https://github.com/rebus-org/Rebus.Events) 😄
