### ISSUE TITLE
Bus workers.

### ISSUE THREAD

**Issue by takinosaji** [rebus-org/Rebus#542]
Greetings to creators of rebus! :)

I have a question about bus workers. 
1) Do they work in separate threads?
2) Is it right setting of workers:

>   .Options(o => {
                  ......
                    if (workersCount > 1)
                    {
                        o.SetNumberOfWorkers(workersCount);
                    }
                 .....
                })

**Comment by mookid8000** [comment]
>> 1) Do they work in separate threads?

Yes – a "worker" is a dedicated thread that will continuously attempt to receive and process a message. The message will initially be processed by the worker, but if an `await` is encountered, the rest of the message handling will happen on thread pool threads.

This allows for the thread to return to trying to receive yet another message. How many message you want to allow for being handled in parallel is controlled by

    o.SetMaxParallelism(10);

which would allow for up to 10 messages being handled in parallel.

>>2) Is it right setting of workers:

Yes – although you will not need the `if (workersCount` thing – just go right ahead and do this:

    o.SetNumberOfWorkers(workersCount);

but please note that you need to change the parallelism accordingly to at least `workersCount`.

**Comment by takinosaji** [comment]
So i should use 

> o.SetNumberOfWorkers(workersCount);

 and 

> o.SetMaxParallelism(workersCount);

 together and pass the same number?

**Comment by mookid8000** [comment]
Yes 😄 

And you can set the parallelism higher if you are using `await` in your handlers and you want to take advantage of that.

**Comment by takinosaji** [comment]
@mookid8000 excuse me. Didn't caught your point....higher you mean where?

**Comment by mookid8000** [comment]
This is definitely an option:

	o.SetNumberOfWorkers(workersCount);
	o.SetMaxParallelism(workersCount);

If you are using `await` in your code, you can have better CPU utilization by e.g. lowering number of workers:

	o.SetNumberOfWorkers(1);
	o.SetMaxParallelism(workersCount);

or increase throughput without affecting CPU usage that much:

	o.SetNumberOfWorkers(workersCount);
	o.SetMaxParallelism(workersCount * 5);

**Comment by takinosaji** [comment]
Then i don't really understand this concept. I thought that workers are processing messages in parallel. For each worker separate thread is arranged. How SetMaxParallelism count actually related to workersCount?

**Comment by mookid8000** [comment]
Try reading up on `async`/`await` – it allows for processing many things in parallel with fewer threads

**Comment by s-drki** [comment]
what about If the order of message handling was important, meaning messages must be handled in the same order of sending. In this case the NumberOfWorkers and MaxParallelism must be set to 1 to prevent from parallel handling?

**Comment by mookid8000** [comment]
> what about If the order of message handling was important, meaning messages must be handled in the same order of sending. In this case the NumberOfWorkers and MaxParallelism must be set to 1 to prevent from parallel handling?

Yes, exactly 😄  that will ensure that only one single message is being handled at any instant in time
