### ISSUE TITLE
Return to source queue auto-move option

### ISSUE THREAD

**Issue by chandmk** [rebus-org/Rebus#543]
ReturnToSourceQueue auto-move option doesn't seem to be working any more in Rebus 2.0.

**Comment by mookid8000** [comment]
Thanks for reporting it 😄 which transport are you using?

**Comment by chandmk** [comment]
I am using RabbitMq transport.

**Comment by mookid8000** [comment]
aaah now I get it! You are using the OLD return-to-source-queue tool 😄 

With Rebus 2 you need to use the ["Forklift" that comes with RabbitMQ](https://github.com/rebus-org/Rebus.RabbitMq/tree/master/Rebus.Forklift.RabbitMq)

Sorry for not realizing this before now 😄 

At the moment you will have to clone the source code and build the CLI tool yourself.

**Comment by chandmk** [comment]
I am using the new tool.  --auto-move has no effect.  New tool still prompts to choose between S (source Queue), C (Custom queue)
