### ISSUE TITLE
Q: Publisher with flaky subscribers

### ISSUE THREAD

**Issue by tonyeung** [rebus-org/Rebus#544]
Hi, checking out various ESB options and got a question. The readme has no direction on where I should ask and the google group seems to be gone. I posted the question on SO but I'll post it here, too. http://stackoverflow.com/questions/40029602/publisher-with-no-subscribers

Hypothetical scenario, publisher publishes message, no one's available to process it. What I've been able to figure out is that the message will black hole.

There is a SO post for a publisher with ONLY ONE subscriber, and the answer was to send a message rather than publish it. I get that. http://stackoverflow.com/questions/36715599/rebus-subscriber-publisher-system-process-message-only-by-single-subscriber

What I'm more concerned about is what if by some freak accident I'm publishing stuff that's supposed to be processed by some subscribers but they're all down for some reason (bad publish? act of god? I don't know)

**Comment by mookid8000** [comment]
Answered [here](http://stackoverflow.com/a/40030344/6560) (which I think is actually the right place for questions like this 😄 )
