### ISSUE TITLE
Databus file delition 

### ISSUE THREAD

**Issue by SlyJay** [rebus-org/Rebus#545]
I've tried to play a little bit with databus both with filesystem and sql server persistence but it seems  that files are not deleted after a message is executed and dequeued. I've also tried to find a delete method in databus attachment and in business implementation itself but it seems  I cannot figure it out. Is there any way to manage it?
Thanks in advance 

Sly

**Comment by mookid8000** [comment]
There is no automatic deletion of databus attachments because there is no way for the bus to know when the last consumer has read the attachment for the last time. 

Instead, the databus storages all have a "last read time" made accessible from the outside somehow, allowing for creating some kind of scheduled job that performs a sensible cleanup.

**Comment by SlyJay** [comment]
Thank you for replying so fast :)
Ok perfect we’ll start working on some kind of cleaner. So is there any method we can use to delete those files by id like the openread of a databusattachment or anything similar?

**Comment by mookid8000** [comment]
Rebus provides no APIs besides the ones exposed on [`IDataBus`](https://github.com/rebus-org/Rebus/blob/master/Rebus/DataBus/IDataBus.cs) and the accompanying [`DataBusAttachment`](https://github.com/rebus-org/Rebus/blob/master/Rebus/DataBus/DataBusAttachment.cs) out of the box.

My plan with these things was to provide enough API in Rebus to be able to create and read attachments, and then you would pick a storage that you would feel comfortable with.

All storages then provide some kind of native way of accessing the "last read time" timestamp, and with a little more work you would also be able to retrieve the custom metadata associated with an object in storage.

These things would then enable you to hand-roll e.g. a scheduled task that would remove all data bus attachments that had not been read for a week or a month or so, but it would require you to simply work on the files in the file system, the rows in SQL Server, or the blobs in Azure, using whichever client library that would be necessary.

With a little more work it would of course be possible to extend the existing data bus API with some more capabilities – it's just not something I have needed myself just yet.
