### ISSUE TITLE
SQLServerTransport uses DateTime and not DateTimeOffset, 

### ISSUE THREAD

**Issue by xenoputtss** [rebus-org/Rebus#546]
I'm dealing with high latency network (WAN) and the single message at a time pattern is too slow.  I decided to steal the shoveling concept from RabbitMQ (basicly bulk copy messages to/from two queue systems https://www.rabbitmq.com/shovel.html ).

as soon as I did this I realized that Expiration and Visibility are stored as DateTime values.  The local and remote machines are in different timezones.  When I moved messages around, messages wouldn't be processed for hours.

If I make the changes to make Visibility and Expiration stored as DateTimeOffset, do you think this is worth while to bring into Rebus proper or does this not go into a direction you want to take Rebus?

**Comment by mookid8000** [comment]
I guess it would not hurt to use `DateTimeOffset` instead of `DateTime`. Don't you think it would be possible to implement in a way where only newly-created tables get the `DateTimeOffset` type columns, while the existing send/receive SQL can work with both types?

**Comment by mookid8000** [comment]
(PS: I have created an issue [here](https://github.com/rebus-org/Rebus.SqlServer/issues/1) – the SQL transport has a [new home](https://github.com/rebus-org/Rebus.SqlServer) 😉 )
