### ISSUE TITLE
Question: Bus reply on failed message

### ISSUE THREAD

**Issue by runes83** [rebus-org/Rebus#548]
I have this code to resend a message later when failed, but when I do Bus.Reply on the failed message it get sent to this worker, not the worker it came from since the return-address is now the current worker.

Will it help to override the rbs2-return-address header on Bus.Defer below?

```c#
  public async Task Handle(IFailed<CreatePadesCommand> failedMessage)
        {
            int retryCount = 0;
            if (failedMessage.Headers.ContainsKey("retry-count"))
                Int32.TryParse(failedMessage.Headers["retry-count"], out retryCount);

            if (retryCount <= AppSettingsReader.RetryAttempts)
            {
                retryCount++;
                await Bus.Defer(TimeSpan.FromMinutes(2*retryCount), failedMessage.Message, new Dictionary<string, string>() { { "retry-count" ,retryCount.ToString()}});
            }
                
        }`

**Comment by mookid8000** [comment]
Yes.

Another slightly better option is to 

    var delay = TimeSpan.FromMinutes(2*retryCount);
    var additionalHeaders = new Dictionary<string, string> {
        { "retry-count", retryCount.ToString()}
    };

    await bus.Advanced.TransportMessage.Defer(delay, additionalHeaders);

because the operations on the `ITransportMessageApi` work on the original transport message (including original headers like return address and message ID).
