### ISSUE TITLE
Saga Sample Application

### ISSUE THREAD

**Issue by mvanhelmont** [rebus-org/Rebus#550]
Is it posible to create a sample application that use saga to coordinating stuff. The wiki gives some guidelines but general it's easier to understand i there is a sample application.

Thanks already

**Comment by mookid8000** [comment]
It's a great idea. I will see if I can get a sample app done one of the following days.

**Comment by jmkelly** [comment]
I'd love to see this as well.

If you're pushed for time @mookid8000 , push up the skeleton of the project, and I'll attempt to fill in the gaps.  I'll give you one guess which transport I'll initially be using though 😉

**Comment by mookid8000** [comment]
I made a demo [here](https://github.com/rebus-org/RebusSamples/tree/master/Sagas) - please check it out and see if something is missing 😄

**Comment by mvanhelmont** [comment]
That's really fast thanks.. I have see that it can works all kind of ways. My first thought was that it works like.. Do this then that end so on. But it can do so much more. I always thought that there can be only one IAmInitiatedBy.

I will give it a try first time to write a system based on messages. What I see I like it and this sample helps me beter to understand how to setup and use it.

Thanks
