### ISSUE TITLE
BuiltinHandlerActivator seems occur  a bug  if use Rebus.Rabbitmq

### ISSUE THREAD

**Issue by houwenlong789** [rebus-org/Rebus#551]
I download Sagas sample, Every thing works fine.
But if I change transport to Rabbitmq,  cient and SagaDomo work well. 
   Logger throw exception as follow:
   Additional information: Could not resolve Rebus.Timeouts.ITimeoutManager with decorator depth 0 - registrations: Rebus.Injection.Injectionist+Handler

I think the BuiltinHandlerActivator not works well with rebus.Rabbimq

**Comment by mookid8000** [comment]
Could you maybe post the entire error including stack trace and everything?

**Comment by houwenlong789** [comment]
Sorry It`s my fault, I forget change sql connection string that cause the problem.

**Comment by mookid8000** [comment]
No problem 😁  good to hear you fixed it
