### ISSUE TITLE
Durable messages in RMQ topics

### ISSUE THREAD

**Issue by takinosaji** [rebus-org/Rebus#552]
Hi!

I am sending messages to rmq topic exchange using following method: `bus.Advanced.Topics.Publish`
How can i make that message durable?

Thanks!

**Comment by mookid8000** [comment]
It is be durable by default.... is that not what you are experiencing?

**Comment by takinosaji** [comment]
It happens that they are disappearing after rmq server restart.

**Comment by mookid8000** [comment]
That sounds weird. 

Rebus declares exchanges and queues as durable, which means that they survive RabbitMQ server restarts.

Moreover, Rebus will set the `persistent` flag of all sent messages to true. You can see it happen [here](https://github.com/rebus-org/Rebus.RabbitMq/blob/master/Rebus.RabbitMq/RabbitMq/RabbitMqTransport.cs#L464).

Could you tell me some more about what you are experiencing?

**Comment by takinosaji** [comment]
Then it maybe something with my rmq. I ll check. Thanks for attention!

**Comment by mookid8000** [comment]
No problem 😄  I'll close this one for now – feel free to reopen if you continue experiencing problems, then we will take it from there.
