### ISSUE TITLE
Rebus - RMQ connection recovery

### ISSUE THREAD

**Issue by takinosaji** [rebus-org/Rebus#553]
Hi Rebus team!

Does rebus reconnect to rmq in case if it become unavailable and available again (restart for instance) automatically? Does it have such prebuilt functionality at all?

Thanks!

**Comment by mookid8000** [comment]
Yes it does 😄 

There's a caveat though: Rebus cannot start if it cannot connect to the broker initially, but once running, it will do everything in its power to reconnect. There's an issue on allowing Rebus to start even though the broker is initially unreachable: #492 but I am not sure I think this is such a good idea after all.
