### ISSUE TITLE
Problems with AmbientTransactionContext.Current on ASP.NET

### ISSUE THREAD

**Issue by JornWildt** [rebus-org/Rebus#554]
As discussed here http://stackoverflow.com/questions/40402203/how-to-set-rebus-transaction-context-for-a-web-service there is an issue in `AmbientTransactionContext.Current` with the use of `CallContext.LogicalGetData` in ASP.NET. The problem is that `CallContext.LogicalGetData` is thread specific whereas ASP.NET does not guarantee return to the same thread after an `await` statement.

Consider the situation where an HTTP module sets the  `AmbientTransactionContext.Current` to `new DefaultTransactionContext()`. The first `await Bus.Publish(msg)` sees this context and publishes as expected. A second `await Bus.Publish(msg)` may execute on another thread and does *not* see the same context thus leading to various inconsistencies.

For comparison NHibernate requires you to assign a `current_session_context_class` that manages "ambient" storage. Here we can choose between "web" (which will probably use HttpContext.Current) and "thread_static". I would expect to see a similar approach in Rebus?

**Comment by mookid8000** [comment]
I take it that OWIN is not available to you for some reason?

With OWIN you could remove the need for an ASP.NET HTTP module and implement the Rebus transaction context like this:

	app.Use(async (context, next) => {
		using(var context = new DefaultTransactionContext())
		{
			AmbientTransactionContext.Current = context;
			try
			{
			    await next();

			    await context.Complete();
			}
			finally 
			{
				AmbientTransactionContext.Current = null;
			}
		}
	});

**Comment by mookid8000** [comment]
But of course I realize that some people might be stuck in pre-OWIN ASP.NET land, so it would probably be nice if I had a good story to tell when people want to extend their HTTP request pipeline with HTTP modules...

I'll see what I can do... just a sec

**Comment by mookid8000** [comment]
Rebus 2.0.2 allows for customizing the accessor functions used to get/set the ambient transaction context.

You should be able to do something like this:

    AmbientTransactionContext.SetAccessors(
        context => HttpContext.Current.Items["current-rbs-context"] = context,
        () => HttpContext.Current?.Items["current-rbs-context"] as ITransactionContext
    );

in order to make it work under ASP.NET (probably with some error handling in case `HttpContext.Current` is null in the setter)

**Comment by JornWildt** [comment]
Works perfectly. Thank you!

**Comment by JornWildt** [comment]
May I suggest you add a note about this on http://stackoverflow.com/questions/40402203/how-to-set-rebus-transaction-context-for-a-web-service? Then I'll mark it as the answer ASAP.

**Comment by mookid8000** [comment]
Done 😄
