### ISSUE TITLE
Why disabling timeouts in SqlServer?

### ISSUE THREAD

**Issue by JornWildt** [rebus-org/Rebus#555]
In Rebus.SqlServer we have the following piece of extension code:

    static void Configure(StandardConfigurer<ITransport> configurer, Func<IRebusLoggerFactory, IDbConnectionProvider> connectionProviderFactory, string tableName, string inputQueueName)
    {
        configurer.Register(context =>
        {
            var rebusLoggerFactory = context.Get<IRebusLoggerFactory>();
            var asyncTaskFactory = context.Get<IAsyncTaskFactory>();
            var connectionProvider = connectionProviderFactory(rebusLoggerFactory);
            var transport = new SqlServerTransport(connectionProvider, tableName, inputQueueName, rebusLoggerFactory, asyncTaskFactory);
            transport.EnsureTableIsCreated();
            return transport;
        });

        configurer.OtherService<ITimeoutManager>().Register(c => new DisabledTimeoutManager());

        configurer.OtherService<IPipeline>().Decorate(c =>
        {
            var pipeline = c.Get<IPipeline>();

            return new PipelineStepRemover(pipeline)
                .RemoveIncomingStep(s => s.GetType() == typeof(HandleDeferredMessagesStep));
        });
    }

Why is `DisabledTimeoutManager` used here? It makes it impossible to use an external timeout manager (or any other timeout manager?). When I do the following it fails with "Attempted to register primary -> Rebus.Timeouts.ITimeoutManager, but a primary registration already exists: primary -> Rebus.Timeouts.ITimeoutManager":

    busConfigurer
      .Transport(t => t.UseSqlServer(dbConnectionString, RebusMessagesTableName, rebusConfig.inputQueue))
      .Sagas(s => s.StoreInSqlServer(dbConnectionString, RebusSagasTableName, RebusSagaIndexTableName))
      .Timeouts(t => t.UseExternalTimeoutManager("timeoutmanager"));

It does not matter whether .Transport or .Timeouts come first.

**Comment by mookid8000** [comment]
Well.... it's because the SQL transport has built-in message deferral, i.e. it does not actually need a timeout manager.

If you look at the messages table, each row is stored with a timestamp of when that particular message is to become visible, which in turn is used by the transport when querying for new messages.

**Comment by JornWildt** [comment]
So you are saying that we can throw away the timeout manager when using Sql server, right?

May I suggest some way to make this fact visible to poor programmers like me instead of just saying "Attempted to register primary -> Rebus.Timeouts.ITimeoutManager, but a primary registration already exists: primary -> Rebus.Timeouts.ITimeoutManager" :-)

**Comment by mookid8000** [comment]
> May I suggest some way to make this fact visible to poor programmers like me instead of just saying "Attempted to register primary -> Rebus.Timeouts.ITimeoutManager, but a primary registration already exists: primary -> Rebus.Timeouts.ITimeoutManager" :-)

Yes. I feel bad about that error message. I will improve that error message, I promise 😄

**Comment by mookid8000** [comment]
> So you are saying that we can throw away the timeout manager when using Sql server, right?

Yes 👍

**Comment by cariarer** [comment]
Tss... the error message is still the same ;-) Google to the rescue...

**Comment by mookid8000** [comment]
> (...) the error message is still the same ;-) 

Sorry! I've published Rebus.SqlServer 5.0.2 now with an improved error message 😄 thanks for reminding me!
