### ISSUE TITLE
It should be possible to configure SQL server transaction level

### ISSUE THREAD

**Issue by JornWildt** [rebus-org/Rebus#556]
The Rebus.SqlServer implementation has a `IsolationLevel.ReadCommitted` in `DbConnectionFactoryProvider` that cannot be changed from the outside. In our application we need it to be IsolationLevel.Snapshot to work with the remaining code base. Please make it possible to change it.

**Comment by mookid8000** [comment]
(moved to [here](https://github.com/rebus-org/Rebus.SqlServer/issues/4) because the SQL bits have a new home 😄 )
