### ISSUE TITLE
Common WaitAll for synchronous applications

### ISSUE THREAD

**Issue by JornWildt** [rebus-org/Rebus#557]
When Rebus 2.0 is used in non-async applications it is very easy to forget a `Wait()` on all the `Bus.Publish(msg)` operations - and leaving out Wait() means we get no exception handling at all since the operation may fail long after the code had any sort of exception handling setup, probably even on another thread.

Unfortunately the compiler do not issue any kind of warning for this, so, as said, it is very easy to forget this and introduce subtle errors (especially on existing applications where developers are not used to insert the Wait()).

Would it be possible for the IBus implementation to collect all Publish() etc. Task instances in the ambient transaction context and then make a WaitAll() method available i ITransactionContext? That would make it possible to wait for all tasks to complete as part of the common transaction handling where we anyway depend on the ambient context for Commit() / Abort() depending on the outcome of the application operation.

**Comment by mookid8000** [comment]
This is currently being investigated – #435 describes the issue and a PR #549 from @colin-higgins was an attempt to make something work.
