### ISSUE TITLE
Failing to correlate inherited sagas

### ISSUE THREAD

**Issue by JornWildt** [rebus-org/Rebus#560]
I have a system with multiple sagas that all inherit from a generic base saga (which in turn inherits from a base saga). The idea is to have some common error handling and setup in the base classes.

Unfortunately Rebus is only able to correlate data for one of the sagas - in fact the *first* saga it receives a message for:

1. Rebus receives message X and detects that it belongs to saga HandleXSaga. It then calls CorrelateMessages in that saga.
1. Rebus receives message Y and and fails to correlate it with HandleYSaga.

If I swap the sequence of X and Y I get the opposite reaction - it only correlates with the first saga.

The error I get is:

    Could not find any correlation properties for message X and saga data BaseSagaData`1[System.Int64]

Both sagas inherit from the base saga class that declares the saga data as `BaseSagaData<T>` (where `T` is the message ID type). Both messages have the message ID type `long`. So apparently it is the saga data class type that defines the "key" to the correlation mapping - and since both sagas share the same saga data type it fails to distinguish the two?

Is it impossible to inherit from sagas in this way?

The implementation worked with Rebus 0.45 - upgrading to 2.0 introduced this problem.

**Comment by JornWildt** [comment]
Writing this made me realise a solution that seems to work: change `BaseSagaData<T>` to `BaseSagaData<S,T>` where S is the saga type and T is the message ID type. In this way the saga data type depends on the concrete, inherited saga type and thus makes the different saga data distinguishable.

**Comment by mookid8000** [comment]
Sorry for the slow reply – the base class story distracted me 😄 

It turns out that Rebus' built-in correlation property cache _uses only the saga data type_ as key, which means that one set of correlation properties will be used for each saga data type.

The solution was simply to qualify the cache key further, so that it is of a saga data type-saga type-combo.

The fix is out in 2.1.2 in a few minutes.

**Comment by mookid8000** [comment]
In case you're curious: I've added [this test case](https://github.com/rebus-org/Rebus/blob/master/Rebus.Tests/Bugs/SagaBaseClassCorrelationCheck.cs) to reproduce the issue. As you can see, it was enough to use the same saga data in two saga handlers.
