### ISSUE TITLE
Missing logging of received messages

### ISSUE THREAD

**Issue by JornWildt** [rebus-org/Rebus#561]
Previous versions of Rebus (0.45) logged the label of received messages which was a big help when debugging (both in development and production). Rebus 2.0 does not log received messages. Is there a reason for this? Would it be possible to get it by default?

Current I have solved it by decorating ITransport with my own logging transport:

    class TransportContributor : ITransport
    {
      ITransport InnerTransport;

      public TransportContributor(ITransport innerTransport)
      {
        InnerTransport = innerTransport;
      }

      public async Task<TransportMessage> Receive(ITransactionContext context, CancellationToken cancellationToken)
      {
        TransportMessage msg = await InnerTransport.Receive(context, cancellationToken);
        if (msg != null)
        {
          Logger.Debug("Received message: " + msg.GetMessageLabel());
        }
        return msg;
      }
    }

**Comment by mookid8000** [comment]
> Rebus 2.0 does not log received messages.

Yeah. That actually seems kind of silly, especially because Rebus 2 happily logs a DEBUG event for each outgoing message. The least I could do was to be symmetric about it 😁

**Comment by mookid8000** [comment]
Regarding your homegrown logging of handled messages, you can definitely do what you did.

Another way is to take advantage of Rebus' ability to [extend the pipelines](http://mookid.dk/oncode/archives/3938), in this case by inserting a step e.g. at the front of the incoming messages pipeline.

I am using this in a project that I am currently doing – first I create an extension method so I can go `.Options(o => o.LogMessageHandled()`:

	public static void LogMessageHandled(this OptionsConfigurer configurer)
	{
		configurer.Decorate<IPipeline>(c =>
		{
			var pipeline = c.Get<IPipeline>();

			return new PipelineStepInjector(pipeline)
				.OnReceive(new MessageLoggingStep(), PipelineRelativePosition.After,
					typeof(DeserializeIncomingMessageStep));
		});
	}

As you can see, extension method decorates the `IPipeline` with the nifty `PipelineStepInjector`, which is capable of injecting a step relative to another existing step. In this case, I insert the logging behavior right after the `DeserializeIncomingMessageStep`, which means I know that the message could be properly deserialized when my `MessageLoggingStep` is then executed.

The step looks like this:

	public class MessageLoggingStep : IIncomingStep
	{
		static readonly ILogger Logger = Log.ForContext<MessageLoggingStep>();

		public async Task Process(IncomingStepContext context, Func<Task> next)
		{
			var stopwatch = Stopwatch.StartNew();

			try
			{
				await next();
			}
			finally
			{
				var elapsedSeconds = stopwatch.Elapsed.TotalSeconds;
				var message = context.Load<Message>();
				var messageType = message?.GetMessageType() ?? "NULL";
				var messageId = message?.GetMessageId() ?? "NULL";

				Logger.Information("Message {MessageId} / {MessageType} handled in {ElapsedSeconds}",
					messageId, messageType, elapsedSeconds);
			}
		}
	}

which – as you can probably tell – uses Serilog's ability to extrapolate named values from a format string and a couple of values. This means that we can filter, group, and aggregate on message handling times when we have the log events in Elasticsearch.

**Comment by mookid8000** [comment]
We should probably look into making the logging symmetric

**Comment by mookid8000** [comment]
Incoming messages are logged with DEBUG level in 2.1.5. It looks like this:

    Dispatching message String/b64c3d85-9ae5-4068-b5f3-afa974b4b383 to 3 handlers took 3 ms
