### ISSUE TITLE
Support long as saga correlation type

### ISSUE THREAD

**Issue by JornWildt** [rebus-org/Rebus#562]
In `CorrelationProperty` we have:

    static readonly Type[] AllowedCorrelationPropertyTypes =
    {
        typeof (Guid),
        typeof (int),
        typeof (string),
    };

Please also support `long` (which was supported in Rebus 0.45).

Maybe also add other scalar types like bytes and unsigned versions.

**Comment by mookid8000** [comment]
Fixed in 2.1.3 which is on NuGet.org now

Supported types are now:

* `Guid`
* `Guid`
* `Guid`
* `Guid`
