### ISSUE TITLE
Does existing sagas survive upgrade from 0.45 to 2.0?

### ISSUE THREAD

**Issue by JornWildt** [rebus-org/Rebus#563]
We have existing installations of Rebus 0.45 sagas with lots of ungoing sagas in SQL server. Will these survive a code update to Rebus 2.0 or do we have to initiate som sort of database migration? If yes, then how?

The message queue table in SQL server for 2.0 is different from 0.45. Can it be migrated or do we have to make sure the queues are empty before updating? Same question for the SQL server subscription table.

Are there any SQL scripts available for upgrading the database structures? Alternatively we are planning to use new database table names when installing the next version - and then remove the old tables later followed by a rename of the new tables in version.

**Comment by mookid8000** [comment]
> We have existing installations of Rebus 0.45 sagas with lots of ungoing sagas in SQL server. Will these survive a code update to Rebus 2.0 or do we have to initiate som sort of database migration? If yes, then how?

I am pretty sure that the saga persistence schema (the saga data table and the saga index table) are the same, and I am also pretty sure that the saga data can be loaded. I do not recall having done anything to the saga persister when I ported it forward to Rebus 2.

_However, you should be sure to try this out in a test environment before you do it for real._

> The message queue table in SQL server for 2.0 is different from 0.45. Can it be migrated or do we have to make sure the queues are empty before updating? Same question for the SQL server subscription table.

You should make sure the queues are empty, and you should let Rebus 2 re-create the schema.

There's a difference in both header format and SQL Transport schema between 0.45.0 and 2.

> Are there any SQL scripts available for upgrading the database structures? Alternatively we are planning to use new database table names when installing the next version - and then remove the old tables later followed by a rename of the new tables in version.

Don't have any scripts. I would do what you describe and leave the old tables around for a while.
