### ISSUE TITLE
[Question] Azure Services bus message TTL

### ISSUE THREAD

**Issue by mclausen** [rebus-org/Rebus#569]
Hi Team Rebus,

Quick question, what is the TTL on asb messages, and it there anyway to configure it?

**Comment by mookid8000** [comment]
Infinite

Unless you add the `Heaers.TimeToBeReceived` header with a value that can be parsed as a `TimeSpan` – then TTL will be set accordingly.

E.g. like this:

    var headers = new Dictionary<string,string> {
        {Headers.TimeToBeReceived, "00:00:10"}
    };

    await bus.Send("look! I'm gone in 10 s!", headers);

**Comment by mookid8000** [comment]
btw if you know what it is going to be for a specific message type, you can do this:

    [Header(Headers.TimeToBeReceived, "00:00:10")]
    class SomeMessage
    {

    }

**Comment by mclausen** [comment]
Thanks @mookid8000, just what i needed 👍
