### ISSUE TITLE
Can't get CorrelationId when using FileSystem transport

### ISSUE THREAD

**Issue by GrzegorzBlok** [rebus-org/Rebus#571]
I can't get CorrelationId when sending Rebus message while using FileSystem transport.

```c#
foreach (var msg in busMessagesToSend)
{
   await _bus.Send(msg);
   var correlationId = MessageContext.Current?.TransportMessage.Headers.GetValueOrNull(Headers.CorrelationId);
}
```
I also tried this code: `MessageContext.Current.Headers[Headers.CorrelationId]`, but with no luck.
BTW. which way of retrieving CorrelationId is preferable?

The message is sent and handled correctly and I am able to get the CorrelationId inside the message handler using similar code as above. So, the problem is with getting CorrelationId when sending message(s).

**Comment by mookid8000** [comment]
The thing is that `MessageContext.Current` is null when you are outside of a message handler.

The correlation ID of the sent message is set when it is sent _when Rebus sees that you have not provided one yourself_ – i.e. you can simply come up with an ID and set it has a correlation ID when sending the message:

    var correlationId = Guid.NewGuid().ToString();

    var headers = new Dictionary<string,string> {
        { Headers.CorrelationId, correlationId }
    };

    await bus.Send(message, headers);
