### ISSUE TITLE
FakeSyncBus ?

### ISSUE THREAD

**Issue by NKnusperer** [rebus-org/Rebus#572]
After updating to Rebus 3 our custom DI integration was failing to pass the `RealContainerTests.CanInjectSyncBus` tests. After adding support for this new Type the test is passing,
however our own test suit which just use a FakeBus are failing like this:
```
System.InvalidOperationException : No ISyncBus implementation was passed to the FakeAdvancedApi upon construction. Please pass an implementation if you would like to be able to run isolated tests against the data bus API
   at Rebus.Testing.FakeAdvancedApi.get_SyncBus()
```
Sadly there seems to be no implementation for testing to be available.

**Comment by mookid8000** [comment]
just a sec....

**Comment by mookid8000** [comment]
3.0.1 with `FakeSyncBus` is out in a few minutes 😄
