### ISSUE TITLE
reading messages from SQL

### ISSUE THREAD

**Issue by stevengopmo** [rebus-org/Rebus#573]
I have a few messages that have errored out in my sql message queue, but the data in the table is encoded/encrypted.  How can I read them?  Is there a tool or do I need to handle the .Fail<message> and log them separately?  A quick perusal of the other repositories and I found Snoop, but it appears to be exclusively for MSMQ

**Comment by mookid8000** [comment]
Unless you explicitly opted in for another serializer or enabled either compression or encryption the contents of the Body column is simply UTF8-encoded JSON... you can see it by going

    select cast(body as varchar(max)) from messages

**Comment by stevengopmo** [comment]
sweet!  thank you.
