### ISSUE TITLE
Instanciate a clean Handler on every message

### ISSUE THREAD

**Issue by sregojo** [rebus-org/Rebus#576]
I am using the BuiltinHandlerActivator to register some handlers, the register method accepts a lambda returning a Handler instance.
Is there any way of register a Handler bu ensuring rebus intanciates a new Handler on every message?

**Comment by mookid8000** [comment]
Yes, definitely – when you register factory methods like this:

    adapter.Register(() => new MyHandler());

then a new handler instance will be created for each message to be handled.

You are of course free to either

    // pass fresh dependency instances to your handler:
    adapter.Register(() => {
        var someRepository = new SomeRepository(connectionString);

        return new MyHandler(someRepository);
    });

or

    // treat dependencies as singletons
    var someRepository = new SomeRepository(connectionString);

    adapter.Register(() => new MyHandler(someRepository));

**Comment by sregojo** [comment]
Ok, that sounds great. Thanks.
Regarding the second example, "pass fresh dependency instances to your handler".
My question is, what is the best way of using an IoC container for resolving the Handlers dependencies.
By now I have something like:
```
var activator = new BuiltinHandlerActivator())
Configure.With...
	.Start();

IEnumerable<IHandleMessages> handlers = container.GetAllInstances<IHandlerStartup>();
handlers.ForEach(h => activator.Register(() => h));
```
But is not working.. It cannot locate any handler when receiving a message even the handlers list variable have some of them. I got "Message with ID X and type Y could not be ditpatched to any handlers. However if I do `activator.Register(() => new MyHandler());` it works.

**Comment by mookid8000** [comment]
> what is the best way of using an IoC container for resolving the Handlers dependencies

Read the [wiki page about container adapters](https://github.com/rebus-org/Rebus/wiki/Container-adapters) (especially the bit about disposing your container), and then go 

    Install-Package Rebus.SimpleInjector -ProjectName <your-project>

 😁 – then your handler instances will be resolved by the container, and dependencies will be fulfilled as they should.

(it looks like you are using SimpleInjector – is that right? It has a "container adapter" [right here](https://github.com/rebus-org/Rebus.SimpleInjector), which is the Rebus word for adapting an IoC container to be used as a handler activator)

**Comment by sregojo** [comment]
Thanks so much, I really appreciate your help.
Yes, I am using SimpleInjector and Rebus.SimpleInjector. ;-)
I am struggling with the right order of doing the initialization.
Basically I dont know when I have to do:
```
            Configure.With(simpleInjectorContainerAdapter)
                    .Transport(t => t.UseXXX(....))
                    .Start();
```
Because if I resolve anything for getting the container adapter, I get an exception when I execute the previous code. Internally it is trying to register things in the container, but I already resolved one instance of something for getting the container adapter. (registering after resolving is not supported by SimpleInjector)

**Comment by mookid8000** [comment]
You should not get the container adapter from the container.

You should

    Configure.With(new SimpleInjectorContainerAdapter(container))
        .(....)

which will insert `IBus` into the container 😄

**Comment by sregojo** [comment]
It works.
As a nice to have, we would like to also use some instances from the container when we configure the transport:
```
Configure.With(new SimpleInjectorContainerAdapter(container))
.Transport(t => t.UseAmazonSqs(credentials, config))
.Start();
```
I guess we have to create a custom extension method, lets say:
void UseAmazonSqs(this StandardConfigurer<ITransport> configurer, Container container)
and use under the covers the extension method in Rebus.Config.AmazonSqsConfigurationExtensions

What is your opinion on that?
