### ISSUE TITLE
Implementing Amazon SnsSqs

### ISSUE THREAD

**Issue by sregojo** [rebus-org/Rebus#577]
I am trying to implement a transport based on Sns and Sqs for pub/sub.
I did some working code but it only works when I do bus.Send from the publisher.
I dont get the ISubscriptionStorage methods called when I do bus.Publish.
I get Sending XXXX -> <no destinations>
I expected that ISubscriptionStorage.GetSubscriberAddresses(string topic) get called at some point when I publish by bus.Publish(message) or bus.Advanced.Topics.Publish("TopicName", message)

**Comment by mookid8000** [comment]
How did you register your `ITransport` and `ISubscriptionStorage`?

**Comment by sregojo** [comment]
You are right, that was the cause. I dint do:
```
            configurer
                .OtherService<ISubscriptionStorage>()
                .Register(c => new SnsSubscriptionStorage(), description : "It must to be configured!!!!");
```
Thank you so much

**Comment by mookid8000** [comment]
ah, super! 😄
