### ISSUE TITLE
Rebus 3, how to ignore ambient transaction now?

### ISSUE THREAD

**Issue by Rzpeg** [rebus-org/Rebus#578]
Hello,

I used to have the following extension to ignore the rebus ambient transaction for some corner cases (related to cross-domain calls in handlers, for example).

```
 public class IgnoreRebusAmbientTransaction : IDisposable
    {
        private readonly ITransactionContext transactionContext;

        public IgnoreRebusAmbientTransaction()
        {
            this.transactionContext = AmbientTransactionContext.Current;
            AmbientTransactionContext.Current = null;
        }

        public void Dispose()
        {
            AmbientTransactionContext.Current = this.transactionContext;
        }
    }
```

so I could put

```
using (new IgnoreRebusAmbientTransaction())
{
 // cross domain call
}
```

After updating to Rebus 3, the field AmbientTransactionContext.Current is readonly and cannot be set.
How to achive the same result in Rebus 3 ?

Regards,
Stan

**Comment by mookid8000** [comment]
Use `AmbientTransactionContext.SetCurrent(..)` instead 😄 

Sorry about the inconvenience ... 😐
