### ISSUE TITLE
Custom invokeStrategy in DispatchIncomingMessageStep

### ISSUE THREAD

**Issue by sregojo** [rebus-org/Rebus#579]
Could it be usefull having a plugable Strategy in DispatchIncomingMessageStep
May be something like:

```
            invokeStrategy.Begin(context)
            foreach (var invoker in invokers)
            {
                invokeStrategy.Invoke(invoker);
                handlersInvoked++;

                // if dispatch was aborted at this point, bail out
                if (context.Load<bool>(AbortDispatchContextKey))
                {
                    _log.Debug("Skipping further dispatch of message {0}", messageLabel);
                    break;
                }
            }
            invokeStrategy.End()
```
Inside the invokeStrategy.Invoke() in our specific case we could have something like:
```
        public void Invoke(HandlerInvoker invoker)
        {
            if (invoker.InvokeOncePerMessage(context))
            {
                invoker.SaveAsSuccessful(context);
                return;
            }
             invoker.SaveAsFailed(context);
        }
```
Inside  invokeStrategy.End() something like:
```
        public void End()
        {
            if(failedInvokers.Any())
            {
                throw new RebusApplicationException("Some handlers failed", failedInvokers);
            }
        }
```

Our use case is the following:
We have multiple handlers for a given message type. When one of those handlers raises an exception we want to continue with the processing by the rest of the handlers and having a mechanism of recording what handlers have failed and what success.
In our specific use case when at least one handler fails, we are going to persist that information, send the message to a dead letter queue and reprocess the message from dl queue later.
When reprocessing the message we are going use that information for not sending the message to those handlers wich already have succesfully procesed it.
We could easily create an custom DispatchIncomingMessageStep but I am not sure if this feature should be a brand new Step or an extension of the existing one.

**Comment by mookid8000** [comment]
I would do almost anything to avoid tracking failure for handlers individually in the handler pipeline.

In your case – instead of doing this:

                           _________
                          |         |
    ____                  |  h1     |
    |\/|  --> ()###) -->  |     h2  |
    ----                  |_________|


I suggest you do this:

                                                     ________
                           _____                    |        |
                          |     |   --> ()###) -->  |   h1   |
    ____                  |  r  |                   |________|
    |\/|  --> ()###) -->  |     |
    ----                  |     |                    ________
                          |_____|   --> ()###) -->  |        |
                                                    |   h2   |
                                                    |________|

that is: Instead of making up clever mechanisms for tracking the internal state of your endpoint, I suggest you use messages for what they're good at, which is to be successfully processed or not (in which case it is moved to an error queue). You can easily do that by receiving the message in a router `r` which will then forward a copy of the message to each of the two handlers `h1` and `h2` which live in their own endpoints.

**Comment by sregojo** [comment]
Ok, thanks. I'll try to go that way.

**Comment by ilcorvo** [comment]
This topic sound like [this question I posted on Stackoverflow](https://stackoverflow.com/questions/36014172/how-to-configure-rebus-to-have-topics-based-on-handlers-type). 
I went through the strategy suggested by mookid: create a separate endpoint for each topic (in my case the handler type).
Furthermore, to keep the business layer clean of the decoupling strategy, I create a new pipeline incoming step that clones the message with the new destinations: one for each topic/handler.

**Comment by mookid8000** [comment]
Rebus also has a "transport message forwarder" mechanism, which can be pretty useful too in scenarios like these.

You can use it to distribute a message copy to two other queues like this:

     Configure.With(...)
        .Transport(...)
        .Options(o => {
            o.AddTransportMessageForwarder(async transportMessage => {
                return ForwardAction.ForwardTo(new[] {"destination-a", "destination-b"});
            });
        })
        .Start();

**Comment by ilcorvo** [comment]
Oh I see. Sorry I was not able to find documentation on it, so I implemented quite the same feature. 
It differs just for the fact that in my step I dynamically take destination addresses from subscription storage.
