### ISSUE TITLE
UseCompression on databus causes image to be unreadable?

### ISSUE THREAD

**Issue by rasmuschristensen** [rebus-org/Rebus#580]
Hi,

I'm using databus to persist images with SqlServer and option DataCompression.Always. When I read the image data, I get the data but not able to display the images. If I remove the compression option, store a new image and read it, everything works. Either I'm missing something related to compression or there might be an issue with image data and compression??

**Comment by mookid8000** [comment]
sounds like a bug to me.... I'll take a look at it, probably tonight

**Comment by mookid8000** [comment]
Any chance I can get you to send me an image file that has turned out to have this problem?

**Comment by mookid8000** [comment]
I've made [this test](https://github.com/rebus-org/Rebus/blob/master/Rebus.Tests/DataBus/Zip/TestZippingDataBusStorageDecorator.cs) now that attempts to reproduce an issue with the zipping data bus storage decorator, but so far it has not succeeded in doing that.

Moreover, I have coded [this small application](https://github.com/mookid8000/DataBusImageCompressionThing) that creates an attachment out of a locally stored image file and reads it back in. So far, I have achieved the same results with/without compression.

Could you maybe reproduce the issue and send it to me? (or simply show me how you made it fail)

**Comment by mookid8000** [comment]
Any chance you could show me how you made it fail?

**Comment by rasmuschristensen** [comment]
Currently I'm not able to reproduce it again...

**Comment by mookid8000** [comment]
Allrighty 👍 😄  

Let me know if you still suspect anything is wrong.
