### ISSUE TITLE
Encryption is on but the message is not encrypted

### ISSUE THREAD

**Issue by runes83** [rebus-org/Rebus#581]
We use Rebus 0.99.74 and have some message that fails because the the message is not encrypted but the encryption headers are set
* rbs2-content-encryption: rijndael
* rbs2-encryption-iv: Hhg5AieJ/9pr4XomRsDx1A==

Is there any scenario this could happen?

**Comment by mookid8000** [comment]
that sounds weird!! can I see your configuration?

**Comment by runes83** [comment]
```c#
 private static IBus ConfigureBus(IContainer container)
        {
            string queueAddress = AppSettingsReader.RunningInAzure ? string.IsNullOrEmpty(AppSettingsReader.AzureOverrideQueue) ? "document-worker-azure" : AppSettingsReader.AzureOverrideQueue : "localworker";
            string accountQueue = "accountqueue";

            var adapter = new AutofacContainerAdapter(container);
            var bus = Configure.With(adapter)
                    .Transport(t => t.UseAzureServiceBusAsOneWayClient(AppSettingsReader.ServicebusConnectionString))
                    .Routing(r => r.TypeBased()
                        .MapAssemblyOf<SomeAssembly.HeartBeatCommand>(queueAddress)
                        .MapAssemblyOf<SomeOthrerAssembly.HeartBeatCommand>(accountQueue)
                        )
                    .Options(o =>
                    {
                        o.EnableCompression(
#if DEBUG
                        1024 * 150
#endif
                        );
#if !DEBUG
                        o.EnableEncryption(AppSettingsReader.RebusEncryption);                    
#endif

                    })
                    .Start();


            return bus;


        }
```

**Comment by runes83** [comment]
We are not able to duplicate this on our dev machines this only happens in production.

**Comment by mookid8000** [comment]
> Could there be some scenario where the encryption headers are set but the encryption is not completed?

I find this very hard to believe – you can see the code [here (outgoing step)](https://github.com/rebus-org/Rebus/blob/master/Rebus/Encryption/EncryptMessagesOutgoingStep.cs) and [here (the encryptor)](https://github.com/rebus-org/Rebus/blob/master/Rebus/Encryption/RijndaelEncryptor.cs#L59-L76)

**Comment by mookid8000** [comment]
I think I know what it is! Did you by any chance _forward_ the message?

As in:

    await bus.Advanced.TransportMessage.Forward(somewhere);

?

I need to investigate further, but I think it looks like the decrypted body will be forwarded along with the original headers......... which isn't so smart

**Comment by runes83** [comment]
I've taken a look at the code with the tag 0.99.74 and cannot find anything obvious. Could this happen on a retry? For example IHandle>IFailed< ?

**Comment by runes83** [comment]
public async Task Handle(IFailed<CreatePadesCommand> failedMessage)
        {
            int retryCount = 0;
            if (failedMessage.Headers.ContainsKey("retry-count"))
                Int32.TryParse(failedMessage.Headers["retry-count"], out retryCount);

            if (retryCount < AppSettingsReader.RetryAttempts)
            {
                retryCount++;
                var delay = TimeSpan.FromMinutes(2 * retryCount);
                var additionalHeaders = new Dictionary<string, string> {
                    { "retry-count", retryCount.ToString()}
                };
                await Bus.Advanced.TransportMessage.Defer(delay, additionalHeaders);

            }
            else if(retryCount == AppSettingsReader.RetryAttempts)
            {
                await Bus.Advanced.TransportMessage.Defer(TimeSpan.FromHours(2));
            }

        }

**Comment by mookid8000** [comment]
That's it!

**Comment by runes83** [comment]
What is the correct way of doing this?

**Comment by mookid8000** [comment]
It should work the way you are doing it. Let me check this out – I will get back to you, probably some time tonight.

**Comment by runes83** [comment]
That's ok thank you for the help

**Comment by mookid8000** [comment]
The problem was exactly what I suspected – when a message is forwarded, it got done by snatching the `TransportMessage` from the current message context and forwarding that.

The problem was that when using compression and encryption, the `TransportMessage` in the context would have been changed, even though the headers were not.

And then, when the transport message was forwarded, it would forwarded the decompressed/decrypted copy, and not the original body.

The solution was to store an `OriginalTransportMessage` in addition to the `TransportMessage`, which is then used when it is time to forward a message.

When the build server has finished crunching, I will release the fix.

This will also be a good opportunity for you to get up on the newest Rebus version 😉  I'll let you know when it's ready 😄

**Comment by mookid8000** [comment]
It's fixed in 3.0.2, which is in the NuGet Gallery now 😄 

Thanks for reporting this!

**Comment by espenhal** [comment]
Thanks for fixing this so quick! :)
We are now about to upgrade from 0.99.74 to 3.0.2. 
But we wonder if it would be possible to have different versions of Rebus send/recieve messages on the same bus? And if we stop our bus when upgrading Rebus, will messages allready on the bus, that was sent with 0.99.74, be picked up again when restarting services with 3.0.2? 
Any known pit falls to look out for?

**Comment by mookid8000** [comment]
I am preeetty sure that 0.99.74 and 3.0.2 are wire compatible. Not 100%, but 99.999% sure.
