### ISSUE TITLE
Documentation for IdempotentSaga

### ISSUE THREAD

**Issue by Niklas-Peter** [rebus-org/Rebus#582]
https://github.com/rebus-org/Rebus/blob/master/Rebus/Sagas/Idempotent/IdempotentSaga.cs

The comments in the source code suggest what it does, but I think you should at least mention it in the Wiki. 
Is the separate NuGet package Rebus.IdempotentSaga needed at all or is it only intended for old Rebus versions (I assume this, because it has another logo on NuGet than the more recent packages)?

**Comment by mookid8000** [comment]
you are right – the idempotent saga thing ought to be documented on the wiki, and yes you are absolutely right that the NuGet package is for Rebus versions <= 0.84.0
