### ISSUE TITLE
Missing JSON file

### ISSUE THREAD

**Issue by paulmarshall** [rebus-org/Rebus#584]
In the sample RebusSamples/PubSub/PubSub.Publisher, Program.cs refers to a "rebus_subscriptions.json" file that hasn't been uploaded to the repository.

**Comment by mookid8000** [comment]
isn't it created automatically when the application starts?

**Comment by paulmarshall** [comment]
Yes - and something I discovered when I actually downloaded and ran the code. Sorry.

Each of the subscribers send a SubscriberRequest message to the queue listened to by the Publisher so when an event is raised, the publisher then knows to whom has subscribed to the message so it knows whi to publish the message to - presumably to each of the Subscriber1/2 queues?

**Comment by mookid8000** [comment]
Exactly, yes 😄
