### ISSUE TITLE
PubSub MSMQ Multicast

### ISSUE THREAD

**Issue by bchattdeveloper** [rebus-org/Rebus#589]
I'm new to this so help me if I misunderstand.  

Your page on pub/sub indicates that manual sending to each subscriber is required of the publisher because there is no multicasting in MSMQ.  However, it is possible to configure an MSMQueue for multicasting by using the following address, "234.1.1.1:8081". 

I'm struggling to test me pub/sub implementation using MSMQ and I wonder if this has something to do with it.  Sorry for being general, but I just need help figuring out the whole situation and I get confused.

Thanks,

**Comment by mookid8000** [comment]
> However, it is possible to configure an MSMQueue for multicasting by using the following address, "234.1.1.1:8081"

I am aware that MSMQ has a "multicast" feature, but IMO it is pretty obscure and I don't think it would be possible to use it for topic-based pub/sub.

> I'm struggling to test me pub/sub implementation using MSMQ and I wonder if this has something to do with it. Sorry for being general, but I just need help figuring out the whole situation and I get confused.

Rebus does not use MSMQ's multicast features at all. It relies on MSMQ's ordinary queues only, and then it uses a "subscription storage" to implement pub/sub.

I suggest you take a look at [the pub/sub sample](https://github.com/rebus-org/RebusSamples/tree/master/PubSub) – it shows how pub/sub can be had with MSMQ and a simple JSON-formatted file-based subscription storage.
