### ISSUE TITLE
Figure out why pipeline invoker is slow

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#590]
I heard NServiceBus had one, so I figured Rebus should have one too: An expression-based dynamically compiled pipeline invoker!

It's currently residing here: [CompiledPipelineInvoker.cs](https://github.com/rebus-org/Rebus/blob/feature/pipeline-invoker/Rebus/Pipeline/CompiledPipelineInvoker.cs)

It can be enabled by going `.Options(o => o.UseExperimentalPipelineInvoker())`

It's odd though, because it's currently slower than the original `DefaultPipelineInvoker` – when running the [TestDispatchPerformance test](https://github.com/rebus-org/Rebus/blob/feature/pipeline-invoker/Rebus.Tests/Profiling/TestDispatchPerformance.cs) it comes out with these results – first the new invoker:

    Performing sample 1: 6,84228
    Performing sample 2: 6,05261
    Performing sample 3: 7,04337
    Performing sample 4: 7,32062
    Performing sample 5: 6,14826
    5 runs
    Avg s: 6,68143
    Avg msg/s: 14967

    Experimental pipeline invoker: True

    Stats:
        Rebus.Retry.Simple.SimpleRetryStrategyStep: 00:00:11.6663421 (24,6 %)
        Rebus.Pipeline.Receive.ActivateHandlersStep: 00:00:10.0791685 (21,3 %)
        Rebus.Pipeline.Receive.DeserializeIncomingMessageStep: 00:00:09.0782772 (19,2 %)
        Rebus.Pipeline.Receive.DispatchIncomingMessageStep: 00:00:02.4532902 (5,2 %)
        Rebus.Pipeline.Receive.HandleDeferredMessagesStep: 00:00:11.8209110 (25,0 %)
        Rebus.Sagas.LoadSagaDataStep: 00:00:02.2483170 (4,7 %)

and then the original:

    Performing sample 1: 4,34802
    Performing sample 2: 4,42305
    Performing sample 3: 4,1209
    Performing sample 4: 4,68276
    Performing sample 5: 5,51003
    5 runs
    Avg s: 4,61695
    Avg msg/s: 21659

    Experimental pipeline invoker: False

    Stats:
        Rebus.Retry.Simple.SimpleRetryStrategyStep: 00:00:06.9782145 (22,2 %)
        Rebus.Pipeline.Receive.ActivateHandlersStep: 00:00:07.7297130 (24,6 %)
        Rebus.Pipeline.Receive.DeserializeIncomingMessageStep: 00:00:05.6786682 (18,1 %)
        Rebus.Pipeline.Receive.DispatchIncomingMessageStep: 00:00:01.7212883 (5,5 %)
        Rebus.Pipeline.Receive.HandleDeferredMessagesStep: 00:00:08.3071161 (26,5 %)
        Rebus.Sagas.LoadSagaDataStep: 00:00:00.9494961 (3,0 %)

(don't pay too much attention to the actual numbers – it's a Debug build, running on a Macbook Pro that has 6% power left and is currently running on a Macbook's power supply....)

I wonder if there is something that can be done about the expressions....... the place where all the fun happens looks like this (capable of generating a `Func<IncomingStepContext, Task>` or `Func<OutgoingStepContext, Task>`):

    static Func<TContext, Task> GenerateFunc<TContext, TStep>(IReadOnlyList<TStep> steps, string processMethodName)
        where TContext : StepContext
        where TStep : IStep
    {
        // pipeline terminator: create function (context) => CompletedTask
        var contextParameter = Expression.Parameter(typeof(TContext), $"context{steps.Count}");
        var noopExpression = Expression.Constant(CompletedTask);
        var expression = Expression.Lambda<Func<TContext, Task>>(noopExpression, contextParameter);

        // start with the end - construct each step function such that its invocation looks like this
        // (context) => step[n-1].Process(context, () => step[n].Process(...))
        for (var index = steps.Count - 1; index >= 0; index--)
        {
            var step = steps[index];
            var processMethod = GetProcessMethod(step, processMethodName, typeof(TContext));

            var contextParameterp = Expression.Parameter(typeof(TContext), $"context{index}");
            var stepReference = Expression.Constant(step);
            var invocationExpression = Expression.Invoke(expression, contextParameterp);
            var nextExpression = Expression.Lambda<Func<Task>>(invocationExpression);
            var callExpression = Expression.Call(stepReference, processMethod, contextParameterp, nextExpression);

            expression = Expression.Lambda<Func<TContext, Task>>(callExpression, contextParameterp);
        }

        return expression.Compile();
    }

This is my first time compiling expressions, so I am just happy I made it work 😄 but I am thinking that there is something I am missing, because it really ought to be much faster than the original invoker.

I wonder if someone can help cast some light on this 💡

**Comment by NKnusperer** [comment]
Interesting issue, however I cannot see an obvious problem with the generated Expression.
I tried to dump out the generated IL code so I could compare it with a hand-crafted pipeline invocation to find out the difference like this:
```
var assemblyBuilder = AppDomain.CurrentDomain.DefineDynamicAssembly(new AssemblyName("CompiledPipelineInvoker"), AssemblyBuilderAccess.Save);
var moduleBuilder = assemblyBuilder.DefineDynamicModule("CompiledPipelineInvokerModule", "CompiledPipelineInvoker.dll");
var typeBuilder = moduleBuilder.DefineType("CompiledExpression");
var methodBuilder = typeBuilder.DefineMethod("InvokeCompiledPipelineInvoker", MethodAttributes.Public | MethodAttributes.Static);
expression.CompileToMethod(methodBuilder);
typeBuilder.CreateType();
```

Unfortunately this does not work because of the referenced "live objects":

> System.InvalidOperationException: 'CompileToMethod cannot compile constant 'Rebus.Profiling.PipelineStepProfiler+RegisterCollectedProfilerStatsStep' because it is a non-trivial value, such as a live object. Instead, create an expression tree that can construct this value.'

:disappointed:

**Comment by dadhi** [comment]
Check results with [FastExpressionCompiler](https://github.com/dadhi/FastExpressionCompiler). The performance may be significally different depending on kind of expressions you use.

**Comment by mookid8000** [comment]
@dadhi Interesting! I'll go look at it

**Comment by mookid8000** [comment]
btw I have changed the implementation slightly – I am usually not a "beautiful code kind-of-guy", and I am definitely one who brags, but this particular piece of code seems pretty elegant to me (I changed the reverse traversal of the pipelines into a recursive head-tail buildup):

        static Func<TContext, Task> GenerateFunc<TContext, TStep>(IReadOnlyList<TStep> steps, string processMethodName)
            where TContext : StepContext
            where TStep : IStep
        {
            var expression = GenerateExpression<TContext, TStep>(steps, processMethodName, 0);

            return expression.Compile();
        }

        /// <summary>
        /// Recursively builds and expression that invokes the pipeline, FUN STYLE BABY!
        /// </summary>
        static Expression<Func<TContext, Task>> GenerateExpression<TContext, TStep>(IReadOnlyCollection<TStep> steps, string processMethodName, int index)
            where TContext : StepContext
            where TStep : IStep
        {
            // we need a context parameter no matter what
            var contextParameter = Expression.Parameter(typeof(TContext), $"context{index}");

            // if we have no steps to invoke, just return the terminator expression
            if (!steps.Any())
            {
                var noopExpression = Expression.Constant(CompletedTask);

                return Expression.Lambda<Func<TContext, Task>>(noopExpression, contextParameter);
            }

            // otherwise, get an expression for invoking the tail of the pipeline...
            var tail = steps.Skip(1).ToList();
            var tailExpression = GenerateExpression<TContext, TStep>(tail, processMethodName, index + 1);

            // ...and attach it to the invocation of the head of the pipeline:
            var head = steps.First();
            var processMethod = GetProcessMethod(head, processMethodName, typeof(TContext));

            var stepReference = Expression.Constant(head);
            var invocationExpression = Expression.Invoke(tailExpression, contextParameter);
            var nextExpression = Expression.Lambda<Func<Task>>(invocationExpression);
            var callExpression = Expression.Call(stepReference, processMethod, contextParameter, nextExpression);

            return Expression.Lambda<Func<TContext, Task>>(callExpression, contextParameter);
        }

        static MethodInfo GetProcessMethod(IStep step, string methodName, Type contextType)
        {
            var processMethod = step.GetType().GetMethod(methodName, new[] { contextType, typeof(Func<Task>) });
            if (processMethod != null) return processMethod;

            throw new ArgumentException($"Could not find method with signature {methodName}({contextType.Name} context, Func<Task> next) on {step}");
        }

**Comment by mookid8000** [comment]
only thing missing is to make it faster than the current implementation 😄

**Comment by dadhi** [comment]
FastEC works with manually created expressions as well, may check unit tests or benchmarks. That's how DryIoc use it. Need to add some usage samples to readme )

**Comment by mookid8000** [comment]
hmm, I am unsure how I cam use the `ExpressionCompiler` – instead of this:

            var expression = GenerateExpression<TContext, TStep>(steps, processMethodName, 0);

            return expression.Compile();

 I tried this:

            var expression = GenerateExpression<TContext, TStep>(steps, processMethodName, 0);
            var contextParameter = Expression.Parameter(typeof(TContext), "context");
            var lambdaExpression = Expression.Lambda(expression, contextParameter);

            return ExpressionCompiler.Compile<Func<TContext, Task>>(lambdaExpression);

but then I get `System.ArgumentException : Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.`, and then I tried this:

            var expression = GenerateExpression<TContext, TStep>(steps, processMethodName, 0);
            var contextParameter = Expression.Parameter(typeof(TContext), "context");

            return ExpressionCompiler.TryCompile<Func<TContext, Task>>(
                expression,
                new List<ParameterExpression> {contextParameter},
                new[] {typeof(TContext)}, typeof(Task)
            );

and then I get a function call that does not seem to do anything, except it never returns...

😩

**Comment by dadhi** [comment]
Hmm, will check. May be you found a bug, may be not. ArgEx telling that passed delegate type is not compatible with compiled result..

**Comment by dadhi** [comment]
Did you have GenerateExpression committed so that I could compile and check?

**Comment by mookid8000** [comment]
Yes, it's in the [feature/pipeline-invoker branch](https://github.com/rebus-org/Rebus/tree/feature/pipeline-invoker) – I am currently trying to get the [`InvokesInOrder()`](https://github.com/rebus-org/Rebus/blob/feature/pipeline-invoker/Rebus.Tests/Pipeline/TestCompiledPipelineInvoker.cs#L102-L119) test to run

**Comment by dadhi** [comment]
Cool, we check from here !

**Comment by dadhi** [comment]
Regarding usage.. what was wrong. Your `GenerateExpression` is already returning the `LambdaExpression`. So this is enough

    var lambdaExpression = GenerateExpression(...);
    var lambda =  ExpressionCompiler.Compile<Func<TContext, Task>>(lambdaExpression);

As for direct call to `TryCompile`, the parameter provided is not the same used by generated lambda expression. It should be like this:

    var lambda =  ExpressionCompiler.TryCompile<Func<TContext, Task>>(
        lambdaExpression, lambdaExpression.Parameters,
        new[] {typeof(TContext)}, typeof(Task));

Looking into the target (tested) pipeline expression, with the recursive nesting of lambdas for the steps, it seems not so optimal and rather hard on compiler:
```
{value(TestCompiledPipelineInvoker+NamedStep)
.Process(context0, () => Invoke(context1 => value(TestCompiledPipelineInvoker+NamedStep)
.Process(context1, () => Invoke(context2 => value(TestCompiledPipelineInvoker+NamedStep)
.Process(context2, () => Invoke(context3 => value(TestCompiledPipelineInvoker+NamedStep)
.Process(context3, () => Invoke(context4 => value(TestCompiledPipelineInvoker+NamedStep)
.Process(context4, () => Invoke(context5 => value(TestCompiledPipelineInvoker+NamedStep)
.Process(context5, () => Invoke(context6 => value(TestCompiledPipelineInvoker+NamedStep)
.Process(context6, () => Invoke(context7 => value(TestCompiledPipelineInvoker+NamedStep)
.Process(context7, () => Invoke(context8 => value(TestCompiledPipelineInvoker+NamedStep)
.Process(context8, () => Invoke(context9 => value(TestCompiledPipelineInvoker+NamedStep)
.Process(context9, () => Invoke(context10 => value(TestCompiledPipelineInvoker+NamedStep)
.Process(context10, () => Invoke(context11 => value(TestCompiledPipelineInvoker+NamedStep)
.Process(context11, () => Invoke(context12 => value(TestCompiledPipelineInvoker+NamedStep)
.Process(context12, () => Invoke(context13 => value(TestCompiledPipelineInvoker+NamedStep)
.Process(context13, () => Invoke(context14 => value(TestCompiledPipelineInvoker+NamedStep)
.Process(context14, () => Invoke(context15 => value(System.Threading.Tasks.Task`1[System.Int32]),
 context14)), context13)), context12)), context11)), context10)), context9)), context8)), context7)), context6)), context5)), context4)), context3)), context2)), context1)), context0))}
```

May be an iterative approach (if feasible) would be better. Just my 5 cents.

**Comment by mookid8000** [comment]
yeah well – it doesn't seem to improve on the original invoker that did this:

    public Task Invoke(IncomingStepContext context)
    {
        var step = TerminationStep;

        for (var index = _incomingSteps.Length - 1; index >= 0; index--)
        {
            var nextStep = step;
            var stepToInvoke = _incomingSteps[index];
            step = () => stepToInvoke.Process(context, nextStep);
        }

        return step();
    }

Funnily enough, a simple `Func<IncomingStepContext, Task>` function built from C#7 local methods seems to be just as fast as the expression-based invoker:

    static Func<IncomingStepContext, Task> GenerateReceiveFunction(IReadOnlyList<IIncomingStep> steps)
    {
        if (!steps.Any())
        {
            Task CompletedFunction(IncomingStepContext context) => CompletedTask;
            return CompletedFunction;
        }

        var head = steps.First();
        var tail = steps.Skip(1).ToList();
        var invokeTail = GenerateReceiveFunction(tail);

        Task ReceiveFunction(IncomingStepContext context)
        {
            Task NextFunction() => invokeTail(context);
            return head.Process(context, NextFunction);
        }

        return ReceiveFunction;
    }

**Comment by dadhi** [comment]
The expression is just a lightweight tool to compose delegate at runtime. The result delegate speed should not be different from normal delegate, in theory.. but not in practice :-( That's FEC is supposed to fix, in addition, improving the compilation time.

**Comment by mookid8000** [comment]
right 😄 

My last attempt today at making the invocation faster took the original `for(var index =...`-based approach and rewrote it to use C#7 local functions:

    public Task Invoke(IncomingStepContext context)
    {
        Task InvokerFunction(int index)
        {
            if (index == _incomingSteps.Length) return Noop;

            Task InvokeNext() => InvokerFunction(index + 1);

            return _incomingSteps[index]
                .Process(context, InvokeNext);
        }

        return InvokerFunction(0);
    }

It's so simple now! And this one actually seems to be slightly faster in most trials – running 10 samples of 100k invocations yielded these results:

	+----------------------------------------------------------------------------------------+
	| Action     | Med msg/s: 30354 | Recursive, action-based                                |
	| Default    | Med msg/s: 31189 | Original Invoker                                       |
	| Compiled   | Med msg/s: 31331 | Expression-based, compiled with FastExpressionCompiler |
	| DefaultNew | Med msg/s: 31554 | Invoker based on C#7 local methods                     |
	+----------------------------------------------------------------------------------------+

where the code snippet shown above is the `DefaultNew` invoker. I think I'll keep that one for now 😁

**Comment by dadhi** [comment]
Nice touch with local functions, recursion will be probably a primary usage, Do you use it from 2017? or there is a way with 2015?

**Comment by mookid8000** [comment]
Using is from 2017. I think you need VS 2017 to compile C#7

**Comment by mookid8000** [comment]
Results are flimsy, though – on the buildserver, these results happened:

    Running 10 samples with 100000 msgs and mode Action
        Avg s: 4.59343
        Avg msg/s: 21770
        Med s: 4.55219
        Med msg/s: 21967

    Running 10 samples with 100000 msgs and mode Compiled
        Avg s: 4.73772
        Avg msg/s: 21107
        Med s: 4.7071
        Med msg/s: 21245

    Running 10 samples with 100000 msgs and mode Default
        Avg s: 4.67224
        Avg msg/s: 21403
        Med s: 4.68925
        Med msg/s: 21325

    Running 10 samples with 100000 msgs and mode DefaultNew
        Avg s: 4.72516
        Avg msg/s: 21163
        Med s: 4.67976
        Med msg/s: 21369

I.e. the action-based invoker won by a small margin

**Comment by mookid8000** [comment]
and the `Default` invoker was faster than `DefaultNew` on average

**Comment by mookid8000** [comment]
The only significant discovery so far, is that the pipeline invoker either is a) not that much of a hotspot, or b) structured badly and will need radical changes if performance is to be improved.

**Comment by mookid8000** [comment]
I'm closing this issue for now.... see previous comment on why 😐
