### ISSUE TITLE
Polymorphic dispatch strange behavior

### ISSUE THREAD

**Issue by mitchmchenry** [rebus-org/Rebus#596]
_Originally posted on StackOverflow.  Reposted here by request._

I'm having a strange problem with polymorphic message dispatch in Rebus 3.1.2 with MSMQ transport and StructureMap 4.4.2 container.

If I have a message:

`public class SomeMessage`

and some handlers:

```
public class Handler1 : IHandleMessages<SomeMessage>
public class Handler2 : IHandleMessages<SomeMessage>
```

When I send SomeMessage, both handlers fire as expected.

However, when I have a message:

`public class SomeMessage : ISomeInterface`

and some handlers:

```
public class Handler1 : IHandleMessages<SomeMessage>
public class Handler2 : IHandleMessages<ISomeInterface>
```

When I send SomeMessage, only Handler1 fires. But if I comment out Handler1 and send the message again, Handler2 will fire.

The same is true if SomeMessage inherited from SomeBaseClass and Handler2 handled SomeBaseClass (or even object). Only Handler1 will fire. But if I comment out Handler1, Handler2 will fire.

It's almost like it doesn't attempt polymorphic dispatch if it finds any handlers for the specific message class.

Because Handler2 will fire when I comment out Handler1, I don't think it's a container issue. I'm guessing if this was really broken, someone else would have noticed. So I'm assuming it's me, but I don't know where to go from here.

AFAIK, there's nothing to configure about polymorphic dispatch, right?

Any idea what I might be doing wrong?

**Comment by mookid8000** [comment]
Hmm... it looks like the StructureMap container adapter does not correctly resolve polymorphic things... I will look into this

**Comment by mitchmchenry** [comment]
Ah, OK.  I was afraid I was missing something.

Sorry, I just noticed I messed up the code blocks in my post when I pasted from SO.  Fixed now.

Thanks for looking into this.

**Comment by mookid8000** [comment]
If my testing is correct, it seems that StructureMap behaves in a weird, inconsistent manner – it will automatically resolve 1 single handler instance in a polymorphic fashion when calling `GetAllInstances`, but it will continue to resolve 1 single instance even if there are multiple matches.

**Comment by mitchmchenry** [comment]
Ouch, I was hoping it was just going to be a simple fix in the adapter.  Yeah, it's really strange that it's able to resolve the polymorphic handlers, but only one at a time.  I haven't messed much with `GetAllInstances` myself, but that can't be expected behavior, right?  The documentation doesn't really give any details on what it's supposed to do beyond the simple "all concretes for an interface" example.

**Comment by mookid8000** [comment]
Unfortunately I don't know that much about StructureMap – IIRC the container adapter was contributed by @rasmuskl a long time ago.

If someone knows how SM is supposed to behave when calling `GetAllInstances` on a contravariant interface, feel free to chime in 😄

**Comment by mookid8000** [comment]
btw I'm moving the issue to [here](https://github.com/rebus-org/Rebus.StructureMap/issues/1) because it's a problem with the SM container adapter and doesn't really have anything to do with Rebus code
