### ISSUE TITLE
Ignore 'Unhandled Messages' Exception

### ISSUE THREAD

**Issue by michaelmsm89** [rebus-org/Rebus#598]
I have a situation where a previously deployed application has subscribed to a topic 'foo.#' (wildcard with RabbitMQ to listen to all messages with a topic beginning 'foo.'). We have now implemented a large number of new messages for the topic of foo which are published from elsewhere, for which this deployed application does not have handlers for as it doesn't know/care about them.

Currently we are experiencing a RebusApplicationException of "Message with ID X and type X could not be dispatched to any handlers". We could remove the subscriptions from the subscription persistence (rabbitMQ) for this app and then register specifically for the topics we want, such as 'foo.bar', rather than using the wildcard subscription.

However in our situation we would prefer to just ignore messages we are subscribed to but have no handlers. Is there a way to configure this within Rebus?

I noticed that in [DispatchIncomingMessageStep.cs](https://github.com/rebus-org/Rebus/blob/333dbedf486acb92bd6c6250755537032c6215fd/Rebus/Pipeline/Receive/DispatchIncomingMessageStep.cs), on line 73, an exception is thrown if no handlers were invoked. The comment states `// throw error if we should have executed a handler but we didn't` but in my case, we should not have executed a handler as we have none.

```c#
            foreach (var invoker in invokers)
            {
                await invoker.Invoke();
                handlersInvoked++;

                // if dispatch was aborted at this point, bail out
                if (context.Load<bool>(AbortDispatchContextKey))
                {
                    _log.Debug("Skipping further dispatch of message {messageLabel}", messageLabel);
                    break;
                }
            }

            // throw error if we should have executed a handler but we didn't
            if (handlersInvoked == 0)
            {
                var message = context.Load<Message>();
                
                var messageId = message.GetMessageId();
                var messageType = message.GetMessageType();

                var text = $"Message with ID {messageId} and type {messageType} could not be dispatched to any handlers";

                throw new RebusApplicationException(text);
            }
```

If this also checked that there are actually handlers to invoke, i.e. 
```c#
 if (handlersInvoked == 0 && invokers.Any())
```
then it would only throw the exception if an existing invoker didn't handle the message, rather than in our case where no invoker exists at all.

In #130 I see the intention is to explicitly handle this scenario as an error, but I'm wondering if being able to ignore the error would be an equally valid option?

**Comment by mookid8000** [comment]
There was a time when Rebus worked like that (because NServiceBus used to do that too), but I changed it early on because my experience with it was that that was not what you wanted to happen 99% of the time – not being able to find any handlers is almost always because of a misconfigured IoC container, and in those cases you will be happier if the message ends up in an error queue to be redelivered at a later time.

> I'm wondering if being able to ignore the error would be an equally valid option?

I can definitely see how it would be nice for you if it was possible to configure it to behave like that, but unfortunately there's no way out of the box to do it. It should be possible though to insert a new incoming message step right before the `DispatchIncomingMessageStep` that checks to see if the message did not find any handlers, and whether it is safe to ignore it, and then refrain from invoking the rest of the pipeline.

If you need a hint on how to extend the message pipelines, I suggest you read the [One way of extending the Rebus pipeline](http://mookid.dk/oncode/archives/3938) and [A Rebus extension example](http://mookid.dk/oncode/archives/3947) posts on my blog.

**Comment by michaelmsm89** [comment]
Thanks for the reply, I'll look into modifying the pipeline to avoid this issue. An alternative for my case would be to unsubscribe from every subscription on startup, and then re-subscribe to only the topics I care about, dropping the subscriptions I no longer have handlers for. Is there a way to retrieve a list of all current subscriptions from RabbitMQ via Rebus AdvancedTopic API so that I can loop over them and unsubscribe from them all?

**Comment by mookid8000** [comment]
> unsubscribe from every subscription on startup, and then re-subscribe to only the topics I care about

This would actually introduce a small risk of a race condition between removing a subscription and introducing it again in case a message was published at that exact time.

> Is there a way to retrieve a list of all current subscriptions from RabbitMQ via Rebus AdvancedTopic API so that I can loop over them and unsubscribe from them all?

Unfortunately, no 😐 

My suggestion is to either

a) do an appropriate `await bus.Unsubscribe<EventType>()`, or
b) do an `await bus.Advanced.Topics.Unsubscribe("Application.Messages.EventType, Application.Messages")` if the event type is no longer available, or
c) edit the subscription storage manually "behind the scenes" in a deployment script

**Comment by jstafford5380** [comment]
Sorry for the necro, but I also need this behavior. The topic in question is a "public" topic with many message types that I am not interested in for this particular service. I tried implementing an IIncomingStep and utilizing IHandlerActivator but `GetHandlers` was not returning any handlers even on message that had registered handlers. My handlers are registered correctly, in fact the messages get processed just fine if i remove this custom step. I can also verify that the incoming message has been deserialized correctly into the correct type. Do you have an example of how I'm supposed to do this?

Here's what I had implemented

```csharp
internal class IgnoreUnhandledMessagesStep(
    ILog logger,
    IHandlerActivator handlerActivator) : IIncomingStep 
{
    private readonly ILog _logger = logger;
    private readonly IHandlerActivator _handlerActivator = handlerActivator;

    public async Task Process(IncomingStepContext context, Func<Task> next)
    {
        var transactionContext = context.Load<ITransactionContext>();
        var message = context.Load<Message>();

       // when stepping through, this always returns an empty collection even if handlers are registered for the type.
        var handlers = await _handlerActivator.GetHandlers(message.Body, transactionContext);
        if (!handlers.Any())
        {
            _logger.Debug("Not handlers found for {messageType}", message.Headers[Headers.Type]);
            return;
        }

        await next();
    }
}
```

**Comment by jstafford5380** [comment]
Nevermind, I was able to use `context.Load<HandlerInvokers>()` and then check length of this instead
