### ISSUE TITLE
integration between different varsions of rebus (headers\message encoding)

### ISSUE THREAD

**Issue by dron231** [rebus-org/Rebus#601]
There is old system which is working with Rebus (version 0.78) and new one (with Rebus 3.1.2)
I need to handle message in the new service (which were send from old system)

The old Rebus version uses UTF7 encoding and messages inside the queue looks like (json, ASCII; without headers): 
+AHs-
  +ACIAJA-type+ACI-: +ACI-System.Object+AFsAXQ-, mscorlib+ACI-,
  +ACIAJA-values+ACI-: +AFs-
    +AHs-
      +ACIAJA-type+ACI-: +ACI-ServiceContracts.WorkPlanService.Messages.WorkPlanContractMessage, ServiceContracts+ACI-,
      +ACI-WorkPlanSource+ACI-: 0,
      +ACI-ExternalReference+ACI-: +ACI-eca0214c-f948-4271-b10d-da4df3cf2686+ACI-,
      +ACI-WorkPlanNumber+ACI-: +ACI-c7df78ae-d+ACI-,
      +ACI-SalaryNumber+ACI-: +ACI-734d8bb2-e+ACI-,
      +ACI-ControlCenter+ACI-: +ACI-178+ACI-,
      +ACI-IsActive+ACI-: true,
      +ACI-StartTime+ACI-: +ACI-2017-04-14T14:28:10.2272438+-03:00+ACI-,
      +ACI-EndTime+ACI-: +ACI-2017-04-14T22:28:10.2252448+-03:00+ACI-,
      +ACI-PreparednessStartTime+ACI-: null,
      +ACI-LowActivityPeriod+ACI-: 7,
      +ACI-PlanType+ACI-: +ACI-777+ACI-,
      +ACI-StationNumber+ACI-: +ACI-556+ACI-,
      +ACI-TeamNumber+ACI-: +ACI-AAA+ACI-,
      +ACI-VehicleNumber+ACI-: +ACI-059+ACI-,
      +ACI-AreaStationNumber+ACI-: +ACI-231+ACI-,
    +AH0-
  +AF0-
+AH0-

The new one uses UTF8 and message looks like(json, ASCII; without headers):
{
  "$type": "System.Object[], mscorlib",
  "$values": [
    {
      "$type": "WorkPlanService.Messages.WorkPlanContractMessage, ServiceContracts",
      "WorkPlanSource": 0,
      "ExternalReference": "eca0214c-f948-4271-b10d-da4df3cf2686",
      "WorkPlanNumber": "c7df78ae-d",
      "SalaryNumber": "734d8bb2-e",
      "ControlCenter": "178",
      "IsActive": true,
      "StartTime": "2017-04-14T14:28:10.2272438+03:00",
      "EndTime": "2017-04-14T22:28:10.2252448+03:00",
      "PreparednessStartTime": null,
      "LowActivityPeriod": 7,
      "PlanType": "777",
      "StationNumber": "556",
      "TeamNumber": "AAA",
      "VehicleNumber": "059",
      "AreaStationNumber": "231"
    }
  ]
}

in the MessageHandler (Rebus 3.1.2) I got the error:
An error occurred when attempting to receive the next message: System.Runtime.Serialization.SerializationException: Could not deserialize JSON text '+AHs-
  +ACI-rebus-correlation-id+ACI-: +ACI-720102c2-e50f-4766-8c2b-bd50becddab6+ACI-,
  +ACI-rebus-msg-id+ACI-: +ACI-1e19dd0f-1d0b-4eaf-aec9-91f2bceaa41f+ACI-,
  +ACI-rebus-content-type+ACI-: +ACI-text/json+ACI-,
  +ACI-rebus-encoding+ACI-: +ACI-utf-7+ACI-
+AH0-' ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: +. Path '', line 0, position 0.
.....

Could You please suggest me - what I should to do to be able to process messages from old system in the new one?

**Comment by mookid8000** [comment]
Rebus used to have a "legacy integration mode" whereby Rebus version >= 2 could use the old format for transport messages. This turned out to be troublesome in some cases though, and using it could introduce some funny behavior because it wasn't as simple as I originally though it was.

My suggestion in your case is to either

1. update Rebus versions, so that you're using Rebus >= 2 in all places, or
1. use the raw MSMQ api to manually create an adapter that functions as a proxy for your old Rebus endpoint

where (1) is definitely my personal favorite. 

If something is keeping you from upgrading your "old" endpoints to Rebus 2, feel free to ask for more information here – maybe I can give you a few hints of something seems hard.

**Comment by dron231** [comment]
Big thanks for Your comment.
I also prefer first approach.
