### ISSUE TITLE
MSMQ vs SQL Transport Recipient 

### ISSUE THREAD

**Issue by stevengopmo** [rebus-org/Rebus#602]
Hi,

We have a load balanced environment and we are using SQL Transport now instead of MSMQ.  For the Recipient do we still need to include @machinename as part of the recipient address or since we are now in SQL Server land does it actually matter?

**Comment by mookid8000** [comment]
It doesn't matter when you're using SQL Server 😄 it functions as a central broker, so queue names are global

**Comment by stevengopmo** [comment]
just to confirm, if I have a load balanced client (clientA & clientB) and clientA does a bus.Send, it will get the response and not have to contend with possibly clientB grabbing it because it was not addressed properly?

**Comment by mookid8000** [comment]
What do you mean exactly by "load-balanced client"?

**Comment by stevengopmo** [comment]
we have our web client on 2 different machines.  The website does a bus.Send to a windows server sitting on another machine.  The service does it's work then does a bus.Publish back to all listeners.

I guess stating it that way it probably doesn't matter as long as the service is doing Publish instead of Send.  It would only be a problem if it was doing Reply maybe?

**Comment by stevengopmo** [comment]
I think that the only thing is how will my 2 web clients be able to subscribe separately without the @machinename as part of their subscription?

**Comment by mookid8000** [comment]
> I think that the only thing is how will my 2 web clients be able to subscribe separately without the @machinename as part of their subscription?

If they use the same queue name it will change how your things work. If they are supposed to work as individual instances then they must use unique queue names. Funnily enough, a simple way to implement that (since they're on separate machines) is to qualify the queue name further by appending the machine's name 😁

**Comment by stevengopmo** [comment]
Thank you for your responses on this.  I had to do a bit of checking but in our case they (the servers) are functioning as one so we don't really have to give them unique names.  But I can see that changing sometime in the future (maybe) so it's good to know how we can do it.  Someday we'll also want to look at doing some distribution for the backend services but not today :)  thanks for your quick responses!

**Comment by mookid8000** [comment]
You're welcome 😄 good to hear you figured it out.
