### ISSUE TITLE
Outgoing message not dispatched

### ISSUE THREAD

**Issue by ShiroYacha** [rebus-org/Rebus#604]
Hi,
I have a question with rebus's dispatching mechanism. It seems that if I want to send a message (Send/Publish, etc.) via a worker thread (e.g. I am using a Timer here) inside a HandleMessage method, the message will not get sent. It seems to be related to issue #435 but my objective here is to really spawn a new thread or periodically use a timer to send new messages after receiving a message. Is my approach wrong to this objective?

Thanks!
Min

**Comment by mookid8000** [comment]
If you are starting a timer from a Rebus message handler, the ambient Rebus transaction context will flow to timer callbacks. When you `await bus.Send(yourMessage)` from the timer callback, the context will be picked up by Rebus, and it will enlist the send operation in it.

You can make this work by manually clearing the ambient transaction context on the timer callback, e.g. like this (e.g. using `System.Threading.Timer`):

    var timer = new System.Threading.Timer(interval);
    timer.Tick += (o, ea) => {
        // clear the context
        AmbientTransactionContext.SetCurrent(null);

        // do what you want to do in here:
        ...
    };
    timer.Start();

    // remember to dispose the timer some time later:
    timer.Dispose();

While this can fix your situation and make things work the expected way, I am curious as to what you want to achieve by starting a timer from a message handler – IMO it feels a little weird to do so.

**Comment by ShiroYacha** [comment]
Thanks for the quite response. I am currently exploring some scenarios with rebus. My case is that a worker will respond to a trigger (a message published on the bus) by emitting messages periodically (e.g. heart-beat or some signals).

**Comment by mookid8000** [comment]
If I were you, I would keep the Rebus handler and the timer separate.

The timer could be active all the time, and then it could just check some shared state on each timer tick, to see if it should publish heartbeats or not.

The message handler would then only need to toggle the shared state.

This would be a much improved design IMO.
