### ISSUE TITLE
Big Ooops in PROD

### ISSUE THREAD

**Issue by stevengopmo** [rebus-org/Rebus#607]
Hi,

It looks like we didn't do a good job of backwards testing when we upgraded from ~0.86 to the latest version of Rebus.  We use Raven for our Saga storage and it looks like how the sagas are stored is VERY different from the old way.  Is there anyway to capture when the saga was not found and then do something interesting like load the old one with Raven and transfer the data to a new one?

**Comment by mookid8000** [comment]
well.... maybe you could decorate `ISagaStorage` with an adapter, that tries to use the real saga storage, and then if that fails tries to load the saga data in the old format and convert it on the fly....

you can install a decorator like this:

    Configure.With(...)
        .(...)
        .Options(o => {
            o.Decorate<ISagaStorage>(c => {
                var sagaStorage = c.Get<ISagaStorage>();

                return new YourSagaStorageDecorator(sagaStorage);
            });
        })
        .Start();

where `YourSagaStorageDecorator` would then implement `ISagaStorage` in the way described above

**Comment by stevengopmo** [comment]
Thank you!  I'll work on it now.

**Comment by mookid8000** [comment]
I hope it works out for you!

Please remember to back up your data before getting creative with this 😄

**Comment by stevengopmo** [comment]
backup?  what's a backup?  https://techbeacon.com/sites/default/files/most_interesting_man_test_in_production_meme.jpg

**Comment by mookid8000** [comment]
![](http://i.imgur.com/b9YZl.gif)

**Comment by stevengopmo** [comment]
so I think the trick here is to override the Find method.  If not found by the default storage, try looking for it using mine.  But, how can I save it from there.  The Insert method requires IEnumerable<ISagaCorrelationProperty>.  What does that look like?  Is this just a collection of all my config.Correlate properties as defined in the Saga?

**Comment by mookid8000** [comment]
> But, how can I save it from there.

Just wait for the corresponding call to `Update`, and then update the document in a way that corrects the structure

> The Insert method requires IEnumerable. What does that look like?

The correlation properties are passed to you from the outside – it is not necessarily something you need to save, but you may need it if your particular saga storage needs to know beforehand which properties sagas might be queried by.

> Is this just a collection of all my config.Correlate properties as defined in the Saga?

Yes 😄

**Comment by stevengopmo** [comment]
let me say that back to you in my words.

Instead of calling insert in the Find method, I should just return an object from the Find that looks like the correct object.  Then the update method will take care of it automagically.

**Comment by mookid8000** [comment]
you will of course have to test it, but that is my guess

btw if you cannot make it work, I don't think it is too much work to simply fetch the source code of the 0.84.0 version of the saga persister and then adapt the code to work with Rebus 2

**Comment by stevengopmo** [comment]
not ready to give up yet, but where can I find the old code?

**Comment by mookid8000** [comment]
last "Rebus 1" version was [0.84.0](https://github.com/rebus-org/Rebus/releases/tag/0.84.0) – all the code is in the repository, including the RavenDB saga persister

**Comment by stevengopmo** [comment]
Success!  Thank you for your responses today.  We should be able to push this to PROD and solve our problem by end of day now.

**Comment by mookid8000** [comment]
Good to hear 😄 👍
