### ISSUE TITLE
Guidance on how to manually redirect failed second-level retries to error queue

### ISSUE THREAD

**Issue by dalager** [rebus-org/Rebus#608]
Framed as a question on SO: 
http://stackoverflow.com/questions/43760922/how-to-forward-a-message-with-exceptions-to-rebus-error-queue

(is this form of X-Posting considered bad form, btw? My apologies then and feel free to kill ;) )

**Comment by mookid8000** [comment]
no worries 😃 I answered your question [here](http://stackoverflow.com/a/43769002/6560)

**Comment by sbochoa** [comment]
Hi, what if I need to use the native ASB dead letter queue? currently after 3 scheduled retries I'm just throwing exceptions until MaxDeliveryCount is reached and it is automatically sent to the native ASB dead letter queue but is there a better way to do this? Thanks! 😃

**Comment by mookid8000** [comment]
Unfortunately Rebus does not provide a way out of the box to do anything but move the failed message to an ordinary queue.

Rebus is pretty extensible though, so it would definitely be possible to switch off its own error tracking and make it rely on Azure Service Bus' built-in tracking.
