### ISSUE TITLE
Missing Serilog Exception info on LogEvent

### ISSUE THREAD

**Issue by mclausen** [rebus-org/Rebus#610]
Hi Rebus Team

We're currently using Rebus together with Serilog. On top of that we are using an Application Insights sink, to help push logging telemtry to Application Insights.

Whenever an exception occur, we of course would like that to show up as an exception on our dashboards :). Unfortunatly, Rebus.Serilog does not always provide the exception along with the logging event explicitly.

So i have been tinkering a little...

1.
I've been working a bit on a PR which will extract the exceptions from the  params object[] objs signature in the ILog interface, and sending the exception  along with the log statement, but before submitting i wanted to hear your thoughts about this strategy? :) 

2.
In Rebus when handling the Poison error message, it would be extremely cool to be able to access the real exception being thrown. As of now, it seems like all the error messages that have been picked up doing 
retry, is getting flattened into a string. When logging with serilog, it would be nice to be able to send along the exception.

**Comment by mookid8000** [comment]
1) Can you even do that?

Isn't the problem that [this line](https://github.com/rebus-org/Rebus/blob/master/Rebus/Retry/PoisonQueues/PoisonQueueErrorHandler.cs#L64) logs all caught exceptions as a single `errorDetails` string?

2) Yeah well.... Rebus has all the `Exception` objects available at the time when the error is logged, so it should definitely do that. Logging multiple exceptions will require a change to the logger signature though, so it will be a Rebus 4 thing. I will think about this 😄

**Comment by mclausen** [comment]
For the first one i actually just added this method 
https://github.com/mclausen/Rebus.Serilog/blob/master/Rebus.Serilog/Serilog/SerilogLoggerFactory.cs#L97

And that allowed me to get back the exception on the LogEvent which i could use to forward exception telemtry, however I hesitated a bit to create the PR, just to see if you had any tricks up your sleeve 😄.

**Comment by mookid8000** [comment]
ah, great idea to simply wrap them in an `AggregateException` 😄 👍
