### ISSUE TITLE
Support for Azure Cosmos DB

### ISSUE THREAD

**Issue by runes83** [rebus-org/Rebus#613]
Would very much like to see support for Azure Cosmos DB AS Saga storage. 
I think this would be a very good match for running Rebus microservices in the cloud.

**Comment by mookid8000** [comment]
I would love to see that too 😉

**Comment by runes83** [comment]
We have an implementation that we could contribute, we are testing it a bit internally and get back to you on how to ow to publish after the summer vacation :-)

**Comment by mookid8000** [comment]
I'll close this issue for now – still looking forward to seeing the Cosmos DB saga storage 😄
