### ISSUE TITLE
remoting call in handler

### ISSUE THREAD

**Issue by joffreynorsys** [rebus-org/Rebus#621]
Hello,

I work on a project using rebus and .net remoting...
There is a error message when i try to call a remote method in a rebus handler : TransactionContext is not serializable. I think is due to AmbiantTransactionContext which set TransactionContext into CallContext (i'am on .net framework 4.6.1).

Could you help me ?

Thank you.

**Comment by mookid8000** [comment]
You need to "unmount" the ambient transaction context when you do stuff that requires marshaling the call context to another app domain:


    var context = AmbientTransactionContext.Current;
    try
    {
        // do remoting stuff
    }
    finally
    {
        AmbientTransactionContext.SetCurrent(context);
    }

**Comment by joffreynorsys** [comment]
I work only if clear the slot manually...

```csharp
            var context = AmbientTransactionContext.Current;
            CallContext.FreeNamedDataSlot("rebus2-current-transaction-context");
            try
            {
                return Processors[destination].Execute<TQuery, TResult>(query);
            }
            finally
            {
                AmbientTransactionContext.SetCurrent(context);
            }
```

Have you a more elegant solution ?

**Comment by mookid8000** [comment]
sorry, I must have been tired or something when I posted it – I forgot this line:

    AmbientTransactionContext.SetCurrent(null);

I have updated the code to include it

**Comment by joffreynorsys** [comment]
Ok thank you.

Rebus is a very great tools! continue!
