### ISSUE TITLE
Downgrade the Target Framework to a lower ".NET Standard" version whenever possible?

### ISSUE THREAD

**Issue by mirandaasm** [rebus-org/Rebus#622]
Hi there.

I've noticed that, when porting to .NET Core, you guys used the ".NET Standard v1.6" as the "default" Target Framework for all of your projects.

However, the higher the target framework version is, the less "compatible" the resulting package is. According to the MS recommendations, you should always try to target a lower version of the target framework whenever possible (ref: https://docs.microsoft.com/en-us/dotnet/standard/net-standard)

By taking a look at the "core" Rebus project, it seems it would be possible to target the ".NET Standard v1.3" at least (maybe even 1.0). By doing this, you would enable your package to be consumed by a lot more projects out there in the wild.

Quoting the relevant parts from the related link above:

> **Which .NET Standard version to target**
> 
> When choosing a .NET Standard version, you should consider this trade-off:
>     * The higher the version, the more APIs are available to you.
>     * The lower the version, the more platforms implement it.
> 
> In general, we recommend you to target the lowest version of .NET Standard possible. So, after you find the highest .NET Standard version you can target, follow these steps:
>     1. Target the next lower version of .NET Standard and build your project.
>     2. If your project builds successfully, repeat step 1. Otherwise, retarget to the next higher version and that's the version you should use.

**Comment by mookid8000** [comment]
That's an interesting idea! Ideally, it would target .NET Standard 1.0, killing several birds with one stone 🐦 ✝️

**Comment by mookid8000** [comment]
I succeeded in "downgrading" the target to .NET Standard 1.5, it only seemed to require that the `System.Threading.Thread` be referenced.

When I tried to de-bump to .NET Standard 1.4, I ran into a problem with `Assembly` suddenly not having a `GetTypes()` method.

Any idea how targets <= .NET Standard 1.4 figure out which types are in an assembly?

**Comment by stephenpope** [comment]
DefinedTypes ? https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.definedtypes?view=netstandard-1.4 (seems to be .NET Standard 1.0 compatible too).

The new API docs browser is super useful for awkward stuff like this  : https://docs.microsoft.com/en-us/dotnet/api/

**Comment by mirandaasm** [comment]
Hi there. Sorry the delay, I've been out of the office the whole day.

Yeah, DefinedTypes seems to be the way to go with .NET Standard 1.0-1.4, as pointed out by @stephenpope.

Not sure if this can help, but there's a SO thread that may be related to this topic: https://stackoverflow.com/questions/38443347/getting-all-types-that-implement-an-interface-in-net-core

I'll clone the Rebus repo and see what I can come up with.

**Comment by mirandaasm** [comment]
@mookid8000, sent you a PR #623 about this.

**Comment by mookid8000** [comment]
I merged it! Thank you @mirandaasm , you are awesome 👍

**Comment by mirandaasm** [comment]
Sweet bro! I am glad I was able to help. 👍
