### ISSUE TITLE
Error using Bus.defer when the message is on another queue

### ISSUE THREAD

**Issue by runes83** [rebus-org/Rebus#629]
Version: 3.1.5.0
Getting routing error when using Bus.Defer on message that are mapped/routed to another queue.

**Comment by mookid8000** [comment]
??? What does the error say?

**Comment by runes83** [comment]
I had to clear the error log do to this filling it up, but the error is that it cannot find handlers for the message of type.
I fixed it like this:

**Comment by mookid8000** [comment]
I looked at the code and realized that that is how `bus.Defer` works – it will alwaus send to the sender's own input queue, unless you set the `DeferredRecipient` to something else.

A simpler way of achieving what you want would be to

    var headers = new Dictionary<string, string> {
        {Headers.DeferredRecipient, "worker"}
    };

    await bus.Defer(delay, message, headers);

**Comment by mookid8000** [comment]
but this left me wondering whether `bus.Defer` should look up an endpoint mapping (like `bus.Send` does), and then a new `bus.DeferLocal` could work like `bus.SendLocal` and always defer the message with the sender's input queue as the destination.

**Comment by runes83** [comment]
I think that is a good idea, Bus.Defer should use the routing like all other messages. It is not obvious that it do not do that.

**Comment by mookid8000** [comment]
it's done in 4.0.0-b18 which is on nuget.org now

thanks for helping me clear this up 😄
