### ISSUE TITLE
Getting Saga data error when not using sagas

### ISSUE THREAD

**Issue by runes83** [rebus-org/Rebus#631]
Version: 3.1.5.0
I'm getting a lot of errors about sagas in my logs:

Rebus.Exceptions.ConcurrencyException: Update of saga with ID 0a4dc4e6-63f2-4a81-a572-639afe4124d6 did not succeed because someone else beat us to it
   at Rebus.Persistence.SqlServer.SqlServerSagaStorage.<Update>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Sagas.LoadSagaDataStep.<SaveSagaData>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Rebus.Sagas.LoadSagaDataStep.<SaveSagaData>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Rebus.Sagas.LoadSagaDataStep.<Process>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Receive.ActivateHandlersStep.<Process>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Retry.Simple.FailedMessageWrapperStep.<Process>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.<Process>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Encryption.DecryptMessagesIncomingStep.<Process>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Retry.Simple.SimpleRetryStrategyStep.<DispatchWithTrackerIdentifier>d__7.MoveNext()

But I have not used saga or even set it up in my worker, the last line indicates something about SimpleRetry and I do use IHandleMessages<IFailed<T>> could this be trying to load sagas in some way?

**Comment by mookid8000** [comment]
That sounds weird......

If [this predicate](https://github.com/rebus-org/Rebus/blob/master/Rebus/Sagas/LoadSagaDataStep.cs#L65) works and [this getter](https://github.com/rebus-org/Rebus/blob/master/Rebus/Pipeline/Receive/HandlerInvoker.cs#L117) works I cannot see why anything saga-like can happen.

Can you maybe show me some code or reproduce it somehow in an isolated project?

**Comment by runes83** [comment]
I'll see if I'm able to share the code that creates this, would the handler + the Rebus setup code be ok?

I've started noticing this, when we started using Serilog and Seq the other week.

**Comment by runes83** [comment]
The setup code:

```c#
private static IBus ConfigureBus(IContainer container)
        {
            string queueAddress = "queue1";
            string internalQueueAddress = "queue2";
            int numberOfWorkes = 5;
#if DEBUG
            queueAddress = Environment.MachineName + queueAddress;
            internalQueueAddress = Environment.MachineName + "-" + internalQueueAddress;
            numberOfWorkes = 1;
#endif
            var adapter = new AutofacContainerAdapter(container);
            var bus = Configure.With(adapter)
                      .Logging(l => l.Serilog(logger))
                    .Transport(t => t.UseAzureServiceBus(AppSettingsReader.ServicebusConnectionString,internalQueueAddress))
                    .Routing(r => r.TypeBased()
                            .MapAssemblyOf<Namespace.AccountService.Models.Internal.RebusCommands.HeartBeatCommand>(queueAddress)
                            .MapAssemblyOf<Namespace.Commands.HeartBeatCommand>(internalQueueAddress)
                        )
                        
                      .Options(o =>
                      {
                          o.SimpleRetryStrategy(secondLevelRetriesEnabled: true, maxDeliveryAttempts: 5,errorQueueAddress: internalQueueAddress+"-error");
                          o.EnableCompression(
#if DEBUG
                        1024 * 150
#endif
                        );
#if !DEBUG
                    o.EnableEncryption(AppSettingsReader.RebusEncryption);                    
#endif
                    o.SetNumberOfWorkers(numberOfWorkes);
                    o.SetMaxParallelism(numberOfWorkes*2);
                    if (AppSettingsReader.Debug)
                              o.LogPipeline(true);
                      })
                    .Start();

#if DEBUG
            Code.Extensions.RunSync(()=> bus.Send(new HeartBeatCommand("scheduler-heartbeat")));
#endif

   
            return bus;
        }
```

Handler code
```c#
 public class FixMissingInvoiceApiCallCommandHandler : IHandleMessages<FixMissingInvoiceApiCallCommand>
    {
        public ISessionDataBase SessionDataBase { get; set; }
        public IBus Bus { get; set; }

        public ITransactionClient TransactionService { get; set; }


        public async Task Handle(FixMissingInvoiceApiCallCommand message)
        {
            List<Task> tasks=new List<Task>();
            List<TransactionModel> transactions = new List<TransactionModel>()
            
            var list = await SessionDataBase.GetLogItemsNotInvoicedForApiRequest(100);
            int listCount = list.Count();
            Log.Logger?.Information("Started FixMissingInvoiceApiCallCommand with {listCount} to process", listCount);

            foreach (identificationlog item in list)
            {
                transactions.Add(new TransactionModel()
                {
                    //code
                });
            }

            var response = await //Sevice call
            
            response.Body.ForEach(x =>
            {
                tasks.Add(Bus.SendLocal(new SaveInvoiceApiCallTransactionRefCommand()
                {
                 //Code
                }));
            });

            if (tasks.Any())
                await Task.WhenAll(tasks);

            
        }
    }
```

Serilog tag:
SourceContext: Rebus.Retry.ErrorTracking.InMemErrorTracker

Have removed som namespacing and internal code

**Comment by runes83** [comment]
It would also be very convenient if the MessageHandler name could be included in the error message/stack.

**Comment by mookid8000** [comment]
Hmmm.... the fact that

1. you have not configured the SQL Server saga storage by going `.Sagas(s => s.StoreInSqlServer(...))`, and
1. you are aggregating your logs into Seq

tells me that the logs must come from somewhere else.... 

Could you maybe go through your setup and verify that you are not accidentally mixing logs from different endpoints?

When I use Serilog and log aggregation myself, I always ensure that the logger passed to Rebus is qualified with something that lets me differentiate between endpoints later – with Serilog you do that like this:

```csharp
var baseLogger = Log.Logger; //< or wherever you store your base logger
var endpointLogger = baseLogger.ForContext("queue", "my-input-queue");

Configure.With(...)
    .Logging(l => l.Serilog(endpointLogger))
    .(...)
```

which means you can then filter your logs by `queue='my-input-queue'` and be sure to see what happened on that particular queue.

**Comment by runes83** [comment]
Hello @mookid8000 I will double check my logs if that not another service have logged into this  service. I'll get back to you on the mater.

**Comment by mookid8000** [comment]
Any news on this?

**Comment by mookid8000** [comment]
I am pretty eager to release Rebus 4, but I would like to get this issue fixed before I release it.

Did you find out if your logs got mixed in your aggregator?

**Comment by mookid8000** [comment]
🏏 s

**Comment by mookid8000** [comment]
(that was a rebus, btw.)

**Comment by mookid8000** [comment]
🤣

**Comment by mookid8000** [comment]
well..... I'm closing this issue now – please don't hesitate to get back to me if you still believe this is an issue

**Comment by runes83** [comment]
This could be a log bleeding between services, this issued could be closed. Sorry bothering :-)

**Comment by mookid8000** [comment]
No problem – good you figured it out 👍
