### ISSUE TITLE
Messages Validation

### ISSUE THREAD

**Issue by Rajivhost** [rebus-org/Rebus#634]
How can I for example integrate FluentValidation if I want to validate some messages before they dispatched to the appropriated handlers?

**Comment by mookid8000** [comment]
When Rebus handles an incoming message, it gets passed through a pipeline of processing steps.

You can get an overview of which processing steps are active, both for the incoming and outgoing pipelines, but [outputting their contents to the log](https://github.com/rebus-org/Rebus/wiki/Log-message-pipelines).

In your case, I would insert a new incoming pipeline step (i.e. an implementation of `IIncomingStep`) right before the `DispatchIncomingMessageStep`, which then calls your validator with the message body.

The Rebus codebase has quite a few examples on how additional pipeline steps can be inserted into either pipeline, so I suggest you go look at that for inspiration 😄 

Thanks for using Rebus 👍

**Comment by Rajivhost** [comment]
Ok, Maybe it's would be great to have an extension lib for that concerns.
