### ISSUE TITLE
TransactionScope and Azure ServiceBus throws

### ISSUE THREAD

**Issue by KasperGrondahlChristensenVisma** [rebus-org/Rebus#635]
When using Rebus with Azure ServiceBus as backend, and using TransactionScope for transactions, publishing to the bus will throw `System.InvalidOperationException : Local transactions are not supported with other resource managers/DTC.` This seems to be due to Azure ServiceBus detecting that there's an ongoing transaction, and then throwing because it doesn't support enrolling in the transaction.

The RabbitMQ backend seems to just ignore the transaction.

The problem is reproducible like this:
```
using System;
using System.Configuration;
using System.Data.SqlClient;
using System.Threading.Tasks;
using System.Transactions;
using NUnit.Framework;
using Rebus.Activation;
using Rebus.Config;

namespace Tests.Rebus
{
    public class RebusTransactionTest
    {
        private static readonly string SqlConnectionString = ConfigurationManager.ConnectionStrings["Main"].ConnectionString;
        private static readonly string AzureConnectionString = <Azure SB conn string here>;

        private class TestMessage
        {
            public string Name { get; set; }
            public Guid Value { get; set; }

            public override string ToString()
            {
                return $"Name: {Name}  Value: {Value}";
            }
        }
       
        [Test]
        public async Task Should_send_within_transaction_scope()
        {
            // arrange            
            var activator = new BuiltinHandlerActivator();
            var bus = Configure.With(activator)
                .Logging(e => e.None())
                .Transport(t => t.UseAzureServiceBusAsOneWayClient(AzureConnectionString))
                .Start();

            using (var tran = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                // enforce SQL transaction
                using (var con = new SqlConnection(SqlConnectionString))
                {
                    con.Open();
                    var cmd = con.CreateCommand();
                    cmd.CommandText = @"select 1";
                    cmd.ExecuteNonQuery();
                }

                var message = new TestMessage() {Name = "TransactionScopeTest", Value = Guid.NewGuid()};

                // act
                await bus.Publish(message);                                                     
                      
                tran.Complete();
            }
        }        
    }
}
```
The above will throw the mentioned exception when publishing to the bus.

It's possible to suppress the transaction and get the above test to pass, by wrapping the publishing like this:
```
Task task;
//Suppress transactions for writing to the bus, otherwise Azure ServiceBus will throw an exception since it doesn't support transactions
using (var t = new TransactionScope(TransactionScopeOption.Suppress))
{
    task = bus.Publish(message);
}
await task.ConfigureAwait(false); //await task after transaction scope is disposed, otherwise dispose of the scope can fail, if it's done on another thread
```

By doing this, the message will be published, without enrolling in the transaction, like is the case for RabbitMQ.

Maybe the Rebus library could support this "transaction ignoring" when working with Azure ServiceBus?

**Comment by mookid8000** [comment]
bummer dude!

Which version of Rebus.AzureServiceBus are you using?

It should be fairly easy to make the transport suppress the transaction scope when it's time to send the outgoing messages. I can publish a prerelease package with this change so you can try it out – would you be interested in doing that?

**Comment by KasperGrondahlChristensenVisma** [comment]
Sorry for the delayed reply.

We are currently using Rebus.AzureServiceBus version 3.0.0, and are definitely interested in running our test with a fixed prerelease.

**Comment by mookid8000** [comment]
No problem 😄 

I have released 3.0.1-b1 with automatic suppression of ambient transactions throughout.

Please note that the package now targets .NET 4.5.1 because `TransactionScope` in .NET 4.5 is broken when used with async stuff.

**Comment by KasperGrondahlChristensenVisma** [comment]
Thank you for that. 

I have now upgraded our solution to Rebus.AzureServiceBus 3.0.1-b1 and removed my own "workaround" - and all tests are passing, so this looks great!

**Comment by mookid8000** [comment]
good to hear! I'll leave you running with it for a while, and then I will do a real 3.0.1 release when you tell me to 😄

**Comment by mookid8000** [comment]
How is it going with this one? Things still working for you?

**Comment by KasperGrondahlChristensenVisma** [comment]
We haven't put this into production, so I have no further information as of now.
