### ISSUE TITLE
Breaking change In release 4?

### ISSUE THREAD

**Issue by vdecristofaro** [rebus-org/Rebus#636]
I am experiencing a very strange behaviour after having updated Rebus to version 4.0.1 from 3.1.5.
The problem is deeply described on [this](https://stackoverflow.com/questions/45886811/rebus-with-simple-injector-breaking-change) StackOverflow question.

I can copy/paste it here for reference if needed.

Any help?

**Comment by mookid8000** [comment]
I am gonna close this one now 😄 

(because it was not a problem with Rebus, it more an issue with Rebus.SimpleInjector ... the details are described [in this StackOverflow answer](https://stackoverflow.com/a/45927755/6560))
