### ISSUE TITLE
MessageDeferredToSelf<TMessage> should inherit MessageDeferredToSelf

### ISSUE THREAD

**Issue by ggeurts** [rebus-org/Rebus#637]
The MessageDeferredToSelf<TMessage> class currently inherits from MessageDeferred class instead of MessageDeferredToSelf class, causing an InvalidCastException on calls to FakeBus.DeferLocal.

**Comment by mookid8000** [comment]
good catch 😄 I'll fix it in a few hours

**Comment by ggeurts** [comment]
Super! That saves me the hassle of a private build and pack cycle.

**Comment by mookid8000** [comment]
it's fixed in 4.1.0-b04

sorry about the prerelease, it's going to have to wait for a little bit more testing before I let it into the wild
