### ISSUE TITLE
Reply message creates duplicate records in the SQL DB Tables

### ISSUE THREAD

**Issue by MikeMiles** [rebus-org/Rebus#638]
Hi 
How can I stop duplicate records from being created whenever I use the bus Reply functionlity with a SQL Database.
If I drop the Send Local then the data is not save to the SQL Database
Regards,
Mike
PS Code snippet may help - or show what I have done wrong :-)

```csharp
using (BuiltinHandlerActivator adapter = new BuiltinHandlerActivator())
{
    IBus localBus = ConfigureReplyAdapter(queueName, adapter);
    jobToSet.MarkedAsComplete = true;
    adapter.Handle<Job>(async (bus, request) =>
        {
            if (request.JobNumber == jobToSet.JobNumber)
                await bus.Reply(jobToSet);
        })
        .Handle<Job>((bus, context, reply) =>
        {
            receivedMessage.Set();
            return null;
        });

    localBus.SendLocal(jobToSet);
    receivedMessage.WaitOrDie(TimeSpan.FromSeconds(30));

}
```

**Comment by mookid8000** [comment]
What do you mean by "duplicate records"?

It seems like your reply is also a `Job` – the code you posted here will execute the first handler method for the `Job` request as well as the `Job` reply. That's probably not what you want 😄 

Usually, when using request/reply, you will use separate types for requests and replies respectively.

E.g. for `Job` you may want to create a corresponding `JobReceipt`, which you then reply back to the sender.
