### ISSUE TITLE
Possible to control the topic names?

### ISSUE THREAD

**Issue by jmenziessmith** [rebus-org/Rebus#639]
Hi, from what I have seen looking at the code, topic names are based on the fully qualified name of the event class being published.

Is there a way to control / override the topic names generated by Rebus? In particular, for Azure Service Bus

Thanks

**Comment by jmenziessmith** [comment]
Just found this with the recommendation to use extension methods, so closing :)

https://github.com/rebus-org/Rebus.AzureServiceBus/issues/4

**Comment by mookid8000** [comment]
👍
