### ISSUE TITLE
Problem with publish

### ISSUE THREAD

**Issue by joffreynorsys** [rebus-org/Rebus#640]
Hello,

I have a message handler which do async work and finish by publish message in the bus.

The problem : when i configure the bus to handle message synchronously (worker = 1, max parallelism= 1), the publish is fast ( < 5 ms). But when i configure the bus with parralelism (worker = 2, max parralelism = 20), the publish is very slow ( 5 seconds) after a time and create a blocking point for handlers. All handlers are waiting for publish. 

After some seconds, publishing is done and the process continue...

So to conclude, the process is faster with worker =1 and max parallelism=1 than with worker = 2 and max parallelism= 20...

Do i a mistake in parallelism configuration ?

Thank you.

EDIT : 
If i use some instance of rebus (whith worker = 1 and max parallelism = 1) rather one instance with parallelism, there is no problem, publish is fast ( < 5 ms).

**Comment by mookid8000** [comment]
That sounds pretty weird. If you can reproduce it (e.g. in a simple console application), please send it to me and then I will debug it for you.

**Comment by mookid8000** [comment]
Sorry, didn't mean to close it 😄

**Comment by joffreynorsys** [comment]
I have difficulties to reproduce the problem. 

But in find the problem call. My super simplified code : 

```csharp
 public class CommandHandler : IHandleMessages<Command1>
    {
        private IBus _bus;
        public CommandHandler(IBus bus)
        {
            _bus = bus;
        }
        public async Task Handle(Command1 message)
        {

            //When i remove this call (an old assembly which execute 62 synchronous requests)
            //the publish work fine
            Work();
            //Thread.Sleep(200);

            Event e = new Event();
          
            Stopwatch sw = new Stopwatch();
            sw.Start();
            await _bus.Publish(e);
            sw.Stop();
            Console.WriteLine(DateTime.Now.ToString("hh:mm:ss.fff") + " publish duration : " + sw.Elapsed.TotalMilliseconds);
        }
    }
```

So when i remove the "work" call the publish work fine. The call execute 62 synchronous sql request in sqlserver... The duration of this call is less than 200ms

To reproduce, i try to replace work by Thread.sleep(200) or task.delay(200) but it work fine. It's may be cause by I/O operation ? So it may be my rebus configuration is wrong...

I also try to call work with await (`await Task.Run(() => Work())`) but it's the same thing...

**Comment by joffreynorsys** [comment]
Oh ! I repoduce the problem by coding a `lock` surrounding `Thread.Sleep`. it explain all...
So, i think,  in this configuration, workers = 1 and max parallelism = 1 is better

**Comment by joffreynorsys** [comment]
I confirm the lock problem in the old assembly, When i remove the lock it work fine.
You can close this issue...

just another question : Rebus.TransactionScope 3.0 seems not comptatible with Rebus 4, When do you plan to publish to nuget the Rebus.TransactionScope 4?

**Comment by mookid8000** [comment]
> just another question : Rebus.TransactionScope 3.0 seems not comptatible with Rebus 4, When do you plan to publish to nuget the Rebus.TransactionScope 4?

Look [here](https://www.nuget.org/packages/Rebus.TransactionScopes/)
