### ISSUE TITLE
Could not load type Rebus.Transport.DefaultTransactionContextScope

### ISSUE THREAD

**Issue by summerson1985** [rebus-org/Rebus#643]
Hi!

Having upgraded to Rebus 4.0.1 I started getting the following error:

Could not load type 'Rebus.Transport.DefaultTransactionContextScope' from assembly 'Rebus, Version=4.0.1.0, Culture=neutral, PublicKeyToken=null'.
   at Rebus.TransactionScopes.TransactionScopeExtensions.EnlistRebus(TransactionScope transactionScope)

We are using Rebus.TransactionScopes and create transaction and then enlist as per below:

```
using (var scope = new TransactionScope(TransactionScopeOption.Required, TransactionScopeAsyncFlowOption.Enabled) {
 scope.EnlistRebus(); // <-- this is throwing
}
```

There are no more nuget updates related to Rebus and it seems the issue is related to Rebus.TransactionScopes is still version 3:
![nuget](https://user-images.githubusercontent.com/21013156/30925381-f70e4e40-a3b1-11e7-98a6-cb9de15eceaa.png)

Please advise on this

**Comment by summerson1985** [comment]
And I just noticed that the issue might potentially be fixed by adding this library: https://www.nuget.org/packages/Rebus.TransactionScopes/
Seems like there has bedn a name change to plural: TransactionScopes

**Comment by dariogriffo** [comment]
Please look at 
https://www.nuget.org/packages/Rebus.TransactionScopes/
v4.0.0 is available

**Comment by summerson1985** [comment]
Indeed removing Rebus.TransactionScope v3.0.0 and adding Rebus.TransactionScope**s** v4.0.0 solved an issue.
Thanks Dario!

**Comment by mookid8000** [comment]
damn – don't know what happened about the pluralization there..... 🤔
