### ISSUE TITLE
High CPU usage on Idle when MaxDegreeOfParallelism is high

### ISSUE THREAD

**Issue by AlasdairStarkSMS** [rebus-org/Rebus#646]
My CPU has 4 cores and I have the number of workers set to 4. My application is a TCP server that publishes messages to an SQS queue when a device connects. So when no devices are connecting the application is in an idle state, listening for TCP clients.

If I run my application with a maximum parallelism of 4 then my idle CPU utilization peaks at about 1%.

If I change the maximum parallelism to 256 then my idle CPU utilization peaks at about 18%.

If I change the maximum parallelism to 2048 then my idle CPU utilization peaks at about 80%.

There are no devices connecting to my application so it is not publishing any messages. Why does this setting increase the idle CPU usage?

I need a high degree of parallelism as the application is publishing hundreds of messages to an SQS queue per second. I ran these tests on my local machine but the situation is even worse in the production environment. My application is deployed to ECS using burst instances so CPU credits are being used up while no devices are connecting.

Edit: I'm using version 4.0.1.0 in a .NET Core application.

**Comment by mookid8000** [comment]
The "max parallelism" setting configures how many parallel RECEIVE operations you can have, at most.

Since the Amazon SQS driver has full `async` support in its receive API, having a max parallelism of 2048 then means that 2048 parallel receive operations will be initiated by Rebus.

It's too much. Turn it down.

😆

**Comment by mookid8000** [comment]
You can read more about it here: https://github.com/rebus-org/Rebus/wiki/Workers-and-parallelism

**Comment by mookid8000** [comment]
Oh, and just to be super-clear about this: The max parallelism setting does in NO WAY influence how many asynchronous outbound operations you can perform – e.g. if you

    await Task.WhenAll(Enumerable.Range(0, int.MaxValue)
        .Select(n => bus.Send($"THIS IS MESSAGE NUMBER {n")));

then you will have a pretty high number of parallel outbound operations going on.

**Comment by AlasdairStarkSMS** [comment]
Thanks for the information. Our application doesn't receive messages at all and the subscriptions are passed in through an environment variable so I don't think it's using the input queue at all.

Could you just clarify whether or not number of workers has any influence on sending messages?

We started adjusting the max parallelism setting because the our send timeout of 6000ms was being reached when we load tested the server with around 20 connections per second. Every connection publishes a message. This is realistic for the expected load in the production environment. When we turned it up we no longer saw the timeouts. From you explanation it sounds like it must have been a coincidence but we're sure that we didn't change anything else - the whole deployment is automated.

**Comment by mookid8000** [comment]
> Thanks for the information. Our application doesn't receive messages at all and the subscriptions are passed in through an environment variable so I don't think it's using the input queue at all.

What matters, then, is whether your Rebus endpoint is a one-way client (i.e. a client that does not have an input queue and is not capable of receiving messages) or an ordinary endpoint.

You configure this aspect via the `.Transport(...)` configurer like so:

```csharp
Configure.With(...)
    .Transport(t => t.UseAmazonSQS(..., "name-of-queue"))
    .(...)
```

for an ordinary endpoint that received messages from the `name-of-queue` queue, and

```csharp
Configure.With(...)
    .Transport(t => t.UseAmazonSQSAsOneWayClient(...))
    .(...)
```

for a one-way client that is only capable of sending messages (or publishing messages if you have configured a centralized subscription storage).

> Could you just clarify whether or not number of workers has any influence on sending messages?

It has no influence.
