### ISSUE TITLE
Custom logger is broken in Rebus 4.1.0

### ISSUE THREAD

**Issue by chathurilanchana** [rebus-org/Rebus#653]
Hi,
I have a custom logger for rebus configured as below. This worked fine with Rebus 3.1.5. But now when I change the version to 4.1.5, I receive some misformatted messages that I can't use String.Format. One of such message is "Starting periodic task {taskDescription} with interval {timerInterval}". The correct format for this message should be "Starting periodic task {0} with interval {1}". I wonder whether this is because of a mistake. (There are some messages with the correct format, but once in a while I receive badly formatted messages like the one I mentioned above.)

    public class RebusLogger : IRebusLoggerFactory
    {
        private readonly ILog _log;
        public RebusLogger(ILog log)
        {
            _log = log;
        }
        public ILog GetCurrentClassLogger()
        {
            return _log;
        }

        public ILog GetLogger<T>()
        {
            return _log;
        }
    }

    public class OurLoggerBridge: ILog
    {
        private readonly ILogger _logger;

        public OurLoggerBridge(ILogger logger)
        {
            _logger = logger;
        }

        public void Debug(string message, params object[] objs)
        {
            var formattedString = String.Format(message, objs);
            _logger.Debug(formattedString);
        }

        public void Info(string message, params object[] objs)
        {
            var formattedString = String.Format(message, objs);
            _logger.Info(formattedString);
        }

        public void Warn(string message, params object[] objs)
        {
            var formattedString = String.Format(message, objs);
            _logger.Warn(formattedString);
        }

        public void Error(System.Exception exception, string message, params object[] objs)
        {
            var formattedString = String.Format(message, objs);
            _logger.Error(exception.Message);
        }

        public void Error(string message, params object[] objs)
        {
            var formattedString = String.Format(message, objs);
            _logger.Error(formattedString);
        }
    }

**Comment by mookid8000** [comment]
It's because Rebus 4 has a primitive implementation of [structure logging](https://www.google.dk/search?q=structured+logging&oq=structured+logging&aqs=chrome..69i57j0l5.2269j0j7&sourceid=chrome&ie=UTF-8), providing more meaningful names to logged values via string interpolation.

If the logging library then supports it (e.g. like the immensely awesome [Serilog](https://serilog.net/)), logged values can then have their names preserved, allowing for later inspecting e.g. by filtering, aggregating, etc.

In your case, you should derive your class from Rebus' [`AbstractRebusLoggerFactory`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Logging/AbstractRebusLoggerFactory.cs) and then call its [`RenderString`](https://github.com/rebus-org/Rebus/blob/2619856dd979c50008546c29977b609471b21f00/Rebus/Logging/AbstractRebusLoggerFactory.cs#L25-L60) method in all places instead of `string.Format(...)`.

**Comment by mookid8000** [comment]
> There are some messages with the correct format (....)

If you encounter format strings with `{0}`, `{1}`, etc., please let me know – all numbered placeholders should have been replaced by named placeholders by now... 😃

**Comment by chathurilanchana** [comment]
I see below  messages for the info log when I start the bus which is not in structure format.
 "Initializing RabbitMQ connection manager for transport with input queue '{0}"
"Successfully initialized consumer for {0}"

And thank you very much for the explanation!

**Comment by mookid8000** [comment]
Looks great 😄 there's only this small thing:

    public void Warn(System.Exception exception, string message, params object[] objs)
    {
        _logger.Warn(exception.ToString());
    }

    public void Error(System.Exception exception, string message, params object[] objs)
    {
        _logger.Error(exception.ToString());
    }

In these cases you're logging the exception only, but the `message` + `objs` might contain valuable and helpful information. Therefore I suggest you change it to something like

    var text = RenderString(message, objs);
    _logger.Warn($"{text}: {exception}");

to have both things included. If your logging library has support for including the exception without turning it into a string, you should of course use that instead.

**Comment by chathurilanchana** [comment]
Thank you very much!
