### ISSUE TITLE
TypeNameHandling.All or TypeNameHandling.Objects is required for the correct message dispatch to handlers

### ISSUE THREAD

**Issue by rsivanov** [rebus-org/Rebus#655]
Why couldn't we use the value from rbs2-msg-type header to determine the correct message type instead of relying only on complete type information from the message body itself. We could get much more compact messages if we used TypeNameHandling.None.

**Comment by mookid8000** [comment]
We could *definitely* do that – I actually thought it was doing that, but apparently I was wrong.

**Comment by mookid8000** [comment]
This will be fixed in 4.2.0
