### ISSUE TITLE
Question: How to use and modify correlation ids when using Pub/sub messaging.

### ISSUE THREAD

**Issue by alexdrl** [rebus-org/Rebus#656]
We are succesfully using pub/sub messaging using rebus and rabbitmq. How can we access or modify correlation ids in a pub/sub environment? We need to enter thee Sagas?

We are trying to emulate that with pipeline steps, but another question that arrives is how can we create the pipeline steps using DI, because we store a "CorrelationTokenStore" in dependency injection.

**Comment by mookid8000** [comment]
> How can we access or modify correlation ids in a pub/sub environment? We need to enter thee Sagas?

I'm sorry, but I am not sure I understand the question? Do you want to modify the correlation IDs passed as headers with each message?

> how can we create the pipeline steps using DI

Simple answer: You can't. Everything is wired up during startup, meaning that Rebus does not "resolve" anything besides message handlers at runtime.

What you _could_ do was to provide a pipeline step that simply gets the container injected, and then resolve the correlation token store.

**Comment by alexdrl** [comment]
> I'm sorry, but I am not sure I understand the question? Do you want to modify the correlation IDs passed as headers with each message?
Yes, we want to add a custom correlation id when sending multiple messagea with the publish and subscribe methods.

> What you could do was to provide a pipeline step that simply gets the container injected, and then resolve the correlation token store.
How can we do that? Has the IResolutionContext.Get<T> method capability to retrieve the IServiceProvider instance?

**Comment by mookid8000** [comment]
> How can we do that? Has the IResolutionContext.Get method capability to retrieve the IServiceProvider instance?

No – you would have to "inject" it simply by passing the container reference to your configuration method, e.g. like so:
```csharp
.Options(o => {
    o.AutomaticallySetCorrelationIdFromCorrelationTokenStore(container);
})
```
where `AutomaticallySetCorrelationIdFromCorrelationTokenStore` could then look somewhat like this:
```csharp
public static class ConfigEx
{
    public static void AutomaticallySetCorrelationIdFromCorrelationTokenStore(this OptionsConfigurer configurer, YourContainer container)
    {
        configurer.Decorate<IPipeline>(c => {
            var pipeline = c.Get<IPipeline>();
            var step = new YourCorrelationIdStep(container);
            return new PipelineStepInjector(pipeline)
                .OnSend(step, PipelineRelativePosition.Before, typeof(AssignDefaultHeadersStep));
        })
    }
}
```
and `YourCorrelationIdStep` would then figure out which correlation to set on each outgoing message.

**Comment by alexdrl** [comment]
> No – you would have to "inject" it simply by passing the container reference to your configuration method, e.g. like so:

But if I pass the ServicesCollection like that, the container instance will not be the same as the application instance, right?

> Yes, we want to add a custom correlation id when sending multiple messagea with the publish and subscribe methods.

So this is not possible?

**Comment by mookid8000** [comment]
Oh, sorry – I forgot how ServiceProvider works – you need to use the `AddRebus` overload that gives your callback two arguments, like this:
```csharp
serviceCollection.AddRebus((configure, provider) => configure
    .Logging(l => l.Console(minLevel: LogLevel.Debug))
    .Transport(t => t.UseInMemoryTransport(new InMemNetwork(), "ioc-text"))
    .Options(o => o.AutomaticallySetCorrelationIdFromCorrelationTokenStore(provider)));
```
meaning that you are then free to look up stuff using the passed-in `provider` instance.
