### ISSUE TITLE
Decoralate bus starting to registration in IOC Container

### ISSUE THREAD

**Issue by joffreynorsys** [rebus-org/Rebus#661]
Hello,

Today when bus starting, there are regstrations in IOC Container. It's cause some difficulties if we need to resolve some instances before starting bus... (specialy with SimpleInjector)

The idea could be to have all registrations in the Configure method (with IBus instance but not started) and to have a Start method on IBus instance.

What do you think about this ?

**Comment by mookid8000** [comment]
I think the solution would be to change the Rebus+SimpleInjector API to be more like the one from Rebus+Autofac, which looks like this:
```csharp
var builder = new ContainerBuilder();

builder.RegisterRebus((configurer, context) => configurer
    .Logging(l => l.Serilog())
    .Transport(t => t.UseRabbitMq(...))
    .Options(o => {
        o.SetNumberOfWorkers(2);
        o.SetMaxParallelism(30);
    }));

// the bus is registered now, but it has not been started.... make all your other registrations, and then:
var container = builder.Build(); //< start the bus

// now your application is running



// ALWAYS do this when your application shuts down:
container.Dispose();
```
Do you think something like this could be made with SimpleInjector?

The `Start` method should NOT be moved to `IBus` because it does not make sense to call it more than once.

**Comment by joffreynorsys** [comment]
The problem is to resolve instance for executing something before starting bus (by doing this, i know there is a risk to resolve a not starting `IBus`...)
SimpleInjector not allow registering after resolving and i think is a good thing.

What do you think about a `Prepare()` method on `RebusConfigurer` which make work of `Start()` method but not call `startAction` et return `void`. This method register `IBus` in ContainerAdapter with a delegate (factory) and a singleton lifetime.

Rebus start on the first `RebusConfigurer.Start()` or  `IBus` resolving from container. 

If rebus already started when `Start()` is called then it return the started instance. The same thing if rebus is already started on the first resolving.

The difficulty  with this solution is may be the delegate compatibility with other DI tools...

**Comment by mookid8000** [comment]
Hmm.... I have to think some more about this.

For now, you can delay the actual start of the bus to later by doing this:

```csharp
var bus = Configure.With(...)
    .Transport(t = t.(...))
    .Options(o => {
        o.SetNumberOfWorkers(0);
    })
    .Start();

// bus can send messages and subscribe/unsubscribe
// now, but it has not started receiving anything

// when you feel like it, start processing messages
// like so:
bus.Advanced.Workers.SetNumberOfWorkers(1);
```

**Comment by joffreynorsys** [comment]
Ok thanks for the tips!
