### ISSUE TITLE
Provide a way to automatically forward events from FakeSyncBus to FakeBus

### ISSUE THREAD

**Issue by oliverhanappi** [rebus-org/Rebus#662]
When testing code, a unit test should not need to know whether the code under test uses the async or sync version of the bus for publishing messages etc. However, the current fake implementations FakeBus and FakeSyncBus record events separately. Due to this fact refactorings may break tests in unobvious ways because using either the sync or async version of the bus should be equivalent.

It would be very useful if a FakeSyncBus would be able to automatically (and optionally?) forward its recorded events to a FakeBus.

**Comment by mookid8000** [comment]
You are absolutely right 😄 

I am beginning to think that maybe 

* Rebus 5 should not contain testing helpers in the core DLL
* Testing helpers like `FakeBus`, `FakeSyncBus`, `SagaFixture`, etc. should be moved to a new `Rebus.Testing` NuGet package (which can then move faster and more independently of the Rebus core package)
* Maybe the current `FakeBus` and `FakeSyncBus` should instead be replace by one full `FakeBus` implementation, also recording events for e.g. calls to `bus.Advanced.Workers.SetNumberOfWorkers(...)` etc.

What do you think?

**Comment by oliverhanappi** [comment]
I think that a full FakeBus implementation, which records all "logical" events regardless of the used api is a good idea. It should really not matter that much, e.g., with which api a message has been published.

I also think that it is a good idea to record all kinds of events, even when there are probably not that many uses where calls like `calls to bus.Advanced.Workers.SetNumberOfWorkers(...)` are tested against. But it would be definitely consistent 😉

As our application evolved, we thought that it was a little bit cumbersome to setup the FakeBus because you need to opt-in for each part of the api separately. First, we created the FakeBus independently in each test fixture, but recently we centralized that into a factory.

I also like the idea of a separate, faster moving NuGet package for testing helpers 😃

**Comment by mookid8000** [comment]
Rebus 5.0.0-b01 is out now. Stuff previously residing in the `Rebus.Testing` namespace has now been moved to a new NuGet package: Rebus.TestHelpers, which is also out now.

It would be cool if you would try it out 😄
