### ISSUE TITLE
Async await problems in SendOutgoingMessageStep with some transports

### ISSUE THREAD

**Issue by dtabuenc** [rebus-org/Rebus#665]
I discovered this project today and am impressed with how clean and readable the codebase is. I'm evaluating using this in a project where we want to use PostgreSql for the transport. While testing publishing a message to multiple endpoints, I ran into a "A command is already in progress" error from postgres.

I've tracked the problem down to this bit of code in the SendOutgoingMessageStep:

```cs
async Task Send(List<string> destinationAddressesList, TransportMessage transportMessage, ITransactionContext currentTransactionContext)
{
    var sendTasks = destinationAddressesList
          .Select(async address => await _transport.Send(address, transportMessage, currentTransactionContext).ConfigureAwait(false))
           .ToArray();
     await Task.WhenAll(sendTasks).ConfigureAwait(false);
 }
```

The issue here is that the sends to all the destinations are done in parallel, but certain transports such as the postgres  can not support this (since the same connection would be used concurrently from different threads).

Is this parallel behavior on purpose? Is there any way we can make this configurable so for some transports will execute the sends in a simple non-parallel for loop?

As an aside, the performance of then `Send` method can be improved by removing the unecessary `async` keyword from both the method, and the lambda in the select:

```cs
Task Send(List<string> destinationAddressesList, TransportMessage transportMessage, ITransactionContext currentTransactionContext)
{
    var sendTasks = destinationAddressesList
          .Select(address => _transport.Send(address, transportMessage, currentTransactionContext))
          .ToArray();
   
    return Task.WhenAll(sendTasks)
}
```

This code is completely equivalent in function to the async/await code above, but avoids the generation of the async state machine by the compiler. In general, I always avoid async if the only thing being awaited is the last line of the method/lambda since the await can simply be replaced with a return in that case.

**Comment by mookid8000** [comment]
Thanks 🙂 

As this particular concurrency issue is specific for Postgres, I would prefer to fix it by serializing access to the `NpgsqlConnection` object in the Postgres transport. 

Rebus has an `AsyncBottleneck` (an async semaphore in disguise), which could probably be included in the transaction context along with the connection, and then be used to avoid concurrently accessing the connection object.

I also suspect this is a problem with the SQL Server transport as well.

**Comment by mookid8000** [comment]
Good find btw 👍

**Comment by mookid8000** [comment]
Oh, and regarding the use of compiler-supported `async` stuff – I once rewrote most of Rebus' incoming message processing steps to avoid the state machine and directly return `Task` objects wherever possibly, but it actually turned out to negatively impact the dispatch performance.

As this was clearly against my intuition about these things, I just rolled back the change... 😐 and then I thought to myself: "I guess the compiler-generated state machine must be pretty efficient, even though it is not pretty in IL or decompiled methods." (*)

I didn't approach it in any scientific kind of way though, so my results might have been skewed by other factors. 

---
(*) I do not actually think this way. I usually think in Danish, so the exact wording is probably quite different.

**Comment by dtabuenc** [comment]
`AsyncBottleneck` approach would be perfect. Would you like a pull request on that? 

As for the `async` stuff, I would be really curious as to why it might have been slower. I can accept that the state machine code is efficient enough that the difference in performance might not be so significant, but cannot imagine how it could possibly be slower since the state machine is just additional code  wrapping your own code. Plus, there's the capturing/restoring of the execution context that has to happen, even though the execution context will not be used at all (since there's no code beyond the await). Anyways, no big deal on that (probably a very minor optimization anyways). I was just curious.

**Comment by mookid8000** [comment]
> Would you like a pull request on that?

That would be awesome 👍 

> As for the async stuff, I would be really curious as to why it might have been slower. I can accept that the state machine code is efficient enough that the difference in performance might not be so significant, but cannot imagine how it could possibly be slower since the state machine is just additional code wrapping your own code. Plus, there's the capturing/restoring of the execution context that has to happen, even though the execution context will not be used at all (since there's no code beyond the await). Anyways, no big deal on that (probably a very minor optimization anyways). I was just curious.

I feel the same way 😁

**Comment by mookid8000** [comment]
Fixed by rebus-org/Rebus.Postgresql#8 – thanks for reporting it and fixing it 😄
