### ISSUE TITLE
4.2.0 breaks assembly references

### ISSUE THREAD

**Issue by lkt82** [rebus-org/Rebus#668]
Hi versioned 4.2.0 is versioned as 1.0.0.0 at the assembly level ! this breaks all other libraries reference it. Like Rebus.Autofac that references 4.1.0.0

**Comment by mookid8000** [comment]
damn!! why did I not catch that???

sorry, will publish a fix asap

**Comment by mookid8000** [comment]
I have no idea how that happened – I have published 4.2.1 now, and I have verified that the contained Rebus.dll has the correct version.

Thanks for reporting it 👍

**Comment by lkt82** [comment]
No props . thanks :)
