### ISSUE TITLE
How to correlation sagas on an "optional" field?

### ISSUE THREAD

**Issue by MrMDavidson** [rebus-org/Rebus#677]
The scenario I'm describing is a made up, replica, of our actual issue so I apologies if it sounds a little contrived and with arbitrary restrictions.

Imagine you have a situation where a customer wants to withdraw funds from their account. When this happens you require the customer to authorise the withdrawal. And if the customer's account is a joint account, the other party to the account also has to authorise the request. Perfect for a saga, right?

```C#
public class WithdrawalApprovalSagaData : SagaData {
  //... other fields here...

  public Guid WithdrawalId { get; set; }
  public Guid PrimaryWithdrawalRequestId { get; set; }
  public bool WaitingForPrimaryApproval { get; set; }
  public Guid SecondaryWithdrawalRequestId { get; set; }
  public bool WaitingForSecondaryApproval { get; set; }
}

public class BeginWithdrawalProcess {
  public Guid WithdrawalId { get; set; }
}

public class WithdrawalApproved {
  public Guid WithdrawalRequestId {get; set; }
}
```

You've then got your saga...

```C#
public class WithdrawalSaga<WithdrawalSagaData> : IAmInitiatedBy<BeginWithdrawalProcess>, IHandleMessages<WithdrawalApproved> {

  protected override void CorrelateMessages(ICorrelationConfig<WithdrawalApprovalSagaData> config) {
    config.Correlate<BeginWithdrawalProcess>(m => m.WithdrawalId, d => d.WithdrawalId);

    // Correlate approvals to their requests
    config.Correlate<WithdrawlApproved>(m => m.WithdrawalRequestId, d => d.PrimaryWithdrawalRequestId);
    config.Correlate<WithdrawlApproved>(m => m.WithdrawalRequestId, d => d.SecondaryWithdrawalRequestId);
  }

  public Task Handle(BeginWithdrawalProcess message) {
    if (IsNew == false) return Task.FromResult(false);

    Data.WithdrawalId = message.WithdrawalId;

    var account = GetAccountForWithdrawal(message.WithdrawalId);
    // Create the request and store the identifier for it
    Data.PrimaryWithdrawalRequestId = CreateApprovalRequest(account.PrimaryCustomerId);
    Data.WaitingForPrimaryApproval = true;
    if (account.Type == AccountType.Joint) {
      Data.SecondaryWithdrawalRequestId = CreateApprovalRequest(account.SecondaryCustomerId)
      Data.WaitingForSecondaryApproval = true;
    }

    return Task.FromResult(false);
  }

  public Task Handle(WithdrawalApproved message) {
    if (message.WithdrawalRequestId == Data.PrimaryWithdrawalRequestId) {
      Data.WaitingForPrimaryApproval = false;
    }
    if (message.WithdrawalRequestId == Data.SecondaryWithdrawalRequestId ) {
      Data.WaitingForSecondaryApproval = false;
    }

    if ((Data.WaitingForPrimaryApproval == false) && (Data.WaitingForSecondaryApproval == false)) {
      ReleaseFunds(Data.WithdrawalId);
      MarkAsComplete();
    }

    return Task.FromResult(false);
  }
}
```

I know, it's a little contrived 😄. But the idea is that we start some saga and based on what the saga is operating on we fire off some actions that we don't know until we start the saga. Once the saga starts we wait for some events and then finally complete the saga. Cool, standard stuff. 

We're using `SqlServerSagaStorage` and I found an old Github issue (which I can no longer find) where someone has this same issue, you proposed a fix, but then reverted it because it was inconsistent with other storage mechanisms.

If you were to run this saga for a joint account, everything would be fine. If you checked the `RebusSagaIndex` table you'd have a some data like;

| saga_type      | key                           | value    | saga_id  |
|----------------|-------------------------------|----------|----------|
| WithdrawalSaga | WithdrawalId                  | 64611bc0 | bd50b0ed |
| WithdrawalSaga | PrimaryWithdrawalRequestId    | 4b579f35 | bd50b0ed |
| WithdrawalSaga | SecondaryWithdrawalRequestId | cbb67317 | bd50b0ed |

Now if you ran this same saga for an individual account you'd end up with data such as...

| saga_type      | key                           | value    | saga_id  |
|----------------|-------------------------------|----------|----------|
| WithdrawalSaga | WithdrawalId                  | 51611bc0 | ff50b0ed |
| WithdrawalSaga | PrimaryWithdrawalRequestId    | 33579f35 | ff50b0ed |
| WithdrawalSaga | SecondaryWithdrawalRequestId | 00000000 | ff50b0ed |

And again everything would be fine. However if two people, from different individual accounts, tried to withdraw funds at the same time... it would break. Horribly. If you looked at the table (between transactions...) you'd see data something like...

| saga_type      | key                           | value    | saga_id  |
|----------------|-------------------------------|----------|----------|
| WithdrawalSaga | WithdrawalId                  | 81611bc0 | ef50b0ed |
| WithdrawalSaga | PrimaryWithdrawalRequestId    | 73579f35 | ef50b0ed |
| WithdrawalSaga | SecondaryWidthdrawalRequestId | 00000000 | ef50b0ed |
| WithdrawalSaga | WithdrawalId                  | 31611bc0 | bb50b0ed |
| WithdrawalSaga | PrimaryWithdrawalRequestId    | 13579f35 | bb50b0ed |
| WithdrawalSaga | SecondaryWithdrawalRequestId | 00000000 | bb50b0ed |

However the `SqlServerSagaStorage` has a primary key on `saga_type`, `key`, `value` so the second saga `WithdrawalSaga` to be created will violate this (it also has `SecondaryWithdrawalRequestId` as an empty GUID). Ideally `SecondaryWithdrawalRequestId` would be a nullable GUID and the constraint would exclude nulls but Rebus only supports simple types. In this scenario the other ideal fix would be that the `WithdrawalApproved ` would have the `WithdrawalId` on it and I'd correlate on that... this is all a bit contrived but this is a legacy system I'm dealing with and it doesn't know about the `WithdrawalId` so it can't be changed to make that change. But I can definitely see this situation occurring; where you need to correlate on a (secondary) field... but only some times. 

My actual work around in this scenario is to assign `Guid.NewGuid()` to `SecondaryWithdrawalRequestId` 
when it isn't a joint account and set an additional flag, `IsFakeSecondaryWithdrawalRequestId`. But it feels like a kludge I'm having to do at the application level for an infrastructural issue. Additionally this is a very easy bug to let slip into production. Even with proper unit tests because you'd be testing your saga not your saga serialisation.

Note: This issue would apply regardless of the data type. I'm lucky here in that we use GUIDs for identifiers so I know I can generate a relatively unique placeholder value.

**Comment by mookid8000** [comment]
You are right that this solution can lead to some potentially pretty nasty situations.

Similar nastiness can arise if you change the value of an existing correlation property.

I usually stay away from doing anything similar to this, i.e. I almost always model my things so I have one single constant correlation property, which is also different from the saga data ID, because that one cannot be predicted.

This kind of issue is pretty hard to solve in a consistent manner across all saga persisters. At some point, I considered introducing a constraint that would prevent correlation properties from being changed after the fact.

My only worry with that, is that I have sometimes suggested people to use a changing correlation property to correlate timeouts, this way providing a way to "detach" the saga from a timeout in order to effectively disable it.

Any thoughts?

**Comment by MrMDavidson** [comment]
Whilst I agree things are much simpler if you're able to have all systems actively participate in the saga and take on some kind of identifier... it's not always possible. I've come across several scenarios where a non-participating event occurs (ie. Something not explicitly requested by the saga) but that is definitely of interest to the saga.

There's always going to be a work around; in this scenario I could extend my `WithdrawalRequest` table to include the `WithdrawalId` (this is the problem with a contrived example... I'd obviously /have/ this identifier on the table in the real world already) and then if I couldn't extend the system publishing `WithdrawalApproved` messages I could have an intermediary system which listens for `WithdrawalApproved`, looks up the `WithdrawalId` somehow associated with it, and then publishes a new message (Eg. `WithdrawalRequestForWithdrawalApproved`) which has that identifier included.

You've rightly tagged the issue as a question; it really was just "Is there a way to do this in a easy manner?" I would definitely argue against preventing correlation identifiers from changing. I wonder if making the correlation identifiers special / changing their value more intentional would help? Be it a call to something like `base.CorrelationChanged<Data, Msg>(d => d.Property, m => m.Property)` or perhaps similar to the `MarkAsComplete()`, `MarkAsUnchanged()` there could be `MarkAsCorrelationModified()` or whatever? That said, whilst helpful in codifying the developers intent it doesn't help the default / null value in the primary key of the `SqlSagaStorage`.

**Comment by mookid8000** [comment]
> I could have an intermediary system which listens for `WithdrawalApproved`, looks up the `WithdrawalId` somehow associated with it, and then publishes a new message (Eg. `WithdrawalRequestForWithdrawalApproved`) which has that identifier included

You could even use the same message and attach the found withdrawal ID to the message in the form of a header, and then you can use the header value to look up the saga:
```csharp
protected override void CorrelateMessages(ICorrelationConfig<MySagaData> config)
{
    config.CorrelateHeader<WithdrawalRequest>("withdrawal-id", d => d.WithdrawalId);
    // (...)
}
```
Now, having suggested this, I even think you could insert a pipeline step before `LoadSagaDataStep`, which would look up the ID and add it to the headers collection.

It's a pretty good idea about the correlation property thing, actually – it would make saga updates much faster if it didn't have to potentially update its entire index on every revision, and it would greatly reduce the risk of locking issues in the index table.

I'm closing this one for now 😄 thanks @MrMDavidson for bringing up this interesting discussion 👍

**Comment by mookid8000** [comment]
Sorry btw for being so slow to reply 😅
