### ISSUE TITLE
Consider adding the ability to "Start" the bus without starting message processing

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#678]
Usually the bus is configured like this:
```csharp
Configure.With(...)
    .(...)
    .Start();
```
(or something like
```csharp
container.RegisterRebus(configure => configure(...))
```
when using the ASP.NET Core container or Autofac)

Both immediately start the bus – when `Start()` is called or when the container gets built, respectively.

It would be neat to provide a generic mechanism which would allow for doing something like this:

```csharp
var starter = Configure.With(...)
    .(...)
    .Create();

// time goes by

var bus = starter.Start();
```

and then some analogous mechanism for the register-/build-type of containers.

**Comment by zabulus** [comment]
Isn't this is an RRR problem?

**Comment by mookid8000** [comment]
> Isn't this is an RRR problem?

Sometimes it is, and sometimes it isn't 😄 

I don't care how people (mis)treat their IoC containers, but this is a feature that has been requested a couple of times, and I sometimes implement this myself by "starting" the bus with 0 workers:
```csharp
var bus = Configure.With(...)
    .(...)
    .Options(o => {
        o.SetNumberOfWorkers(0);
    })
    .Start()

// do other things

// start the bus 4real
bus.Advanced.Workers.SetNumberOfWorkers(1);
```
which is what I usually suggest people do when they ask for this feature.

It would be nice to provide a more discoverable implementation of that feature, though.

**Comment by mookid8000** [comment]
Will be out in Rebus 5.0.0-b03 in a few minutes
