### ISSUE TITLE
QUESTION: Anyone have any luck using LightInject for registering handlers?

### ISSUE THREAD

**Issue by replaysMike** [rebus-org/Rebus#681]
I'm attempting to switch from StructureMap to LightInject for performance reasons, but I'm struggling with auto registering handlers. Works fine if I manually register each message type and handler as such:

`container.Register<IHandleMessages<MyMessage>, MyHandler>();`

but when attempting to auto-register all handlers in an assembly, the handlers can't be found:

`container.RegisterAssembly(typeof(HandlerBase).Assembly, (s, Type) => Type.GetInterfaces().Contains(typeof(IHandleMessages<>)));
`

It seems like it can't automatically register a concrete class for the type and I can't find any LightInject specific way of accomplishing this. Anyone else ever try?

**Comment by mookid8000** [comment]
I'll close it because I assume someone who knows his/her way around LightInject can answer it [here](https://stackoverflow.com/questions/48780797/using-lightinject-to-register-all-classes-that-implement-a-generic-interface)
