### ISSUE TITLE
Understanding message ownership

### ISSUE THREAD

**Issue by replaysMike** [rebus-org/Rebus#682]
Just when I thought I understood Rebus routing principals I through myself for a loop today when configuring a simple client/server setup where a single client fires off messages to X number of consumers watching the queue - simple horizontal scaling. My goal was to route each message type to it's own queue while doing this, and after doing all my reading I realized that you can't setup a single container capable of receiving messages from more than 1 queue, I need to create and configure separate containers for each queue I want to listen to. My confusion about this (and seemingly a few others) was around the syntax of specifying message ownership on the server/consumer.

Client/Producer:
```
Configure.With(adapter)
    .Transport(t => t.UseMsmq("input-queue"))
    .Routing(r => r.TypeBased()
    .Map<CreateOrderMessage>("output-queue1")
    .Map<CancelOrderMessage>("output-queue2"))
    .Start();
```
X Server/Consumer(s):
```
Configure.With(adapter)
    .Logging(l => l.NLog())
    .Transport(t => t.UseMsmq("output-queue1"))
    .Routing(r => r.TypeBased())
    .Map<IHandleMessages<CreateOrderMessage>>("create-order-message"));
    // configure another container to listen to output-queue2
```

My confusion was mostly caused by my misunderstanding of this syntax: `.Map<IHandleMessages<CreateOrderMessage>>("create-order-message"));`

I thought originally on the server side this would tell the server to listen for this message type on queue "create-order-message" but that instead defines message ownership (and I'm not sure what that designates despite the docs). Additionally, that line seemed to be completely irrelevant as it will pick up any message on the "output-queue1" with a registered handler for that message. So what exactly does that Map<> line signify in a simple messaging setup like this?

**Comment by mookid8000** [comment]
It's pretty simple, actually 😄 (but I realize everything is simple once you understand it)

First, I suggest you rename your queues – using "output" as part of a queue name sort of indicates that the queue has an outwards direction, but _all queues are input queues_ (at least in the queue model that Rebus employs), which means that behind each queue there will be a Rebus endpoint, which will process messages sent to that queue.

---

Then I suggest you go and read [this part](https://github.com/rebus-org/Rebus/wiki/Routing#so-how-does-rebus-make-use-of-the-endpoint-mapping-in-different-scenarios) of [the Routing documentation](https://github.com/rebus-org/Rebus/wiki/Routing), which I just added 😉 I realized that the question "how does Rebus actually use the endpoint mappings?" was not properly answered anywhere, so I added that.

Let me know if it's still unclear 😄

**Comment by replaysMike** [comment]
I bet it is, and I appreciate the tips :) It's just the explanation of it isn't entirely clear. The new addition to the docs is definitely appreciated, but I am still unclear on the topic of queue ownership.

In the above, the `.Map<IHandleMessages<CreateOrderMessage>>("create-order-message"));` method takes in a destinationAddress. Is this actually a queue name? What is confusing is because the Msmq takes in an inputQueue, but I can define additional addresses in the Map statements. On the client side the inputQueue seems to be what I would receive replies on and would send messages using the destinationAddress queue. On the server side it would be listening on the queue defined for each message type and is provided in `UseMsmq(queueName)`. But if that is the case, I really don't need to utilize Map<> on the server side since I can only watch messages on a single queue, or am I misundestanding still?

**Comment by replaysMike** [comment]
It occurred to me that maybe my terminology could be at fault here too, please forgive my inability to absorb the concepts ;) Perhaps a sample makes more sense.

Client:
```
var bus = Configure.With(adapter)
    .Transport(t => t.UseMsmq("txe-clientinput"))
    .Routing(r => r.TypeBased()
        .Map<CreateOrderMessage>("create-order-message")
        .Map<CancelOrderMessage>("cancel-order-message"))
    .Start();
```

Server/Container:
```
var adapter = new LightInjectContainerAdapter(container1);
var bus = Configure.With(adapter)
    .Logging(l => l.NLog())
    .Transport(t => t.UseMsmq("create-order-message"))
    .Routing(r => r.TypeBased());
    .Start();
```

Server/Container 2:
```
var adapter = new LightInjectContainerAdapter(container2);
var bus = Configure.With(adapter)
    .Logging(l => l.NLog())
    .Transport(t => t.UseMsmq("cancel-order-message"))
    .Routing(r => r.TypeBased())
    .Start();
```

Does this seem sane?

**Comment by mookid8000** [comment]
Yes it looks sane :)

The two server processes don't need `.Routing(r => r.TypeBased()` though, because they're not going to route anything – it doesn't harm anything, it's just unecessary.
