### ISSUE TITLE
Transaction Precisions

### ISSUE THREAD

**Issue by joffreynorsys** [rebus-org/Rebus#685]
Hello,

Could you give me some precisions on transactions ?
I read the wiki and see  in "Automatic retries and error handling"

```
Configure.With(...)
    .Options(b => b.HandleMessagesInsideTransactionScope())
    .(...)
```
for create an ambiant transaction for each message handle

But i also see in "Transaction" /  " I am in a Rebus message handler "

"In this special case, Rebus will create a queue transaction which will surround the entire processing of the message. " => I anderstand wthere is a transaction concept without any configuration...

What is the difference between these two concept ? There is a timeout processing for the second ?

Note : i use sql server transport.

Thank you.

**Comment by mookid8000** [comment]
Rebus has its own transaction around everything – it's also "ambient", so you can access it from anywhere within the call hierarchy of a Rebus message handler via

    var context = AmbientTransactionContext.Current;

if you wanted to inspect it.

It's there, so Rebus can pick it up and enlist actions in it, e.g. when you call 

    await bus.Publish(yourEvent);

from deep within the call hierarchy.

The ability to surround Rebus handler invocation with a `System.Transactions.TransactionScope` (by calling the `HandleMessagesInsideTransactionScope` configuration extension from Rebus.TransactionScopes) is just there as a convenience, if you want to use stuff that can enlist itself in an ongoing ambient .NET transaction.

As such, the ability to automatically manage a `TransactioneScope` does not change anything at all in Rebus.

I hope that explains is 😄
