### ISSUE TITLE
Question : Is there a way to save context data in a handler between retries ?

### ISSUE THREAD

**Issue by IsaacSee** [rebus-org/Rebus#686]
Hi, I am trying to figure out how to save contextual data to be reused in case of retr/error (with an handler). I tried to update headers but it looks like they are not saved on the end of the processus.
I would like to avoid to Send/Defer the message on error by myself since the default retryHandler is working perfectly.

Am i missing something ?

Thanks in advance.

**Comment by mookid8000** [comment]
You are not missing anything, and unfortunately no: There's no built-in way to save any state between retries.

Rebus uses an in-mem dictionary of message IDs to track deliveries between retries. If your system does not break if the data gets lost from time to time (e.g. when restarting your application), then that could be a viable strategy.

If you need something more persistent, I suggest you take a look at Rebus' sagas – you could check out the [Coordinating stuff that happens over time](https://github.com/rebus-org/Rebus/wiki/Coordinating-stuff-that-happens-over-time) page on the wiki, if you need a place to start.
