### ISSUE TITLE
Error tracking does not work if a handler takes more than 10 minutes

### ISSUE THREAD

**Issue by poizan42** [rebus-org/Rebus#688]
The InMemErrorTracker has the "CleanupTrackedErrors" task which is hardcoded to clean up tracked errors after 10 minutes. This does not work so well if you have tasks that takes more than 10 minutes to complete, in which case an error will just make it keep being processed again and again.

**Comment by mookid8000** [comment]
yeah well – I guess I never thought that it would be relevant to track errors for longer than that 😄 but I don't see any reason why this should not be configurable, so I'll see if I can do that for Rebus 5

**Comment by mookid8000** [comment]
Rebus 5.0.0-b05 has a configurable max age on the error trackings.

It can be configured like this:

```csharp
Configure.With(...)
    .(...)
    .Options(o => {
        o.SimpleRetryStrategy(errorTrackingMaxAgeMinutes: 20);
    })
    .Start();
```

to configure the max age to 20 minutes.

Thanks for reporting this issue 👍

**Comment by poizan42** [comment]
@mookid8000 Thanks for the quick fix!

However I'm wondering if this is really the best solution. Why is it necessary to periodically clean them up? Shouldn't CleanUp always be called when processing a message is done?

The big problem with this is that it fails the "principle of least surprise". You can have a handler that works fine when you are testing it, for example where it is running a task with a timeout. So you test it with a short timeout and everything seems to works, and you won't think to try with a timeout longer than 10 minutes because there's no particular reason to think that this setting exists, so you never hit a problem before it goes into production.

**Comment by mookid8000** [comment]
> Why is it necessary to periodically clean them up? Shouldn't CleanUp always be called when processing a message is done?

It is necessary, because it should be possible to consume messages from the same queue (["competing consumers"](http://www.enterpriseintegrationpatterns.com/patterns/messaging/CompetingConsumers.html)) from two different processes, most likely on two separate machines – and in that case, it would be a terrible memory leak, if processes would "remember" their error trackings for too long after their messages had been successfully consumed by another process.

**Comment by poizan42** [comment]
But if you do that then the InMemErrorTracker for any of the processes wouldn't be able to track all the errors. I would have assumed that something called InMem was not supposed to work with multiple processes listening to the same queue.
