### ISSUE TITLE
SimpleRetryStrategy clears items saved on IncomingStepContext

### ISSUE THREAD

**Issue by dankennedy** [rebus-org/Rebus#694]
I'm not sure if this is an issue or the way that I'm using things but we use the SimpleRetryStrategy to handle transient failures which attempt message handling 3 times. We also implement the 2 events BeforeMessageHandled and AfterMessageHandled to build a Serilog logger with some items in context i.e. message type, message id, and I load it from within the handler i.e. context.Save(log) and MessageContext.Current.IncomingStepContext.Load<ILogger>().  On the first receipt of a message everything is fine but if an exception occurs and it retries then the items saved to IncomingStepContext are no longer there. Presumably a new context is created without those items. As the event is not "re-fired" though I don't get chance to re-populate them. 

Am I doing something obvious that's incorrect or should I look to create a PR to transfer the saved items to the new context on retry?

Any advice much appreciated.

Thanks

**Comment by mookid8000** [comment]
When a message is retried, it is a completely new delivery attempt. This means that no state is carried over, except for the tracking by message ID (done by the "simple retry strategy") of the number of times this particular endpoint has tried to consume the message.

Therefore, `BeforeMessageHandled` should simply be raised once for each delivery attempt. It's not clear to me whether you are actually experiencing this, but hopefully you are 😄 

Please let me know if this is not what you are seeing.

**Comment by mookid8000** [comment]
As I've always said: Who cares about problems that come and go, as long as they end up going. 😝

`</kidding>`

But seriously, it sounds weird that the before-hook was not invoked on each delivery attempt – are you absolutely sure? Could there be some other reason why those callbacks could somehow go unnoticed?

**Comment by dankennedy** [comment]
He he, I totally agree. I can't see how it might have been missed/unnoticed, but as you quite rightly say, if it isn't broken now, just walk away 🤣 

Thanks again
