### ISSUE TITLE
BeforeTransportMessage hook?

### ISSUE THREAD

**Issue by larsw** [rebus-org/Rebus#696]
Hi,

There's a reference to a ```BeforeTransportMessage``` hook on the Correlation ID wiki page,
but I can't find it when I search through the code. Is it deprecated, or do I need to look other places?

**Comment by mookid8000** [comment]
ah, sorry - that was a Rebus 1 leftover 😄 

The "new" way of doing that would be to either [insert a step into the incoming messages pipeline](https://github.com/rebus-org/Rebus/wiki/Incoming-messages-pipeline), or leverage [`Rebus.Events`](https://github.com/rebus-org/Rebus.Events) for a convenient callback-based approach.

I have updated the wiki page accordingly.
