### ISSUE TITLE
Cannot configure RabbitMQ connection heartbeat 

### ISSUE THREAD

**Issue by dmitrynovik** [rebus-org/Rebus#697]
I need to configure RabbitMQ connection heartbeat as described here: https://www.rabbitmq.com/heartbeats.html

// set the heartbeat timeout to 60 seconds
cf.RequestedHeartbeat = 60;

However, because Rebus effectively hides RabbitMQ connection factory inside its internal ConnectionManager, I cannot find the way to do it.

**Comment by dmitrynovik** [comment]
It is probably an issue for Rebus.RabbitMq project

**Comment by mookid8000** [comment]
Exactly 😄 

[Here's a link](https://github.com/rebus-org/Rebus.RabbitMq/issues/24) for anyone who ends up here some time in the future.
