### ISSUE TITLE
When a message cannot be dispatched to any handlers, the retry mechanism tries 5 times, while it can fail right away

### ISSUE THREAD

**Issue by boyanio** [rebus-org/Rebus#704]
When a message is received but cannot be dispatched to any handlers, the retry mechanism tries 5 times. Is it really necessary? With the fail-fast option, it can just fail right away.

**Comment by mookid8000** [comment]
You are absolutely right 😄

**Comment by mookid8000** [comment]
From 5.0.0-b12 and on, there's a `IFailFastException` marker interface, which may be put on exceptions to have them fail fast (at least by default – it doesn't happen if the `IFailFastChecker` has been replaced with something that doesn't respect that marker interface).

Moreover, messages that cannot be dispatched to any handlers now result in Rebus throwing a `MessageCouldNotBeDispatchedToAnyHandlersException` (which is derived from the previous `RebusApplicationException`, thus not breaking any exception handlers), and this exception happens to carry to `IFailFastException` marker.

Conclusion: From 5.0.0-b12 Rebus will only attempt to dispatch messages once if it can't find any handlers for them.

Thanks for your suggestion 😄

**Comment by boyanio** [comment]
Great! I was thinking exactly the same scenario :)

**Comment by mookid8000** [comment]
Great minds think alike 💭 

(...though fools seldom differ 😁 )
