### ISSUE TITLE
Contribution: Rebus.Consul

### ISSUE THREAD

**Issue by larsw** [rebus-org/Rebus#705]
Hi @mookid8000,

Just for kicks, I've whipped together a preliminary version of a Consul-backed subscription storage for Rebus.

It is available here: https://github.com/larsw/Rebus.Consul

If it works out alright, do you want it under the rebus-org umbrella?

**Comment by mookid8000** [comment]
Closing this one btw because the Rebus.Consul repo is ready 😄
