### ISSUE TITLE
How to keep log flow in a rebus based sulution

### ISSUE THREAD

**Issue by tresoldigiorgio** [rebus-org/Rebus#706]
I use massively rebus to let different processes communicate with each other, but I need to maintain a continuous flow of logs by macro operation. A possible way is to use an operationId that have to be send in every bus message of the entire operation flow. 
Example:
1. Button click on UI
2. Log the button click with operationId 1
3. Message send to bus with operationId 1
4. Process 2 handle the message and do other operations
5. Process 2 Log the operations result with operationId 1
6. Message send to bus with operationId 1
7. Process 3 handle the message and do other operations
8. Process 3 Log the operations result with operationId 1

When i need the log for the button click i can search all log with operation id = 1 and i found all the log.
I hope I've been exhaustive.

Any other suggestion???

Thanks!
Giorgio

**Comment by mookid8000** [comment]
Rebus has a builtin mechanism for this: [CorrelationIDs](https://github.com/rebus-org/Rebus/wiki/Correlation-ids).

Correlation IDs default to carry the message ID of the initiating message, but if you set it yourself to some value, Rebus will not overwrite it.
