### ISSUE TITLE
NATS integration

### ISSUE THREAD

**Issue by xxsybreedxx** [rebus-org/Rebus#707]
Hi, just discovered this project, looks very interesting, the only question that I have, is it possible to integrate it with NATS (www.nats.io) somehow?

**Comment by mookid8000** [comment]
I have no experience with NATS whatsoever, but judging from the code examples shown [on the C# driver's GitHub page](https://github.com/nats-io/csharp-nats), it should be fairly straightforward.

The trick would be to map Rebus' fairly high level concepts to the most appropriate implementations in NATS, relying on native implementations as much as possible.

Do you have any experience with NATS?

**Comment by mookid8000** [comment]
(closing this issue btw – we can still keep chatting in here)
