### ISSUE TITLE
deferred message in future

### ISSUE THREAD

**Issue by mvanhelmont** [rebus-org/Rebus#708]
I am using azure storage queue as transport and like to defer message for 1 month (to send a followup mail to customer). I know of the limitation of azure storage with is 7 days. But i what to know if it's possible to defer a message longer? 

When i defer a message for more than 7 days i don't get any exception but my queue stays 0 of 0 messages

**Comment by mookid8000** [comment]
I was not aware of that limitation. 

I would expect Azure Storage Queues to return an error (something like a HTTP 400 Bad Request or something) when trying to set the visibility too far into the future, which I would have expected the queue client to translate into an exception.

Can you show me the line of code that defers the message 1 month into the future?

**Comment by mvanhelmont** [comment]
I have tested with the storage emulator only. But 8 days is already enough so like: Bus.DeferLocal(TimeSpan.FromDays(8), "8 days DELAY");

![8days](https://user-images.githubusercontent.com/5310629/40904482-2d76d02c-67db-11e8-92a0-a7cddcfbdf43.png)

and when i do Bus.DeferLocal(TimeSpan.FromDays(1), "1 day DELAY");

![1day](https://user-images.githubusercontent.com/5310629/40904483-2d92a82e-67db-11e8-9c2f-d7ee1f1d9607.png)

**Comment by mookid8000** [comment]
It's not totally clear whether you're doing this, but my suspicion is that you forgot to either `await` or `.Wait()` the `Task` returned by the `Defer` method. If you do not want on the `Task` somehow, any exceptions caught while executing it will disappear.

Try and change your code to

    await Bus.DeferLocal(TimeSpan.FromDays(8), "8 days DELAY");

if you're inside an `async` method, or into

    Bus.Advanced.SyncBus.DeferLocal(TimeSpan.FromDays(8), "8 days DELAY");

if you're not in a place where you can properly await the result of the `Task`.

**Comment by mvanhelmont** [comment]
you were completely right i totally forgotten the await so i don't get the exception. crazy enough there where also no error message inside log4net. Do you know of any solution? we use storage because it's cheap. We also tried to setup a sql timeout manager but this is disabled because transport support is native.

thanks for your quick reply

**Comment by mookid8000** [comment]
> crazy enough there where also no error message inside log4net

Yeah, but that's because error logging is only performed for code that executes "by itself", i.e. on a background thread where there's no way to catch exceptions.

In general, exceptions are just better for error handling, because then the calling code can either log it or try to do something else. It requires, of course, that the calling code does not let go of the `Task` and let the exception disappear 😜 

>  this is disabled because transport support is native

Yeah, well - I had a similar problem with AmazonSQS, which also has native support for deferred messages in a crippled way, so there I disabled the validation and made it possible to configure a timeout storage.

I will do the same with the Azure Storage Queues transport. I'll do that tonight, so it should be ready for you by tomorrow.

**Comment by mvanhelmont** [comment]
Thanks that helps a lot

**Comment by mookid8000** [comment]
It's out in Rebus.AzureStorage 4.2.0 in a few minutes 😄 

With 4.2.0 you can switch to using e.g. SQL Server (or an external timeout manager) to store timeouts like this:

```csharp
Configure.With(...)
    .Transport(t => {
        var options = new AzureStorageQueuesTransportOptions { 
            UseNativeDeferredMessages = false //< disables native message deferral
        };

        t.UseAzureStorageQueues(_storageAccount, QueueName, options: options);
    })
    .Timeouts(t => {
        // use SQL Server
        t.StoreInSqlServer(...);
        // ...or use another endpoint that can store them
        t.UseExternalTimeoutManager("timeouts");
    })
    .Start();
```
