### ISSUE TITLE
Retrieve Destination queue from MessageContext

### ISSUE THREAD

**Issue by arnarleifs** [rebus-org/Rebus#711]
Is there a possibility to retrieve the destination queue given the MessageContext? If not, is there any nice way to be able to do this. I am using a MSMQ setup with the Rebus.

**Comment by mookid8000** [comment]
What do you mean by 

> Is there a possibility to retrieve the destination queue (...)?

?

A "destination queue" in my mind would something that would make sense if you wanted to send an outgoing message, e.g. like so:

```csharp
await bus.Send(someKindOfMessage);
```

In this case, Rebus would ask the current [`IRouter`](https://github.com/rebus-org/Rebus/wiki/IRouter) implementation for a destination queue by calling `GetDestinationAddress` with the message.

As such, the "destination queue" only makes sense given a message to send.

Maybe you can tell me some more about what you are trying to achieve?

**Comment by arnarleifs** [comment]
What I mean is whenever the message has arrived within the proper handler, I want to override the _Handle_ method which stores the message, destination and source. I noticed I could retrieve the **source** by using the _MessageContext.Current.Headers["rbs2-return-address"]_. Therefore I was wondering if there was a similar way to retrieve the **destination** of the message.

**Comment by mookid8000** [comment]
>  I noticed I could retrieve the source by using the MessageContext.Current.Headers["rbs2-return-address"]

You should be aware that the mentioned header is the RETURN ADDRESS, and this is _not necessarily the source_, because the sender could override that particular header to have replies sent somewhere else.

Please tell me some more about what you are trying to achieve, maybe from a slightly higher perspective...?

**Comment by arnarleifs** [comment]
What I am trying to achieve is to keep a transaction log of each message being sent and processed. My initial idea was to create an abstract **MessageHandler** which all other message handlers derive from. Within that **MessageHandler** I want to do the following:

```
public abstract class BaseMessageHandler<TEvent> : IHandleMessages<TEvent>
{
    private readonly IBus _bus;

    protected BaseMessageHandler(IBus bus)
    {
        _bus = bus;
    }

    public abstract Task HandleMessage(TEvent message);

    public Task Handle(TEvent message)
    {
        var context = MessageContext.Current;

        _bus.Publish(new TransactionEvent
        {
            MessageId = context.Headers["rbs2-msg-id"],
            SourceQueue = context.Headers["rbs2-return-address"],
            DestinationQueue = "",
            MessageBody = Encoding.Default.GetString(context.TransportMessage.Body)
        });

        // Call the primary message handler
        return HandleMessage(message);
    }
}
```
The **TransactionEvent** is sent within the **BaseMessageHandler** and processed and eventually stored within a database. Does this clarify what I am trying to achieve?

**Comment by mookid8000** [comment]
First off, If I were you, I would simply turn on Rebus' message auditing capability like so:
```csharp
Configure.With(adapter)
    .Transport(t => t.UseMsmq("server.input"))
    .(...)
    .Options(b => b.EnableMessageAuditing("audit@cpvm010"))
    .(...)
```
which will forward a copy of all successfully handled messages and all published messages to the queue `audit` on the machine `cpvm010`, attaching additional headers so it's possible to tell whether the message was audited because it was published or handled.

If you choose to implement message auditing yourself, please make the `Handle` method `async` like this:

```csharp
public async Task Handle(TEvent message)
```

and then `await` the call to `Publish`  like this;

```csharp
await  _bus.Publish(new TransactionEvent
{
    MessageId = context.Headers["rbs2-msg-id"],
    SourceQueue = context.Headers["rbs2-return-address"],
    DestinationQueue = "",
    MessageBody = Encoding.Default.GetString(context.TransportMessage.Body)
});
```
because otherwise the publish operation will continue on another thread and will not be enlisted in the same Rebus transaction context as the one handling the current message.

Last thing: I still don't understand what "destination queue" means here 🤔 😁

**Comment by arnarleifs** [comment]
Hehe, I noticed the `await` and `async` just moments after I posted it here 😃 I will try to describe it using a scenario: 

> A message is published from a system called "System One" and it sets the return address to a queue which is associated with "System One". This message is delivered to three different locations "A", "B" and "C". When the message is processed by "A" it will be marked with a return address to "System One" and "Destination Address" to a queue associated with "A" and the same thing goes for "B" and "C". 

Does this clarify what I mean? I could of course keep this information within the different system, but I was wondering if this is something that `Rebus` keeps as information.

**Comment by mookid8000** [comment]
Oh so it's the input queue name of the endpoint currently handling the message?

If you enable Rebus' built-in message auditing, these headers will be attached: [`AuditHeaders.cs`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Auditing/Messages/AuditHeaders.cs)

In this case, `rbs2-audit-handlequeue` is probably what you're after 😄

**Comment by arnarleifs** [comment]
Where do I retrieve this `rbs2-audit-handlequeue` header? 😳

I have already setup the bus instance to `EnableMessageAuditing`. I can't see those headers anywhere within the `MessageContext`, should I be looking some place else?

**Comment by ryanhendersonabs** [comment]
@mookid8000 I'm 5 years late here, but I have a similar question -- is there any way to determine what queue a message came from in the handler, without using custom headers? We reuse a single handler across several different queues, so for logging and other contextual purposes, knowing the source queue name where the message was pulled from would be useful.

**Comment by mookid8000** [comment]
@ryanhendersonabs ~~Rebus will automatically set the `rbs2-sender-address` header (available as `Headers.SenderAddress`) on all outgoing messages, so yes~~ 🙂 

I think I misunderstood your question at first. If you want the name of the bus' own input queue, you can just pass it to your handler (e.g. in the form of a configuration object or something like that). Is that what you're trying to achieve? Or did I miss something?

**Comment by xhafan** [comment]
I'm also after the input queue name the handled message came from. I have multiple queues, due to message priorities, and I would like to log the input queue name in the message handler. I can see the input queue name here: 
```
((AbstractRebusTransport)
                        ((RebusBus) ((ITransactionContextWithOwningBus) ((MessageContext) MessageContext.Current)
                            .TransactionContext).OwningBus).GetPropertyValue("_transport")).Address
```
Is there a better way to get the input queue name? Cheers.

**Comment by mookid8000** [comment]
@xhafan No, I actually don't think there is a better way if the code doesn't already know. In the rare cases where I've needed my Rebus handlers (or the code executing in them) to know the names of their own input queues, I've simply "told" them at the same time as configuring the bus. 

Maybe you could figure out a way to do it like that too? 

E.g. if you would like to be able to look up the input queue name via `messageContext.TransactionContext.Items["inputqueue"]` you could follow [this example on how to install an incoming pipeline step](https://github.com/rebus-org/Rebus/wiki/Auto-flowing-user-context-extensibility-example#create-an-incoming-pipeline-step-that-sets-current-principal) and just install your own `IIncomingStep` that makes the queue name available.
