### ISSUE TITLE
Question: API for assessing if a HandlerInvoker will be skipped?

### ISSUE THREAD

**Issue by MrMDavidson** [rebus-org/Rebus#713]
We have some custom `IIncomingStep`s in our pipeline. One of the steps, early in the pipeline, may call `SkipInvocation()` on one or more of the `HandlerInvoker`s for the message. One thing I noticed in the course of doing this is that if the invoker being skipped was an `IAmInitiatedBy<TMessageType>` then when the pipeline gets to `LoadSagaDataStep` the saga data will still be initialised and persisted to the saga store. This means that if another `TMessageType` with the same correlation comes along but **does** allow the `IAmInitiatedBy<TMessageType>` to be invoked then the handler's checks of `IsNew` to preserve idempotency would return false. Whilst we're definitely doing some esoteric stuff it does seem odd to me that there is no corresponding API to `SkipInvocation()` for testing if the invoker will actually be called. Eg. I can imagine https://github.com/rebus-org/Rebus/blob/master/Rebus/Sagas/LoadSagaDataStep.cs#L62 being modified to;
```C#
var handlerInvokersForSagas = context.Load<HandlerInvokers>()
  .Where(l => l.WillExecute)
  .Where(l => l.HasSaga)
  .ToList();
```

Which would save a potential network round trip to the data store.

Ideally the ability to check if the invoker will actually be called would be public.

Any thoughts on this?

**Comment by mookid8000** [comment]
The reason `HandlerInvoker` does not have a way of checking that, is because it didn't seem necessary.

Now it seems necessary, though. It's a change I can introduce in Rebus 5

**Comment by MrMDavidson** [comment]
Sounds good - I'll keep an eye on it.
