### ISSUE TITLE
add Newtonsoft.Json.Encryption to Message-compression-and-encryption?

### ISSUE THREAD

**Issue by SimonCropp** [rebus-org/Rebus#715]
add this https://github.com/SimonCropp/Newtonsoft.Json.Encryption#rebus to here https://github.com/rebus-org/Rebus/wiki/Message-compression-and-encryption

**Comment by mookid8000** [comment]
Done: https://github.com/rebus-org/Rebus/wiki/Message-compression-and-encryption#json-encryption

Thanks man 👍 🌮
