### ISSUE TITLE
Moving sagas from Azure to SqlServer?

### ISSUE THREAD

**Issue by JLewRocks** [rebus-org/Rebus#718]
Hi, we would like to update Rebus from a very old version (.99) to the latest.  We are currently using Azure Storage which is blob-based for the sagas,  We would like to move the sagas to SqlServer.  Do you have any recommendations on what would be the best way to copy the saga data from Azure to SqlServer?  There is information stored in the saga data regarding the workflow that we need to retain.
Thanks

**Comment by mookid8000** [comment]
Unfortunately this is not really a supported scenario.

I suggest you look at the blob-based saga persister and then write some C# code that traverses all of your blobs, reading out the serialized JSON text and the corresponding index rows from table storage.

You can then look at the way the SQL-based persister works and recreate the structure in SQL Server.

It requires some coding, but it should be doable in a few  hours or so.

**Comment by JLewRocks** [comment]
That's what I thought, thank you.
