### ISSUE TITLE
How is Rebus different from MediatR and Brighter?

### ISSUE THREAD

**Issue by rosdi** [rebus-org/Rebus#719]
Hi,

This is not an issue... I am just curious and do not know better place to ask.. feel free to close it if you think it is inapproriate/wrong channel..

I just found out Rebus in the last 2-3 days... looks neat but the nagging question is how is it different than MediatR and Brighter?

https://github.com/jbogard/MediatR
https://github.com/BrighterCommand/Brighter

Apologise if this is the wrong place to ask this question.

Regards,
Rosdi.

**Comment by mookid8000** [comment]
If I understood this correctlt, MediatR is an in-process command dispatcher, basically implementing the part where you have this:

```csharp
var command = new PromoteEmployee(employeeId, newTitle);
```

and you want something like this to implement what that should do:

```csharp
public class EmployeePromoter : IHandle<PromoteEmployee>
{
	// command handlers can have things injected
	public EmployeePromoter(IEmployeeRepository employeeRepository)
	{
		// ...
	}

	// strongly typed handler signature to receive the command
	public void Handle(PromoteEmployee command) 
	{
		// ...
	}
}
```
(actual class/interface names are definitely not correct, this is just an example)

Rebus implements this part too, including many of the same features like IoC container integration for most popular containers, polymorphic dispatch, async handlers, etc.

Rebus is just much more oriented towards distributed messaging, where message queues (like MSMQ, RabbitMQ, Azure Service Bus, Amazon SQS, etc.) are used to move messages out of your processes, into other processes, possibly into many processes running on many different machines.

I don't think MediatR does any of that. My perception of MediatR is more that it's a nice facade for a domain model, which makes it easy to implement a command-based way of mutating entities in your database.

Brighter on the other hand is much more like Rebus in that it works nicely on top of several distributed queue implementation.

My perception is that Rebus looks more like NServiceBus with the types of APIs and the structure of everything, where my guess that Brighter is more "its own". I don't have any experience or actual knowledge to back this up though 😁
