### ISSUE TITLE
Subscribe to a topic in a custom queue in RMQ

### ISSUE THREAD

**Issue by mjalil** [rebus-org/Rebus#721]
Hi @mookid8000 ,
I need to be able to subscribe to each topic in its own queue, not in the transports input queue.
in my case messages of some topics in front of the queue may take longer to be processed, and block process of other fast-processing events, you know, so slow down message processing.
in a single queue no message is processed until front of it is processed (no matters success or fail).
so i decided to process each topic on its own queue, to decrease slow down side effect.
but i can not do `bus.Advanced.Topics.Subscribe(topic, queueName)`
what do you recommend?

**Comment by mookid8000** [comment]
To "subscribe to each topic in its own queue" you would start two Rebus endpoints and then subscribe to two different things.

You can start as many Rebus endpoints as you like in the same process.
