### ISSUE TITLE
Log error

### ISSUE THREAD

**Issue by Jeern** [rebus-org/Rebus#723]
Hi Mogens,

A few places in the rebus code you have this:

            LogStartStop("Starting periodic task {taskDescription} with interval {timerInterval}", _description, Interval);

Kind of obvious what the error is :)  I assume you have been too thorough replacing old formatting code with new ?

Anyway it breaks my code

**Comment by Jeern** [comment]
Sorry I should have been more explicit :) I have injected a Custom ILog, where I assume that the string message is an old fashioned format string you know with  {0} {1} etc. and the params array are the argument. So I create a text like this: string.Format(message, args) - this throws in this case because you sent me "Starting periodic task {taskDescription} with interval {timerInterval}" which does not contain {0} and {1} but instead variable names as in inline formatting (variable names that are not there I might add :) hence the "obvious" remark...

**Comment by Jeern** [comment]
BTW. The code that breaks now has worked with Rebus for years to my knowledge

**Comment by mookid8000** [comment]
Rebus 4 switched to semi-structured logging, allowing e.g. Serilog and other structured logging libraries to pick up field names from log events.

If you're using an old school logging library you probably need to derive your logger factory from [Rebus' `AbstractRebusLoggerFactory`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Logging/AbstractRebusLoggerFactory.cs) and then call its `RenderString` method to convert format string and arguments to a string.

May I ask why you implemented your own logger factory?

**Comment by Jeern** [comment]
Perfect thank you. :)  I Will try the RenderString Method. So you are telling me that serilog understands {taskDescription} ? Anyway - we implemented our own because we have a Company wide Logging solution

**Comment by mookid8000** [comment]
Yes 😄 if you use e.g. Elasticsearch, MongoDB, or SQL Server to store your logs, there will be a field called `taskDescription` you can query by.

That's not a fun example though. It's more fun when logging something like this

```csharp
_log.Debug("Dispatching {messageType} {messageId} to {count} handlers took {elapsedMs:0} ms", 
    messageType, messageId, handlersInvoked, stopwatch.ElapsedMilliseconds);
```

because then you can e.g. query by (pseudo SQL) `select messageType where elapsedMs > 500` or whatever your log aggregator lets you do.
