### ISSUE TITLE
ThreadPoolWorker is not awaiting correctly

### ISSUE THREAD

**Issue by MrMDavidson** [rebus-org/Rebus#725]
In our production environment we're intermittently seeing

> A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

The stack trace for this is;
```C#
System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction):94
System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose):319
System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady):2545
System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows):166
System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more):162
System.Data.SqlClient.SqlDataReader+<>c__DisplayClass12.<ReadAsync>b__11(Task t):43
System.Data.SqlClient.SqlDataReader.InvokeRetryable[T](Func`2 moreFunc, TaskCompletionSource`1 source, IDisposable objectToDispose):36
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):41
 
Rebus.SqlServer.Transport.SqlServerTransport+<ExtractTransportMessageFromReader>d__30.MoveNext():108
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):41
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult():11
 
Rebus.SqlServer.Transport.SqlServerLeaseTransport+<ReceiveInternal>d__13.MoveNext():617
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):41
 
Rebus.SqlServer.Transport.SqlServerTransport+<Receive>d__28.MoveNext():235
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):41
 
Rebus.Workers.ThreadPoolBased.ThreadPoolWorker+<ReceiveTransportMessage>d__17.MoveNext():121
```

For reference the thing causing the SQL exception (eg. the top of the stack trace) can be for instance the connection being terminated.

Looking at the code and the stack trace we believe it's because in [ThreadPoolWorker](https://github.com/rebus-org/Rebus/blob/master/Rebus/Workers/ThreadPoolBased/ThreadPoolWorker.cs#L86) `TryAsyncReceive` is not being awaited.  We're still on 4.0.0 but looking at the diffs the only difference is that `ConfigureAwait(false)` is being used.

As this isn't being called in an async context it can't just be `await`ed and has to be ran synchronously. I'm a little wary of randomly changing this because of the core nature of it and the possibility of introducing deadlocks. Any insight here?

**Comment by mookid8000** [comment]
I know that `async void` is considered harmful in some circles 😨 in this case it's used because there's no way for a returned `Task` to be watched, so the `TryAsyncReceive` method watches its own exceptions, and the `void async` construct is simply used to get the compiler to help generate code that is more efficient and requires less allocations than `Task.Run(() => TryAsyncReceive(token, parallelOperation))`.

At a very early point in Rebus 2's lifetime, the signature was `async Task TryAsyncReceive(token, parallelOperation)`, but the `Task` was just returned into the void. Then I changed it to `async void`.

I haven't observed any problems with this myself, so I am pretty surprised that you're suddenly experiencing indications that it should be a problem.

> Looking at the code and the stack trace we believe it's because in `ThreadPoolWorker` `TryAsyncReceive` is not being awaited. 

but.... can you see any way an exception could escape [this `try`/`catch`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Workers/ThreadPoolBased/ThreadPoolWorker.cs#L86-L122)?


> We're still on 4.0.0 but looking at the diffs the only difference is that ConfigureAwait(false) is being used.

Yeah well, I don't think that makes a difference either.

**Comment by MrMDavidson** [comment]
I'm wondering if it's just a timing thing that's causing the exception to be observed in the finalizer instead of inside the catch block? Looking through our exception handling we've actually had some incidents of this going back a few months (still on 4) but it seems like it's picking up steam in its frequency. I'm not sure if this is because we're reducing the noise of other exceptions in our system and noticing it more or it's because we're making more use of Rebus throughout that's making it happen more.

I wonder if this can be solved by simply changing the signature back to `async Task TryAsyncReceive` and then change the call to [`TryAsyncReceive`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Workers/ThreadPoolBased/ThreadPoolWorker.cs#L83) to be something like;

```C#
TryAsyncReceive(token, parallelOperation)
  .ContinueWith(t => { _log.Error(t.Exception, "Error bubbled out of TryAsyncReceive"); }, 
        TaskContinuationOptions.OnlyOnFaulted);
```

**Comment by mookid8000** [comment]
As an experiment, I've released 5.0.0-b15 with the change you proposed.

It doesn't change anything functionally, the only consequence seems to be a small degradation of dispatch performance: On my machine I went from ~29k msg/s to ~26k msg/s (running the [`TestDispatchPerformance`](https://github.com/rebus-org/Rebus/blob/master/Rebus.Tests/Profiling/TestDispatchPerformance.cs) test using `PipelineInvokerMode.DefaultNew`, which is what Rebus uses by default these days)

And.... now that I've written this, I realize you said

> (...) still on 4 (...)

so if you would like me to release a 4.3.0 beta something version, please let me know.

I'd be happy if you would try it out for a while and see if any logs with `Unhandled exception in thread worker` show up.

**Comment by mookid8000** [comment]
Hi @MrMDavidson , have you had a chance to try it?

**Comment by MrMDavidson** [comment]
Unfortunately we haven't had a chance to bump our version yet to try this out due to other commitments. I'll look at trying to do so next week.

**Comment by MrMDavidson** [comment]
We've integrated this change in one of our branches and haven't had any issues so far. I'll get back to you once it's out in production under real world loads 👍

**Comment by mookid8000** [comment]
So.... 😁 how is it going?

**Comment by MrMDavidson** [comment]
Unfortunately we haven't had a chance to merge this into our main branch to see how it works at production scale. It's working fine in development so far, though.

**Comment by mookid8000** [comment]
I'm closing this one for now, considering it solved 😄 I've been running with Rebus 5 with this change since it was introduced, and I can't see any way an exception can escape now.

Thanks for reporting it 👍
