### ISSUE TITLE
Symbol packages?

### ISSUE THREAD

**Issue by poizan42** [rebus-org/Rebus#730]
Are there symbols available anywhere for the NuGet packages?

If not could they be included for builds in the future? There's some information about how to do that at

* https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages
* http://www.symbolsource.org/Public/Wiki/Publishing

**Comment by mookid8000** [comment]
That's definitely something to consider. 

I have never really missed symbol packages myself, because I use R# and let it decompile classes/methods by default, but I can definitely see how including the actual source would be a great service to developers.

**Comment by poizan42** [comment]
What is R#? Not [this](https://sourceforge.net/projects/r-sharp/) I guess and not [this](https://github.com/SMRUCC/R-sharp) either.

Anyways, while there are some plugins for VS that allows stepping through decompiled source, it really is a much nicer experience if you can just step into the original source.

But besides source-level stepping the pdb files are also necessary to get line numbers in stack traces which can help a lot in debugging.

**Comment by mookid8000** [comment]
ReSharper: https://www.jetbrains.com/resharper/ 😄 

but I didn't know that symbol packages allowed for stepping into the source code – that's pretty neat!
