### ISSUE TITLE
avoid duplicate deferred messages

### ISSUE THREAD

**Issue by stevengopmo** [rebus-org/Rebus#732]
I have a service that I want to do a `bus.defer` on startup to trigger a message that processes stuff in the future.  If the service (console app) is stopped and restarted I don't want to have multiple deferred messages in the queue.  Is there a built in way to either check for the existence of this deferred message or maybe clear any messages of that type that exist?

**Comment by mookid8000** [comment]
Not readily, no.

Question is: Why do you not want to receive the deferred message again? Is it because you're actually using it as if it was a scheduler of some kind?

In that case, I suggest you use something like [Quartz .NET](https://github.com/quartznet/quartznet) 

Can you explain why you do not want to receive the message again?

**Comment by stevengopmo** [comment]
yes sorry let me explain further.  I have a console app that I want to use to poll directories for new files.  I was thinking the app can start, configure rebus, defer the first message to scan directories.  After time passes the handler does the work, including sending messages to other handlers (probably `bus.SendLocal`) and does `bus.defer` again.  I was thinking this is a good way to avoid reentry problems based on the first message taking too long to process.

The problem with this approach is if someone stops the app prior to the deferred message getting sent when it starts again it will send another `bus.defer` which will mean there are now 2 messages that will get handled after some time.  And that could grow of course if the behavior (stopping the service in between deferred messages) continues.

Quartz is overkill for what I want to do especially since the deferred message is only a portion of what I mostly handle via Rebus.

So after posting this I thought I might ~steal~ borrow from your timer sample and just send the message to scan on a timer interval.  What do you think, any particular gotchas that I should look out for in this approach?

**Comment by mookid8000** [comment]
I think I would use a normal .NET timer then, e.g. a `System.Timers.Timer`. And yes, there's definitely the reentrancy problem to look out for, as it sounds like it doesn't make sense to carry out more than one directory scan at a time.

I think I would simply solve that by flicking a bool ("double-checked locking" style) in the timer callback, ensuring that the callback has finished executing before executing it again. The directory scan would then be carried out in the callback, and not by a Rebus handler.

Sounds to me like that would be the easiest way to handle that.
