### ISSUE TITLE
TransportMessage headers = NULL

### ISSUE THREAD

**Issue by arnarleifs** [rebus-org/Rebus#733]
Hi,

I have been receiving this error on/off when processing messages through the Rebus. I am not assigning the headers especially but just using the built-in feature. Have you come across this?

See stacktrace:
` An error occurred when attempting to receive the next message: System.ArgumentNullException: Value cannot be null. Parameter name: headers at Rebus.Messages.TransportMessage..ctor(Dictionary2 headers, Byte[] body) at Rebus.Msmq.MsmqTransport.d__15.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Rebus.Workers.ThreadPoolBased.ThreadPoolWorker.d__17.MoveNext()`

**Comment by arnarleifs** [comment]
This happened because of a transport message which was not populated correctly.

**Comment by mookid8000** [comment]
Good you figured it out 👌
