### ISSUE TITLE
Use Task.Run in Handler to Send a message

### ISSUE THREAD

**Issue by tresoldigiorgio** [rebus-org/Rebus#735]
Can you tell me why this code doesn't work? :-D

`using System;
using System.Threading.Tasks;
using Rebus.Activation;
using Rebus.Bus;
using Rebus.Config;
using Rebus.Handlers;
using Rebus.Transport.InMem;
 
namespace TestConsole
{
    class Program
    {
        public static IBus Bus;
 
        static void Main(string[] args)
        {
            using (var activator = new BuiltinHandlerActivator())
            {
                activator.Register(() => new Handler());
 
                Bus = Configure.With(activator)
                    .Logging(l => l.None())
                    .Transport(o => o.UseInMemoryTransport(new InMemNetwork(), "TestQueue"))
                    .Start();
 
                Bus.SendLocal("Test").Wait();
 
                Console.WriteLine("Press enter to quit");
                Console.ReadLine();
            }
        }
 
        public class Handler : IHandleMessages<string>, IHandleMessages<int>
        {
            public Task Handle(string message)
            {
                Console.WriteLine("string");
                Task.Run(() => Bus.SendLocal(1).Wait());
                return Task.CompletedTask;
            }
 
            public Task Handle(int message)
            {
                Console.WriteLine("int");
                return Task.CompletedTask;
            }
        }
    }
}`

I try to Send a message in a Task.Run started from an Handle function.

Thanks!!!

**Comment by mookid8000** [comment]
What do you mean by "it doesn't work"? Do you see an error of some kind? Does the string message not arrive? Does the integer message not arrive?

Your code is also a little bit "un-idiomatic"... C# has the `async` keyword, which is basically letting the compiler help you make your asynchronous code look synchronous, so I suggest you change your code into this:
```csharp
using System;
using System.Threading.Tasks;
using Rebus.Activation;
using Rebus.Bus;
using Rebus.Config;
using Rebus.Handlers;
using Rebus.Transport.InMem;

namespace TestConsole
{
    class Program
    {
        public static IBus Bus;

        static void Main(string[] args)
        {
            using (var activator = new BuiltinHandlerActivator())
            {
                activator.Register(() => new Handler());

                Bus = Configure.With(activator)
                    .Logging(l => l.None())
                    .Transport(o => o.UseInMemoryTransport(new InMemNetwork(), "TestQueue"))
                    .Start();

                Bus.SendLocal("Test").Wait();

                Console.WriteLine("Press enter to quit");
                Console.ReadLine();
            }
        }

        public class Handler : IHandleMessages<string>, IHandleMessages<int>
        {
            public async Task Handle(string message)
            {
                Console.WriteLine("string");

                await Bus.SendLocal(1);
            }

            public async Task Handle(int message)
            {
                Console.WriteLine("int");
            }
        }
    }
}
```

Try that – let me see what the result is then 😄

**Comment by tresoldigiorgio** [comment]
You are right. I was not so clear! sorry!
I have to handle a message that run an another task (with Task.Run) that do long operations and then send a message, the first handle method have to finish so the program can handle others messages. The problem is that the Send in the Task.Run (in first handle method) not work. The message never start! 
If i change my code:

`
public class Handler : IHandleMessages<string>, IHandleMessages<int>
    {
        public Task Handle(string message)
        {
            Console.WriteLine("string");
            Task.Run(() => Bus.SendLocal(1).Wait());
            Task.Delay(1000);
            return Task.CompletedTask;
        }

        public Task Handle(int message)
        {
            Console.WriteLine("int");
            return Task.CompletedTask;
        }
    }
`
the Send in Task.Run works! Why?

Thanks
