### ISSUE TITLE
Could we make ITransactionContextWithOwningBus public and add some logging

### ISSUE THREAD

**Issue by mattwhetton** [rebus-org/Rebus#741]
Hey,

We're using 2 Rebus buses (1 as a shared competing consumers bus, 1 as a local instance specific bus). We just hit a problem where we were getting some inconsistent behaviour as a result of publishing messages off the back of a handled message. Ultimately the inconsistency was due to sometimes the message being published on a different bus to the one that handled the message.

So 2 questions / requests:

1. Could we make ITransactionContextWithOwningBus a public interface? This is basically so we can find at publish time which bus we should be publishing on (if an OwningBus exists)
2. Is there somewhere we add some logging (or maybe even an exception), if a message send is attempted using an already completed transaction context? This was essentially our issue - we had some async code that wasn't awaited properly, resulting in an event not makign it to rabbitmq.

I'm happy to make the changes and do a PR, I just wanted to make sure they make sense, and that I do them in the most appropriate place.

Cheers

Matt

**Comment by mookid8000** [comment]
1. Sorry, I don't think I understand your problem fully. How could the published message _sometimes_ be published on one bus, and _sometimes_ on another?

2. You suggestion of throwing an exception is so obvious an improvement that I am embarrassed that I didn't come up with it! 🙃Rebus' transaction context implementation is [here](https://github.com/rebus-org/Rebus/blob/master/Rebus/Transport/TransactionContext.cs), and I would say that all `On(...)` methods ought to guard against adding callbacks to an already completed context.

**Comment by mattwhetton** [comment]
I'll look to get a PR up for the exception in TransactionContext, thanks.

The first one is a little complicated, and as a result of our implementation and some layers of abstraction, but ultimately we inject a BusProvider that lets us publish either via a shared bus (competing consumers) or a local bus (instance specific). 

The problem for us is that when we handle EventA and we want to pubish EventB (as part of the handle), we'd like to publish using the same bus that EventA was handled on - so that the transaction context is the same. So when we publish we'd like to be able to determine which the owning bus is, so that we can use that one.

Hope that makes sense?

**Comment by mookid8000** [comment]
Just as a note to anyone who might come by this issue in the future: The "throw exceptions when adding callbacks to an already-completed transaction context"-issue was fixed by #744 and released in Rebus 5.0.1

**Comment by mookid8000** [comment]
So... how's it going? 😁

**Comment by mattwhetton** [comment]
Hey.

For our issue we kind of resolved it by adding something into the pipeline to record the owning bus, and then used that later. 

If we could make ITransactionContextWithOwningBus it would make it simpler, but I didn't want to submit a PR for that change unless you thought it was the right thing to do?
