### ISSUE TITLE
Moving static classes in the context of each bus instance

### ISSUE THREAD

**Issue by boyanio** [rebus-org/Rebus#743]
Hello,

Today one can write unit tests with the help of `FakeBus` and `SagaFixture<>`. However, as Rebus depends internally on some static classes, like `RebusTime`, it is not possible to run these tests in parallel in situations where one of the tests wants to perform time checks. Have you considered moving static classes in the context of each bus instance? In this case one could write independent tests as each tests creates its own bus instance.

**Comment by mookid8000** [comment]
I never considered that, no. It's probably because I never tried using a test runner that would run tests in parallel inside the same appdomain.

Which test runner are you using?

**Comment by boyanio** [comment]
We use NUnit. The way we use it just by different classes that test a command handler or saga workflow.

**Comment by mookid8000** [comment]
merged to `master`... will be out with Rebus 6
