### ISSUE TITLE
Azure Event Grid support

### ISSUE THREAD

**Issue by Liero** [rebus-org/Rebus#746]
Are there any plans to support Azure Event Grid transport?

**Comment by mookid8000** [comment]
Not at the moment, as Rebus is very well integrated with Azure Storage Queues and Azure Service Bus.

But I am very curious to know what you think Event Grid support would provide?

**Comment by Liero** [comment]
I'm not sure exactly, but I think that Event Grid is supposed to be primary choice for serverless architecture.

I guess that comparing to Azure Service Bus it is cheaper, and comparing to Storage Queues it is faster in geographically distributed pub/sub scenarios.

**Comment by mookid8000** [comment]
Is Event Grid meant to work as a generic message transport? Isn't it more meant to expose events in relation to Azure resources, e.g. making it possible to do stuff when a blob appears, when a VM starts, etc.?

**Comment by Liero** [comment]
Event Grid is serverless pub/sub solution. It can route existing events published by various azure services to various subscribers, but you can as well produce your custom application events and handle them in your custom code. App built using microservices is a good example, see https://azure.microsoft.com/en-us/resources/samples/serverless-eventing-platform-for-microservices/
