### ISSUE TITLE
FalseResult = Task.FromResult(true) ?

### ISSUE THREAD

**Issue by mrjonez** [rebus-org/Rebus#751]
Hi,
In file
https://github.com/rebus-org/Rebus/blob/master/Rebus/Sagas/Exclusive/ConcurrentDictionaryExclusiveSagaAccessLock.cs on line15,
FalseResult  should be Task.FromResult(false) instead of true?

Thanks
/John

**Comment by mookid8000** [comment]
Yes it should! Fortunately, `ConcurrentDictionaryExclusiveSagaAccessLock` is not used anywhere, but you are absolutely right that it's quite buggy when `FalseResult` actually returns `true` 😁
