### ISSUE TITLE
Make in memory providers more accessible

### ISSUE THREAD

**Issue by oliverhanappi** [rebus-org/Rebus#762]
Rebus provides many in memory implementations for its services like transport, data bus, saga storage and subscription storage. These are very convenient for unit testing, however the underlying stores offer only a very restricted API tailored towards the consumption by Rebus.

It is very hard to inspect and manipulate these stores in other ways, e.g. during tests. In the process of creating #663 I realized that I often want to use an existing in memory implementation but need to create an individual one just because some members are internal or private.

I suggest to extend the API surface of the in memory implementations roughly as follows:

**Transport**

- Add a method `InMemNetwork.GetMessages(string queueName)` to get a list of transport messages without consuming them for inspection.
- Initialize `InMemTransportMessage._creationTime` using `RebusTime.Now`.
- Refactor `InMemNetwork` to log activities using the `ILog` interface rather than outputting directly to the console.

**DataBus**

- Add a property `InMemDataStore.AttachmentIds => _data.Keys` for retrieving all known attachment ids.
- Add a method `InMemDataStore.Delete(string id)` to delete an attachment and its metadata.
- Add a method `InMemDataStore.Reset()` to clear all stored data (like `InMemNetwork.Reset()`).

**SagaStorage**

- Make `InMemorySagaStorage.Instances` public.
- Add a method `InMemorySagaStorage.Reset()` to clear all stored instances (like `InMemNetwork.Reset()`).

**SubscriptionStorage**

- Add a property `InMemorySubscriberStore.Topics` to get a list of topics for which subscriptions exist.
- Add a method `InMemorySubscriberStore.Reset()` to clear all subscriptions (like `InMemNetwork.Reset()`).

**Time Service**

- Make `RebusTime.CurrentTimeFactory` public because `RebusTimeMachine` is very limited and there may exist other time services in the integrating applications that should be used.

What do you think?

**Comment by mookid8000** [comment]
Good ideas pretty much all of it 😄 

Regarding time, Rebus 6 will have the [`IRebusTime`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Time/IRebusTime.cs) service, so time can be faked throughout.

I think all the other things are good ideas, and I don't think it messes with anything.

**Comment by mookid8000** [comment]
That would be absolutely awesome 😄 I suggest you start out by targeting the `release/4` branch, and then we can just bring it into 5 and 6 afterwards.

**Comment by mookid8000** [comment]
release in Rebus 4.3.0

**Comment by oliverhanappi** [comment]
Awesome, thanks a lot 😄
