### ISSUE TITLE
Hagar serializer

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#766]
[Hagar](https://github.com/ReubenBond/Hagar) looks pretty interesting. See if it's possible to use it as a serializer for messages.

**Comment by jods4** [comment]
So many .net serializers popping up those days...
If you look at binary serialization, **Ceras** might be worth considering, too. It has a _lot_ of features:
https://github.com/rikimaru0345/Ceras/wiki/Full-feature-list-&-planned-features

**Comment by mookid8000** [comment]
Wow, Ceras looks really impressive! I've opened #820 for it, maybe someone will come by and work on it 😉

**Comment by mookid8000** [comment]
@jods4 check out out 👉 https://github.com/rebus-org/Rebus.Ceras

(took another look at Hagar – it's not even on NuGet yet, so I'm just archiving this issue for now)
