### ISSUE TITLE
Any plan to support Google Cloud Pub Sub?

### ISSUE THREAD

**Issue by dariogriffo** [rebus-org/Rebus#767]
Making research to start a project on GCP, and wanted to know if there is any plan to support [Google.Cloud.PubSub](https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.PubSub.V1/)

Regards

**Comment by mookid8000** [comment]
Hi @dariogriffo , I'm closing this issue for now – feel free to revive it, if you still feel it's relevant (and maybe have learned enough GCP to be able to contribute with a Pub Sub transport.... 😛 )

**Comment by runes83** [comment]
Any updates on this? Have anyone made this?

**Comment by mookid8000** [comment]
@runes83 Haven't heard from anyone having done this 🙂 do you know anything about it? And are you thinking about running Rebus stuff in Google Cloud?
