### ISSUE TITLE
Efficiently filtering messages

### ISSUE THREAD

**Issue by ronnyek** [rebus-org/Rebus#769]
There are cases where say I have multiple categories of the same type of message that I'd like to be able to discriminate between with a field that's say an enum or something. 

I was curious if there was a way to be able to effectively have a handler subscribe to messages where that field is set to a specified value, without having to just break that out into separate messages, with separate handlers.

I saw some things in searching about filtering by aborting within the context... I dont really want to abort the messages, I just dont want this current handler handling messages with certain values.

If neither route is appropriate, are there any other ways to accomodate such a thing? 

An example of a use case is that I have multiple services listening for messages, and I'd effectively like to use pubsub, but have specific handler subscribing to message type with descriminator

**Comment by mookid8000** [comment]
Maybe you could use (custom-named) topics?

E.g. consider having topics `topic-a`, `topic-b`, and `topic-c` – then two subscribers could e.g. subscribe to
1. `topic-a` and `topic-c`
1. `topic-b` and `topic-c`

and then, if the publisher then published to either `topic-a`, `topic-b`, or `topic-c` depending on the contents of the message, then the event would be received by either 1, 2, or both 1 & 2.

**Comment by mookid8000** [comment]
CLosing this, because it's a question. Feel free to continue the talk in here, if you have more questions.

**Comment by ronnyek** [comment]
So this looks interesting. I found examples for rabbitmq that demonstrate this... does it require a specific backing queue, or something rebus supports in an abstract form?

As best as I can tell now, my usage of Rebus creates RebusTopics and RebusDirect, would these custom topics actually be like a totally new topic channel, or would it be more akin to having special things when publishing to denote a different path (in the rebus example they used something like `cars` and `cars.bmw`) and then special way of subscribing?

I currently heavily rely on IHandleMessages, and let rebus handle channels/topics etc... one sender will grab IBus and publish a NewUserCreated message, and then something else will subscribe with IHandleMessages<NewUserCreated>.

I'm just trying to figure out what I'd need to change from my current usage to make this work, and what caveats if any I'd run into from doing this

**Comment by mookid8000** [comment]
> (...) does it require a specific backing queue, or something rebus supports in an abstract form

No, it's just how RabbitMQ works, when publishing to a topic exchange

> (...) my usage of Rebus creates RebusTopics and RebusDirect, would these custom topics actually be like a totally new topic channel (...)

Just a tiny correction here: 🤓`RebusTopics` and `RebusDirect` are _exchanges_, and exchanges have types – they're of the "topics exchange" and "direct exchange", respectively.

The type of the exchange determines how the "routing key" on each message is interpreted. In a topics exchange, it's interpreted as a topic, and it just supports wildcards, as you've seen.

When you subscribe to a topic, you then create a _binding_ to your input queue. Bindings support wildcards, which then means that all messages published that match the binding (wildcards'n'all) will then be delivered to the bound queue.

As you can probably see by now, you don't need to change anything to make use of RabbitMQ's support for wildcards in subscriptions.
