### ISSUE TITLE
Auto deletion of queue (or queue binding?) after no subscribers receiving

### ISSUE THREAD

**Issue by ronnyek** [rebus-org/Rebus#774]
Just a question here...
So with rabbit, it seems like messages broadcast into the ether until subscribers register at which point in time queue/queue binding is created. 

Does rebus or the rabbit plugin have any notion of cleaning up or deleting those bindings, so messages go back to being broadcast into the ether, so as to not potentially let messages pile up indefinitely?

I seem to recall servicebus having something like that (or maybe my company implemented something like that)

**Comment by mookid8000** [comment]
Rebus supports ["auto-delete queues"](https://www.rabbitmq.com/queues.html#properties) by calling `SetAutoDelete` on the RabbitMQ options builder like so:
```csharp
Configure.With(...)
	.Transport(t => t.UseRabbitMq(...).SetAutoDelete(true))
	.Start();
```
This way, RabbitMQ will automatically make the queue and its bindings disappear once the connection is lost.

**Comment by ronnyek** [comment]
Excelllent! thanks !

**Comment by ronnyek** [comment]
I'm seeing that extension method on `RabbitMqQueueOptionsBuilder` not the `RabbitMqOptionsBuilder`. I'm not sure how exactly I get at that queue options builder, but vs is complaining with the latest stable rebus/rebus.rabbitmq nugets

**Comment by mookid8000** [comment]
ah, sorry – I updated the code I posted to be correct.... I forgot the `.InputQueueOptions(...)` thing

**Comment by ronnyek** [comment]
I just saw that before you posted that... I'll give that a whirl... thanks!

**Comment by ronnyek** [comment]
Would you guys be open to a pull request to incorporate an overload for ttl on the queueDeclare as described near the bottom of:
https://www.rabbitmq.com/ttl.html

Which basically makes it sound like you include `x-expires` attribute when we declare the queue, and it wont delete immediately after no consumers... but if no consumers within ttl, at that point it deletes the queue?

My use case is during maint windows, we might kill all consumers of a particular message type, but only for a split second, and wouldnt want to to immediately just toss away all the messages contained within, but if say it went a few days with nothing consuming, delete at that point in time? 

Seems like I could just use the .`AddArgument` on the inputqueueoptions, but it looks like its blowing up because I'm attempting to pass value as a string (limitation on `AddArgument`)

**Comment by mookid8000** [comment]
> Would you guys be open to a pull request (...)

You had me at "pull request", so yes 🤠
