### ISSUE TITLE
Manipulate pipeline step ordering

### ISSUE THREAD

**Issue by thomasdc** [rebus-org/Rebus#775]
I have several custom incoming pipeline steps. They can be used separately or combined by clients. However, when they are combined, the pipelines should be processed in a specific ordering.

I've read the [documentation on extensibility](https://github.com/rebus-org/Rebus/wiki/Auto-flowing-user-context-extensibility-example), but I'm wondering how can I control the pipeline ordering more granular than:

```
return new PipelineStepInjector(pipeline)
                .OnReceive(XXX, PipelineRelativePosition.Before, typeof (YYY))
```

Where YYY might be a extension step that's used by the client or not. The extension step XXX might even be in an assembly that's not aware of the assembly YYY resides in.

**Comment by mookid8000** [comment]
`PipelineStepInjector` is just a decorator of `IPipeline`, so you can implement whichever ordering algorithm you like by hooking in your own decorator like this:
```csharp
Configure.With(...)
	.(...)
	.Options(o => o.OrderThingsMyWay())
	.Start();
```

where `OrderThingsMyWay` is an extension method that could look like this:

```csharp
public static class RebusPipelineOrderingExtensions
{
	public static void OrderThingsMyWay(this OptionsConfigurer configurer)
	{
		configurer.Decorate<IPipeline>(c => new MyPipelineDecorator(c.Get<IPipeline>()));
	}
}
```

Your pipeline decorator can then implement the ordering:

```csharp
public class MyPipelineDecorator : IPipeline
{
	readonly IPipeline pipeline;

	public MyPipelineDecorator(IPipeline pipeline) => this.pipeline = pipeline;

	public IOutgoingStep[] SendPipeline()
	{
		var steps = pipeline.SendPipeline();

		// order them

		return steps;
	}

	public IIncomingStep[] ReceivePipeline()
	{
		var steps = pipeline.ReceivePipeline();

		// order them

		return steps;
	}
}
```

Most of the time, you should probably try to make the ordering of your steps irrelevant, or at least be ordered only relative to Rebus' built-in steps, e.g. like "insert my step after `DeserializeIncomingMessageStep`", or "insert my step right before `ActivateHandlersStep`", etc.

But as you can see, you can implement your own ordering by decorating the pipeline.

I hope it works out for you 😄 if not, please tell me more about your problem.
