### ISSUE TITLE
Feature request - Add CancellationToken parameters on IHandleMessages 

### ISSUE THREAD

**Issue by dariogriffo** [rebus-org/Rebus#776]
Just wondering how large will be the effort to allow handling messages passing a cancellation token?
Ideally processing of messages should not take much, but I'm thinking about something that there could be the case where the handler is accessing the database with a large timeout and they want to stop the application "gracefully", not killing the process, but stopping the service/program/webapp

```
public interface IHandleMessages<in TMessage> : IHandleMessages
{
    Task Handle(TMessage message, CancellationToken cancellationToken);
}
```

Ideally the Configure. class can provide another method that receives a CancellationTokenSource, and in case it doesn't it will use a private property default (CancellationToken).
Obviously this means a huge breaking change for Rebus.
Hope this makes sense.

**Comment by mookid8000** [comment]
This is an excellent idea, but I don't think it's necessary to break the `IHandleMessages` interface (which is also much a thing I would like to NOT do, because it's one of the few things that end up being used a lot in people's code...)

Rebus happens to have a cancellation token internally in its "injectionist" (the dependency injection/decoration helper that it uses to build its configuration), which means that it's actually available.

One way of making it available to message handlers throughout would be to ensure that the incoming message context would have it, so that handlers could get to it via the message context.

I'll just play around a bit, and then I'll let you know what I come up with.

**Comment by dariogriffo** [comment]
That means the TokenSource has to be available outside the configuration or the configuration provide a set of delegates to call when cancellation is required.
On my current developments I inject a ITokenSource into every handler. That implementation is a singleton that contains a CancellationTokenSource I can also access let's say from the service stop method to trigger the cancel in my handle messages methods.

**Comment by mookid8000** [comment]
It'll be made available like this:
```csharp
public class LongRunningMessageHandler : IHandleMessages<SomeMessage>
{
	readonly IMessageContext _messageContext;

	public LongRunningMessageHandler(IMessageContext messageContext)
	{
		_messageContext = messageContext;
	}

	public async Task Handle(SomeMessage message) 
	{
		var cancellationToken = _messageContext.IncomingStepContext.Load<CancellationToken>();

		// do something that takes a long time here
		await Task.Delay(TimeSpan.FromHours(24), cancellationToken);
	}
}
```

**Comment by mookid8000** [comment]
@dariogriffo check out [this test](https://github.com/rebus-org/Rebus/blob/release/5/Rebus.Tests/Cancellation/VerifyLongMessageHandlerCanBeCancelled.cs) to see it in action

Is there something you feel is missing in that example?

**Comment by dariogriffo** [comment]
I would like to know the accessibility outside Rebus context, since is there where the consumer will trigger the cancel action.
Something like [this](https://gist.github.com/dariogriffo/a96ba2c55c6660c5d500317692282d19)

**Comment by mookid8000** [comment]
...but if you already have access to the `CancellationTokenSource`, it should be pretty easy to get Autofac to inject `cancellationTokenSource.Token` into your handlers....?

There's no reason Rebus should know about that.

Or, if you use Rebus' built-in `CancellationToken` as shown above, your tasks will be cancelled when the bus is disposed, which is what happens when your Autofac container is disposed.

**Comment by dariogriffo** [comment]
> ...but if you already have access to the CancellationTokenSource, it should be pretty easy to get Autofac to inject cancellationTokenSource.Token into your handlers....?

This is what I'm doing at the moment, injecting into the constructor of my handlers the token.

>There's no reason Rebus should know about that.

It depends, since Rebus waits for the bus disposal to cancel the token, it might be that we are never able to trigger a cancellation in the Handle(...) without injecting the token in the constructor
My thinking is that in a windows service there should be 1 single CancellationTokenSource in the whole application, that will be signaled on the Stop, or any other circumstance, and Rebus token should be the "hanging" from that source like in [this example](https://docs.microsoft.com/en-us/dotnet/standard/threading/how-to-listen-for-multiple-cancellation-requests)

Just asking what is the purpose of having that token inside Rebus if it cannot be set to cancel, when the user wants? 
(please take the question politely, it may sound hursh, but by no means I'm trying that)

**Comment by mookid8000** [comment]
Wow, cool – I was not aware that there's was a `CancellationTokenSource.CreateLinkedTokenSource(..)` method. That definitely opens up some possibilities.

But let's go back to Rebus 😄 Rebus, as far as your application should be concerned, is something you START, and then at some point you `Dispose` it (either directly on `IBus`, or indirectly by disposing your IoC container).

If you want to hook the disposal of your bus up with a cancellation token, then it's out of the hands of Rebus, because it's something you happen to want to do in your application. In fact, it will automatically happen, because I bet Topshelf disposes your Autofac container, when it's shutting down.

Only thing missing in this puzzle is for Rebus to be able to cancel any long-running message handlers, which may happen to be handling messages at the shut-down time. 

Out of the box, Rebus will wait up to 30 s for executing handlers to finish, when shutting down*, but until now there hasn't been any way to cancel handlers, which would potentially run for longer than the shutdown-timeout dictated by Rebus' configuration.

Now, though, the incoming step context carries along with it Rebus' internal `CancellationToken`, which gets signaled when the bus is about to be disposed. I believe that that's a pretty good step forward.

I hope it's clear to you now that it's IS in fact possible to signal Rebus' internal `CancellationToken`, and the way to do it, is to dispose the bus (or the container hosting it). In that way, it's actually pretty simple.

Now, if there's something you feel is not possible to do, when it works like this, please explain some more about it. 😄 

---
(*) this is a configuration value you can tweak, if you like

**Comment by dariogriffo** [comment]
Great answer, everything is clear, I think we are on the same page, and probably is my fault, not explaining me correctly.

> Only thing missing in this puzzle is for Rebus to be able to cancel any long-running message handlers, which may happen to be handling messages at the shut-down time.

That's my proposal, if the internal token of Rebus is linked to an outisde world CancellationTokenSource (probably via configuration) and the handler implementation (via the context as you shown on the first gist) passess all the way down the token everything should go smoothly, and there is no need to shutdown after 30 seconds, things should stop immediately.

**Comment by mookid8000** [comment]
> Only thing missing in this puzzle is for Rebus to be able to cancel any long-running message handlers, which may happen to be handling messages at the shut-down time.

It would be more correct to say

> Only thing missing in this puzzle WAS for Rebus to be able to cancel any long-running message handlers, which may happen to be handling messages at the shut-down time.

because it's possible in 5.3.0-b1 as described – the `CancellationToken` is in the incoming step context, and cancellation is triggered by disposing the bus.

**Comment by mookid8000** [comment]
I just added a little convenient extension method to `IMessageContext` that makes it easy to fetch the `CancellationToken` by calling `GetCancellationToken`:
```csharp
public class LongRunningMessageHandler : IHandleMessages<SomeMessage>
{
	readonly IMessageContext _messageContext;

	public LongRunningMessageHandler(IMessageContext messageContext)
	{
		_messageContext = messageContext;
	}

	public async Task Handle(SomeMessage message) 
	{
		var cancellationToken = _messageContext.GetCancellationToken();

		// do something that takes a long time here
		await Task.Delay(TimeSpan.FromHours(24), cancellationToken);
	}
}
```

**Comment by MrMDavidson** [comment]
I know you don't want to modify `IHandleMessages<T>` (which makes sense given its very widespread use) but I wonder if it's worth while providing something like;
```C#
public interface IHandleCancellableMessages<T> : IHandleMessage<T> {
  Task Handle(T message, CancellationToken cancelToken);
}
```
The dispatching code would then be something like;

```C#
if (handler is IHandleCancellableMessages<T>) {
  await handler(message, context.GetCancellationToken());
} else {
  await handler(message);
}
```

(Disclaimer: Psuedo-C# written in the comment field, not compile tested)

**Comment by mookid8000** [comment]
Well.... I can definitely see how that could be done, and I've had the same thoughts about `IMessageContext` also:

```csharp
public class MyMessageHandler : IHandleMessagesWithContext<MyMessage>
{
	public async Task Handle(MyMessage message, IMessageContext context)
	{
		// ...
	}
}
```

but, you know, I have yet to see any really compelling arguments that tip the scale for me.....

**Comment by mookid8000** [comment]
Regarding tipping the scale: @MrMDavidson and @dariogriffo Your comments on this thread definitely add to the discussion 😄 let's see how things work out

**Comment by MrMDavidson** [comment]
There's lots of nifty stuff on the `IMessageContext` that's useful so I can see why you want to pass that in. However I would err on the side of passing the cancellation token in to the `Handle` method. Reason being is that most people expect async methods to follow the form `Task Handle[Async](SomeArg arg1, SomeArg2 arg2, SomeArg3 arg3, CancellationToken cancelToken)`. Having to hunt for that cancellation token hurts discoverability and increases dev effort for people simply consuming the library ("I know there's a cancel token somewhere... how do I get that again? Need to fire up my browser and look at the docs / examples"). I'd also worry that having the `IMessageContext` (especially with the ability to do `IncomingStepContext.Load<...>()`) starts to look a little bit like a service locator and would encourage future modifications to the library to just stash things in the step context for consumer devs to pull out. Don't take that as me being against the context - it's super useful when you're doing pipeline and transport work on Rebus. But in the context of a consumer of the library just wanting to process a message I think it makes it more difficult and less discoverable.

**Comment by dariogriffo** [comment]
I couldn't agree more with @MrMDavidson. I'm not even that close to the idea of having another handle interface for the sake of passing the cancellation token. Modifying current Handle is a massive breaking change? Yes. Versioning and documentation should be the primary aspect to focus.
In any case and whatever decision you make @mookid8000 I'm more than happy with Rebus and that users of this library can participate on this level of commitment.

**Comment by mookid8000** [comment]
Yeah, welll.....can't say that I disagree with you guys @MrMDavidson and @dariogriffo ... if I had made Rebus today, the handler interface should have looked like this:
```csharp
public interface IHandleMessages<in TMessage>
{
	Task Handle(TMessage message, CancellationToken cancellationToken);
}
```
and, actually, the NServiceBus naming should probably have been dropped also, so something like
```csharp
public interface IMessageHandler<in TMessage>
{
	Task Handle(TMessage message, CancellationToken cancellationToken);
}
```
or simply
```csharp
public interface IHandler<in TMessage>
{
	Task Handle(TMessage message, CancellationToken cancellationToken);
}
```
would have been nice.

**For now**, I'll keep the `CancellationToken` in the items dictionary, made available via the `GetCancellationToken()` extension method for `IMessageContext`.

We can always make that breaking change later. 

But please understand that I am not feeling 100% happy about this, I'm more like 70/30, or maybe even 60/40 that this is the right thing to do. 

I think alignment with how `CancellationToken`s are used everywhere else in .NET is the best argument _for_ adding it to the signature of the `Handle` method.

I'll keep this discussion slow-cooking in the back of my mind, and then I might change my mind. 😁

**Comment by dariogriffo** [comment]
That's perfectly fine, even more knowing the CT is on the MessageContext. 

> I think alignment with how CancellationTokens are used everywhere else in .NET is the best argument for adding it to the signature of the Handle method.

Agree 100%
So... we will wait and see
Thanks for all your time and effort on this!

**Comment by mookid8000** [comment]
This is out in Rebus 5.3.0 and 6.0.0-b03

Thanks for suggesting this great feature! 👍 😄

**Comment by arindamdat** [comment]
I am using Rebus 6.0.1. But I am not able to get the IMessageContext injected through the constructor of my handler. I get activation error `Cannot resolve parameter 'Rebus.Pipeline.IMessageContext messageContext' of constructor 'Void .ctor(Rebus.Pipeline.IMessageContext`

**Comment by mookid8000** [comment]
Which IOC container are you using?

**Comment by arindamdat** [comment]
Autofac

**Comment by mookid8000** [comment]
Could you tell me some more about the error? E.g. it would be nice to see the full stack trace from the error, and you could also show how you configured Rebus.

**Comment by marmagni** [comment]
Hi guys,

I also need to implement custom cancellation code to prevent default azure bus timeout of 5 minutes.

So to a generic way to do this, is using OOP.

```c#
public abstract class HandlerBase<TMessage> : IHandleMessages<TMessage>
{
        public Task Handle(TMessage message)
        {
            using (var tokenSource = new CancellationTokenSource(1000))
            {
                return Handle(message, tokenSource.Token);
            }
        }

        public abstract Task Handle(TMessage message, CancellationToken cancellationToken);
}
```

and then...

```c#
public class MyEventHandler : HandlerBase<MyEvent>
 {
            public override async Task Handle(MyEvent message, CancellationToken cancellationToken)
            {
                    //your code goes here...
            }
 }
```

**Comment by mookid8000** [comment]
One thing to note though: I'd be very surprised if this
```csharp
public Task Handle(TMessage message)
{
    using (var tokenSource = new CancellationTokenSource(1000))
    {
        return Handle(message, tokenSource.Token);
    }
}
```
would work, because the `CancellationTokenSource` is disposed immediately when returning the `Task` from `Handle(TMessage)`. If you await the call
```csharp
public async Task Handle(TMessage message)
{
    using (var tokenSource = new CancellationTokenSource(1000))
    {
        await Handle(message, tokenSource.Token);
    }
}
```
then the `using` block will work as intended.

**Comment by marmagni** [comment]
Yeah @mookid8000 you are right, I forgot await keyword, thk.
