### ISSUE TITLE
Pushing failed messages to the back of the queue x times before marking as poison

### ISSUE THREAD

**Issue by kyrrem** [rebus-org/Rebus#782]
I was considering extending the current error handling in Rebus with an option to putting messages back on the queue (retaining headers and all) x amounts of time before marking it as posion and sending it to the error queue.

Mainly this is to avoid filling up the error queue on short queue downtime due to networking or other external issues, giving the system a bit more time to recover. This could also resolve some failures related to getting messages out of order (i know you shouldn't rely on message ordering ideally, but it may still happen intentionally or not).

I was thinking of just registering a new IErrorHandler in the container, which can optionally push messages back with a header for retry count, then after x failures it forwards the message to the standard PoisonQueueErrorHandler. 

Does that sound like a good approach to you, or is there some other way that you more easily would accept as a PR to Rebus main? Also should I do this in release/5 or in master?

**Comment by mookid8000** [comment]
hi @kyrrem , sounds like an interesting feature!

I think it would be fairly simple to implement what you describe _without_ changing Rebus at all, simply by registering the new `IErrorHandler` as a decorator of the existing one.

The decorator would then do what you describe for the first _n_ attempts, and then it would defer the handling of the failed message to whatever it is decorating.

You could install the decorator like this:
```csharp
Configure.With(...)
	.(...)
	.Options(o => {
		o.Decorate<IErrorHandler>(c => new CustomRetryStrategyErrorHandler(c.Get<IErrorHandler>()));
	})
	.Start();
```
which you could then wrap in an extension method, so it could look like this:
```csharp
Configure.With(...)
	.(...)
	.Options(o => o.UseCustomRetryStrategyErrorHandler())
	.Start();
```

To begin with, I suggest you implement it in a separate project, and then we can consider adding it to Rebus core. How does that sound?

**Comment by kyrrem** [comment]
That sounds exactly like what we thought. 

I will try to implement this and give you a heads up when done in case you want to include it maybe as a plugin / extension package.

**Comment by mookid8000** [comment]
Hi @kyrrem , did you figure something out?

**Comment by mookid8000** [comment]
Hi again @kyrrem , don't know how far you got with this one... I'm closing the issue for now, but feel free to comment on it, if you feel like picking it up again 😄
