### ISSUE TITLE
Fallback to generic type definition to find message address

### ISSUE THREAD

**Issue by joffreynorsys** [rebus-org/Rebus#783]
Hello,

About routing, is a way to fallback to generic type definition (of generic message type) to find the destination address when the constructed generic type has no address ?

**Comment by mookid8000** [comment]
If you customize the router, you can implement that logic yourself.

You can implement [`IRouter`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Routing/IRouter.cs) and install it like this:
```csharp
Configure.With(...)
    .(...)
    .Routing(r => r.Register(c => new MyRouter()))
    .Start();
```
probably wrapping the `r.Register....` part in an extension method, so it can look like this:
```csharp
Configure.With(...)
    .(...)
    .Routing(r => r.UseMyRouter()))
    .Start();
```
and then your `IRouter` implementation can look at the `Message` and return whichever address it wants to.

Do you think that would work for you?

**Comment by joffreynorsys** [comment]
Oh great! I don't see this customization possibility...
I try this.

Thank you.
