### ISSUE TITLE
Deferred start capability

### ISSUE THREAD

**Issue by joffreynorsys** [rebus-org/Rebus#784]
Hello, 

I don't find this 5.0 feature : 

> Deferred start capability - call Create() instead of Start(), and the returned IBusStarter can be used to start message processing when it is desired to do so

Is not in the RebusConfigurer ?

**Comment by mookid8000** [comment]
`Create()` is an extension method from the `Bus.Startup` namespace. So if you add
```csharp
using Bus.Startup;
```
to the top of your file, you should be able to
```csharp
var starter = Configure.With(...)
    .(...)
    .Create();
```
followed by
```csharp
starter.Start();
```

**Comment by joffreynorsys** [comment]
Thank you.

I had already to deal with this using Routing.TypeBased.
Why not put all extensions configuration in the same namespace as `Configure` ?

**Comment by mookid8000** [comment]
> Why not put all extensions configuration in the same namespace as `Configure` ?

I asked myself that too – it's clearly not discoverable enough. I'll consider that for Rebus 6 🙂
