### ISSUE TITLE
Exception in periodic task "DueMessagesSender": "System.Collections.Generic.KeyNotFoundException: The given key 'rbs2-defer-recipient' was not present in the dictionary.

### ISSUE THREAD

**Issue by vegar** [rebus-org/Rebus#788]
I've setup a oneway bus using the filesystem, and are rewarded with a log slowly being filled up with the following exception:

```
2019-04-08 14:09:49.635 +02:00 [WRN] Exception in periodic task "DueMessagesSender": "System.Collections.Generic.KeyNotFoundException: The given key 'rbs2-defer-recipient' was not present in the dictionary.
   at Rebus.Pipeline.Receive.HandleDeferredMessagesStep.TimerElapsed()
   at Rebus.Threading.TaskParallelLibrary.TplAsyncTask.<>c__DisplayClass14_0.<<Start>b__0>d.MoveNext() in C:\projects-rebus\Rebus\Rebus\Threading\TaskParallelLibrary\TplAsyncTask.cs:line 82" { SourceContext: "Rebus.Threading.TaskParallelLibrary.TplAsyncTask" }
```

By inspecting the message, I can confirm that the `rbs2-defer-recipient` header is missing. But why is it missing, and why is it a problem that it is missing?

This is my bus setup:
```
config
  .Logging(cfg => cfg.serilog())
  .Routing(cfg => cfg.TypeBased())
  .Transport(cfg => cfg.UseFileSystemAsOneWayClient(options.FileSystemPath))
  .Subscriptions(cfg => cfg.UseJsonFile(options.SubscriptionFile)
  .Timeouts(cfg => cfg.UseFileSystem(options.FileSystemPath))
  ;
```

Example of message being sent:
```
{
    "Headers": {
        "rbs2-intent": "p2p",
        "rbs2-msg-id": "01b877ec-b91d-48d8-8970-f0f934cdcc2e",
        "rbs2-senttime": "2019-04-08T14:24:12.6341952+02:00",
        "rbs2-msg-type": "Common.Rebus.Messages.HelloWorldMessage, Common",
        "rbs2-corr-id": "01b877ec-b91d-48d8-8970-f0f934cdcc2e",
        "rbs2-corr-seq": "0",
        "rbs2-content-type": "application/json;charset=utf-8"
    },
   "Body": "eyIkdHlwZSI6IkNvbW1vbi5SZWJ1cy5NZXNzYWdlcy5IZWxsb1dvcmxkTWVzc2FnZSwgQ29tbW9uIiwiTWVzc2FnZSI6IldlYiBzZXJ2aWNlIHN0YXJ0ZWQifQ=="
}
```

**Comment by mookid8000** [comment]
Oh, it must be because your configuration includes the
```
.Timeouts(cfg => cfg.UseFileSystem(options.FileSystemPath))
```
part, even though it's a one-way client.

One-way clients _can_ defer messages into the future, but they must do that by sending their deferred messages to someone else (another endpoint with a timeout storage), or by using a transport that supports deferred messages natively (like e.g. Azure Service Bus).

I would have guessed that you would have seen some kind of error, preventing you from starting your client with this configuration, but apparently that didn't happen.

**Comment by mookid8000** [comment]
Another thing – this line:
```
.Routing(cfg => cfg.TypeBased())
```
doesn't really do anything like that, you need to make additional calls to it to set up your mappings – for example, to map the destination address for `SomeMessage` and set it to `queue-name`, you would call
```
.Routing(cfg => cfg.TypeBased().Map<SomeMessage>("queue-name"))
```

**Comment by vegar** [comment]
Thanks for very quick reply!

I guess this is situations you'll end up in when you are copy pasting others config without quite understanding what it does....

My real config is slightly more complicated then what I included in the issue: I have an `if / else` inside the `.Transport()`-step, either setting up a oneway or a regular bus based on a option value. Guess I need to include this check around the `.Timeout()`-step as well.

When it comes to the routing, I have a very special self made `TypeBasedRouterWithAttributeFallback`-implementation of `IRouter` that I use. It's basically a `TypeBasedRouter` that I've wrapped in `try { } catch { }`es. If the regular router throws because on missing map, I first check to see if the message class itself has a special attribute telling it's queue. If not, I re-throw the exception. 

The `TypeBasedRouter` didn't look like it was created with extension in mind, but it was sort of possible to decorate  based on exception message inspection.... ....guess I should have borrowed some code instead... ;-)

**Comment by mookid8000** [comment]
Ah, that makes sense 😄 

PS: If you want to be able to sent messages into the future with a one-way client, you need to configure it to use an "external timeout manager" like so:
```csharp
Configure.With(...)
    .(...)
    .Options(t => t.UseExternalTimeoutManager("timeoutmanager"))
    .(...)
```
where `timeoutmanager` is then the queue name of another endpoint that has a timeout storage configured.
