### ISSUE TITLE
Race condition of an IsNew=True Saga running for the first time, and emitting commands that correlate with itself

### ISSUE THREAD

**Issue by Plasma** [rebus-org/Rebus#795]
Hello,

We noticed in production a semi-occasional time where a Saga was seemingly emitting messages that were never processed. We identified the cause was that they were sent fine, but during processing were dropped during `LoadSagaDataStep`.

We noticed that when the Saga was IsNew = True (so the current handler was responsible for initiating this new Saga instance), and it sends some commands to be processed by the Bus, that correlate back to the Saga (via `IHandleMessages<T>`, notably, not `IAmInstantiatedBy<T>`), then Rebus can dutifully pick up that newly sent commands, and notice there is no correlating Saga (yet), and so discards the commands by skipping any further invocations (See https://github.com/rebus-org/Rebus/blob/master/Rebus/Sagas/LoadSagaDataStep.cs#L155-L156 ).

The reason it cannot find the Saga yet is because the original handler that was running was still in-flight and yet to persist the first Revision of the Saga Data to be correlated against.

**Comment by mookid8000** [comment]
That's very surprising. Rebus goes to great lengths to enforce carrying out actions in the following order:
1. receive message
1. invoke handler (i.e. create saga data, save it)
1. send outgoing messages
1. ACK the received message

Since the saga data is updated/inserted in step (2), and all outgoing messages are sent in step (3), then it should not be possible to experience a problem like the one you describe.

Which transport are you using?

**Comment by mookid8000** [comment]
Hi there @Plasma , have you had a chance to take a look at this?

**Comment by MrMDavidson** [comment]
We're still investigating an exact repro/work around for this but it looks to be the way we were preforming a send on the transport (we were not enrolling in the rebus context correctly). I'll provide an update in about 24 hours.

**Comment by mookid8000** [comment]
Excellent 👍

**Comment by mookid8000** [comment]
Hi @MrMDavidson , did you mean 24 days? 🤣 

Sorry, couldn't help myself there.... did you figure something out?

**Comment by mookid8000** [comment]
Closing this one now 😄 I assume you figured it out somehow. If not, please let me know.
