### ISSUE TITLE
EnforceExclusiveAccess on saga's hangs in some scenarios

### ISSUE THREAD

**Issue by sensoryoverload** [rebus-org/Rebus#797]
When registering saga's that share a sagadata class while also using EnforceExclusiveAccess, the bus will get stuck forever because there are duplicate SemaphoreSlim locks created in NewEnforceExclusiveSagaAccessIncomingStep.cs with the same id in the same thread.

I have added a console application that does just this:

https://github.com/sensoryoverload/RebusFailsAtEnforcingExclusiveAccessForSaga

There are various scenarios where this could happen. For example the BuiltinHandlerActivator allows registering the same saga twice and this will also fail.

A simple solution could be filtering the duplicates before setting the lock with .Distinct()

**Comment by mookid8000** [comment]
Thanks for the reproduction – the bug will be fixed in Rebus 5.3.1 and 6.0.0-b07

Both versions will be on NuGet.org as soon as the build server finishes munching through the tests.

Thanks for reporting this! 👍
