### ISSUE TITLE
Single Message Type Group Serial Processing?

### ISSUE THREAD

**Issue by jshurst** [rebus-org/Rebus#798]
First of all I just want to say that Rebus is on of the best architected and well written pieces of code that I’ve ever seen.  Kudos on making such a great project!

I have a question though.

I would like to do the following:

```
bus.Send(new UpdateStudentGrade { StudentId = 1 });
bus.Send(new UpdateStudentGrade { StudentId = 2 });
bus.Send(new UpdateStudentGrade { StudentId = 1 });
```

What I want to happen is that Student 1 and Student 2 run at the same time, but the second call to update Student 1 is queued until the first call to Student 1 has finished.  Both messages to update grades for Student 1 should not process at the same time (also, there could be thousands of students).

Is this possible?  I’m using SQL Server transport.

Thanks.

**Comment by mookid8000** [comment]
Thanks for the kind works 😄 

Unfortunately, Rebus does not provide a way to serialize the processing of certain messages. 

Usually, this kind of problem should be solved by handling concurrency in your data store, so e.g. if your handler for `UpdateStudentGrade` goes and updates data in your SQL Server database, you should carry out your work in an appropriate database transaction.

This way, one of the handlers will either wait for a database lock to be released before it can do its work, or it will experience a database deadlock exception and be rolled back and retried.

If you cannot do your work in a way that handles concurrency properly, then you can serialize all message processing completely, by setting number of workers = max parallelism = 1 like this:

```csharp
Configure.With(...)
	.(...)
	.Options(o => {
		o.SetNumberOfWorkers(1);
		o.SetMaxParallelism(1);
	})
	.Start();
```

Another option, which is slightly more involved (but is a natural way forward, if you find out that processing all of your messages serially does not work fast enough), is to introduce a content-based router, that load-balances your commands.

It would work like this:

![image](https://user-images.githubusercontent.com/32968/57220148-837c9d80-6ffa-11e9-8b5b-705dc91f9294.png)

where the router then forwards commands to an appropriate updater by doing a modulo on the student ID.

I hope this makes sense 😄

**Comment by jshurst** [comment]
Thanks for the reply, and you're right, I can probably just do a transaction around the datastore.  

I was hoping that I could turn Rebus into an actor-model like system  (I have a hammer called Rebus, it's solves all the things right?!  😄)

Something like:
`.Options(o => { o.EnableActorModel(actorIdProperty: "Id"); }); `

Or perhaps is implied from a base model with an Id property.
`ActorModelBase.Id = 1;`

I'll also investigate the content based router.

Thanks!

**Comment by mookid8000** [comment]
> I have a hammer called Rebus, it's solves all the things right?! 

Yeah, sure 😁 and like all hammers, it _can_ be used to punch screws in, but the result might not be pretty.

But, seriously: Handling concurrency in your data store is probably a good idea – Rebus or not. 😇
