### ISSUE TITLE
Working with queue and database Transactions

### ISSUE THREAD

**Issue by KorpEduardoSikora** [rebus-org/Rebus#800]
Hi, 

I have a scenario where don't know what is the best approach..

- I'm using database transaction (UnitOfWork) for my controllers and Handlers.
- I also want to implement queue [transactions ](https://github.com/rebus-org/Rebus/wiki/Transactions).

The scenario where I got stuck is the following:

I have both transactions active and I have to commit them, I could do it in two orders:
1. Commit database transaction.
2. Commit Rebus queue transaction.

What if the Rebus queue transaction generate an error?

The other order could be:
1. Commit Rebus queue transaction.
2. Commit database transaction.
	
What if the database transaction generate an error?

**Comment by mookid8000** [comment]
This is a good example of the trade-off you need to make – this is why, you're _forced_ to choose between

* at least once delivery, or
* at most once delivery

where 

"at least once" means implies that you risk receiving the same message twice, if there's an error in an unfortunate place, and

"at most once" implies that you risk _losing_ a message, if there's an error in an unfortunate place

You almost always want "at least once"!

Let me use your bullets as examples:

> I have both transactions active and I have to commit them, I could do it in two orders:
> 
> * Commit database transaction.
> * Commit Rebus queue transaction.
> 
> What if the Rebus queue transaction generate an error?

If the Rebus queue transaction fails (or something else prevents it from being fully committed), then it will be rolled back. No matter which Rebus transport you are using, an un-committed queue transaction will be rolled back at some point in time.

This means that you will eventually receive the same message again.

> 
> The other order could be:
> 
> * Commit Rebus queue transaction.
> * Commit database transaction.
> 
> What if the database transaction generate an error?

If your work transaction fails in this case (can happen for many reasons: bug in your code, database deadlocked, intermittent network outage, etc etc etc), then you will lose the message being handled, as it was already deleted from the queue.

So...

Rebus supports at-least-once delivery all the way through, by nesting transactions properly when calling your message handlers.

This means that you're always guaranteed that the last thing Rebus does (also when using the unit-of-work package), is to commit the queue transaction (or "ACK the message") for the message being handled.

In fact, it will also buffer all outgoing messages sent from your message handlers, meaning that the commit order is alway

1. your uow is committed
1. all outgoing messages are sent/published
1. the incoming message is ACKed

This also means that if you e.g. publish events saying "this and that happened", your uow will be committed before these events can be received in downstream systems.

I hope that clears it 😄

**Comment by KorpEduardoSikora** [comment]
> This means that you will eventually receive the same message again.

I understood what you meant, but my scenario/worry is on the "send/publish" commands, not when receiving them.

Imagine a scenario where I have 10 SQL commands and I do commit them (the database would be modified). Then the next thing I do is try to publish messages, and at the commit statement some error occurs.. as the following code shows:

```csharp
UnitOrWork.commit;
using(var scope = new RebusTransactionScope())
{
    await bus.publish(firstMessage);
    await bus.publish(secondMessage);
    await scope.CompleteAsync();  // any kind of errors occurs
}
```

What do I do about the commited sql?
The same problem if I move the "UnitOrWork.commit;" command to the end of the method and it throws an error..

**Comment by mookid8000** [comment]
Ah, ok – I didn't understand that that was the scenario.

The thing that differs then, is that you're most like performing your database transaction and sending/publishing your messages from "an unsafe place", e.g. like a web request or something like that.

If you want to be absolutely sure that all of your work is done, then you need to send a single command message, and then do your 10 SQL commands and send/publish any outgoing messages from the handler of that command message.

**Comment by KorpEduardoSikora** [comment]
I beliebe I did not fully understand what you meant by "a single command message".

Even if I send a "single command message" first, isn't there a remote possibility of it failing too?

I just want to build my framework evaluating the extremes scenarios..

**Comment by mookid8000** [comment]
> Even if I send a "single command message" first, isn't there a remote possibility of it failing too?

Oh yeah, sure – but the point is that the least likely thing to fail is often your message queue, as it's not capable of deadlocking and stuff like that. Also, many brokers come in high available configurations, because it's just easier to build software when your queues are super-available.

You can of course have retries around the send operation for that single message if you want, or you can just bubble the error up to whichever client triggered the thing – the important thing here is that _the operation is atomic_, so it's not possible for it to end up in an inconsistent state.
