### ISSUE TITLE
Proper way to publish from a non-async context

### ISSUE THREAD

**Issue by ronnyek** [rebus-org/Rebus#801]
Greetings! I've been doing some experimentation to troubleshoot a coworkers issue. 

Basically the jist of it it is that he's got a timer (system.timer) and from that timeer elapsed event, hes trying to publish a new message. 

To accommodate the fact that Publish is async, we've tried just about everything from bus.Publish(message).GetAwaiter().GetResult(), or .Result(), or .Wait().

I'm basically seeing that either messages dont get sent with no indication why, or I get this exception...

```
Rebus.Exceptions.RebusApplicationException: 'Could not 'GetOrAdd' item with key 'rabbitmq-outgoing-messages' as type System.Collections.Concurrent.ConcurrentQueue`1[Rebus.RabbitMq.RabbitMqTransport+OutgoingMessage]'

```

I'm not currently using any explicit transaction support, so I'm honestly not super sure where this is coming from.

Any advice would be greatly appreciated.

**Comment by ronnyek** [comment]
the exception may be unrelated, I'm just trying to find ways to make sure I'm using library as intended, and hopefully prevent the less experienced dev from encountering the same issues.

**Comment by mookid8000** [comment]
Sure thing!

I suggest you use Rebus' synchronous API:
```csharp
var syncBus = bus.Advanced.SyncBus;
```
It has synchronous implementations for all methods of `IBus` – e.g. `Publish`
```csharp
syncBus.Publish(yourEvent);
```

I have no idea what that error you're seeing is about – let's see what happens when you use the sync API. 😄

**Comment by ronnyek** [comment]
I was totally unaware the SyncBus existed... so that works a treat, and good to know there's a better way to send more explicitly from non async context.

Regarding that error, that sending via SyncBus did not resolve the error, but I rebuilt the test to simplify, and the error went away. It may be something with timing. I had a test that would receive a message, increment a processed count and then at once a certain number was reached, it stopped re-sending... so its possible I was trying to send messages too rapidly, or I don't know.
