### ISSUE TITLE
Using MessageContext within RebusTransactionScope on incoming pipeline to invoke handler throws error

### ISSUE THREAD

**Issue by EduSikora** [rebus-org/Rebus#804]
Hi,

We've encoutered a strange error when using the "MessageContext.Current.Headers" within a "RebusTransactionScope" on the incoming pipeline, before invoking the handler.

Take a look below:

![image](https://user-images.githubusercontent.com/21113262/58433789-186d3680-808f-11e9-970d-15101d2e4cf7.png)

Within RebusTransactionScope
![image](https://user-images.githubusercontent.com/21113262/58433856-579b8780-808f-11e9-935a-2175bbb12e95.png)

I've created a small example of this happening:
https://github.com/EduSikora/Rebus-Tests

**Comment by mookid8000** [comment]
oh.... please don't create a `RebusTransactionScope` inside a Rebus handler – it's purely meant to be used outside of Rebus handlers.

Inside a Rebus handler, everything you do to `IBus` (`await bus.Send(...)`, `await bus.Publish(..)` etc) is enlisted in the handler's transaction, ensuring that outgoing messages are sent AFTER your handler has successfully finished executing.

`RebusTransactionScope` is meant to be used e.g. in a web application, where you might want to allow for controllers to use `IBus` and send/publish messages and them commit them atomically(*) after the controller's action has executed.



---
(*) Rebus will use the underlying transport's transactions when available, so e.g. MSMQ can send a batch of messages and commit the work as a single atomic operation. Other transports emulate this behavior and might not actually send the messages atomically.

**Comment by EduSikora** [comment]
Oh, okay!!

Thanks for the explanation @mookid8000!!
