### ISSUE TITLE
Deferred InMemory Message does not get redelivered

### ISSUE THREAD

**Issue by JonnyBooker** [rebus-org/Rebus#807]
### Behaviour
I am throwing a exception inside a message handler and I have secondLevelRetry logic which should defer the message for a period of time, however it seems that after deferral there is no re-delivery.

### Scenario
I have created a test harness for this scenario to show this issue:

```c#
void Main()
{
	using (var activator = new BuiltinHandlerActivator())
	{
		var busStarter = Configure.With(activator)
			.Subscriptions(s => s.StoreInMemory(new InMemorySubscriberStore()))
			.Options(options =>
			{
				options.SimpleRetryStrategy("logging-error", 1, true);
			})
			.Transport(t => t.UseInMemoryTransport(new InMemNetwork(), "logging"))
			.Create();

		var handler = new TestClassHandler(activator.Bus);
		activator.Bus.Subscribe<TestClass>();
		activator.Register(() => handler);

		using (var bus = busStarter.Start())
		{
			bus.Publish(new TestClass
			{
				Id = Guid.NewGuid()
			});

			Console.ReadLine();
		}
	}
}

private void AddMessageQueueLogEventDetailsHandler(BuiltinHandlerActivator activator)
{
	var handler = new TestClassHandler(activator.Bus);

	activator.Bus.Subscribe<TestClass>();
	activator.Register(() => handler);
}

// Define other methods and classes here
public class TestClass
{
	public Guid Id { get; set; }
}

public class TestClassHandler : IHandleMessages<TestClass>, IHandleMessages<IFailed<TestClass>>
{
	private readonly IBus _bus;

	public TestClassHandler(IBus bus)
	{
		_bus = bus;
	}

	public Task Handle(TestClass message)
	{
		throw new Exception("Test Exception");
	}

	public async Task Handle(IFailed<TestClass> message)
	{
		await _bus.Defer(TimeSpan.FromSeconds(5), message);
	}
}
```

### Expected Behaviour 
I would expect redelivery of the message after the duration specified

**Comment by mookid8000** [comment]
What do your logs say?

Judging by the code you posted, I would believe that your 
```csharp
await _bus.Defer(TimeSpan.FromSeconds(5), message);
```
would fail with an error saying something like "don't know where to send FailedMessageWrapper, because that type has not been mapped", or something like that.

What you want is probably
```csharp
await _bus.Defer(TimeSpan.FromSeconds(5), message.Message);
```
because you want to defer the message, and not the wrapper.

Moreover, maybe you even want to
```csharp
await _bus.DeferLocal(TimeSpan.FromSeconds(5), message.Message);
```
so that you set yourself as the recipient, no matter which queue you're using.

I'm closing this issue for now – please feel free to come back here, if what I wrote didn't help you 😄

**Comment by JonnyBooker** [comment]
I didn't notice I'd done that... I did have it correct originally but this harness program is wrong 😆 

So I corrected the program and wrapped the `Defer` in a try catch and found it was still throwing a "not mapped" exception for my `TestClass`. I added a routing for it via the following line added to the activator:
```c#
.Routing(r => r.TypeBased().Map<TestClass>("logging"))
```
Which then led me to this error:
> System.InvalidOperationException: A timeout manager has not been configured. Please configure a timeout manager with the .Timeouts(...) configurer, e.g. like so:

At which time I added the timeout line:
```c#
.Timeouts(t => t.StoreInMemory())
```
And this all made it work! 

However I took your advice and used the `DeferLocal` which meant I could remove the routing line of code which I find more preferable.

Still a little confused why exactly the type needed to be "route mapped" even though it had already been dispatched to that handler fine. 

Thank you for the help!

**Comment by mookid8000** [comment]
> Still a little confused why exactly the type needed to be "route mapped" even though it had already been dispatched to that handler fine.

It's because the message was `Publish`ed, which routes messages (events) to everyone who `Subscribe`d to it... if the sender had used `await bus.Send(theMessage)`, then it would have required an endpoint mapping.
