### ISSUE TITLE
JSON sample message

### ISSUE THREAD

**Issue by rnarayana** [rebus-org/Rebus#812]
I've been trying to replace MassTransit with Rebus, and I've a JavaScript publisher, and .NET receiver (earlier MT, now trying to move to Rebus). Is there a sample JSON that can be used for publishing? I went through the Hearders and Body in TransportMessage class, still not sure what should be the format if sending as JSON via a JavaScript publisher.

I'm using Azure Service Bus.

**Comment by mookid8000** [comment]
Don't think there's a sample anywhere, but it's not hard: Check out the wiki page about [wire-level format of messages](https://github.com/rebus-org/Rebus/wiki/Wire-level-format-of-messages) for a start.

To make Rebus happy when you compose your transport message, you need to provide a `rbs2-msg-id` header with a unique message ID (probably just `Guid.NewGuid().ToString()`). This is enough to enable Rebus to try to consume your message.

Then, depending on which serializer you're using, you need some extra things. E.g. if you're using the built-in JSON serializer, you need to provide a `rbs2-content-type` header with a proper MIME type/encoding for the contents, most likely `application/json;charset=utf-8`, as well as the `rbs2-msg-type` header with the name of a .NET type to deserialize into. Anything that can be resolved with `Type.GetType(name)` can be used, so e.g. a short assembly-qualified type name is perfect: `SomeAssembly.SomeNamespace.SomeMessage, SomeAssembly`.

**Comment by mookid8000** [comment]
Btw. all of Rebus' known headers are listed and documented here: [`Headers.cs`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Messages/Headers.cs)
