### ISSUE TITLE
Send message to very specific consumer

### ISSUE THREAD

**Issue by ronnyek** [rebus-org/Rebus#813]
So generally I've been able to get away with using publish/subscribe, and reply... but we've got a new use case that I'd like to know how best to support.

We've got this concept of agents that spin up and connect and end up round robin-ing load as they all consume the same queue etc. This is how we generally WANT things to work.

Now we have a need to notify a very specific agent of something. I'm wondering if rebus has some concept of being able to send a message directly to an agent based on some criteria.

I believe mass transit has a concept of send, where you specify a queue to dispatch the message to. I feel like I could h ave an agent id and publish, and have agents abort processing the message if they arent that agent, but seems like it'd have potential of hitting retry limit etc.

I feel like I must be missing something in the documentation.
(I realize dispatching messages to specific consumers is generally bad, and will definitely inhibit scalability etc... this is a unique scenario software, and likely the only place we'll need to be able to do this.)

**Comment by mookid8000** [comment]
Sorry, but to me publish/subscribe + reply sounds a little funny.

How can an event (i.e. a statement that something occurred, e.g. like "order was processed", "package was shipped", "document returned from signing service", etc.) result in a reply?

When you publish an event, the publisher should not care whether 0, 1, or n subscribers get the event, and if some of them suddenly reply, then I think that would be pretty crazy.

Or maybe there's something I'm missing completely here?

Regarding the "notifying a specific agent" problem, Rebus has some functionality that you might want to look into.

First off, the ability to send a command/request to one single recipient:
```csharp
await bus.Send(new SomeCommand(...));
```
or
```csharp
await bus.Send(new SomeRequest(...));
```
Rebus then requires that the sender be configured with an "endpoint mapping", which is basically a mapping from the message type (here `SomeCommand` or `SomeRequest` to the destination queue), which can be done like this:
```csharp
Configure.With(...)
	.(...)
	.Routing(t => t.TypeBased()
		.Map<SomeCommand>("command-processor")
		.Map<SomeRequest>("request-processor")
	)
	.Start();
```
When you send commands/requests like this, Rebus will throw an error if it doesn't know where to send the message, so you're sure to never lose it like a publisher could have, if noone subscribed.

This way of sending lends itself well to "command processing" or "request/reply" type of messaging, where you either send commands for some work to be carried out, or you send a command (a "request" in this case) where the processing yields a result of some kind... e.g. if the recipient is a ["channel adapter"](https://www.enterpriseintegrationpatterns.com/patterns/messaging/ChannelAdapter.html) in front of an external system.

Btw. if you do not feel like using Rebus' built-in endpoint mappings mechanism, you can easily implement your own routing, e.g. by simply sending messages directly to their destination queue:
```csharp
await bus.Advanced.Routing.Send("some-queue", new SomeCommand(...));
```
