### ISSUE TITLE
Documentation Request: Unit tests for steps

### ISSUE THREAD

**Issue by Kizmar** [rebus-org/Rebus#814]
Would it be possible to get an example of a unit test for a custom IIncomingStep? OutgoingStep too for that matter?

Currently trying to go off the testing documentation and the incoming step never gets hit. Not sure what I'm missing. Thanks. :)

**Comment by mookid8000** [comment]
That's a great idea 😄 I'll put it on the backlog

**Comment by mookid8000** [comment]
I've written some docs on it now: https://github.com/rebus-org/Rebus/wiki/How-to-test-incoming-and-outgoing-steps

Check it out and see if you think something is missing. 🙂
