### ISSUE TITLE
Redesign TransactionContext

### ISSUE THREAD

**Issue by jods4** [rebus-org/Rebus#824]
Seeing that you are doing breaking changes for Rebus 6, maybe it's the appropriate time to consider tweaking `ITransactionContext`?

1. As it stands (let's revisit this down below); `ConcurrentDictionary<string, object> Items` is exposing the implementation of `ITransactionContext` and prevents any improvements.
It would be better if the interface exposed operations such as `TryGet`, `GetOrAdd`, `Remove` and hides how the context is implemented.

Just like the `ConcurrentQueue`s I've replaced, `ConcurrentDictionary` is way too heavy for its usage here. Considering that the context usually contains almost no items (< 10, or < 5 even) and that its use is typically "initialize" then "read-only"; it would be better to use a `SortedList` protected with a `ReaderWriterLockSlim`.

2. The whole API doesn't feel right to me.
For example, you can add `OnDispose` actions, typically to dispose a resource (e.g. connection) that you've put in the context, hence transferring ownership.
The API lets you take out resources from `Items`, yet there's no way to remove an `OnDispose` action.
If the context is always transferring ownership then it would be better to not have `OnDispose` at all and automatically dispose all `IDisposable`s found in `Items`.
Going further, the transports I've looked at all seem to use the context in a `GetOrAdd` mode simply because there's no "init" phase.

If transports could register a specific, transient `ITransactionContext` in the context; then you could inject this context instead and it would get initialized before first use and manage its own resources. That would be cleaner and more efficient.

3. Nit: looking at `RebusTransactionScope`, I think it could inherit from `TransactionContext` directly instead of wrapping it. 
In the current codebase it would remove one allocation and one indirection; and work exactly the same.

4. Finally a question: how can you escape the ambient Rebus transaction scope?
The API seems to be using a new `RebusTransactionScope` but this is not safe if you're forking work.
That new `AmbientTransactionContext` will be seen by all other threads working in the same async context, and it's not what you want.

**Comment by mookid8000** [comment]
I'll work my way backwards through these 😁 

> 4. Finally a question: how can you escape the ambient Rebus transaction scope?

Rebus 6.0.0-b18 lets you do this:
```csharp
using(new RebusTransactionScopeSuppressor())
{
    // do stuff with IBus without being enlisted in an ambient transaction
}
```

**Comment by mookid8000** [comment]
> 3. Nit: looking at RebusTransactionScope, I think it could inherit from TransactionContext

It once did, but I found it confusing that is was both a "scope" and a "transaction context". I find it kind of idiomatic in .NET to have a "scope" be something you do this to:
```csharp
using (var scope = new RebusTransactionScope())
{
    // we're in a scope now!
)
```
where "context" is more like something that gets passed to methods in objects with different lifestyles than said context:
```csharp
public async Task Process(IncomingStepContext context, Func<Task> next)
{
    // a "context" is passed to us in here
    await next();
}
```

**Comment by mookid8000** [comment]
(2) and (1): You may be right about this. This could definitely be something to address in the future, but for now I don't feel like changing these things.

I _could_ probably be persuaded by a PR or two, but these are not high up on my prioritized list of things to do right now.

And with that, I'm going to close this issue 🙂 thanks for raising it, and feel free to object if you disagree.
