### ISSUE TITLE
Package description missing for Rebus NuGet packages

### ISSUE THREAD

**Issue by boskjoett** [rebus-org/Rebus#827]
The package description for all Rebus NuGet packages is the default text "Package Description".
It would be nice with a real description of what each NuGet package contains and does.

**Comment by mookid8000** [comment]
So true! 😁

**Comment by mookid8000** [comment]
TODO:

- [ ] Rebus
- [ ] Rebus.ActiveMq
- [ ] Rebus.AmazonS3
- [ ] Rebus.AmazonSQS
- [ ] Rebus.Async
- [ ] Rebus.Autofac
- [ ] Rebus.AutoScaling
- [ ] Rebus.AzureBlobs
- [ ] Rebus.AzureQueues
- [ ] Rebus.AzureServiceBus
- [ ] Rebus.AzureStorage
- [ ] Rebus.CastleWindsor
- [ ] Rebus.Ceras
- [ ] Rebus.Consul
- [ ] Rebus.DryIoc
- [ ] Rebus.Events
- [ ] Rebus.Hagar
- [ ] Rebus.Jil
- [ ] Rebus.LightInject
- [ ] Rebus.Log4net
- [ ] Rebus.MessageValidation
- [ ] Rebus.Microsoft.Extensions.Logging
- [ ] Rebus.MongoDb
- [ ] Rebus.MsgPack
- [ ] Rebus.Msmq
- [ ] Rebus.MySql
- [ ] Rebus.Ninject
- [ ] Rebus.NLog
- [ ] Rebus.Oracle
- [ ] Rebus.Owin
- [ ] Rebus.PostgreSql
- [ ] Rebus.Protobuf
- [ ] Rebus.RabbitMq
- [ ] Rebus.RavenDb
- [ ] Rebus.Serilog
- [ ] Rebus.ServiceProvider
- [ ] Rebus.SimpleInjector
- [ ] Rebus.SqlServer
- [ ] Rebus.StructureMap
- [ ] Rebus.TestHelpers
- [ ] Rebus.TransactionScopes
- [ ] Rebus.UnitOfWork
- [ ] Rebus.Unity
- [ ] Rebus.Wire
- [ ] Rebus.XmlConfig

**Comment by mookid8000** [comment]
all done!
