### ISSUE TITLE
TPL worker factory doesn't set CancellationToken inside IncomingStepContext

### ISSUE THREAD

**Issue by tompazourek** [rebus-org/Rebus#832]
I know that TPL-based workers are still only WIP and experimental in v6, but I noticed that when they are used, the `IncomingStepContext` is missing the `CancellationToken`.

I'm not sure if this is a known issue or not, but it can cause a hard to spot bug, because if you try to resolve the `CancellationToken` (either via `Load` from the `IncomingStepContext`, or via the extension method), it still returns the default value of the `CancellationToken` struct, even when the token is not present in the step context dictionary.

That means you'll actually get a cancellation token, but that token's cancellation will never be requested as it's a new default instance created every time it's loaded. This is because the `Load<T>` method returns `default` when it doesn't find the type:

```
/// <summary>
/// Loads the instance stored under the specified key. Returns null if none could be found.
/// </summary>
public T Load<T>(string key)
{
    object instance;
    return _items.TryGetValue(key, out instance)
        ? (T)instance
        : default(T);
}
```

Even the xmldoc comment says `Returns null if none could be found.`, which is actually not correct. In the case of `CancellationToken`, it returns a default instance if it's not found, which causes all this unexpected behaviour.

**Comment by mookid8000** [comment]
you are absolutely right 😁 and I've fixed it in Rebus 6.0.0-b17
