### ISSUE TITLE
Customizing routing key bind in input queue - RabbitMQ

### ISSUE THREAD

**Issue by kewinbrand** [rebus-org/Rebus#834]
Hey,

Is there a way to use a different routing key than the InputQueueName when binding the input queue? 
I guess there should be a field in the options (RabbitMq*OptionsBuilder) to tell what routing key to use. Not sure how this would work in other transports.

What do you think?

**Comment by kewinbrand** [comment]
Hi,

I solved it another way :sweat_smile:.
Thank you

**Comment by mookid8000** [comment]
Hi @kewinbrand , sorry for not replying .... have been bogged down with work for a while now.

Good to hear you solved it 😄
