### ISSUE TITLE
How to implement a new Transport Mechanism?

### ISSUE THREAD

**Issue by MercedeX** [rebus-org/Rebus#840]
I wish to use custom In-Memory Transport, NetMQ and also use LiteDB for persistence. Where should I start? Is there any sample or documentation that might be helpful?

**Comment by mookid8000** [comment]
You can start by deriving from [AbstractRebusTransport](https://github.com/rebus-org/Rebus/blob/master/Rebus/Transport/AbstractRebusTransport.cs), which will give you in-mem buffering of outgoing messages.

You can then create a suite of contract tests by importing the [Rebus.Tests.Contracts](https://www.nuget.org/packages/Rebus.Tests.Contracts) NuGet package, this way ensuring that your transport behaves as it should.

And then you should simply look at the current transport implementations. 🙂 and then you can ask here, if you have any questions 😃
