### ISSUE TITLE
Is it possible to disable Polymorphic-message-dispatch ? 

### ISSUE THREAD

**Issue by sabbadino** [rebus-org/Rebus#842]
Is it possible to disable this feature ? 
https://github.com/rebus-org/Rebus/wiki/Polymorphic-message-dispatch

My messages have an inheritance chain that was done only for convenience to avoid duplication of code ( properties), 
for example : 
class messageupdate {
....
}

class messageadd : messageupdate {
....
one more property
}

and , of course I got the messageupdate notifications both from a subscription to messageadd   and messageupdate 

thank you 
enrico

**Comment by mookid8000** [comment]
It's not readily possible, but since it's entirely up to the "handler activator" (the adapter for whichever IoC container you're using), it's definitely possible to e.g. implement your own container adapter that doesn't do contravariant resolve.

**Comment by mookid8000** [comment]
IIRC the Autofac container actually _doesn't_ do contravariant resolve ootb, as it's something that must be explicitly enabled... so maybe you could try that?
