### ISSUE TITLE
Polymorphic Routing

### ISSUE THREAD

**Issue by CzechsMix** [rebus-org/Rebus#844]
Ideally I'd like to expose my events as interfaces only, and encapsulate the concrete type within the publisher.

I did something like this

```csharp
IPublisherEvent @event = new PublisherEvent("Hello from Publisher!");
bus.Publish(@event);
```

And my subscribers subscribed to IPublisherEvent,

but the bus didn't find any subscribers because the type based router asked for subscribers to the concrete type.

Is what i'm looking for possible, or is there some way to force the bus to publish as the interface type?

**Comment by mookid8000** [comment]
Rebus gets a topic name for published events from its ["topic name convention"](https://github.com/rebus-org/Rebus/blob/master/Rebus/Topic/ITopicNameConvention.cs), by default implemented like this: [DefaultTopicNameConvention.cs](https://github.com/rebus-org/Rebus/blob/master/Rebus/Topic/DefaultTopicNameConvention.cs).

You can register your own topic name convention like this:
```csharp
Configure.With(...)
	.Transport(t => ...)
	.Options(o => o.Register<ITopicNameConvention>(c => new MyTopicNameConvention()))
	.Start();
```
most likely hiding the ugly parts behind an extension method on `OptionsConfigurer`, so you get a nice configuration API like this:
```csharp
Configure.With(...)
	.Transport(t => ...)
	.Options(o => o.UseMyTopicNameConvention())
	.Start();
```
So, with a little bit of type reflection, you should be able to make it work for you 🙂

**Comment by mookid8000** [comment]
❗️❗️❗️
Btw. for the love of God and everything asynchronous, please remember to `await`:
```csharp
await bus.Publish(@event);
```
or else you will not know when/if anything fails.
❗️❗️❗️ 
(or use the synchronous API:
```csharp
var syncBus = bus.Advanced.SyncBus;

syncBus.Publish(@event);
```
... or maybe that was what you were doing? oh well, I'll leave this here in case anyone comes by 😄 )

**Comment by CzechsMix** [comment]
Thanks for the quick reply! Loving the library so far.

**Comment by mookid8000** [comment]
@CzechsMix good to hear 🙂

**Comment by CzechsMix** [comment]
Pursuant to this question, would it ever make sense to publish an event to multiple topics?

```csharp
interface ISomeEvent { }
interface ISomeOtherEvent { }
class SomeCompositeEvent : ISomeEvent, ISomeOtherEvent { }
```

Imagine Service A subscribes to ISomeEvent, and Service B Subscribes to ISomeOtherEvent,
Currently, ITopicNameConvention returns a single string per Type (default being the full assembly name of each type). Both Service A and Service B would need to subscribe (and knowledge of) the concrete composit type. But to execute this scenario with interface based topics, the bus would want to get multiple topics (ISomeEvent and ISomeOtherEvent), and publish the message to each one.

This feels like a breaking change, (ITopicNameConvention would need to return IEnumerable<string>) but I was curios to see if there was another reason I hadn't thought of that publishing composite events to multiple topics is a bad idea?

**Comment by mookid8000** [comment]
Well...... I can see why it would make sense in your scenario, but I think you could fairly easily accomplish something like that if you wrapped the bus (possibly as a decorator of `IBus`) and then used its topics API to publish the events (more than once when desired):
```csharp
async Task Publish(object evt)
{
	var topicsApi = bus.Advanced.Topics;
	var topicsToPublishTo = FigureThatOut(evt);

	await Task.WhenAll(topicsToPublishTo
		.Select(topic => topics.Publish(topic, evt)));
}
```
