### ISSUE TITLE
Duplicated message when using Defer

### ISSUE THREAD

**Issue by arielmoraes** [rebus-org/Rebus#847]
We are having an issue with the Defer messages flow, some messages are being duplicated (same message Id in the queue), the problem is we don't know yet what is the root cause.

@mookid8000 do you have any advice?

**Comment by mookid8000** [comment]
What is your setup like ?

**Comment by mookid8000** [comment]
Hi @arielmoraes , could you maybe tell me more about what your setup is like?

E.g. which timeout storage are you using?

Do you have multiple Rebus instances sharing the same timeout storage?

Etc.

**Comment by mookid8000** [comment]
hi @arielmoraes , I'm closing this issue for now – feel free to get back to it when you have more information about the issue 🙂

**Comment by arielmoraes** [comment]
hi @mookid8000, sorry for the long delay. We are trying to figure out what I've described in this issue because now we are using the Sql Server Timeout Manager, and we are facing the exact same scenario as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/6741634/107056568-3a4e1480-67b1-11eb-925d-3103e79b1c58.png)

As we can see in the screenshot the table that stores the Defered Messages have multiple records with the same msg-id.

Do you have any advices on what or where to look?

**Comment by mookid8000** [comment]
> Do you have any advices on what or where to look?

Not really, no. Please tell me anything you can think of about what your're doing.

E.g. show me how you defer the message, tell me exactly how your stuff is configured, etc. etc.

**Comment by arielmoraes** [comment]
**Configuration:**

![image](https://user-images.githubusercontent.com/6741634/107065315-640c3900-67bb-11eb-9ed8-c648ef951569.png)

**Handler:**

![image](https://user-images.githubusercontent.com/6741634/107065397-7be3bd00-67bb-11eb-894a-5ed27d40cedb.png)

We use a distributed lock to update some resource and if the lock was not available we defer the message.

**Comment by mookid8000** [comment]
> could that cause the defer flow to not end properly?

Well... if the program execution was killed multiple times right after deferring the message, then it would end up looking like the symptoms you describe. The incoming message would not be ACKed, and then it would arrive again when the program started up again (or be handled by another instance).

Could there be something that causes your program to crash after having deferred the message but before ACKing the incoming message?

> Is the SqlServerTimeoutManager thread safe when running multiple instances?

Yes. 🙂
