### ISSUE TITLE
Return to source queue tool

### ISSUE THREAD

**Issue by donig** [rebus-org/Rebus#849]
The return to source queue tool page has a bad link to the tool.

Wiki page: https://github.com/rebus-org/Rebus/wiki/Return-to-source-queue-tool

Link: You can download it here (MSMQ): http://mookid.dk/oncode/wp-content/2013/06/returnToSourceQueue.msmq_.zip

**Comment by mookid8000** [comment]
Thanks – I've updated the page to reflect the current situation. 🙂
