### ISSUE TITLE
Improve support for a "shared nothing" approach to messages

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#852]
With Rebus, you're encouraged to model your messages as .NET classes that are automatically serialized/deserialized when you exchange them.

My own preference for sharing these contracts is very simple: Each message type owner is published with an accompanying, appropriately versioned NuGet package containing the relevant message types.

While this approach is simple and pragmatic, it also has some downsides. Sometimes, it can be nice to be able to exchange messages without sharing *anything at all*, besides the knowledge of a contract in the form of

1. queue names
1. topic names
1. layout of one or more message types

I'll just briefly mention how each of the mentioned elements go into a contract.

#### 1. Queue names
 Queue names are part of the contract in a very simple way: When a sender does a
```csharp
await bus.Send(new SomeCommand(...));
```
it needs to know where to send this message. Of course the code shown above can be happily oblivious, but *the bus needs to know*, which is why we use endpoint mappings:
```csharp
Configure.With(...)
	.(...)
	.Routing(r => {
		r.TypeBased()
			.Map<SomeCommand>("some-queue");
	})
	.Start();
```
This is part of the contract between systems, as a sender needs to know the correct queue to send its commands to. But this is already very simple, as the knowledge about specific queue names IS the contract.

#### 2. Topic names
Similar to queue names, topic names are part of the contract between services, because this is how publishers and subscribers find eachother. While this can be as simple as
```csharp
await bus.Advanced.Topics.Publish("some-topic", new SomeEvent());
```
in the publisher, and
```csharp
await bus.Advanced.Topics.Subscribe("some-topic");
```
in the subscriber, thus allowing for publishers and subscribers to connect using knowledge about the presence of a topic named `some-topic` , *this is not the preferred approach with Rebus*, as you're very much encouraged to use .NET type names as topics.

This happens automatically, as
```csharp
await bus.Publish(new SomeEvent());
```
will publish the event to *a topic named after the full .NET type name*, e.g. something like `MySystem.Messages.SomeNamespace.SomeEvent, MySystem.Messages`.

As the subscriber (by default) uses the same topic naming strategy, it can simply
```csharp
await bus.Subscribe<SomeEvent>();
```
to subscribe to that topic, *but this will only work if the type comes from the same assembly.

#### 3. Message types

When a message is sent and/or received, the sender and the receiver need to agree on how to represent and interpret the payload, i.e. how to serialize/deserialize, and the layout of the serialized contents.

It's pretty obvious that a sender cannot simply send
```json
{
    "gimme": [
        {"what": "imperial stout", "count": 6}
    ]
}
```
or
```
0xDC13B5FCRF1B5CD3FC5B9FCD5BCFD51534329462912BBCFFDFEFDBFD3B2F6BBD32F671DD3321DAA
```
when the receiver expects
```json
{
    "items": [
        {"sku": "78342", "count": 6}
    ]
}
```
in a "process order" command.

By default, Rebus assumes that message types are shared (as in a shared DLL, e.g. distributed as a NuGet package), because 

1. topics are named after the full .NET types, and
1. the default serializer puts full .NET type information in the message headers, and
1. the default serializer puts full .NET type information into the message body

### How Rebus can support "shared nothing"

It follows from this that we need to

1. not use full .NET type information as topic names, and
1. not use full .NET type information in message headers, and
1. not use full .NET type information in message bodies

Rebus has two extensibility points that can be used to make this happen: 

1: `ITopicNameConvention`, which gets to decide how Rebus maps .NET types to their corresponding topic names.
2: `ISerializer`, which gets to decide how message headers and bodies are encoded/decoded.

The shared nothing-implementations of these things would need some kind of convention and/or type name mapping configuration to be able to work. Some example approaches could be:

1. Convention using the class name – e.g. `SomeEvent`
1. Convention using the class with its namespace, minus the assembly – e.g. `SomeNamespace.SomeEvent`
1. Configuration for each message type

(1) would make integrating things pretty easy, but it would increase the risk of collisions. Also, a topic named `SomeEvent` doesn't say much about which system the event is from. This can be cool, but it could also be pretty annoying.

(2) would decrease the risk of collisions, and it would provide the ability to tell some more about the owner of a message type (an example could be a topic named `OrderProcessor.OrderProcessed`).

(3) would make moving things around much more flexible, as it would be possible to more easily rename topics, message types, etc.

**Comment by KorpEduardoSikora** [comment]
Hi @mookid8000,

Just sharing how our company implemented the "shared nothing" approach...

We added an Atrribute to all messages:
![image](https://user-images.githubusercontent.com/47144079/73738849-f2bb2580-4723-11ea-99e7-bde01c917b83.png)

That works together with our 3 interfaces:

1. **ICommand**: To send a command, with a fixed destination queue (ie: another microsservice): _bus,Send(...); This is the only type that requires the "destinationQueue" parameter of our EndPoint attribute.
2. **IEvent**: To publish a event to unknown listeners: _bus.Publish(...).
3: **IMesssage**: to receive a command and to use reply to a message on a handler: _bus.Reply(...).

When the service starts running we scan the types on the assemblies and register the messages types with it's endpoint configuration.

On the outgoing pipeline, we add the endpointkey of the message the message headers.
If it is a ICommand, we set the destination queue and use _bus.Advanced.Routing.Send();

On the incoming methods:
We also implemented a custom Serializer with:
```
.AddRebus(config => 
     config.Options(options => 
               options.Decorate<ISerializer>(c => new CustomDeserializer(c.Get<ISerializer>))
    )
);
```
On the Deserialize method, we get the header from the message and try to match with the message type directly and then try to match with the registered messages endpoints.

We apply similar logic to Defer/DeferLocal/SendLocal methods.

We try to set the endpointKey as specific as possible to avoid our teams implementing the same endpointkey on two different messages.

I hope this gives you some ideas to your implementation 👍

**Comment by CzechsMix** [comment]
We used Channel based approach.

The configuration for a sender may do something like

```csharp
config.Route<HelloMessage>().To("Greeter", "Greeter.Hello");
```

The bus listening to the "Greeter" queue would have something like

```csharp
config.Consume("Greeter.Hello").As<HelloMsg>();
```

fromt his configuration, There is a customer ISerializer that manages the json serialization. On the way out, the type of the message is used as the key in a dictionary and the channel added to the headers.

On deserialization the channel header is read and used as a key in a type dictionary that the message data is deserialized to.

So the HelloMsg that gets deserialized may have properties for Text, and From. But the sender may only care about and serialize the Text property. If the HelloMsg object has a default From value, it would be respected in this instance. Additional properties would also be ignored by the receiver.

It adds complexity in message documentation that needs to be shared, but reduces package/dll sharing complexity but only binding each service to the configuration extensions/custom serializer package.

**Comment by RafaelLiendo** [comment]
Hey guy's, I just did a repo improving the "SharedNothing" sample.
Key points are:

1. The consumer dosen't have to know the fully qualified name of the message type
2. The Producers and Consumers only have to agree on a Topic Name
3. I've customized the topic naming convetion

**Comment by RafaelLiendo** [comment]
Hey guy's, I just did a repo improving the ["SharedNothing" sample](https://github.com/rebus-org/RebusSamples/tree/master/SharedNothing)

Please take a look at my repo https://github.com/RafaelLiendo/Rebus.Extensions.SharedNothing

I've aimed to have no breaking changes and to be able to have both scenarios at the same time. With and without sharing a DLL

Things I would still like to improve:

1. Completly remove the need of MessageTypes or Topic Names in the message header in order to be able to deserialize the message.
2. Use a more semantic mapping configuration like @CzechsMix suggested
```csharp
conifg.Publish<SomeEvent>().To("Greeter.SomeEvent");
config.SubscribeTo("Greeter.SomeEvent").As<SomeEventMsg>();
```

That's it. Let me know what you guys think.

**Comment by mookid8000** [comment]
It looks pretty sleek! 👍 although I would prefer the reverse order in
```csharp
config.SubscribeTo("Greeter.SomeEvent").As<SomeEventMsg>();
```
so it would read
```csharp
config.SubscribeTo<SomeEventMsg>().From("Greeter.SomeEvent");
```
instead.

To my eyes, this would introduce a symmetry in how
```csharp
conifg.Publish<SomeEvent>().To("Greeter.SomeEvent");
config.SubscribeTo<SomeEventMsg>().From("Greeter.SomeEvent");
```
use the prepositions "to" and "from" in how the relation is to the topic name.

OTOH a shorter form (which would be reusable in both publishers and subscribers) would simply map .NET types to topic names, similar to how Rebus' "endpoint mappings" map .NET types to queue names:

OK now I'm thinking outside the box – but one thing that has tricked many people over the years is the "endpoint mappings" mechanism.... maybe it would be more clear if the configuration read
```csharp
Configure.With(...)
    .(....)
    .Routing(r => {
        r.Queues()
            .Map<SomeCommand>("some-queue")
            .Map<AnotherCommand>("another-queue");

        r.Topics()
            .Map<SomeEvent>("some-topic")
            .Map<AnotherEvent>("another-topic");
    })
    .Start();
```
or in a way that avoids the curlies:
```csharp
Configure.With(...)
    .(....)
    .Routing(r =>
        r.Queues(q => 
            q.Map<SomeCommand>("some-queue")
             .Map<AnotherCommand>("another-queue")
        )
        .Topics(t => 
            t.Map<SomeEvent>("some-topic")
             .Map<AnotherEvent>("another-topic")
        )
    })
    .Start();
```
🙂

**Comment by RafaelLiendo** [comment]
I like the last two samples you provided, but I still don't like to have two places I need to remember to maintain subscriptions
like this:
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddRebus(configure => configure
        ///...
        .Routing(r =>
            .Topics(t => t 
                .Map<SomeEvent>("some-topic")
                .Map<AnotherEvent>("another-topic")
            )
        })
       
public void Configure(IApplicationBuilder app)
{
    app.ApplicationServices.UseRebus(rebus =>
        rebus.Subscribe<AnotherEvent>());
}
```


So, how about this?

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AutoRegisterHandlersFromAssemblyOf<Handler1>();
    services.AddRebus(configure => configure
        ///...
        .Routing(r => r
            .Send(c => c
                .Type<SomeCommand>("some-queue")
                .Type<AnotherCommand>("another-queue")
                .TypesOfAssembly<YetAnotherCommand>("yet-another-queue")
            )
            .Publish(c => c
                .Type<EventA>("topic-a")
            )
            .Subscribe(c => c
                .Type<EventB>("topic-b")
                .Type<EventC>()
                .TypeImplicit("topic-d")
            )
            .AllowFallbackToDefaultConvention()
        });
}
       
public void Configure(IApplicationBuilder app)
{
    app.ApplicationServices.UseRebus(async rebus =>
        await rebus.AutoSubscribe());
}
```

This would accomplish a few things:

1. Use more familiar Send, Publish, Subscribe instead of Queues and Topics
2. Separates publish from subscribe, so we can do AutoSubscribe and have a single place to maintain subscriptions
3. Fallback to default conventions if not mapped

**Comment by mookid8000** [comment]
Your last snippet looks pretty good! I like how hard it would be to misunderstand what is mapped to what.

I would prefer the last bit to be unnecessary though, so one would simply go
```csharp
app.ApplicationServices.UseRebus();
```
and then any calls made to `.Subscribe(...)` would result in their subscriptions be established at that point.

**Comment by RafaelLiendo** [comment]
Also I wanted to mention that I successfully used the [Rebus.Extensions.SharedNothing](https://github.com/RafaelLiendo/Rebus.Extensions.SharedNothing) in production

## How was my scenario?
My company had a solution in production that used a home grown message bus implementation with RabbitMQ.Client and wanted to use rebus because we could:
1.  have a more mature a battle tested message bus
2.  be able to switch from RabbitMQ in development to Azure Service Bus in production with a single line of configuration
3. maybe use some other features like [Sagas](https://github.com/rebus-org/Rebus/wiki/Coordinating-stuff-that-happens-over-time),  and others.

So, our implementation looked something like this

Publisher
```csharp
var product = _productRepository.FindById(42);
product.LastUpdate = DateTime.Now;
_productRepository.Update(product);

//sometimes we used an anonymous types
bus.publish(Products:ProductUpdated, new { ProductId = product.Id });

//sometimes we sent the entire entity
bus.publish(Products:ProductUpdated, product);

//but the point is that we didn't have a ProductUpdated class to represent that on the publisher side
```

Consumer
```csharp
bus.subscribe<ProductUpdated>("Products:ProductUpdated");
```
## Problem
Common rebus implementation relies heavily on the sharing the DLL containing the messages.
So, the publisher sends the fully qualified Message Type (including the assembly in the Headers and the Subscriber expects to find that exact same type in order to deserialize the message.

But we didn't have a shared DLL, and neither we had Message types on the publisher side so, migrating to use rebus would require a lot of stepts that we didn't wanna do in one go.

## Solution
with [Rebus.Extensions.SharedNothing](https://github.com/RafaelLiendo/Rebus.Extensions.SharedNothing) we could migrate step by step
1.  it uses the topic name instead of the Message Type in the Header, so publisher and subscriber only have to agree on that.
```csharp
services.AddRebus(configure => configure
    .Transport(t => t.UseRabbitMq(connectionString, inputQueueName))
    .UseSharedNothingApproach(builder => builder
        .AddWithCustomName<ProductUpdated>("Products:ProductUpdated")
        .AddWithCustomName<OrderCreated>("Orders:OrderCreated")
    )
);

await bus.Subscribe<ProductUpdated>();
await bus.Subscribe<OrderCreated>();
```
With that, we can deploy it to production and everything works as it was.

2. Now we can start creating Types for our messages on the Publisher side
```csharp
bus.publish(Products:ProductUpdated, new ProductUpdated { ProductId = product.Id });
```
nothing changes on the consumer side and everything still works

3. We move our message types to a new Project called Products.Messages

4. We publish the messages project to a private nuget feed

5. Now we can install the nuget package on the consumer and start using those shared types
```csharp
services.AddRebus(configure => configure
    .Transport(t => t.UseRabbitMq(connectionString, inputQueueName))
    .UseSharedNothingApproach(builder => builder
        // now we can remove this mapping and allow the default convetions to kick in
        //.AddWithCustomName<ProductUpdated>("Products:ProductUpdated")
        .AddWithCustomName<OrderCreated>("Orders:OrderCreated")
        //but we also have to add this line, otherwise this would throw an exception
        .AllowFallbackToDefaultConvention() 
    )
);

await bus.Subscribe<ProductUpdated>();
await bus.Subscribe<OrderCreated>();
```

Notice that we sucessfully migrated the Products service, but the Orders service still remains the same and can be migrated later.

**Comment by SbiCA** [comment]
@RafaelLiendo any plans to PR-ing this? it looks nice and seems to address a scenario I also faced in the past (even though with a way simpler/incomplete solution that would fit in general ... 😏  )

**Comment by TsengSR** [comment]
@mookid8000 
What's the state of this? Since its marked completed, I assume its been implemented, but can't find any documentation on how to set it up.

**Comment by mookid8000** [comment]
@TsengSR You can take a look at this example from the Rebus repository: https://github.com/rebus-org/Rebus/blob/master/Rebus.Tests/Examples/ShowHowToAvoidSharingMessageDllsAcrossProcesses.cs - it demonstrates how two different types can be mapped to the same type name.
