### ISSUE TITLE
Upgrade from 5.4.0 to 6.0.0

### ISSUE THREAD

**Issue by arnarleifs** [rebus-org/Rebus#853]
Hi,

We have been using **Rebus** for quite some time and were thinking about upgrading to the latest version 6.0.0 but stumbled upon an error which might be related to some changes made to the **TransactionContext** but I am not sure. So we have multiple running services using Rebus which all rely on a centralized subscription storage using MSSQL. 

``` c#
builder.RegisterRebus((configurer, context) =>
{
    configurer
        .Logging(l => l.NLog())
        .Routing(r =>
        {
            var routing = r.TypeBased();
            subscriptions.ForEach(sub => routing.Map(sub.Message.GetType(), sub.DestinationAddress));
        })
        .Subscriptions(s =>
            s.StoreInSqlServer(
                ConfigurationManager
                    .ConnectionStrings[ConfigurationConstants.AdministrationConnectionString]
                    .ConnectionString, "Subscription", true))
        .Options(o =>
        {
            // Only setup error queues if the service is subscribing to something
            if (!string.IsNullOrEmpty(queuePrefix))
            {
                o.SimpleRetryStrategy(maxDeliveryAttempts: 5, errorQueueAddress: $"{queuePrefix}.error");
            }
        });

    if (!string.IsNullOrEmpty(queuePrefix))
    {
        configurer.Transport(t => t.UseMsmq($"{queuePrefix}.input"));
    }
    else
    {
        configurer.Transport(t => t.UseMsmqAsOneWayClient());
    }

    return configurer;
});

// Afterwards inside another function the bus subscribes to the messages
subscriptions.ForEach(async s => await bus.Subscribe(s.Message.GetType()));
```

Every time after we updated to the latest version this error came for each message:
`Rebus.Exceptions.RebusApplicationException: Could not 'GetOrAdd' item with key 'msmqtransport-messagequeuetransaction' as type System.Messaging.MessageQueueTransaction`

Are you able to see the problem given the code above?

**Comment by mookid8000** [comment]
This is because the Rebus.Msmq package has not been updated to support Rebus 6.... just a second

**Comment by mookid8000** [comment]
Rebus.Msmq 6.0.0 with support for Rebus 6 is avaiable on NuGet.org in a few minutes..

Thanks for reporting this! 🙂

**Comment by arnarleifs** [comment]
Thanks for the really quick reply! No problem for the report :)
