### ISSUE TITLE
Easy way of forwarding message to error queue

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#858]
If you want to swiftly forward the message currently being handled to the error queue, you currently need to do manual stuff like this:
```csharp
await _bus.Advanced.TransportMessage.Forward("error", new Dictionary<string, string>
{
    [Headers.DeferCount] = "0",
    [Headers.ErrorDetails] = exception.ToString(),
    [Headers.SourceQueue] = "my-queue"
});
```
which is not as pretty as it could have been.

The transport message API needs a `ForwardToErrorQueue` method that would change the above code to
```csharp
await _bus.Advanced.TransportMessage.ForwardToErrorQueue();
```
which is how it should always have been. 😉

**Comment by rsivanov** [comment]
Doesn't FailFastException exist for exactly that kind of scenario - moving the message to an error queue?

**Comment by mookid8000** [comment]
@rsivanov yes it does 🙂 there are a few differences though.

When you throw an exception marked with the `IFailFastException` interface, the entire message transaction is rolled back. This means that all outgoing messages sent/published at that point will not be sent/published. It also generates quite a bit of noise in the log.

If Rebus had the ability to `await _bus.Advanced.TransportMessage.ForwardToErrorQueue()`, it would be a normal send operation, and you would have to log it, if you wanted to log something. It would be much more smooth that way.

I think there's a difference. How do you see it?

**Comment by rsivanov** [comment]
I can see the difference in behavior you're describing, but I'm not sure there should be any. I've just read the page in Rebus wiki about failing fast once again, bthere isn't any technical

**Comment by mookid8000** [comment]
You might be right 🙂 

I also remembered one of the reasons that this API was not added a long time ago – if it was an operation like `await _bus.Advanced.TransportMessage.ForwardToErrorQueue()`, it will be possible to 
```csharp
await _bus.Advanced.TransportMessage.ForwardToErrorQueue();
await _bus.Advanced.TransportMessage.ForwardToErrorQueue();
await _bus.Advanced.TransportMessage.ForwardToErrorQueue();
```
and thus end up with three copies of the same message in the dead-letter queue.

**Comment by mookid8000** [comment]
Rebus 6.2.1 is available on NuGet.org now.

It has the ability to
```csharp
await _bus.Advanced.TransportMessage.Deadletter();
```
which will mark the message currently being handled as one to be dead-lettered. 

Whatever "dead-lettering" means depends on the configuration, so by default it will move the message to the error queue. If you're running with Fleet Manager, then the message will be stored there.

It's possible to customize the message passed along with the poison message like this:
```csharp
await _bus.Advanced.TransportMessage.Deadletter(errorDetails: "Something went horribly wrong!");
```
