### ISSUE TITLE
FileSystemTransport no longer creates directory when sending message

### ISSUE THREAD

**Issue by jr01** [rebus-org/Rebus#860]
In v5 the FileSystemTransport ensured directory existed before sending a message. In v6 no longer. 

Since the destination queue can be dynamic/unknown upfront I think this is a bug.

**Comment by mookid8000** [comment]
This actually mimics how other transports work. No other transport automatically creates destination queues, so I don’t think the file system transport should do it either.

**Comment by jr01** [comment]
Yes, I see your point and agree.
