### ISSUE TITLE
Error while injecting ITopicNameConvention

### ISSUE THREAD

**Issue by Efp95** [rebus-org/Rebus#868]
Hi,

I'm using **Rebus 6.1.0**
and **Rebus.AzureServiceBus 7.1.0**

I'm about to upgrade the version from **Rebus 5.3.1** and **Rebus.AzureServiceBus 6.0.7**

While attempting to override the ITopicNameConvention registration we got the following message from [here](https://github.com/rebus-org/Rebus/blob/060f0cd51affe4844d1167308971fe4cf8a294eb/Rebus/Injection/Injectionist.cs#L119
)

This is how we used to do it
```
.Transport(t =>
{
    t.OtherService<ITopicNameConvention>().Register(_ => new WorkflowTopicNameConvention(workflowId));
    t.UseAzureServiceBus(serviceBus, rebus.InputQueue(workflowId));
})
```

**FYI:** Also, I tried putting the piece of code within the `.Options` section

**Comment by Efp95** [comment]
Update: found out the solution from here: https://github.com/rebus-org/Rebus/issues/692

**Comment by mookid8000** [comment]
Perfect 🙂
