### ISSUE TITLE
Question about rbs2-return-address

### ISSUE THREAD

**Issue by macchmie3** [rebus-org/Rebus#869]
Hi!

Should this property be set automatically? In my case I am trying to fix an issue when specific message is handled ~100 times, not only once. I noticed that the property rbs2-return-address is set to the same queue that the message was grabbed from. My flow for that message should be:

input-queue->audit-queue

**Comment by mookid8000** [comment]
The `rbs2-return-address` will be set to the input queue of the sender by default.

You can set it to another queue by adding it as a header when you send the message
```csharp
await bus.Send(message, new Dictionary<string, string> {
	[Headers.ReturnAddress] = "something-else"
});
```
or simply by changing the default, thus adding another queue name to all sent messages
```csharp
Configure.With(sender)
    .(...)
    .Options(o => o.SetDefaultReturnAddress("something-else"))
    .Start();
```

Does that make sense?

**Comment by macchmie3** [comment]
@mookid8000 
Thank you for your quick answer. Seems like this is not a problem as I do not use "reply" on those messages.

Have you had any case when one message would be processed multiple times? I am using rebus with AzureServiceBus. My MessageHandler Handle method looks like:

```
public async Task Handle(MyMessage message)
        {
            try
            {
                // Do smth here
                Log.Info("Message processing finished");
             }
            catch (Exception e)
            {
                Log.Error("Message processing failed", e);
            }
}

```

I do see that "Message processing finished" is present in my logs (multiple times),so this message gets processed multiple times (99 was the highest count). I attached properties of a sample audit message (count of audit messages is equal to the count of that said info log). The only difference between those audit messages are:
- EnqueuedTimeUtc - since processing a message lasts around 6-10 minutes, each audit message has around that amount of time difference
- SequenceNumber
- rbs2-audit-copytime
- rbs2-audit-handletime

**All other properties are the same**


![Audit_message](https://user-images.githubusercontent.com/12615493/76617066-bb5f4600-6525-11ea-9172-e1a8bc8ef327.png)

**Comment by mookid8000** [comment]
> Have you had any case when one message would be processed multiple times?

No, not unless there was an error.

> (...) since processing a message lasts around 6-10 minutes, each audit message has around that amount of time difference (...)

This explains it! 🙂 

Azure Service Bus provides a "peek lock" on each incoming message, which Rebus must then acknowledge within a timeout (default with Rebus: 5 minutes), _or else the message will become visible in the queue again_!

You can read more about Azure Service Bus' locking mechanics here: https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-transfers-locks-settlement#settling-receive-operations

The solution with Rebus is to have it automatically renew the peek lock, which you can enable like this:
```csharp
 Configure.With(...)
        .Transport(t => t.UseAzureServiceBus(connectionString, "queue")
                         .AutomaticallyRenewPeekLock())
        .(...)
```

**Comment by macchmie3** [comment]
I already use `AutomaticallyRenewPeekLock` :(
What I can add is that we only have this situation on our CI environment, when the resources in Azure are on rather low plans, so performance there is not a high one. Do you think setting different PeekLock duration via  `SetMessagePeekLockDuration` might help?

**Comment by macchmie3** [comment]
@mookid8000 
I have just realised that during "problems" with this message I see (in similar granularity) following errors (btw, number of rebus workers on that instance is 4) (messageId is the Id for a troublesome message):

`Unhandled exception in worker ""Rebus 1 worker 1"" Rebus.Exceptions.RebusApplicationException: Could not abandon message with ID 1297efb8-72fc-4e91-933a-b833f9a3563b and lock token 3743c40d-c65b-48db-bb1e-edc4d9ae90ab ---> Microsoft.Azure.ServiceBus.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue, or was received by a different receiver instance.`

`An error occurred when attempting to complete the transaction context Rebus.Exceptions.RebusApplicationException: Could not complete message with ID 1297efb8-72fc-4e91-933a-b833f9a3563b and lock token 3743c40d-c65b-48db-bb1e-edc4d9ae90ab ---> Microsoft.Azure.ServiceBus.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue, or was received by a different receiver instance.`

**Comment by mookid8000** [comment]
Do you have some timestamps from your log that can maybe help with determining whether the peek lock was renewed too late?

**Comment by macchmie3** [comment]
@mookid8000 
I think that my logs are not ideal here as I do not know which instance on rebus worker is logging each message, but for an instance of audit message with:
rbs2-audit-copytime: 04:16:27.1715519
rbs2-aduit-handletime: 04:11:15.5565948

I have following logs (I do not have ms for this):

04:14:44 Renewing peek lock for message with ID ""c91f6ccc-9a5f-4a3b-b01c-bbd78cae31d7""

04:16:27 An error occurred when attempting to complete the transaction context Rebus.Exceptions.RebusApplicationException: Could not complete message with ID c91f6ccc-9a5f-4a3b-b01c-bbd78cae31d7 and lock token 04681648-6ae2-44c8-9d9b-8861103038fe ---> Microsoft.Azure.ServiceBus.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue, or was received by a different receiver instance.

04:16:27 Unhandled exception in worker ""Rebus 1 worker 3"" Rebus.Exceptions.RebusApplicationException: Could not abandon message with ID c91f6ccc-9a5f-4a3b-b01c-bbd78cae31d7 and lock token 04681648-6ae2-44c8-9d9b-8861103038fe ---> Microsoft.Azure.ServiceBus.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue, or was received by a different receiver instance.

Logs from 04:16:27 are from the same thread, and a different one than 04:14:44

**Comment by macchmie3** [comment]
@mookid8000 
Is there a way to make rebus renew peek lock more often? I see that on Service Bus side max duration is 5 minutes. Can I specify that rebus should renew the 5min lock e.g. once every 3 minutes?

**Comment by mookid8000** [comment]
As you can see [here](https://github.com/rebus-org/Rebus.AzureServiceBus/blob/master/Rebus.AzureServiceBus/AzureServiceBus/AzureServiceBusTransport.cs#L594), Rebus will automatically renew the peek lock when 50% of the time has gone by.

Though now when I look at this, I wonder if the peek lock can ever result in the message being locked for less than the default time, so that e.g. after the first renewal it remains locked e.g. for only 2 minutes or something like that....?

**Comment by macchmie3** [comment]
@mookid8000 
I will spend some time gathering information about what really happens there. I think it is connected to heavy load, maybe rebus cannot renew peeklock correctly, but I do not see error logged from renewing the peek locks in every case.

If i understand correctly - if rebus cannot renew peek lock to a message (cause of timeout, transient error, connection error) then other worker will grab the meesage and a conflict will occur. Is it possible that a log from rebus about problem with renewing peeklock will not be present?

What I will try when I have some time - I will fire the task and look on service bus explorer to monitor the lock token on a message.

**Comment by mookid8000** [comment]
> I will spend some time gathering information about what really happens there. I think it is connected to heavy load, maybe rebus cannot renew peeklock correctly, but I do not see error logged from renewing the peek locks in every case.

I know for a fact that Rebus _can_ correctly renew the peek lock - there's [this pretty long-running test here](https://github.com/rebus-org/Rebus.AzureServiceBus/blob/master/Rebus.AzureServiceBus.Tests/AzureServiceBusPeekLockRenewalTest.cs) to prove it 🙂 question is whether something in some cases can lead to NOT correctly renewing the peek lock before it expired.

> If i understand correctly - if rebus cannot renew peek lock to a message (cause of timeout, transient error, connection error) then other worker will grab the meesage and a conflict will occur. Is it possible that a log from rebus about problem with renewing peeklock will not be present?

I think [the `RenewPeekLock` method](https://github.com/rebus-org/Rebus.AzureServiceBus/blob/master/Rebus.AzureServiceBus/AzureServiceBus/AzureServiceBusTransport.cs#L674-L697) will always log failed renewal attempts.

> What I will try when I have some time - I will fire the task and look on service bus explorer to monitor the lock token on a message.

Interesting experiment!

**Comment by macchmie3** [comment]
@mookid8000 
I once again browse threw the log. This whole case is about our tasks that run during night time on our CI environment. This time I turned off all other tasks and left only the failing one. To remind - everything is run in Azure, app service plan has 2 instances. Rebus is configured with 4 workers for each instance. A small "misconfigure" was that I reduced peeklock duration from 5 minutes to 2min30sec

Abnormalities that I found from todays log - keep in mind that a message was processed 48 times today :( 

**The beggining**
```
10:04:12.000 PM - Message processing started (my custom log from handler)
10:05:27.000 PM - Renewing peek lock for message with ID ""8e8469ee-38e4-446a-9a76-8170363f617f""
10:06:43.000 PM - Renewing peek lock for message with ID ""8e8469ee-38e4-446a-9a76-8170363f617f""
10:07:44.000 PM - Exception in periodic task ""RenewPeekLock-8e8469ee-38e4-446a-9a76-8170363f617f"": Rebus.Exceptions.RebusApplicationException: Could not renew lock for message with ID 8e8469ee-38e4-446a-9a76-8170363f617f and lock token 23bdfcf9-30d1-4f8b-bb57-587a0d4e8f02 ---> Microsoft.Azure.ServiceBus.ServiceBusTimeoutException: The operation did not complete within the allocated time 00:01:00 for object request184. ---> System.TimeoutException: The operation did not complete within the allocated time 00:01:00 for object request184.
10:09:00.000 PM - Renewing peek lock for message with ID ""8e8469ee-38e4-446a-9a76-8170363f617f""
10:09:13.000 PM - Message processing started (my custom log from handler) - i guess it's task no.2
```
I guess that last completed peeklock renewal was done at 10:06:43.000 PM, at this point a second worker/instace grabs the tasks and the problem starts. At this point it gets worse and I see that we should simply work on performance so that timeouts to service bus never happen. I just hope that the issue is on the app service side, not on service bus.


`10:09:50.000 PM - Could not renew lock for message with ID ""8e8469ee-38e4-446a-9a76-8170363f617f"" and lock token ""23bdfcf9-30d1-4f8b-bb57-587a0d4e8f02"" - cancelling peek lock renewal task Microsoft.Azure.ServiceBus.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. Reference:df3405b0-724f-4a58-8893-649b86dde316, TrackingId:b05bd8c8-3b8c-4f9c-8e78-4c1a042ecae6_B3, SystemTracker:dataci:Queue:worker-input-queue, Timestamp:2020-03-17T22:09:48`

Now the task no.1 fails to renew peek lock. as task no.2 already started processing the message again with its own peek lock.

```
10:10:28.000 PM - Renewing peek lock for message with ID ""8e8469ee-38e4-446a-9a76-8170363f617f""
10:11:43.000 PM - Renewing peek lock for message with ID ""8e8469ee-38e4-446a-9a76-8170363f617f""
10:12:58.000 PM - Message processing started (my custom log from handler) - TASK no.3?!
```

At this point I have no idea why task 3 started since there is no message about failed renewals for peek locks. The lock should be properly acquired by task no 2.


`10:13:05.000 PM -  Exception in periodic task ""RenewPeekLock-8e8469ee-38e4-446a-9a76-8170363f617f"": Rebus.Exceptions.RebusApplicationException: Could not renew lock for message with ID 8e8469ee-38e4-446a-9a76-8170363f617f and lock token 78eae0c6-f4e0-4b1f-89d5-18e4d1a5ce23 ---> Microsoft.Azure.ServiceBus.ServiceBusCommunicationException: An established connection was aborted by the software in your host machine ErrorCode: ConnectionAborted ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine`

What happened above is not what I assumed - I though peek lock renewal may fail for task no.2 as it is taken by task no.3. Instead what I see here is that peek lock renewal for task no.2 failed cause of connection error and that's the reason why task no.3 could be started - task no.2 lock expired!


What happens next is kind of the same for about 4 hours until one precious task can be finished with all the locks correctly renewed... 


** I think that this completely explains my problem **. Thanks for your help and quick answers.

**Comment by macchmie3** [comment]
@mookid8000 
Don't you think that when lock renewal fails (cause of timeout) it should be retried? What actually happens is that it waits for next interval to start, and that takes away "precious" time. 
Actually when a fail on lock renewal arise you are 100% sure that a problem will occur as a lock renewal will take place once the lock expires (and another worker grabs the message).

**Comment by mookid8000** [comment]
It probably should be retried, yes.

I've created this issue to track it: https://github.com/rebus-org/Rebus.AzureServiceBus/issues/53
