### ISSUE TITLE
Handler called multiple times when using Lamar

### ISSUE THREAD

**Issue by bosjaH** [rebus-org/Rebus#871]
Hi,

A quick follow up to [this](https://github.com/rebus-org/Rebus/issues/830#issuecomment-598586288) comment.

This seems a consequence of the way Lamar resolves generics. 
With a message ```Message1 : IMessage1``` and a handler ```Message1Handler : IHandleMessages<IMessage1>```, the  current ```GetMessageHandlersForMessage``` method will return 2 instances of Message1Handler if a message with type ```Message1``` comes in.

Seems to me that an easy fix is selecting only the unique handler types.
![image](https://user-images.githubusercontent.com/23117364/76767774-69732600-679a-11ea-8860-a00b8e7d0938.png)

What do you think?

**Comment by mookid8000** [comment]
Actually sounds like a pretty nice fix. 🙂

**Comment by bosjaH** [comment]
Created [a PR](https://github.com/rebus-org/Rebus.ServiceProvider/pull/33) with the change + unit test

**Comment by mookid8000** [comment]
Closed by https://github.com/rebus-org/Rebus.ServiceProvider/pull/33

Thanks!
