### ISSUE TITLE
Open telemetry?

### ISSUE THREAD

**Issue by dariogriffo** [rebus-org/Rebus#873]
I know there is a lot (or not), this is just a first working draft [here](https://github.com/dariogriffo/Rebus.OpenTelemetry)
just leaving this here to call your attention

**Comment by mookid8000** [comment]
oh wow cool! didn't know OpenTelemetry existed, but it looks like a cool idea! let me know if there's anything specific in Rebus you're in doubt about how to instrument

**Comment by dariogriffo** [comment]
Well, I need to take a better look on how usually the code is structured, how this can be brought to the build pipeline, etc, etc.
When I have something more solid (probably by the weekend) a new repo can be created and we can start working better on a PR basis, I will fork it into my user and work as I did with the Events issue, is that OK with you?

**Comment by mookid8000** [comment]
yes, definitely!

I'll close this issue for now then 🙂

**Comment by Meigs2** [comment]
Is adding Open Telemetry still a possibility?

**Comment by dariogriffo** [comment]
> Is adding Open Telemetry still a possibility?

Yup

https://github.com/rebus-org/Rebus.OpenTelemetry

**Comment by Meigs2** [comment]
> > Is adding Open Telemetry still a possibility?
> 
> Yup
> 
> https://github.com/rebus-org/Rebus.OpenTelemetry
> 
> @mookid8000 is there a pre-release package?

Ah, look at that. Thanks.
