### ISSUE TITLE
Pub/Sub message ordering

### ISSUE THREAD

**Issue by demius** [rebus-org/Rebus#877]
Hi there,

I'm having some real trouble with message ordering, particularly on the subscriber end.
I've verified that messages are published in sequence, but the order is random on the subscription end.

This is naturally quite problematic when I'm trying to publish status updates to a process.
I've switched from Azure Service Bus to Azure Storage Queues since ASB doesn't guarantee message order, so I think I've ruled out the transport being the issue.

However, when I look at the queue, the messages appear to be unordered. Is there something I need to configure on the publisher's end to ensure that the messages are committed to the queue in the correct order?

Please help?

**EDIT:** I've switched from using _await bus.Publish(...)_ to _bus.Publish(...).Wait()_ (which is terrible practice!), but yeah, I can't find any other way of ensuring the order in which messages are sent to the transport.

**Comment by mookid8000** [comment]
When you
```csharp
await bus.Publish(firstMessage);

await bus.Publish(secondMessage);
```
they're guaranteed to be processed in order with ASB, UNLESS:

1. the first message fails and is moved to the dead-letter queue, causing the second message to be processed first, or
2. your subscriber is processing messages in parallel, causing the messages to be processed in an indeterministic order

In your case, it's (2) that bites you, because Rebus will default to process 5 messages in parallel. So, if you change your subscriber's configuration to something like
```csharp
Configure.With(...)
	.(...)
	.Options(o => o.SetMaxParallelism(1))
	.Start();
```
then it should work. 🙂

**Comment by demius** [comment]
Hi mookid, thanks for the prompt response. I've set up my subscriber as you suggested (1 worker thread), but the results from the logs are as follows (note the message order):

**Publisher**
[DBG] Rebus.Pipeline.Send.SendOutgoingMessageStep (Thread #9): Sending fundhouse.Reporting.Ipc.Messages.Events.**RatingReportValidationStarted** -> "sub-clarity-web;sub-event-persistor"
[DBG] Rebus.Pipeline.Send.SendOutgoingMessageStep (Thread #15): Sending fundhouse.Reporting.Ipc.Messages.Events.**RatingReportGenerationStarted** -> "sub-clarity-web;sub-event-persistor"
[DBG] Rebus.Pipeline.Send.SendOutgoingMessageStep (Thread #16): Sending fundhouse.Reporting.Ipc.Messages.Events.**RatingReportGenerationCompleted** -> "sub-clarity-web;sub-event-persistor"

**Subscriber** (_the order is incorrect_)
[DBG] Rebus.Pipeline.Receive.DispatchIncomingMessageStep (Thread #12): Dispatching "fundhouse.Reporting.Ipc.Messages.Events.**RatingReportValidationStarted**, fundhouse.Reporting.Ipc" "d7ff8000-c6e1-4c33-9c2a-6c87d4eb9719" to 1 handlers took 2969 ms
[DBG] Rebus.Pipeline.Receive.DispatchIncomingMessageStep (Thread #12): Dispatching "fundhouse.Reporting.Ipc.Messages.Events.**RatingReportGenerationCompleted**, fundhouse.Reporting.Ipc" "833d2ad3-7f0c-41c7-a946-fb09e116220b" to 1 handlers took 956 ms
[DBG] Rebus.Pipeline.Receive.DispatchIncomingMessageStep (Thread #10): Dispatching "fundhouse.Reporting.Ipc.Messages.Events.**RatingReportGenerationStarted**, fundhouse.Reporting.Ipc" "cdf5af61-1c8d-488a-935f-02091f344338" to 1 handlers took 839 ms

**Comment by mookid8000** [comment]
> (....) the 2 out of order messages above are published by the same handler.

Ah, now I get it!

It's because of an optimization in Rebus, which will publish all outgoing messages in parallel if you publish from within the same transaction context.

Could you try and temporarily suppress the Rebus transaction scope when you publish those events?

It can be done like this:
```csharp
using (new RebusTransactionScopeSuppressor())
{
	await bus.Publish(yourEvent);
}
```

**Comment by demius** [comment]
That did the trick, Mogens! Thank you! There does seem to be a significant performance penalty to this unfortunately, but I'll just have to live with it. Thank you again, I was losing my mind!

**Comment by mookid8000** [comment]
Excellent! 👍

**Comment by demius** [comment]
Mogens, I'm curious about the thinking behind the parallel dispatch optimization. Surely this would mess up saga processing as well, wouldn't it? The order of events is super important in most cases - would it be worthwhile to include an option to disable the behavior?

**Comment by mookid8000** [comment]
Ok, here's how it works: When you send an outgoing message, regardless of whether it's directed at a queue or a topic, it's saved in the ASB transport's buffer for outgoing messages – _in order_.

Then, when your handlers have finished executing and there were no errors, the transport will group the outgoing messages by their destination, _preserving their order within each group_.

And then, most likely all groups in parallel, it will start sending messages up to 50 at a time, _in order, using ASB's batch API_.

Therefore, events are actually only emitted in a nondeterministic order if they're different events – but to my knowledge, ASB does not actually guarantee any kind of ordering across topics, so any efforts trying to emit them in order could still be made pointless by ASB.

You can see the code responsible [here](https://github.com/rebus-org/Rebus.AzureServiceBus/blob/master/Rebus.AzureServiceBus/AzureServiceBus/AzureServiceBusTransport.cs#L513-L556).

I guess the point is this: Order is _mostly_ preserved, but you should never (almost never ever) write code that actually relies on it. Sometimes you have to assume some kind of ordering though, and that's where you are. If I were you, I would change the type of events emitted to be one single kind of progress event, and then put whichever information is required in it.
