### ISSUE TITLE
Problem using sagas with sql server on .NET Core 3.1

### ISSUE THREAD

**Issue by felipe-allmeida** [rebus-org/Rebus#880]
I creted a new project using Rebus and Rebus.RabbitMQ. I tried a LOT to create the migrations and update-database with the below image, but it was of no work.

I was only able to successfully create the database when I change the saga to use StoreInMemory(), create the migrations and did the first update-database. After that, I removed the StoreInMemory and added a new migration and did a update-database again. The problem is that on the end of the update-database, package manager console do not ends the process, I have to re-open visual studio in order to use package manager console again.

It apparently only occurs you are **creating the database** with update-database.

I'm using .NET Core 3.1 and the version of your nugets are:

Rebus v6.2.1
Rebus.RabbitMQ v7.0.0
Rebus.ServiceProvider v5.0.6
Rebus.SqlServer v6.1.2

![image](https://user-images.githubusercontent.com/62676728/82211742-ba60e100-98e7-11ea-97e3-9b06368043ae.png)

In the image below you can check that the package manager console is locked after update-database.

![image](https://user-images.githubusercontent.com/62676728/82240788-62d76b00-9911-11ea-82f4-80daa0237515.png)

**Comment by felipe-allmeida** [comment]
Also, the dotnet.exe becomes locked, I can no longer build unless I stop the process on task manager.

**Comment by mookid8000** [comment]
Sorry, but I don't understand what you mean by

> (...) I tried a LOT to create the migrations and update-database with the below image, but it was of no work.

?

**Comment by felipe-allmeida** [comment]
Hi @mookid8000, sorry the bad english. Now I got google covering me haha

Let me put in step by step what I did to try to make it clearer:

1) Create new project and domain models
2) I added Rebus to Startup.cs using SqlServer for Sagas
3) I used Add-Migration
4) I used the Update-Database and it FAILED
5) I removed the SqlServer and used the InMemory Saga
6) I used Update-Database again and it worked partially. The dotnet.exe application no longer closed, which made the project unable to compile.
7) I manually closed dotnet.exe in the task manager.

After doing this I managed to make Rebus work normally.

But for each new environment in my application I have to repeat this whole process (except creating the migration)

**Comment by mookid8000** [comment]
In steps 3 and 4, did you then attempt to migrate something Rebus-related?

All of Rebus' schemas are created automatically, unless you explicitly disable it, so it's not necessary to migrate anything that Rebus needs.

**Comment by felipe-allmeida** [comment]
Nopes, I was just trying to create my domain entities migration **for the first time** in this project

**Comment by mookid8000** [comment]
aaaaah NOW I understand what you're doing 😁 sorry, I've never used Entity Framework's migrations.

Does `update-database` cause the program to be started?

**Comment by felipe-allmeida** [comment]
No, it applies the last schema created by the add-migration on the database.

I'm having 1 problem by using the `add-migration` (creates the schema) and 1 with the `update-database` (updates the database according to the schema).

For the `add-migration`, if I try to create the FIRST migration with Rebus SQL server enabled on the code like the below image the migration will fail due to this error: 
_Could not resolve Rebus.Bus.IBus with decorator depth 0 - registrations: Rebus.Injection.Injectionist+Handler
_ 

![image](https://user-images.githubusercontent.com/62676728/82320957-813d7500-99aa-11ea-87ff-35bedb8861ae.png)

So in order to make the migration work, I have to explicit use the following code:

![image](https://user-images.githubusercontent.com/62676728/82321360-1c364f00-99ab-11ea-9bc2-400d98e4cf8c.png)

For the `update-database`, I have to use it twice. Normally after the schema is created I can only execute the `update-database` command that everything will work fine. But when using Rebus I have to:

1) Run `update-database` while StoreInMemory() is the current _ISagaStorage_
2) Run `update-database` again, but this time I use the _StoreInSqlServer_ function

Even successfully creating the database, my **dotnet ef core** stop working and I have to manually stop on TaskManager or Services on my windows. 

obs: After testing this many times. It appears to me that rebus try to connect to the database BEFORE it has been created. I got it to work by always creating the database first (wich is a pain in the ass because I keep having to change the code *check update-database problems).

**Comment by felipe-allmeida** [comment]
I am considering to try to fix this myself, as I am experiencing this issue in first hand. Just wanted to report this issue first to the Rebus master :)

**Comment by mookid8000** [comment]
Hi @felipe-allmeida , have you figured out how to make it work?

**Comment by mookid8000** [comment]
Hi @felipe-allmeida , I'm closing this one for now – please feel free to pick it up again if you still have a problem 🙂
