### ISSUE TITLE
New Rebus Circuit-Breaker Feature

### ISSUE THREAD

**Issue by robpackwood** [rebus-org/Rebus#882]
This relates back to my StackOverflow question here: https://stackoverflow.com/questions/62069828/rebus-circuit-breaker-implementation

Basically, what I would like is configuration options on the RebusConfigurer class. Perhaps a ConfigureCircuitBreaker method with the following parameters:

- TrackingSeconds (int) - The period after which attempt/failure counts are reset.
- PercentFailureThreshold (int) - The percentage of attempts that must fail before the circuit breaker trips into an open state and reduces the worker count to 0.
- MinimumAttemptThreshold (int) - The number of attempts that must occur before the circuit breaker becomes active.
- ResetIntervalSeconds (int) - Sets a specific reset interval for the circuit to close after being tripped.

This would be so helpful for preventing thousands of messages going into the error queue unnecessarily.

**Comment by mookid8000** [comment]
@seankearon yes! – I can definitely see how that would be useful

**Comment by robpackwood** [comment]
I was the one who originally requested this feature. I have a duct-tape solution I am using locally for now. Hopefully, this isn't completely insane but what I did was is register a Lazy<IBus> to my IOC container and then basically wrapped the PoisonQueueErrorHandler in a class called CircuitBreakerErrorHandler and have some options in a local class I have called RebusConfig such as CircuitBreakerFailedMessageCount, CircuitBreakerTrackingIntervalSeconds, and CircuitBreakerResetIntervalSeconds.

`	public class CircuitBreakerErrorHandler : IErrorHandler, IInitializable
	{
		private readonly Lazy<IBus> _busLazy;
		private readonly ConcurrentQueue<DateTime> _errorDateTimes;
		private readonly PoisonQueueErrorHandler _poisonQueueErrorHandler;
		private readonly RebusConfig _rebusConfig;
		private int _busWorkerCount;
		private readonly object _lock = new object();

		public CircuitBreakerErrorHandler(
			Lazy<IBus> busLazy,
			RebusConfig rebusConfig,
			PoisonQueueErrorHandler poisonQueueErrorHandler)
		{
			_busLazy = busLazy;
			_rebusConfig = rebusConfig;
			_poisonQueueErrorHandler = poisonQueueErrorHandler;
			_errorDateTimes = new ConcurrentQueue<DateTime>();
		}

		public async Task HandlePoisonMessage(
			TransportMessage transportMessage, ITransactionContext transactionContext, Exception exception)
		{
			DequeueStaleErrorDateTimes();
			_errorDateTimes.Enqueue(DateTime.Now);
			await _poisonQueueErrorHandler.HandlePoisonMessage(transportMessage, transactionContext, exception);
			var errorCount = _errorDateTimes.Count;

			lock (_lock)
			{
				if (errorCount >= _rebusConfig.CircuitBreakerFailedMessageCount &&
				    _busLazy.Value.Advanced.Workers.Count > 0)
				{
					_errorDateTimes.Clear();
					_busWorkerCount = _busLazy.Value.Advanced.Workers.Count;

					Log.Logger().Error(
						"{errorCount} errors have occurred within the past {circuitBreakerTrackingIntervalSeconds} " +
						"seconds. Opening circuit-breaker for {circuitBreakerResetIntervalSeconds} seconds.",
						errorCount, _rebusConfig.CircuitBreakerTrackingIntervalSeconds,
						_rebusConfig.CircuitBreakerResetIntervalSeconds);

					Task.WhenAll(
						Task.Factory.StartNew(() => _busLazy.Value.Advanced.Workers.SetNumberOfWorkers(0)),
						Task.Delay(TimeSpan.FromSeconds(_rebusConfig.CircuitBreakerResetIntervalSeconds))).Wait();

					_busLazy.Value.Advanced.Workers.SetNumberOfWorkers(_busWorkerCount);
					Log.Logger().Information("Circuit breaker closed.");
				}
			}
		}

		public void Initialize()
		{
			_poisonQueueErrorHandler.Initialize();
		}

		private void DequeueStaleErrorDateTimes()
		{
			if (_errorDateTimes.TryPeek(out var dateTime) &&
			    (DateTime.Now - dateTime).TotalMilliseconds >
			    _rebusConfig.CircuitBreakerTrackingIntervalSeconds * 1000)
			{
				_errorDateTimes.TryDequeue(out _);
				DequeueStaleErrorDateTimes();
			}
		}
	}`

Then to configure this class as the IErrorHandler I do this:

`				rebusConfigurer.Options(configurer =>
				{
					configurer.Register<IErrorHandler>(c =>
					{
						var settings = c.Get<SimpleRetryStrategySettings>();
						var transport = c.Get<ITransport>();
						var loggerFactory = c.Get<IRebusLoggerFactory>();
						var poisonQueueErrorHandler = new PoisonQueueErrorHandler(settings, transport, loggerFactory);
						var busLazy = container.Resolve<Lazy<IBus>>();
						return new CircuitBreakerErrorHandler(busLazy, config.RebusConfig, poisonQueueErrorHandler);
					});
				});`

Am I way off base here?

**Comment by mclausen** [comment]
What a fantastic feature 🎩 
Internally in our team, we have been discussing how to implement a Circuit breaker against an unreliable service, and then "replay" failed messages. However, implementing it directly into rebus seems by far the best and easiest choice 🙌 

An idea that comes to mind when implementing this, would be to only enable the Circuit breaker on specific conditions, such as an explicit exception being thrown or on a specific key in the Message context is set. 

```
Configure.With(...)
...
.Options(o => {
   o.SetCircuitBreakers(c => 
       c.BreakOn<TException>(new CircuitBreakerOptions({
           TrackingSeconds = 0,
           PercentFailureThreshold = 95,
           MinimumAttemptThreshold = 1,
           ResetIntervalSeconds = 5
       });
       c.BreakOn(messageContext => true, new CircuitBreakerOptions());
     )
  ))
})
```

**Comment by mookid8000** [comment]
Closing this, because all the fun happens here 👉  https://github.com/rebus-org/Rebus.CircuitBreaker
