### ISSUE TITLE
Reply to competing consumer

### ISSUE THREAD

**Issue by Confusingboat** [rebus-org/Rebus#892]
This is mostly a question about something I've been trying to achieve for several days now, that I feel there must be a simple solution for which I'm overlooking.

I have `n` competing consumers on a queue (let's call it `worker-queue`) and I'm trying to leverage `SendRequest` inside a message handler invoked by this queue. The problem is that when I reply, it may go to any of the consumers of `worker-queue` and not always the one who called `SendRequest`.

I'm thinking I could solve this by creating a "sidecar" ephemeral queue per instance that all replies would be sent to (ala randomly generated unique names like `worker-queue-fjdiopafds` which would then be set as the default reply address for the parent `IBus`) and then just hand them all to the `IBus` that sent the request; the problem with this approach is that I believe it will require a custom `IBus` implementation since I can't see an easy way to send a message directly to an instance of `IBus` (and `SendLocal` would just put the reply right back where I don't want it, on `worker-queue`, right?). The further I go down this seemingly simple rabbithole the more I feel like I'm taking the wrong approach to solving the issue.

I've looked into the round-robin message forwarding instead of having workers pull messages off a single `worker-queue`, but that would require either a fixed number of input queues with well-known names or some type of external registry for the queues, the former of which isn't exactly scalable, and the latter of which is overkill, because I don't actually care about the replies if the queue disappears. I do care about the original message that resulted in the call to `SendRequest`, however, since I'm treating those messages as units of work and capitalizing on Rebus' error and retry handling, which is why the original message must stay on the original `worker-queue`, since it may disappear into the void, lost forever if I were to just forward it to one of the ephemeral queues.

As you can see, I'm in deep on this one. Plz halp.

**Comment by Confusingboat** [comment]
So naturally the day I post my inquiry I come to a resolution. After looking over `Rebus.Async` again I noticed that its functionality is based around a static `ConcurrentDictionary`, which means that all I had to do to get it to work was call `EnableSynchronousRequestReply` on another `IBus` in the same application.

In hindsight this issue probably should have been posted in the `Rebus.Async` repo, but initially I wasn't sure if that was even the correct approach to take. I have a working implementation of a dedicated reply queue, which I think might be a desirable feature addition to `Rebus.Async` for some (even though it runs counter to the recommendation of only running one `IBus` per IoC container/application), so I'll leave this issue open to enable a point of discussion on the topic.

**Comment by mookid8000** [comment]
Rebus.Async exists mostly as an experimental feature, and I must admit that the competing consumers scenario is definitely a thing I didn't consider when I originally made it. 🙄 

It's generally not a thing I recommend people to use, as it's counter to the idea of each message carrying the necessary information to be processed - with Rebus.Async, which effectively makes use of asynchronous channels to provide a synchronous API, it's the client's state + the reply message that's necessary to continue work, and that's a much more brittle place to be in.

Would it maybe be possible for you to redesign your messages so that the replies carry enough information with them to be processable by the workers? Because then you will get all the niceness of competing consumers with the added benefit of not having to care about timeouts.

**Comment by Confusingboat** [comment]
I'm actually using Rebus.Async to close the CQRS loop server-side until we get subscriptions implemented in our GraphQL API and client-side, and with the way a couple other things are currently designed, the reply _must_ be returned to the caller since it's used to generate the HTTP response from the GraphQL mutation. I figured targeted replies would be easier to implement and more responsive than subscribing to a notification since Rebus.Async already exists. It's certainly not ideal, but we're on a tight schedule for a product launch and sometimes you've gotta do what you've gotta do.
