### ISSUE TITLE
Registering two handles of the same message type will only invoke the first one. 

### ISSUE THREAD

**Issue by mindisk** [rebus-org/Rebus#896]
I am testing a service that sends out some events. When service starts up is sends an event (`SendAllData`) to notify other services to publish all data they have about all users. I use this event in my tests as indication that the service is ready to handle data. 

The test case is to notify the service that user is updated and as a result, the service should issue an `SendAllData` event with modified user email. 

I register a handle **within a fixture** that signals that the service started.
After the event is signaled, tests can start.
```
var serviceStartedEvent = new ManualResteEvent(false);
activator.Handle<SendAllData>(msg => 
{
     serviceStartedEvent.Set():
     return Task.Completed;
});
```
Now one of the tests needs to see if the event is published by the service when user is modified. 
Therefore, I **within the test** I register a handle of `SendAllData` event.
```
var sendAllDataReceivedEvent = new ManualResteEvent(false);
_fixture.Activator.Handle<SendAllData>(msg => 
{
     if(msg.Users.Contain(updatedUserEmail))
         sendAllDataReceivedEvent.Set():
     return Task.Completed;
});
```

At this moment, the `activator` has two handles registered to the same `SendAllData` event. 
My expectation was that both handles will be invoked by Rebus. 
However, the reality was different. Only the first handle is invoked. The second handle is never invoked, nor it "overwrites"
the first handle. 

Is this by design? To lock one message type per handle?

As possible solution, could I create a new `BuiltinHandlerActivator`, register necessary handles and assign existing `IBus` instance to it?
```
var newActivator = BuiltinHandlerActivator();
newActivator .Handle<SendAllData>(msg => 
{
     if(msg.Users.Contain(updatedUserEmail))
         sendAllDataReceivedEvent.Set():
     return Task.Completed; 
});
newActivator.SetBus(_fixture.Bus);
```

Do you think this solution makes sense and will the second handler be invoked by this `newActivator` instance?

Thanks for your time.

**Comment by mindisk** [comment]
I have noticed that when registering handles with this method, handles with inherited types are not invoked as well.

The event `SendAllData` is a subclass of abstract type `MessageBase`. I tried to register a handle for this type as well and the handle was not invoked. 

As a side note, I have tied using `IHandleMessages` interface and I can say that inheritance handling works fine there.

**Comment by mookid8000** [comment]
Hi @mindisk , I'm kind of puzzled that you seem to be having this problem.

To demonstrate that what you're describing is absolutely possible, I've added this test: [BeAbsolutelySureThatTheBuiltinHandlerActivatorWorks.cs](https://github.com/rebus-org/Rebus/blob/master/Rebus.Tests/Bugs/BeAbsolutelySureThatTheBuiltinHandlerActivatorWorks.cs)

Could you go over it and see if you're doing something different?

I'm closing this for now, as I don't believe there's an issue. But let's keep the conversation going in here anyway 🙂

**Comment by mindisk** [comment]
I feel the same. I have seen setups like your example multiple times and I use it myself in a number of service. This issue puzzled me as much as you. 

The only difference I can see is that I register the second handle on a separate thread after the `IBus` have been started. 
However, I have a number of services that register handles after the bus have been started and it works quite fine. 

With that said, my uneducated guess would be that it is somehow related to xUnit (the testing framework I use) and how it handles fixtures. Yet, the second handle is registered and used in the same test case. Therefore, I have no explanation to why this is happening.  

Since I have added a workaround by just distributing received events over the `EventHandler` I will not pursue this issue anymore.

Thank you for your time.

**Comment by mookid8000** [comment]
> (...) I register the second handle on a separate thread after the IBus have been started (...)

ah, this is the problem!

It's not possible to make registrations in the built-in handler activator while the bus is running. You get an exception, when you do that.

The reason is that it's most likely an error, if you're doing so ... and there's a fairly big risk that you get a race condition between registering the handler and receiving the first message.

The solution is to ensure all your handlers have been registered before you start the bus.

**Comment by mindisk** [comment]
I was not aware of this.

> You get an exception, when you do that.

That is the thing, there is no exception. The activator silently "accepts" my handler registration. 
I think that is what confused me. Since nothing was thrown, it seemed that the handler registration was successful.

**Comment by mookid8000** [comment]
oh, I realize that you're correct: The inline handler registration methods `activator.Handle<TMessage>(...)` can still be called without any exceptions, even after the bus has been started.... the check has apparently only been implemented for the handler factory methods `activator.Register<THandler>(...)`.

Rebus 6.4.0 will carry out this check, regardless of which type of registration you're making on the built-in handler activator.

So.... but that leaves us with the question: Why does it seem like your handlers are not executed? Could you check out the test

https://github.com/rebus-org/Rebus/blob/master/Rebus.Tests/Bugs/BeAbsolutelySureThatTheBuiltinHandlerActivatorWorks.cs

and see in what ways your code differs from it?
