### ISSUE TITLE
Undo actions in Saga

### ISSUE THREAD

**Issue by MaurilioMatsuyama** [rebus-org/Rebus#898]
Hi, I developed a Saga with two stages...
When the second stage fails...I need to undo the action I did in first stage.
Is there a pattern in Rebus for doing this? Or I can make another handler to undo the changes in the first stage?

**Comment by mookid8000** [comment]
There's no mechanism in Rebus that can help you with this, besides what the "process manager" (=saga) pattern offers in the form of the ability to correlate incoming messages with a piece of custom state.

I would recommend that you create a nice model in your saga state to keep track of which actions were carried out, and therefore must be undone in the event of a rollback.
