### ISSUE TITLE
Rebus with 3rd party dependency injection frameworks

### ISSUE THREAD

**Issue by lmoelleb** [rebus-org/Rebus#904]
We use Rebus with both Autofac and Microsoft.DependencyInjection - and it is not a pleasant experience.

As far as I can see, there are two options:

1. Use manual configuration
2. Use the configuration interface with Injectionist, accepting that some things are registered in both Injectionist and the host DI 
framework - with instantiation and cleanup (dispose) issues we need to work around.

Wouldn't it be better to abstract Injectionist out with an interface (like it is already done with IHandlerActivator) and allow an optional adapter to a different DI framework to be provided to RebusConfigurer?

Or did I miss one or another obvious solution (again)?

**Comment by mookid8000** [comment]
>(...) and it is not a pleasant experience

I'm very interested in hearing more details about why you're having a less-than-ideal experience here... 🙂 

> Wouldn't it be better to abstract Injectionist out with an interface (like it is already done with IHandlerActivator) and allow an optional adapter to a different DI framework to be provided to RebusConfigurer?

Rebus versions < 0.84.0 used a container adapter to register things and then used the container to build the bus instance ... but it was a pain to iron out the differences and polyfill missing capabilities across containers...

Around that time I was building an opinionated CQRS library, [Cirqus](https://github.com/d60/Cirqus), which had this funny "configuration container" emerge during its development. I took this configuration container to the next level, called it Injectionist, and then I based Rebus 2 (versions 0.84.0 and onwards) very heavily on it.

The thing about Injectionist that differentiates it from normal containers, is that it has a 1st level concept of "decorators", and it remembers everything it has resolved during a request. This means that the code resolving `IBus` can inspect all resolved instances and initialize them if they're `IInitializable` and ensure they're disposed if they're `IDisposable`.

The last reason why Injectionist makes a lot of sense, is that Rebus doesn't need to resolve that many things at runtime – all of its services have a singleton lifestyle, so it would not add any fun possibilities if you were using an IoC container to resolve them.

I hope all of this makes sense 🙂  but again: I am curious to hear more about what caused your unpleasant experience.

**Comment by lmoelleb** [comment]
The unpleasant experience comes when you want to inject custom implementations into Rebus, and these implementations have dependencies that are also used by things "outside" rebus. In our case we have custom routing - and until Rebus 6 we had custom serialization as well.

You then have two dependency injection containers both responsible for the same type (some of which are singletons) and then object instantiation is something you need workarounds for, instead of something that just works.

For example, using Microsoft.Extensions.Logging, we have to instantiate the LoggerFactory manually, then register the instance with the main DI container and instantiate the logger adapter for Rebus using the same instance. There might be other ways, but this is the one we found first.

We then run into issues with Dispose. Autofac does not know about the IBus instance having a dependency (through the logger adapter) to the LoggerFactory, so it might dispose them out of order. So then we need to tell our main container to not dispose the LoggerFactory instance - and we need to hook into the shutdown (in our case Owin for some .NET Framework stuff we can't move to .NET Core yet) to call Dispose ourselves. I have no idea if our LoggerFactory being disposed after the DI container is just down to luck that could change next time we update nuget packages.

I do not even want to think about what would happen if other libraries would start having their own DI containers as well. Having 3-4 active containers that needs to manage lifetime... yikes.

For Injectionist
Decorators are nice but for me do not justify the complexity of dealing with multiple DI containers. Guess it would differ from user to user.
Initialize: This is a question of taste, personally I tend to avoid these and accept the class must do a check in each method if it really can't do it in the constructor. Sure it is ugly, but it won't leak implementation details out of the class. Looks like something for aspect oriented programming, but of course using Fody or the free Postsharp is not trivial either.
Dispose: In my case the use of Injectionist broke dispose.

**Comment by mookid8000** [comment]
I don't think of Injectionist as an IoC container. It's not involved in anything at runtime, and it doesn't support any kinds of lifecycle policies or anything fancy like that – it's basically just a way for the Rebus configuration system to incrementally build a `RebusBus` instance.

If you'd like to integrate an IoC container with the intention of having Rebus services (e.g. a custom serializer) resolve things in it at runtime, then please do – but since all of the services resolved by Injectionist are singletons, you will have to handle the resolve/release cycle yourself.

> For example, using Microsoft.Extensions.Logging, we have to instantiate the LoggerFactory manually, then register the instance with the main DI container and instantiate the logger adapter for Rebus using the same instance. There might be other ways, but this is the one we found first.

In this case, it seems you didn't discover the registration method that resolves the bus from a factory method accepting `IServiceProvider` – that's what you need in this case:
```csharp
services.AddRebus(
    (configure, provider) => configure
        .Logging(l => l.MicrosoftExtensionsLogging(provider.GetRequiredService<ILoggerFactory>()))
        .Transport(t => t.Use(...))
);
```
It seems to me this would solve the issues you are having with container-administered disposal of thing, don't you think?

>I do not even want to think about what would happen if other libraries would start having their own DI containers as well. Having 3-4 active containers that needs to manage lifetime... yikes.

This is why Rebus does not pretend to have an IoC container 🙂 it's just a `RebusBus` instance, which you must dispose when the application stops. This way, you even have the option of having zero IoC containers in your application.
