### ISSUE TITLE
Upgrade from Rebus 5.4.1 to 6.4.1 results in "Could not get .NET type named"

### ISSUE THREAD

**Issue by renemadsen** [rebus-org/Rebus#905]
When doing:

`await _bus.SendLocal(new TrashInspectionReceived(createModel, fraction, segment, installation));`

We get the error:

`Could not get .NET type named 'TrashInspection.Pn.Messages.TrashInspectionReceived, TrashInspection.Pn'
`

We register all our handlers by:

public class RebusHandlerInstaller : IWindsorInstaller
    {
        public void Install(IWindsorContainer container, IConfigurationStore store)
        {
            container.Register(Component.For<IHandleMessages<TrashInspectionReceived>>().ImplementedBy<TrashInspectionReceivedHandler>().LifestyleTransient());            
            container.Register(Component.For<IHandleMessages<TrashInspectionDeleted>>().ImplementedBy<TrashInspectionDeleteHandler>().LifestyleTransient());            
            container.Register(Component.For<IHandleMessages<TrashInspectionCaseCreated>>().ImplementedBy<TrashInspectionCaseCreatedHandler>().LifestyleTransient());            
        }
    }

And rebus is starting like:
`[INF] Rebus.Internals.ConnectionManager (Thread #1): Initializing RabbitMQ connection manager for transport with input queue "eform-angular-trashinspection-plugin"`
`[INF] Rebus.Threading.TaskParallelLibrary.TplAsyncTask (Thread #1): Starting periodic task "CleanupTrackedErrors" with interval 00:00:10`
`[INF] Rebus.Bus.RebusBus (Thread #1): Bus "Rebus 1" setting number of workers to 1`
`[DBG] Rebus.Bus.RebusBus (Thread #1): Adding worker "Rebus 1 worker 1"`
`[INF] Rebus.Bus.RebusBus (Thread #1): Bus "Rebus 1" started`
`[DBG] Rebus.Workers.ThreadPoolBased.ThreadPoolWorker (Rebus 1 worker 1): Starting (threadpool-based) worker "Rebus 1 worker 1"`
`[INF] Rebus.RabbitMq.RabbitMqTransport (Rebus 1 worker 1): Successfully initialized consumer for "eform-angular-trashinspection-plugin"
`

So, what is the error message acutally telling me I'm doing wrong?

The codebase worked completely perfect before upgrading to 6.4.1

**Comment by mookid8000** [comment]
Could you post the entire exception? (all the details, including a stack trace)

**Comment by renemadsen** [comment]
The entire exception is:

[WRN] Rebus.Retry.ErrorTracking.InMemErrorTracker (Rebus 1 worker 1): Unhandled exception 1 while handling message with ID "1e04f588-ff53-450c-b2bb-ed6561dfc36e"
System.FormatException: Could not get .NET type named 'TrashInspection.Pn.Messages.TrashInspectionReceived, TrashInspection.Pn'
   at Rebus.Serialization.Json.JsonSerializer.GetTypeOrNull(TransportMessage transportMessage)
   at Rebus.Serialization.Json.JsonSerializer.GetMessage(TransportMessage transportMessage, Encoding bodyEncoding)
   at Rebus.Serialization.Json.JsonSerializer.Deserialize(TransportMessage transportMessage)
   at Rebus.Compression.UnzippingSerializerDecorator.Deserialize(TransportMessage transportMessage)
   at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.DataBus.ClaimCheck.HydrateIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Pipeline.Receive.HandleDeferredMessagesStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Retry.FailFast.FailFastStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Retry.Simple.SimpleRetryStrategyStep.DispatchWithTrackerIdentifier(Func`1 next, String identifierToTrackMessageBy, ITransactionContext transactionContext, String messageId, String secondLevelMessageId)

**Comment by mookid8000** [comment]
Well, it seems the error is that a type lookup for `TrashInspection.Pn.Messages.TrashInspectionReceived, TrashInspection.Pn` does not result in anything.

Could you try and check that your application references the `TrashInspection.Pn` assembly, either directly or as a transitive dependency, and then check that the `TrashInspectionReceived` does in fact reside in the `TrashInspection.Pn.Messages` namespace in that assembly?

**Comment by renemadsen** [comment]
> Well, it seems the error is that a type lookup for `TrashInspection.Pn.Messages.TrashInspectionReceived, TrashInspection.Pn` does not result in anything.
> 
> Could you try and check that your application references the `TrashInspection.Pn` assembly, either directly or as a transitive dependency, and then check that the `TrashInspectionReceived` does in fact reside in the `TrashInspection.Pn.Messages` namespace in that assembly?

The problem is that it's the same project. TashInspection.Pn is the sender and receiver and the one starting up the bus...

And namespace is correct.

**Comment by mookid8000** [comment]
Ok, that sounds weird 🤔 the line that throws is this one:
```csharp
var type = _messageTypeNameConvention.GetType(typeName) ?? throw new FormatException($"Could not get .NET type named '{typeName}'");
```
(found [here](https://github.com/rebus-org/Rebus/blob/master/Rebus/Serialization/Json/JsonSerializer.cs#L130))

As you can see, the serializer is using the "message type name convention" to look up the type from the type name, and by default the convention will be `SimpleAssemblyQualifiedMessageTypeNameConvention` (can be seen [here](https://github.com/rebus-org/Rebus/blob/master/Rebus/Serialization/SimpleAssemblyQualifiedMessageTypeNameConvention.cs))

This particular type name convention simply uses `Type.GetType(name)` to get the type, so... could you by any chance be using an alternative type name convention that returns null for your type name?

**Comment by renemadsen** [comment]
> This particular type name convention simply uses `Type.GetType(name)` to get the type, so... could you by any chance be using an alternative type name convention that returns null for your type name?

How do I see/test that?
The message class can be seen here https://github.com/microting/eform-angular-trashinspection-plugin/blob/master/eFormAPI/Plugins/TrashInspection.Pn/TrashInspection.Pn/Messages/TrashInspectionReceived.cs

**Comment by mookid8000** [comment]
> How do I see/test that?

Well, if you didn't change the convention, then it's `SimpleAssemblyQualifiedMessageTypeNameConvention`.

Could you try and see what `Type.GetType("TrashInspection.Pn.Messages.TrashInspectionReceived, TrashInspection.Pn")` returns, e.g. in a unit test?

**Comment by renemadsen** [comment]
> Could you try and see what `Type.GetType("TrashInspection.Pn.Messages.TrashInspectionReceived, TrashInspection.Pn")` returns, e.g. in a unit test?

It returns "TrashInspection.Pn.Messages.TrashInspectionReceived" as I guess is expected to be correct.

**Comment by mookid8000** [comment]
Wow that's really weird. Do you think you would be able to reproduce this in a repository I can download? Because then I would be happy to debug it 🙂

**Comment by renemadsen** [comment]
> Wow that's really weird. Do you think you would be able to reproduce this in a repository I can download? Because then I would be happy to debug it

I can provide a zip file, but it's going to be over 400Mb, since it's a low of moving parts...

**Comment by mookid8000** [comment]
Oh, but that's ok 🙂

**Comment by renemadsen** [comment]
I tried to checkout Rebus tag 6.4.1 and use it instead of the nuget, then _container.install()

And I'm using this:

        public void Install(IWindsorContainer container, IConfigurationStore store)
        {
            Configure.With(new CastleWindsorContainerAdapter(container))
                .Logging(l => l.ColoredConsole())
                .Transport(t => t.UseRabbitMq("amqp://admin:password@localhost", "eform-angular-trashinspection-plugin"))
                .Options(o =>
                {
                    o.SetMaxParallelism(1);
                    o.SetNumberOfWorkers(1);
                })
                .Start();
            
        }

But it's not getting run, and if I comment the above code and have an empty install method, it's getting triggered.

**Comment by renemadsen** [comment]
I tried downgrading to 6.0.0 and now it works, so it seems to be an issue with Rebus.CastleWindsor not working correctly with Rebus 6.4.1?

**Comment by mookid8000** [comment]
> But it's not getting run, and if I comment the above code and have an empty install method, it's getting triggered.

Not sure I understand what you're saying here?

**Comment by renemadsen** [comment]
> Not sure I understand what you're saying here?

I did a lot more testing and found that the problem, was that Rebus.Castle.Windsor was not upgraded to use Rebus 6.4.1, so it was looking for Rebus 6.0.0, but it's not there since Rebus was upgraded to 6.4.1.

So the issue is related to Rebus.Castle.Windsor.

**Comment by mookid8000** [comment]
I've pushed Rebus.CastleWindsor 6.1.0 to NuGet.org now - could you try and see if your stuff works with that?

(I updated the Rebus dependency to 6.4.1, and then I updated the targets to something more contemporary)

**Comment by renemadsen** [comment]
After thoroughly testing I found that it worked :-)

**Comment by renemadsen** [comment]
Finally figured out the reason for cause for this problem, it's the changes done in this commit.

https://github.com/microting/Rebus/commit/0ef305ed65b2738d8f7c79c62a3dced85fa38baf#diff-05bc542f76c223a2db25b48788e1a01c0ad0991998766c9207ff2e2e8e2c70b6

When reverting the changes done in GetTypeOrNull then it works and no tests are breaking. So I suppose that there is no test, which is actually covering the difference.

Upon further investigation, the problem araises, because of the new way Type.GetType does it's lookup in net 5.0.
More can be read about it at https://jeremybytes.blogspot.com/2020/01/using-typegettype-with-net-core.html?m=1
