### ISSUE TITLE
Duplicated message when using Defer

### ISSUE THREAD

**Issue by oocpawel** [rebus-org/Rebus#908]
I saw similar ticket that was closed without investigation here.
My client is using 
- Rebus v3.1.5
- Rebus.Castle.Windsor v3.0.0
- Rebus.Msmq v3.0.0
- Rebus.Jil v3.0.0
- Rebus.NLog v3.0.0
- Rebus.RavenDb v3.0.0 
- Rebus.XmlConfig v3.0.0
with
- RavenDB.Client 3.5.5

Rebus.Workers = 5

Behaviour looks like this. I am running some saga. During saga I can get a message that I want to enqueue after saga so I am using Rebus Defer to postpone for 5 minutes a message if saga is running. After 5 minutes when message arrive once more, i am checking once again if Saga is still running and if not then i am handling this message properly.

The problem is that, it is working ok for some time and after some time defered messages are starting duplicating. So we can see in logs messages with the same id, like this: 1->1->1->1->1->1->2->3->5->6->7
So if we have many messages for example 7000 than in few seconds queue can get up to 14000. And this is serious problem.

**Comment by mookid8000** [comment]
Sounds pretty weird. Can you reproduce it somehow? Then I'll be happy to debug it.

**Comment by oocpawel** [comment]
ok i will try to prepare some tests for that

**Comment by mookid8000** [comment]
Hi @oocpawel , did you figure something out here?

**Comment by oocpawel** [comment]
not yet, because of a black-week

**Comment by oocpawel** [comment]
closed? are you joking? I saw the same ticket already closed without fix: 
[https://github.com/rebus-org/Rebus/issues/847](url)
and this one you are closing too? without checking it?

**Comment by mookid8000** [comment]
Hi @oocpawel , sorry about that - I'd still be happy to investigate, if you can reproduce it somehow.

Or if you have any other hints towards what could be going on here, please let me know.
