### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by sauron2k** [rebus-org/Rebus#910]
Hi

Performing some tests to use Rebus in a windows service with Mysql as transport. I have used the RequestReply project from the RebusSamples repository as a test. I have modified the consumer code to be the following

 class Program
    {
        const string ConnectionString = "MyConnectionStrings";        

        static void Main()
        {
            using (var adapter = new BuiltinHandlerActivator())
            {
                adapter.Handle<Job>(async (bus, job) =>
                {
                    var keyChar = job.KeyChar;
                    var processId = Process.GetCurrentProcess().Id;
                    var reply = new Reply(keyChar, processId);

                    await bus.Reply(reply);
                });

                Configure.With(adapter)
                    .Logging(l => l.ColoredConsole(minLevel: LogLevel.Warn))
                    .Transport(t => t.UseMySql(ConnectionString, "Messages", "consumer.input"))
                    .Start();

                Console.WriteLine("Press ENTER to quit");
                Console.ReadLine();
            }
        }
    }

These are the screenshots of the Visual Studio diagnostic tools for the first 10 minutes.
![DiagnosticTool 0](https://user-images.githubusercontent.com/26332544/99834257-99619d00-2b63-11eb-8375-9c91ed52ad21.PNG)
![DiagnosticTool 1](https://user-images.githubusercontent.com/26332544/99834258-99fa3380-2b63-11eb-9fff-db548acacf1c.PNG)
![DiagnosticTool 2](https://user-images.githubusercontent.com/26332544/99834262-9a92ca00-2b63-11eb-949e-df1bfba96ff1.PNG)
![DiagnosticTool 3](https://user-images.githubusercontent.com/26332544/99834265-9b2b6080-2b63-11eb-8ba5-c4f5f5d365be.PNG)
![DiagnosticTool 4](https://user-images.githubusercontent.com/26332544/99834266-9b2b6080-2b63-11eb-84f0-f1c9c714da16.PNG)

Everything works fine, except for the fact that memory keeps growing in the background for some reason. I'm not doing any work, I just bring the console up with Ctrl + F5 and put it on hold. In less than 5 minutes, the memory increases from 17 megabytes to 30 and goes up to 40 at 10 minutes, 50 to 12 minutes and continues until the System.OutOfMemoryException exception is finally thrown, at many hours later.

What is causing this problem?

**Comment by sauron2k** [comment]
After some tests, I think it must be something related to the mysql transport.

Since I have modified the transport to SqlServer and MSMQ and the memory remains stable at 23 megabytes.

Only when using the Mysql transport is where memory starts to go up and never stops.

**Comment by mookid8000** [comment]
I would also have guessed that the MySQL integration was causing this too, as I've had no other reports like this.

The current version of Rebus.MySql depends on MySql.Data 8.0.12 – have you tried updating it to the newest? (8.0.22)

Can the memory profiler tell you which objects are being accumulated?

**Comment by sauron2k** [comment]
I have updated the Mysql.Data and the same thing happens.

I first tried one by doing a binding redirect in the test project and then I downloaded the Rebus.Mysql master and also updated MySql.Data and referenced the compiled version dll.

I will try to see how to find with the profiler, what objects are accumulating in memory. Since I haven't used a profiler for a while

**Comment by sauron2k** [comment]
Hello, I have continued doing tests to see which objects do not stop growing in memory and although many do not stop growing. These are the main ones I have tried to analyze. 

These are memory snapshots with the Consumer console up (the Producer is not up) without doing anything after 10 minutes

![Snapshot-memory](https://user-images.githubusercontent.com/26332544/100113725-eb126c00-2e70-11eb-98a6-bf718221e5f4.PNG)

The first elements are

**Dictionary<String,Object>** 

these are the elements it contains

![Snapshot-memory1](https://user-images.githubusercontent.com/26332544/100114464-c2d73d00-2e71-11eb-80b1-c47a914cb551.PNG)

Dictionary<String, Int32>		

![Snapshot-memory2](https://user-images.githubusercontent.com/26332544/100114614-e601ec80-2e71-11eb-9819-eddf20660a18.PNG)

List<MySql.Data.MySqlClient.MySqlParameter>

![Snapshot-memory3](https://user-images.githubusercontent.com/26332544/100114702-fdd97080-2e71-11eb-8023-aa0091a69ec2.PNG)

MySql.Data.MySqlClient.MySqlParameter		

![Snapshot-memory4](https://user-images.githubusercontent.com/26332544/100114796-13e73100-2e72-11eb-9069-797c9f452f53.PNG)

At first, I thought that maybe it was caused by some leaked MySqlConnection, because not in everywhere it was created using the Using (){} but checking de MySqlConnectionPool Class using reflection everything was OK, only one connections string was used

I can't find where the failure may come from when checking some of the code.

**Comment by sauron2k** [comment]
After going through the code in all the parts, I couldn't find clues that would lead me to some kind of bug in the code that was causing the memory leaks.

Checking the objects that are constantly being added, I found some errors in the MySQL.Data connector that were related but were bugs from 4 or 5 years ago.

I also found other references to the fact that the connector doesn't really support true Async and some old bug was said to cause a memory leak.

Although there really is no way to prove it or at least I had no way to prove it.

This led me to change the connector and use MySQLConnector as for typical scenarios migrating to this package should be easy.

https://github.com/mysql-net/MySqlConnector

So I downloaded the source code and after making the modifications (basically change the references in the using of the classes), there was no more memory leak. 

I don't know if it's worth a fork to keep one for the MySQL.Data connector and one for the SqlConnector. But in summary, just modifying the connector solves the memory leak problem

**Comment by mookid8000** [comment]
Excellent work! Any chance you could submit your changes in a PR?

**Comment by sauron2k** [comment]
No problem this week I have it a bit complicated but as soon as I can have time I make the submit.

I have not tested the changes exhaustively so I would recommend first going through a battery of tests with that connector, since I have only used it for a request -reply use case, I have not considered the rest of possibilities.

I have not performed tests of one-way sense and how they are verified in a multithreaded environment, since this connector does support native asynchronous, it should be noted that the OpenAsync when opening the connection must have some consideration if it is used with a Task.Wait or similar.

As soon as I can, I do the submit
