### ISSUE TITLE
AutoRegisterHandlersFromAssembly registering all classes on Namespace

### ISSUE THREAD

**Issue by jfalameda** [rebus-org/Rebus#912]
Hi,

I do not know if this is a bug or a feature, when I call AutoRegisterHandlersFromAssembly, it will register al classes present on that namespace.

Eg:

```
Namespace1.Namespace2.Class1

AutoRegisterHandlersFromAssembly<Class1>
```

It will register all classes present on ```Namespace1```

Thanks.

**Comment by mookid8000** [comment]
Not only handlers?

**Comment by jfalameda** [comment]
Hi, What do you mean by handlers?

**Comment by mookid8000** [comment]
"Handlers" as in "message handlers"... like `ProcessOrderHandler`:
```csharp
public class ProcessOrderHandler : IHandleMessages<ProcessOrder>
{
    public async Task Handle(ProcessOrder message)
    {
        // handle message in here
    }
}
```

**Comment by jfalameda** [comment]
Hi,

As I understand one should pass ProcessOrder (Equivalent) to
AutoRegisterHandlersFromAssembly.
In my case it is registering all classes on ProcessOrder (equivalent)
namespace.

Kind Regards,
José.

**Comment by mookid8000** [comment]
But the purpose of `AutoRegisterHandlersFromAssemblyOf<THandler>` is to register HANDLERS, not messages. `ProcessOrder` in the example above is a command message, and `ProcessOrderHandler` is the handler for it.

Maybe you could tell me more about what it is that you observe that makes you believe that

> (...) it will register al classes present on that namespace.

?
