### ISSUE TITLE
Have `IHandleMessage` provide support for UsedImplicitly from Jetbrains annotations

### ISSUE THREAD

**Issue by zlepper** [rebus-org/Rebus#914]
Jetbrains provides an annotations library that is used for some inspections by tools like Rider and ReSharper. One of those is `UsedImplicitly`, which tells the tools that the class is actually used, though it's through fx reflection so there is no direct usage. 

I believe it would be a good idea to add this annotation to IHandleMessages, since those are often found through some sort of assembly scanning. Currently concrete handlers are reported unused, which is a bit confusing when trying to remove actually unused code. We can annotate every handler ourselves, but that is a bit cumbersome, since there is already an indicate due to the interface. 

The specific combinations of flags that are needed are as follows:

```c#
  [UsedImplicitly(ImplicitUseTargetFlags.Itself | ImplicitUseTargetFlags.WithInheritors)]
    interface IHandleMessages<T>
    {
        
    }
```

And yes, I know there would normally be references from unit tests, however this is a Legacy code base, and unit test was clearly not something they thought important, and are a pain to retrofit...

I can make the PR myself, I just wanted to confirm if it was something that would be of shared interest before I went ahead :)

**Comment by mookid8000** [comment]
Sorry, but Rebus' core library should not reference anything from JetBrains.

I suggest you either

1) ALT+ENTER on your concrete handler type and accept ReSharper's offer of disabling the "type is never used" inspection by adding
```
// ReSharper disable UnusedType.Local
```
to the top of your file, or

2) Avoid assembly scanning and reference the handler explicitly in your IoC container configuration code:
```csharp
services.AddRebusHandler<YourHandler>();
```
(here using Rebus.ServiceProvider as an example).


The thing is, the choice of using JetBrains's tools to inspect your code is YOUR choice (and mine, too 😉), but we should not force a random dependency like JetBrains' inspections NuGet on all the people who do NOT use R#. Because then we might end up with a core assembly that has to account for StyleCop/CodeRush/whatever inspections, and that would be silly.

I hope that makes sense. 🙂

**Comment by zlepper** [comment]
To my knowledge they only added as a build time dependency, not a transient one, so it _shouldn't_ affect downstream. 

However I completely understand and agree with what you said, which is also why I made a ticket first, so we didn't waste time :)

**Comment by mookid8000** [comment]
OK maybe I don't know enough about it then!

Do library authors happily add the dependency to their core libraries?

**Comment by zlepper** [comment]
> Do library authors happily add the dependency to their core libraries?

That I don't know, but I would imagine it's a pretty common usecase.

This is from their docs:

> All usages of ReSharper Annotations attributes are erased from metadata by default, which means no actual binary reference to 'JetBrains.Annotations.dll' assembly is produced. If you need to preserve these attributes in metadata, just define 'JETBRAINS_ANNOTATIONS' conditional compilation symbol in your projects.

Though I'm by no means an expert in how the .net compilers works, so there is a chance that I'm wrong. But shouldn't we be able to see what happens if we just make a build with it? 
One thing that I fear might happen is that the annotations doesn't flow downstream properly, but that would require a test (Which I should be able to do, just by pushing to a local nuget repo).

**Comment by mookid8000** [comment]
ok, you've got me convinced that we should at least try and see what happens! 🙂

**Comment by mookid8000** [comment]
as in: If it turns out to be as unintrusive as they claim, then I see no problem in referencing that Nuggie

**Comment by zlepper** [comment]
I'll try after lunch, and then I'll get back to you! :)

**Comment by zlepper** [comment]
So this is lovely...
I cannot get the annotation to "flow" through the Nuget package at all, even if I keep an explicit dependency on JetBrains.Annotations. I honestly believe this must be a bug, since it works between projects in the same solution. And there I can manage to avoid forcing a dependency on downstream consumers (As long as they have the dep themselves, which I consider fine, since they made an explicit choice in that case). 

I have asked them in the comments here: https://youtrack.jetbrains.com/issue/RSRP-481389, so I hope they will return with some sort of answer or indication of what I have done wrong.

**Comment by zlepper** [comment]
So after some tips by JetBrains, telling me to try again, I tried again, this time with a different order of things in the .csproj, and it worked, here ya go, PR :D
