### ISSUE TITLE
Push based transports

### ISSUE THREAD

**Issue by zlepper** [rebus-org/Rebus#917]
Some of the transports, like RabbitMQ supports push, in other words: Faster reaction, and no polling at all. 

Looking over the code it can likely be done by setting the `WaitNoMessageAsync` backoff to zero (By decorating and overwriting that specific method), and then modifying the transport that we are using (RabbitMQ), to just wait for a message to arrive if there is currently no message waiting. 

The last part I would probably do by using System.Channels, so we can just await the next message coming in. 

I know this is a pretty rough description, but would it have any interest in Rebus proper, or would we be completely on our own to maintain that? We would certainly be interested in contributing it back, though that would likely require some guidelines to ensure everything is structured and done properly to fit the rest of the project. 

I can make the changes, since we are going to be going for it internally either way, and then we can talk if it something you would like to be upstreamed back :)

**Comment by zlepper** [comment]
@mookid8000 I'm currently tweaking the RabbitMQ transport to do this, and there is something I'm wondering about: Why is there an internal queue of the consumers? To my knowledge the connections are thread safe, and it's best to reuse the same connection? Or  is that knowledge wrong?

Additionally I have some problems with the contract Rebus has for it's transports: Mainly that `null` is being returned when the queue is empty. With my current implementation it just waits, meaning that it will never return null. Considering the general amount of errors I'm getting, I might need some assistance. Would you be fine with me creating a PR against the RabbitMQ transport, in draft mode, and then we can try to go over the changes?

**Comment by mookid8000** [comment]
>  Why is there an internal queue of the consumers? 

Honestly, I can't remember .... I think it's because `IModel` is not thread safe, and each consumer has an `IModel`, which is then used by Rebus to send all outgoing messages for the current unit of work... or something like that.

It's definitely an interesting thing you're trying to do – I would love to take a look at how to integrate non-polling transports in Rebus, and so I'd appreciate it if you would share your learnings here. 🙂

**Comment by zlepper** [comment]
You are indeed right, IModel isn't actually threadsafe according to the docs: 

> As a rule of thumb, IModel instance usage by more than one thread simultaneously should be avoided. Application code should maintain a clear notion of thread ownership for IModel instances.
> 
> This is a hard requirement for publishers: sharing a channel (an IModel instance) for concurrent publishing will lead to incorrect frame interleaving at the protocol level. Channel instances must not be shared by threads that publish on them

https://www.rabbitmq.com/dotnet-api-guide.html#concurrency-channel-sharing

**Comment by mookid8000** [comment]
Closing this for now.... Rebus _could_ support push-based transports, but I think the best way would be to replace Rebus' default worker factory, this way enabling the creation of something that is not backed by a worker thread like it is now.

I'd be happy to give pointers, if this is something you'd like to look into.
