### ISSUE TITLE
Usage of UseRabbitMqAsOneWayClient() Bus across Threads

### ISSUE THREAD

**Issue by DanielGibbons** [rebus-org/Rebus#918]
Hi,

I've been reading https://github.com/rebus-org/Rebus/wiki/Thread-safety-and-instance-policies, but didn't come across any advice regarding the use of `UseRabbitMqAsOneWayClient()` across multiple threads.

I have an application that consumes from RabbitMQ using the follow Bus instance which is a singleton instance for the lifetime of the application:

```lang=cs
protected override IBus InternalCreateBus(string endpoint = null)
{
    return Configure.With(Activator)
        .Transport(t => t
            .UseRabbitMq(ConnectionString, _source)
            .ExchangeNames(ExchangeName + "Direct", ExchangeName)
            .Prefetch(_options.Prefetch))
        .Serialization(a => a.UseNewtonsoftJson(JsonInteroperabilityMode.PureJson))
        .Options(oc =>
        {
             oc.SimpleRetryStrategy(_options.ErrorQueueName, _options.RetryCount, errorDetailsHeaderMaxLength: _maxErrorLength);
             oc.SetNumberOfWorkers(_options.WorkerCount);
             oc.SetMaxParallelism(_options.MaxParallelism ?? _options.WorkerCount);
        })
        .Start();
}
```

In the same application the workers that are instantiated by the Bus declared above all need to be able to publish to RabbitMQ.

Is it safe/is it recommended for all of these workers to share the same singleton publish bus instance declared in the following way:

```
protected override IBus InternalCreateBus(string endpoint = null)
{
    return Configure.With(Activator)
        .Transport(t => t
            .UseRabbitMqAsOneWayClient(ConnectionString)
            .ExchangeNames(ExchangeName + "Direct", ExchangeName))
        .Serialization(a => a.UseNewtonsoftJson(JsonInteroperabilityMode.PureJson))
        .Start();
}
```

Or is a separate publishing bus required for each worker?

Hope you you can help!

**Comment by mookid8000** [comment]
> Is it safe/is it recommended for all of these workers to share the same singleton publish bus instance declared in the following way?

Glad you asked 🙂 and yes, it is safe!
