### ISSUE TITLE
Process communication with in memory transport / storage

### ISSUE THREAD

**Issue by X1C3** [rebus-org/Rebus#920]
Hi. I have tried to communicate with two processes. I used in memory transport and  storage. But it doesnt worked. Is it even possible with this configuration? Thanks.

**Comment by mookid8000** [comment]
>  Is it even possible with this configuration?

No.

The in-mem transport and persistence implementations rely on storing everything in the current process' memory, and so it's not possible to reach it from other processes.

If you're looking for simple and lightweight ways to communicate between processes, I suggest you take a look at the file system-based transport:
```csharp
Configure.With(...)
	.Transport(t => t.UseFileSystem(@"C:\data\shared\directory", "my-queue"))
	.Start();
```
If you point the bus instances in all of your processes towards the same directory (here `C:\data\shared\directory`), then they will be able to communicate.

**Comment by simonmurrell** [comment]
I tried this

Process 1:

Publisher : 

// Initialize Bus
            adapter = new BuiltinHandlerActivator();
            //adapter.Register(() => new Handler());

            // Log Information
            LogInformation("Starting Bus");

            Configure.With(adapter)
                .Logging(logging => logging.Serilog())
                .Routing(routing => routing.TypeBased().Map<StringMessage>("my-queue"))
                .Transport(transport => transport.UseFileSystem(@"d:\queues\", "my-queue"))
                .Subscriptions(subscription => subscription.UseJsonFile("d:\\queues\\publisher.json"))
                .Start();

With this code below every 5 seconds. No exceptions occurred. Nothing appeared in the path above....

try
            {

                adapter.Bus.Publish(new StringMessage("Hello there, I'm a publisher! - " + DateTime.Now.ToString())).Wait();

            }
            catch (Exception ex)
            {

                Console.WriteLine(ex.Message);

            }


Process 2:

// Initialize Bus
            adapter = new BuiltinHandlerActivator();
            // Register
            adapter.Register(() => new Handler());

            // Log Information
            LogInformation("Starting Bus");

            Configure.With(adapter)
                //.Logging(logging => logging.Serilog())
                .Routing(r => r.TypeBased().Map<StringMessage>("my-queue"))
                .Transport(transport => transport.UseFileSystem("d:\\queues", "my-queue"))
                .Subscriptions(subscription => subscription.UseJsonFile("d:\\queues\\subscriber.json"))
                .Start();

            // Subscribe
            adapter.Bus.Subscribe<StringMessage>();

class Handler : IHandleMessages<StringMessage>
    {
        public async Task Handle(StringMessage message)
        {
            Console.WriteLine("Got string: {0}", message.Text);
        }

    }

    public class StringMessage
    {
        public string Text { get; }

        public StringMessage(string text)
        {
            Text = text;
        }
    }

Subscriber never gets a notification. If I change these into a single process using UseInMemoryTransport and StoreInMemory then it sends and receives messages between publisher and subscriber perfectly.

**Comment by TimoCzotscher** [comment]
Hey, I would like to add a question to this topic.
I am currently trying to use Rebus for interprocess communication as described in this thread.
But if I have one application sending messages:
```
using Rebus.Activation;
using Rebus.Config;
using Rebus.Transport.FileSystem;

using var activator = new BuiltinHandlerActivator();

var appDataDirectoryPath = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);

Configure.With(activator)
    .Transport(t => t.UseFileSystem($"{appDataDirectoryPath}/Temp/rebus-test/", "testqueue"))
    .Start();

var timer = new System.Timers.Timer();
timer.Elapsed += delegate { activator.Bus.SendLocal(DateTime.Now).Wait(); };
timer.Interval = 1000;
timer.Start();

Console.WriteLine("Press enter to quit");
Console.ReadLine();
```

And one receiving messages:

```
using Rebus.Activation;
using Rebus.Config;
using Rebus.Handlers;
using Rebus.Transport.FileSystem;

using var activator = new BuiltinHandlerActivator();

var appDataDirectoryPath = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);

activator.Register(() => new PrintDateTime());

Configure.With(activator)
    .Transport(t => t.UseFileSystem($"{appDataDirectoryPath}/Temp/rebus-test/", "testqueue"))
    .Start();

Console.WriteLine("Press enter to quit");
Console.ReadLine();

public class PrintDateTime : IHandleMessages<DateTime>
{
    public async Task Handle(DateTime currentDateTime)
    {
        Console.WriteLine("The time is {0}", currentDateTime);
    }
}
```

I get a lot of the following errors. There are still messages also consumed successfully, but some are not.
![image](https://github.com/user-attachments/assets/f1d934c9-ca76-4f38-91ea-c59a2b18b107)

Is this because the sending application is also trying to consume messages even if have not registered a handler?
I am not sure why I am getting those errors. Any help would be appreciated!

**Comment by TimoCzotscher** [comment]
Meanwhile, I figured out why I had those errors. It seems like I have to configure the rebus instance of my sending application as one-way client:

```
using Rebus.Activation;
using Rebus.Config;
using Rebus.Routing.TypeBased;
using Rebus.Transport.FileSystem;

using var activator = new BuiltinHandlerActivator();

var appDataDirectoryPath = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);

var bus = Configure.With(activator)
    .Transport(t => t.UseFileSystemAsOneWayClient($"{appDataDirectoryPath}/Temp/rebus-test/"))
    .Routing(r => r.TypeBased().Map<DateTime>("testqueue"))
    .Start();

var timer = new System.Timers.Timer();
timer.Elapsed += delegate { bus.Send(DateTime.Now).Wait(); };
timer.Interval = 1000;
timer.Start();

Console.WriteLine("Press enter to quit");
Console.ReadLine();
```

With the unchanged second application reading the messages it works without errors.
