### ISSUE TITLE
Cosmos DB saga storage

### ISSUE THREAD

**Issue by gideonkorir** [rebus-org/Rebus#923]
Similar to [this previous issue](https://github.com/rebus-org/Rebus/issues/613). I'd like to run rebus on Azure with Cosmos DB rather than use SQL Server since we are using currently using cosmos for all our data storage. 

I've been looking into it and have [an implementation here](https://github.com/gideonkorir/rebus.cosmosdb/tree/initial-cosmos-storage). 

So far this is what I've come up with:

1. Partitioning by some correlation property (e.g. OrderId) means that looking up the saga data by any other correlation property will lead to a cross partition query. My current implementation only supports a single correlation property and throws if multiple properties are specified. This means all tests in `Rebus.Tests.Contracts` that have multiple correlation properties will fail.
2. Partitioning by saga data type (or some value derived from it) allows multiple correlation properties since we always know the partition key but will use up more RUs since we won't be doing a point query unless we are using the `id` property.

I've checked the [MassTransit saga persistence](https://github.com/MassTransit/MassTransit/blob/develop/src/Persistence/MassTransit.Azure.Cosmos/Saga/Context/CosmosSagaRepositoryContext.cs) and [Nservicebus saga persistence](https://github.com/Particular/NServiceBus.Persistence.CosmosDB/blob/master/src/NServiceBus.Persistence.CosmosDB/Saga/CosmosSagaIdGenerator.cs) and they all seem to be using (1) above.

Using (2) might be ok if one is ok with [limits of a single partition](https://docs.microsoft.com/en-us/azure/cosmos-db/concepts-limits)

**Comment by mookid8000** [comment]
I'd definitely go for (1).

Regarding the tests, maybe it would make sense to simply not use the contract tests for this persister.

Or maybe it would make sense to split the contract tests out into separate fixtures for single-property and multi-property correlation scenarios, which would then make it possible for single-property persisters to include only the tests they can work with....?

**Comment by TimterLaare** [comment]
I would love this feature in a future release! What is the status of this issue?

**Comment by mookid8000** [comment]
Not sure 🙂 @gideonkorir does it work for you?

**Comment by gideonkorir** [comment]
@mookid8000 I didn't get to use it in production :( but it was working for all initial tests that I had though I'd be happy to collaborate to get it in a good state

**Comment by TimterLaare** [comment]
@gideonkorir @mookid8000 Which steps need to be taken to get this implemented?

**Comment by mookid8000** [comment]
Hi @gideonkorir , did your CosmosDB saga persister work as expected? Would you be interested in contributing it to rebus-org?

**Comment by mookid8000** [comment]
Hi @gideonkorir and @TimterLaare ,

This issue has been been dormant for a while now, and there has been no comments from anyone else in need of a CosmosDB persister. Maybe the MongoDB saga persister is useful enough for CosmosDB users too?

Anyways, I'm closing this issue for now. Please don't hesitate to get back in here if this is something that should be picked up again.
