### ISSUE TITLE
High CPU usage, no backoff option available?

### ISSUE THREAD

**Issue by cartsp** [rebus-org/Rebus#924]
Hi,

I am using the following config:

```c#
services.AddRebus((options, serviceProvider) =>
    options.Transport(t => t.UseOracle(hostContext.Configuration.GetConnectionString("JMS"), "events_table",
                "CustomerNotificationService"))
            .Subscriptions(s => s.StoreInOracle(hostContext.Configuration.GetConnectionString("JMS"), "events_subs",
                isCentralized: true))
            .Logging(l => l.Serilog())
            .Options(o => {
                o.SetNumberOfWorkers(1);
                o.SetMaxParallelism(1);
            }));
```
The vm it is deployed on only has a single core, yet the windows service this is running as is basically keeping the cpu maxed.  I tried to set the backoff strategy hoping this would help alleviate the problem, but this option is not available for some reason.

![image](https://user-images.githubusercontent.com/1150226/104898538-ac30fc00-5971-11eb-9c7f-8645e5aed723.png)

This is using Rebus v6.4.1 and Rebus.Oracle v2.0.0
Is there something I am doing wrong?

**Comment by cartsp** [comment]
This can be closed, sorry, it was due to the while loop that was constantly running while the service was started

**Comment by mookid8000** [comment]
> This can be closed, sorry, it was due to the while loop that was constantly running while the service was started

😁 

I'm happy to hear that you figured it out!
