### ISSUE TITLE
Domain in description is down

### ISSUE THREAD

**Issue by jirisykora83** [rebus-org/Rebus#925]
Cannot open [mookid.dk/category/rebus](mookid.dk/category/rebus). Maybe should be changed to [https://rebus.fm/](https://rebus.fm/)

**Comment by mookid8000** [comment]
Thanks for telling me. My blog is challenged, apparently, which I will fix one of these days

**Comment by mguinness** [comment]
Website for mookid.dk is still showing error.  Maybe you could change host to rebus.fm in Cloudflare in the interim?  

Otherwise, it might be a good idea to change or remove website mookid.dk/category/rebus from the repo details.

**Comment by mookid8000** [comment]
I've made a temporary fix to the mookid.dk website now. Thanks for reminding me 😳

**Comment by mookid8000** [comment]
Btw for anyone who might come across this thread - the full link is https://mookid.dk/category/rebus
