### ISSUE TITLE
Async IEncryptor

### ISSUE THREAD

**Issue by asleire** [rebus-org/Rebus#926]
Hi,

It's common for our applications to have access to an external key store, such as Azure Keyvault. As such we'd like to utilize that for message encryption. Ideally we'd create a custom implementation of [`IEncryptor`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Encryption/IEncryptor.cs), but its method declarations do not allow the asynchronous implementations we'd need. 

Do you have any thoughts regarding this?

I'm thinking it could be resolved in a non-breaking way by introducing a new interface `IAsyncEncryptor` and register a default implementation that wraps `IEncryptor`, though I haven't fully examined the code. 

I'd be happy to take a shot at a PR if interested.

**Comment by mookid8000** [comment]
Sounds cool 🙂 

And yes, what you describe sounds like an elegant solution.

Before you do that, please check that the way the encryption/description pipeline steps work fit with that approach:

https://github.com/rebus-org/Rebus/blob/master/Rebus/Encryption/EncryptMessagesOutgoingStep.cs
https://github.com/rebus-org/Rebus/blob/master/Rebus/Encryption/DecryptMessagesIncomingStep.cs

If it starts to become wonky, you might want to create new "EncryptMessagesAsyncOutgoingStep" and "DecryptMessagesAsyncIncomingStep" to be used in a similar fashion, but with your new `IAsyncEncryptor`.

**Comment by asleire** [comment]
Related to encryption but not this issue in particular: It would be nice if `EncryptedData` contained an optional field for KeyId to be passed along in a header. This could be used to better support key rotation. 

Also, currently `IEncryptor` exposes a property `ContentEncryptionValue`. I'd like this property to be part of `EncryptedData` as well, making it possible to rotate the content encryption algorithm as well

Should I make these changes as part of my PR?

**Comment by mookid8000** [comment]
Yes, by all means do 😃

**Comment by asleire** [comment]
I added KeyId but didn't change `ContentEncryptionValue`. 

In the decryption step you have a check for `contentEncryptionValue == _encryptor.ContentEncryptionValue`, where you skip decryption if there's no match. If `ContentEncryptionValue` is part of `EncryptedData` we'd have to let the encryptor attempt to decrypt it, but I'm not sure how you'd like to handle eventual errors
