### ISSUE TITLE
IHandleMessages wrapper and custom topics

### ISSUE THREAD

**Issue by midczak** [rebus-org/Rebus#928]
Hi
I faced a problem trying to subscribe message when using custom handlers and custom topic. 
In my project I have IHandleMessages wrapper similiar to shown in [CustomRebusHandlers repository](https://github.com/mookid8000/CustomRebusHandlers/)

In whole project I use TypeBased routing but for one message I need a custom topic. So I used `bus.Advanced.Topics.Subscribe("my-custom-topic");`

Unfortunately Rebus throws exception notifying that message "could not be dispatched to any handlers". I assume that there is a problem to match specific routing with generic handlers

Is there any way I can bring together custom message handlers and custom routing for some specific message? How can I set it up?

(By the way in wiki there is mentioned `bus.Advanced.Routing.Subscribe<TEvent>(destination)` but IRouterApi does not contains any Subscribe<T>() method)

**Comment by mookid8000** [comment]
>  I assume that there is a problem to match specific routing with generic handlers

With Rebus, There's no connection between "routing" and "handlers" 🙂 

"Routing" is solely about the question "to which queue do the messages go?".

"Handlers" is about "what do I do with this message that I've received in my queue?".

So... when you get the "message could not be dispatched to any handlers" error, it means that the message was received by a Rebus instance that could not find a suitable handler for the message.

Of course this could point back to how you route your messages. In general, it should be possible to
```csharp
await bus.Publish(someKindOfEvent);
```
and have it received by a bus that called
```csharp
await bus.Subscribe<SomeKindOfEvent>();
```
With custom topics, the above would translate to
```csharp
await bus.Advanced.Topics.Subscribe("custom-topic");
```
in the subscriber's end (the one that must then have handlers for everything published on the topic `custom-topic`), and
```csharp
await bus.Advanced.Topics.Publish("custom-topic", someKindOfEvent);
```
at the publisher's end.

I hope that makes sense 🙂
