### ISSUE TITLE
SqlScaleout sample seems to deadlock on _cancellationTokenSource.Cancel()?

### ISSUE THREAD

**Issue by kendallb** [rebus-org/Rebus#933]
I have cloned the SqlScaleout sample to work with MySql, and when I run the consumer test program and hit enter, sometimes it never exits and seems to get stuck on this line:

public void Stop() => _cancellationTokenSource.Cancel();

I have verified that the cancelation is in fact taking place and the worker has exited, but the .Cancel() call just never finishes. Sometimes if I wait long enough it eventually works, but other times it just sits there. When I tried using the Tpl version of the worker, it exits much faster.

Not sure of the best way to debug this? Perhaps it's specific to the use of Oracle MySql (which is known to not actually be async at all?). 

I have my sample checked in on my clone of the samples:

https://github.com/kendallb/RebusSamples/commits/feature/mysql-transport

**Comment by kendallb** [comment]
Yep, it's something wrong with the oracle MySql connector. I have finished the first version of the MySqlConnector support library (mysqlconnector.net) and when I use that, it quits immediately. So there is some kind of deadlock that happens related to this.

It's actually easy to reproduce. When playing with the unit test for the MySql integration, if I enable the performance test it locks up and never finishes with the Oracle connector, but the version using MySqlConnector works just fine (it has some exception when it's running, but it does not lock up).

**Comment by kendallb** [comment]
BTW, if you see this, I sent you a direct email to your hello@ email address to ask some stuff about doing some Rebus development outside of Github.

**Comment by mookid8000** [comment]
Good find! So, if I understand this correctly, it will be fixed by https://github.com/rebus-org/Rebus.MySql/pull/13 right?

**Comment by kendallb** [comment]
Yes, this all works correctly with the new version. The reason it was deadlocking is due to the way MySQL handles row locking and the background cleanup thread which simply did a 'delete from blah where blah < now()', which will cause MySQL to try to get an entire table lock which is not possible since there are handlers running that have open transactions, so the entire thing deadlocks.

The fix for MySQL is to avoid keeping the transactions actually open for the duration of the message processing (probably safer anyway) and to select out the ID's during the cleanup. MySQL 8 does have better row locking support like SQL Server, but I don't use that yet so have not implemented support for it. I was planning to update the code at some point to detect MySQL 8 or later and then be able to implement it with the improved row locking.
