### ISSUE TITLE
Check whether Rebus has put a message to a queue be processed

### ISSUE THREAD

**Issue by ddydeveloper** [rebus-org/Rebus#938]
Good morning! I have a question regarding the Rebus testing options. 

I have an email send service which is responsible for a decision "Do I need to send email?" based on business rules. Now I'm trying to figure out how to provide the integration tests. I see the following options:
- check whether emails was send (quite complicated cause I need test infrastructure and it the async process)
- check whether the queue has a message to be processed by worker later

So I am just wondering is it possible with the Rebus API or not?

**Comment by mookid8000** [comment]
You might want to take a look at [Rebus.TestHelpers](https://github.com/rebus-org/Rebus.TestHelpers) – it has a `FakeBus`, which is an implementation if `IBus` that is super-convenient to use when checking whether some code has sent/published messages.

With it you can go
```csharp
var fakeBus = new FakeBus();

RunSomeCode(fakeBus);

var sentMessages = fakeBus.Events
	.OfType<MessageSent<SendEmailCommand>>()
	.Select(m => m.CommandMessage)
	.ToList();

Assert.That(sentMessages.Count, Is.EqualTo(1));

var sentMessage = sentMessages.First();

Assert.That(sentMessage.To, Is.EqualTo("recipient@whatever.com"));
// etc
``` 

Is it something like that you're looking for?

**Comment by ddydeveloper** [comment]
I'll take a look, I think that's exactly what I need for my purposes. Thank you 👍
