### ISSUE TITLE
Bring Rebus.MySqlConnector into the main branch and push a NuGet package

### ISSUE THREAD

**Issue by kendallb** [rebus-org/Rebus#939]
As mentioned here:

https://github.com/rebus-org/Rebus.MySql/issues/10

We have moved over from the Oracle connector to the Open Source one that can be found here:

https://mysqlconnector.net/

Alas since the Rebus project is compiled specifically for the Oracle MySql, it does not work out of the box. So I have now finished a port of the SQL Server code to MySqlConnector, primarily because the old Rebus.MySql project looks to be pretty bare bones and has some bugs in it and is missing features. 

So now my port is done and all unit tests pass. and it's a full clone of the SQL Server version. It could probably be used to back port to the Oracle connector to make that a full featured version also since the differences are minor. But for now I have it as a separate project and plan to push my own NuGet package until it gets accept upstream.

Can we work on getting this into the main Rebus code tree from my code tree, and I can fork it back again to do any future work on it?

https://github.com/kendallb/Rebus.MySqlConnector

**Comment by kendallb** [comment]
I have back ported the MySqlConnector version to work with the Oracle connector as well, which resolved all the outstanding deadlock issues in the previous version.

https://github.com/rebus-org/Rebus.MySql/pull/13

**Comment by mookid8000** [comment]
Excellent work! But.... rebus-org/Rebus.MySql#13 is a huge PR and it has a bunch of merge conflicts.... shouldn't I have accepted your other PRs before this one?

**Comment by kendallb** [comment]
Oh, yeah I forgot I did all those earlier. Probably should have tossed those PR's :(. We can either do a merge and resolve the conflicts or if you would like I can re-base it on top of the new master? Maybe that's the easiest, so I will do that.

**Comment by kendallb** [comment]
Ok, all cleaned up now as a clean rebase on top of master.

**Comment by kendallb** [comment]
Once an official package is published, I can deprecate mine and use yours.

**Comment by mookid8000** [comment]
It's out as Rebus.MySql 3.0.0-b1 🙂
