### ISSUE TITLE
How to return exception information to sender?

### ISSUE THREAD

**Issue by michaelaird** [rebus-org/Rebus#940]
This is more of a design/usage question:

Given an a domain model where the processing of messages might get rejected (for example due to violating business rules), what's the best practices for flowing that failure information back to the process that sent the message initially?

**Comment by mookid8000** [comment]
Best practice is to avoid this as much as you can 🙂 generally, it's a better design if you can get away with letting message handlers take full responsibility for handling messages, including handling any errors that might occur or taking alternate paths if assumptions made by the sender did not hold. 

Of course this might not always be possible, and so you might want to return a reply to the sender. With Rebus, this can simply be done by going
```csharp
await bus.Reply(new SomeKindOfReply(...));
```
in your message handler.
