### ISSUE TITLE
Rebus PubSub native implementation for WorkerService publisher

### ISSUE THREAD

**Issue by ddydeveloper** [rebus-org/Rebus#941]
Good evening! I have a sample project to test Rebus PubSub native driven by RabbitMQ. There is a [project](https://github.com/ddydeveloper/Rebus.PubSub) with the 2 Publishers and 2 subscribers:

- Publisher1 is a simple console app
- Publisher2 is a WorkerService which use ServiceProvider package to setup infrastructure
- Subscriber1 and Subscriber2 both are WorkerServices

PubSub works perfect for Publisher1, any time I send a message both subscribers are able to receive it. But I can't get Publisher2 working as expected. I have a register part for `Program.cs`:
```
private static void AddRebus(this IServiceCollection services)
{
    services.AddRebus(configure => configure
        .Logging(l => l.ColoredConsole(minLevel: LogLevel.Warn))
        .Transport(t => t.UseRabbitMq("amqp://localhost", "PubSub.Publisher2"))
        .Routing(r => r.TypeBased().Map<string>("PubSub.Publisher2"))
    );
}
``` 

and another part inside `Worker.cs` class:
```
private readonly IServiceProvider _provider;
private readonly IBus _bus;

public Worker(IServiceProvider provider, IBus bus)
{
    _provider = provider;
    _bus = bus;
}

protected override async Task ExecuteAsync(CancellationToken stoppingToken)
{
    _provider.UseRebus();
    var count = 0;
    
    while (!stoppingToken.IsCancellationRequested)
    {
        count++;
        await Task.Delay(2000, stoppingToken);
        await _bus.Send($"Message #{count}");
    }
}
```

When sending messages I have the following Exception thrown:
> [ERR] Rebus.Retry.PoisonQueues.PoisonQueueErrorHandler (Rebus 1 worker 1): Moving message with ID "a77ba3bd-4b80-430f-bb93-7fc74768405c" to error queue "error"
System.AggregateException: 1 unhandled exceptions (Message with ID a77ba3bd-4b80-430f-bb93-7fc74768405c and type System.String, mscorlib could not be dispatched to any h
andlers (and will not be retried under the default fail-fast settings))
 ---> Rebus.Exceptions.MessageCouldNotBeDispatchedToAnyHandlersException: Message with ID a77ba3bd-4b80-430f-bb93-7fc74768405c and type System.String, mscorlib could not
 be dispatched to any handlers (and will not be retried under the default fail-fast settings)
   at Rebus.Pipeline.Receive.DispatchIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Sagas.LoadSagaDataStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Pipeline.Receive.ActivateHandlersStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Pipeline.Receive.HandleRoutingSlipsStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Pipeline.Receive.DeserializeIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.DataBus.ClaimCheck.HydrateIncomingMessageStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Pipeline.Receive.HandleDeferredMessagesStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Retry.FailFast.FailFastStep.Process(IncomingStepContext context, Func`1 next)
   at Rebus.Retry.Simple.SimpleRetryStrategyStep.DispatchWithTrackerIdentifier(Func`1 next, String identifierToTrackMessageBy, ITransactionContext transactionContext, St
ring messageId, String secondLevelMessageId)

I almost sure something went wrong with the Rebus configuring but didn't really find the way to fix it. Could you advise what can I try to have the WorkerService publisher configured in a proper way?

**Comment by mookid8000** [comment]
The problem is that when you
```csharp
await _bus.Send($"Message #{count}");
```
the string is not PUBLISHED, it is SENT (and in this case, it gets sent to the queue `PubSub.Publisher2`, because of the endpoint mapping
```csharp
.Routing(r => r.TypeBased().Map<string>("PubSub.Publisher2"))
```
in publisher 2's Rebus configuration)

Rebus has two basic ways of sending messages:

1. point-to-point – this is when you `await bus.Send(yourMessage)`
1. pub/sub – this is when you `await bus.Publish(yourEvent)`

In (1), the message is SENT directly to a queue. Rebus gets told which queue via "endpoint mappings", which is what you configure with the `.Map<MessageType>(queueName)` thing.

In (2), the event is PUBLISHED. It will end up in the queue of any bus instance that called `await bus.Subscribe<YourEvent>()`.

I hope this makes sense and maybe helps you realize why you get the error message in your publisher 🙂

**Comment by ddydeveloper** [comment]
Hi Mogens! 

Thank you for the clear explanation. You were right, just need to use `bus.Publish` to make exchange deliver message to all subscribers queues. Didn't noticed it during implementation. Now it works perfect.
