### ISSUE TITLE
Upgrading to 6.5.0 causes a FileNotFoundException on Jetbrains.Annotations

### ISSUE THREAD

**Issue by Rensvind** [rebus-org/Rebus#946]
![image](https://user-images.githubusercontent.com/282209/108828683-706c0080-75c7-11eb-82ec-4476e9eea6f0.png)

**Comment by mookid8000** [comment]
That's weird! I've just done something – could you try Rebus 6.5.1 ?

**Comment by Rensvind** [comment]
👍 It works now!

**Comment by mookid8000** [comment]
OK! Thanks for reporting this issue! To be honest, I have no idea what went wrong there... someone thought it was a good idea to hook Rebus up with Jetbrains Annotations recently , but to my understanding, it should only make a difference at compile-time.

🙄
