### ISSUE TITLE
Rebus 6.5.2 is no longer marked as CLSCompliant which gives build warnings when upgrading

### ISSUE THREAD

**Issue by karelscholten** [rebus-org/Rebus#947]
It looks like it was removed in commit https://github.com/rebus-org/Rebus/commit/ac6aba930b786373b9ffc9c40912e7121e55cfbd

**Comment by mookid8000** [comment]
Damn! I'll put it back in 😀

**Comment by mookid8000** [comment]
Rebus 6.5.3 has `isCompliant: true`, because that makes it much more CLS compliant 🙄 

Thanks for making me aware of this 🙂
