### ISSUE TITLE
Question: Thread cleanup on shut down?

### ISSUE THREAD

**Issue by kendallb** [rebus-org/Rebus#954]
How does thread termination work for active handlers that are running when Rebus is being closed down? I have our Rebus handlers running as part of our web application stack, so there is one Rebus instance on each of our three web nodes, and I can see when debugging in the console logs, that when the application is closed by IIS, Rebus is terminating the handler threads.

I assume when the handler threads are being terminated, any actively executing handlers will end up being completed before the thread shuts down. Is there any kind of timeout on thread shut down such that it would forcibly terminate a message handler that was executing?

**Comment by mookid8000** [comment]
> I assume when the handler threads are being terminated, any actively executing handlers will end up being completed before the thread shuts down. 

Yes 🙂 

> Is there any kind of timeout on thread shut down such that it would forcibly terminate a message handler that was executing?

Yes, the timeout defaults to 1 minute. You can simply go
```csharp
Configure.With(...)
    .Transport(t => ...)
    .Options(o => o.SetWorkerShutdownTimeout(timeout: TimeSpan.FromSeconds(5)))
    .Start();

```
to change the timeout to 5 seconds.

**Comment by kendallb** [comment]
Cool. I ended up discovering what happened to our missing message. Since we currently run the message handlers within the web application stack and have three web nodes, when I pushed out the new code with the new message type in it, the background task that published the message for updated and started while the web nodes were still in the processing of rolling out the code changes. So effectively there was no registered message handler executing at the time the message was published so it simply got dropped (and an exception does get logged but I did not have the logs set up correctly so I missed it).

The default behavior if there is no registered message handler is to throw an error that gets logged but the message just gets tossed. Can I suggest that instead the default behavior in that case should be for the message to get punted to the dead letter queue, so we can find it and eventually replay it? And not lose it? Or perhaps by default defer it for a bit but if it keeps failing, the dead letter it?

My plan to avoid this is to move the handlers out of the web stack completely and run them in separate services so we can shut them all down together, upgrade them and restart them all at the same time running the new code. That way any new message types won’t be published before those handlers are updated, as they will always come online before we roll through the web nodes.

I would be happy to work on a PR to change the behavior for unmapped messages.

**Comment by mookid8000** [comment]
> The default behavior if there is no registered message handler is to throw an error that gets logged but the message just gets tossed. 

No that should definitely not be the case! With any other transport, if a message cannot be handled (i.e. the container returns 0 handlers for that message type), a `MessageCouldNotBeDispatchedToAnyHandlersException` is thrown, which is tagged with `IFailFastException`, meaning that the message should be immediately forwarded to the error queue when it is received again.

However, if you have three nodes running at that time, there's a fairly high chance that one of the other nodes will snatch the message – maybe that's what you're experiencing?

**Comment by mookid8000** [comment]
In any case, Rebus will forward a message that cannot be handled to the error queue. If that's not the behavior you're seeing, then we should figure out why.
