### ISSUE TITLE
Upgrade from Rebus 4.2.2 to 6.5.5 Causing Crash on Message Mapping in Configure.With

### ISSUE THREAD

**Issue by tobias76** [rebus-org/Rebus#963]
Hello,

We have upgraded our project from the following Rebus modules:

- Rebus 4.2.2 -> Rebus 6.5.5
- Rebus Server 4.0.0 -> Rebus Server 7.1.7

We performed these upgrades to allow us to use the "Automatic retries and error handling" you have posted but we seem to have run into a few issues. The largest issue is when we try to register our rebus versions and thus map the messages to the rebus message queue we are given the following nested exception:

`RebusApplicationException: Unable to send to destination queueName' with the following inner exception`, 
- `SqlException: Invalid object name 'dbo.eRSNotifications`.

Below I have attached the two relevant snippets of code which seem to be causing the issue, as far as we can see. 

Old Code:

![image](https://user-images.githubusercontent.com/5183600/111774568-8e1b4580-88a7-11eb-8dca-4d7cbb08c3ea.png)
![image](https://user-images.githubusercontent.com/5183600/111774689-b9059980-88a7-11eb-84c0-11dde0e8f953.png)

It should be noted the "RebusMessages" string is for the SQL database table they used to be stored in, if I am correct from my reading of the documentation we were able to remove this as rebus now uses multiple tables for performance reasons? However due to the nested exception found I believe this to be the root of our issue? Is this a correct assumption or am I off the mark?

New Code:

![image](https://user-images.githubusercontent.com/5183600/111774274-27962780-88a7-11eb-8249-3c747e2ff171.png)

Any help to solve this problem would be much appreciated so I'd be willing to provide as much info as you require to get through this.

Thankyou,

Toby

**Comment by mookid8000** [comment]
You are absolutely right that Rebus.SqlServer was changed some time between 4 and 7 to use a table-per-queue layout instead of one big message table.

Unfortunately, this also means that Rebus instances using SQL Server as the transport are not readily compatible between these versions.

Once you update your endpoints to the new version of the SQL transport and restart them, they should each create their necessary "input queues" (i.e. tables), and then everything should work the same again.

**Comment by tobias76** [comment]
Thankyou for the quick response @mookid8000.

So, as we have 5 message types would we need to have 5 different handlers each handling a different class? I have found this -> https://github.com/rebus-org/Rebus/wiki/Polymorphic-message-dispatch does this mean we could have a parent class e.g. rebusMessage which all 5 are childs of and thus handle that? Or would we simply need five seperate handlers?

My other question is, do we then need to create five seperate tables for each messages queue? This is the general message I got from your response but I just wanted to be sure.

Thanks again!

**Comment by mookid8000** [comment]
> So, as we have 5 message types would we need to have 5 different handlers each handling a different class?

No 🙂 it works the same way as before: Noone cares which type a message has when it goes into a queue, it just goes into the queue. It then gets received by anyone who consumes messages off of that queue, and then it gets handled if the recipient has a handler for it (if it doesn't, an exception is thrown, and the message goes to the error queue).

> My other question is, do we then need to create five seperate tables for each messages queue? This is the general message I got from your response but I just wanted to be sure.

Yes. But the tables will be created automatically at startup, unless you explicitly disable it (that is: a Rebus instance will automatically ensure that its own input queue exists).

**Comment by tobias76** [comment]
Right, that all makes sense! One final question if you wouldn't mind @mookid8000 if these tables are created on start-up, how does this affect the destinationAddress parameter provided on mapping?

**Comment by mookid8000** [comment]
> if these tables are created on start-up, how does this affect the destinationAddress parameter provided on mapping?

Not at all – the endpoint mappings are only relevant when you
```csharp
await bus.Send(message);
```
or
```csharp
await bus.Defer(message);
```

**Comment by tobias76** [comment]
Hi @mookid8000,

Since fixing the above issues we seem to be getting another mapping error on the receiving of a message. When a message gets recieved by our service, we have developed handlers to work with each message type however our console output gives us a 

`Rebus.Exceptions.MessageCouldNotBeDispatchedToAnyHandlersException: Message with ID -redacted for ease- and type -redacted for ease- could not be dispatched to any handlers.` Which when I turn on the log pipeline I can see seems to occur in the `Rebus.Pipeline.Receive.DispatchIncomingMessageStep`.

What is confusing is the fact we have registered these handlers in the below location, I assume the issue could be with our queueName? Should it be the same as the queue name we are providing to the bus in the Configure.With() section of code elsewhere in our code?:

![image](https://user-images.githubusercontent.com/5183600/112321805-4716c100-8ca8-11eb-97b4-42c24c47099c.png)

**Comment by mookid8000** [comment]
The `MessageCouldNotBeDispatchedToAnyHandlersException` exception is thrown when Rebus finds that it has no handlers for the incoming message.

This means that the message has been properly received from the input queue and deserialized into a .NET type – but your IoC container did not return any usable implementations of `IHandleMessages<YourMessage>`.

My guess is that you have not registered your Rebus handlers in your IoC container.

From the posted screenshot, it seems like you're using Unity – is that still a thing? 😅 – IIRC Unity had a wonky way of differentiating between ordinary registrations and those meant to be resolved as part of a sequence, and for this reason Rebus handlers had to be registered in a very special way to work properly.

You could try and extract the `UnityContainerAdapter` above and call `GetHandlers` on it for one of your messages to see what it returns.

**Comment by tobias76** [comment]
Hi @mookid8000, I have managed to use your previous help to get us upgraded from 4.2.2->6.5.5 but our company has one worry I was hoping you could ease. As we are now using the error handling and retry strategys people were worried as to what happens to a deadletter, in our IFailed handlers we mark a letter as dead which I assume gets sent to the deadletter queue. What happens after it has been put in the deadletter queue? When we restart our activators are these deadletters attempted to resend? Our issue is that we never want to lose a letter, so we'd like deadletters to eventually get sent to the server when possible. Does rebus already do this? Or is there a way for this to happen?

**Comment by mookid8000** [comment]
Failed messages get moved to the dead-letter queue, which is just an ordinary queue named "error" (unless you explicitly configure something else with
```csharp
Configure.With(...)
	.(...)
	.Options(o => o.SimpleRetryStrategy(errorQueueAddress: "something-else"))
	.Start();
```
)

Since "error" is just an ordinary queue, and you are most likely not consuming messages from it, messages will just be sitting there forever(*)

What you most likely want to do, is to fire up SQL Server Management Studio and do a little bit of SQL-fu to get the messages back into their respective source queues. The "source queue" (i.e. the queue the message was received from when it could not be handled) get attached to the message as the `rbs2-source-queue` header, so it can be found in the `[headers]` column.

This part is a little bit tricky, and it always has been, because different transports have different ways of re-delivering messages after they have failed. This is why I created [Fleet Manager](https://rebus.fm/services/fleet-manager/), which completely removes the need for error queues, regardless of which transport you're using, as it simply uses Fleet Manager to store the failed messages.

---
(*) The meaning of "forever" may depend on which transport you're using. Since you're using SQL Server, they will actually stay there forever.

**Comment by tobias76** [comment]
Hi @mookid8000, we are weirdly getting an issue which was previously working but has shown its head in testing. Messages which get sent to the SQL table/queue don't get retrieved by Rebus and sent off to our MSMQ. The code where we configure our bus is here: 
![image](https://user-images.githubusercontent.com/5183600/112996410-0e715e80-9164-11eb-887e-5ef657a276b2.png) 
I understand we are creating our Notifications Handler before the bus is being configured which would mean it is getting an unconfigured bus (See below), I assume this is causing our issue? Is there a better way to configure a bus and send it to our handler class than we are currently using?
![image](https://user-images.githubusercontent.com/5183600/112996687-4bd5ec00-9164-11eb-9177-8f5febaf5c1d.png)
