### ISSUE TITLE
How to make persistent processing attempts?

### ISSUE THREAD

**Issue by dimkadv2** [rebus-org/Rebus#965]
Hi,
how to make persistent processing attempts in error case?

I try this:

```
.Options(x =>
{
    x.Register<ITopicNameConvention>(c => new CustomTopicNameConvention());
    x.SimpleRetryStrategy(maxDeliveryAttempts: 0);
});
```

but after 5 attempts the message still falls into the error queue. The order of the processed messages is important to me (

How can I solve my problem?

Thanks!

**Comment by mookid8000** [comment]
Simply write your retry logic in a message handler, but remember to obtain Rebus' `CancellationToken`, so your code can abort message processing when the bus needs to shut down:
```csharp
public class NeverGonnaGiveYouUpHandler : IHandleMessages<NeverGonnaGiveYouUp>
{
	readonly IMessageContext _messageContext;

	public NeverGonnaGiveYouUpHandler(IMessageContext messageContext) 
		=> _messageContext = messageContext;

	public async Task Handle(NeverGonnaGiveYouUp message) 
	{
		var cancellationToken = _messageContext.GetCancellationToken();

		while (!cancellationToken.IsCancellationRequested)
		{
			try
			{
				await DoSomethingThatCanFail(message);

				// 👇 if success
				return;
			}
			catch(Exception exception)
			{
				Log.Error(exception, "Could not");
			}

			await Task.Delay(TimeSpan.FromSeconds(10), cancellationToken);
		}
	}
}
```

Oh, and if you're using Azure Service Bus, where the message lease can expire, remember to tell Rebus to automatically renew the lease:
```csharp
Configure.With(...)
    .Transport(t => t.UseAzureServiceBus(conn, "queue-name").AutomaticallyRenewPeekLock())
    .Start();
```

**Comment by dimkadv2** [comment]
I forgot to mention that I am using a rabbit. in your example, it turns out that if 1 subscriber took a message from the queue, then he will never return it there (until the application is turned off). Is there any alternative solution, such as not counting the number of attempts?

**Comment by mookid8000** [comment]
>  (...) if 1 subscriber took a message from the queue, then he will never return it there (until the application is turned off).

Is this not exactly what you want? I.e. either the message gets handled successfully (and the subscriber proceeds on to the next message), or it isn't and it keeps trying forever..?

**Comment by dimkadv2** [comment]
the problem is that if 1 subscriber could not process the message (for example, did not get access to the database or some other problem), then there is a possibility that another subscriber will be able to process this message. My challenge is to eliminate the number of attempts. This can be done? Ktsati, thank you for your library! She's really cool!

**Comment by mookid8000** [comment]
> the problem is that if 1 subscriber could not process the message (for example, did not get access to the database or some other problem), then there is a possibility that another subscriber will be able to process this message (..)

If the subscriber keeps retrying forever like the code I posted, then the message will not be returned to the queue unless the subscriber shuts down and breaks its connection with RabbitMQ....
