### ISSUE TITLE
Unsubscribe when message type is deleted

### ISSUE THREAD

**Issue by vegar** [rebus-org/Rebus#967]
Imagine that in one version of your app you subscribed to the message `MyMessage`. In a later version of the app, the `MyMessage`-class was deleted.  Now - in the transport there still exist a subscription for this message. How do I get rid of that? Since `bus.Unsubscribe( )` takes a type and the type is gone I can't use that. 

I've sort of found a workaround that seems to work, which is using 
```
bus.Advanced.Routing.SendDirect(
    "queueName", 
    new UnsubscribeRequest() {
        SubscriberAddress = options.InputQueue,
        Topic = msgTypeName
    })
```
but it both seems a little bit hackish, and I haven't found a good way of unittesting the unsubscription either.

Do you have a tip?
Maybe this is a use case related to #331 that never happened?

**Comment by mookid8000** [comment]
You can use the raw topics API:
```csharp
await bus.Advanced.Topics.Unsubscribe("this-is-a-topic");
```
🙂 

You'll still need to figure out the exact name of the topic though.

**Comment by vegar** [comment]
Ok. But that requires me to add the knowledge about the routing elsewhere, though... 🤔

**Comment by mookid8000** [comment]
>  is there any way of getting hold of the current endpoint for a bus? It seems like once configured, a bus is keeping everything to it self

I'm not sure I understand what you mean by "getting hold of the currend endpoint"... 🤔

**Comment by vegar** [comment]
Take the readme example setup: 

```
Configure.With(someContainerAdapter)
    .Logging(l => l.Serilog())
    .Transport(t => t.UseMsmq("myInputQueue"))
    .Routing(r => r.TypeBased().MapAssemblyOf<SomeMessageType>("anotherInputQueue"))
    .Start();
```

is there any way to go from a `IBus bus` to the string `myInputQueue` ?

**Comment by mookid8000** [comment]
Ah, now I understand – and no, Rebus does not expose its own queue name anywhere, so you would need to keep the name somewhere else to be able to know it.

But why do you want the bus to know its own input queue name?

**Comment by vegar** [comment]
I started looking for the transport address when manually sending the unsubscribe request - the code in original question.
Your workaround by using `bus.Advanced.Topic.Unsubscribe(...)` would remove the need for knowing the queue name, but it would also remove the possibility to specify the destination directly.

We have setup message routing by adding an attribute on the message class telling the owner of the message

```
[MessageOwner('someremotequeue')]
public class OurMessage { }
``` 
When the `OurMessage`-class is deleted from the code, the owner attribute is of cause also deleted, and then the unsubscribe call will fail. 

Since the whole unsubscribe business in this case is a cleanup thing that will only live for a couple of releases, I would rather have one place in the code hardcoding what to clean up than having to configure something in a router one place and something for the actual clean up another place.

Anyway - sometimes you just have to get the job done. What I ended up with was to resurrect the deleted message class so that I could unsubscribe 'the normal way'. Next release we'll delete both the unsubscription code and the message once again.

**Comment by mookid8000** [comment]
> Anyway - sometimes you just have to get the job done. What I ended up with was to resurrect the deleted message class so that I could unsubscribe 'the normal way'. Next release we'll delete both the unsubscription code and the message once again.

True! And that is a nice way to do it. Since you're using attributes on the event types already, maybe you could introduce a new attribute that marks an event type as obsolete, with some kind of expiry based on a future version number or a date... then an automated test could verify that those event types had been removed in the future or something like that, so you're sure to everutually clean up after having removed an event type.

Oh well... happy you figured it out 🙂
