### ISSUE TITLE
NServiceBus RequestTimeout | Rebus implementation

### ISSUE THREAD

**Issue by djhvscf** [rebus-org/Rebus#970]
Hi @mookid8000 , we're wondering what is your suggestion when we need to implement the Nservicebus RequestTimeout logic in Rebus?

This is the [RequestTimeout](https://docs.particular.net/nservicebus/sagas/timeouts) doc for nservicebus

**Comment by mookid8000** [comment]
With Rebus you would simply
```csharp
await bus.DeferLocal(TimeSpan.FromHours(1), yourTimeoutMessage);
```
which will send `yourTimeoutMessage` one hour INTO THE FUTURE 🤠 

To make this work, Rebus needs one of the following things:

* A transport that natively supports sending messages into the future (e.g. Azure Service Bus or Amazon SQS)
* A local timeout manager(1)
* An external timeout manager(2)

---
(1) A local timeout manager can be configured by going
```csharp
Configure.With(...)
	.(...)
	.Timeouts(t => t.StoreIn(...))
	.Start();
```
where the `StoreIn(...)` part configures which storage to use, e.g. SQL Server.

(2) An external timeout manager can be configured by going
```csharp
Configure.With(...)
	.(...)
	.Timeouts(t => t.UseExternalTimeoutManager("timeouts"))
	.Start();
```
which will cause all deferred messages to be sent to the queue `timeouts`, assuming that the Rebus endpoint running there has a local timeout manager configured.
