### ISSUE TITLE
Since Upgrading from Rebus 4.2.2 to 6.5.5 SQL Server is Polled Constantly

### ISSUE THREAD

**Issue by tobias76** [rebus-org/Rebus#977]
Hello,

We have recently  upgraded our project from the following Rebus modules:
    - Rebus 4.2.2 -> Rebus 6.5.5
    - Rebus Server 4.0.0 -> Rebus Server 7.1.7

In the previous version of our project, our service would have one connection to the server which would be reused as and when it was found necessary. However, since upgrading the application seems to create new connections without closing down the previous ones whenever it is necessary. This is causing approximately 80 connections per instance which when run for multiple clients has caused our monitoring software to complain. Can you confirm as to whether there was a change in the way Rebus works as to if these multiple connections is working as intended or could there be a bug somewhere that would need to be resolved?

Thankyou,

**Comment by tobias76** [comment]
Hello,

Just wondering if there was an update here?

Thankyou,

**Comment by mookid8000** [comment]
Hi @tobias76 , that sounds weird. Can you tell me some more about it? E.g. show me the configuration etc.

I am not aware of any current issues like this, so any information you can provide (maybe a repro?) is much appreciated....

**Comment by tobias76** [comment]
Hi @mookid8000, what we seem to have diagnosed is a pool of connections being created, they then seem to poll a specific table, called RebusMessages, and then executes `sp_reset_connection` each time moving on to another connection. We have found it creates a pool of approx 80~ connections. We are using Rebus and it's SQL Server add-on and here are our set-ups, note they are for two technically seperate applications. 

![image](https://user-images.githubusercontent.com/5183600/123052846-2e2ec080-d3fb-11eb-8006-948b3a9329c3.png)
![image](https://user-images.githubusercontent.com/5183600/123052945-469edb00-d3fb-11eb-8968-68fac19d1271.png)

As it seems to pool the RebusMessages table this seems to indicate to me that the second screenshot could be causing the issues, however this code wasn't actually changed in the PR that seems to have brought this issue to light. Is there anything here that to you indicates a potential cause of this?

**Comment by mookid8000** [comment]
The calls to `sp_reset_connection` are normal .NET SQL connection pool behavior, and I would be very surprised if they didn't happen in the past also.

And yes, I think you're right that it's the second configuration that's causing the polling, as the first one has a very gentle backoff-strategy configured.

Also, the second configuration allows for the default parallelism of 5.

I suggest you reduce the parallelism and/or introduce a more gentle backoff-strategy in your second bus exampt. Or, if it's a bus instance only meant for SENDING/PUBLISHING messages, then use the `.UseSqlServerAsOneWayClient(..)` configuration instead.
