### ISSUE TITLE
Dequeue just one message

### ISSUE THREAD

**Issue by meronz** [rebus-org/Rebus#978]
Hi everyone! I'm not sure this is the right place to ask questions, forgive me if it is not.
Is there a way to dequeue just one message from the queue, and then close the process?
For example, with RabbitMQ one can achieve that by calling IModel.BasicGet() and then IModel.BasicAck() when done. But I like how Rebus works and i would like to stick with it.

Right now what I'm doing is something like this, but I feel like there should be a better way to be sure to handle just one message per process. Or maybe what I am trying to achieve is simply wrong.

```c#
activator.Handle<MyMessage>(async (bus, ctx, msg) =>
{
    //...
    autoResetEvt.Set();
}

Configure.With(activator)
    .Transport(t => t.UseRabbitMq("conn-string", "queue-name"))
    .Options(o =>
    {
        o.SetMaxParallelism(1);
        o.SetNumberOfWorkers(1);
    })
    .Start();
    
autoResetEvt.WaitOne();
```

Thank you for your time 🙂

**Comment by mookid8000** [comment]
Well, your usecase is not readily supported by Rebus, as it will encourage you in many ways to start a bus that will then stay running, consuming 0..n messages (possibly in parallel), until you shut it down again.

I'm curious to hear why it is important for you that each of your consumers receive exactly one message?

**Comment by meronz** [comment]
I'm starting Kubernetes jobs with KEDA. Basically, whenever a message is posted on a certain queue, a job is started. The process started is responsible for dequeuing the message as KEDA only checks the number of queued messages. It's not strictly a requirement to handle exactly one message, but I want to be sure to terminate the process to avoid keeping pods running for no reason. 

I did some reading of the source code, it is my understanding that after the Bus has been disposed, no handler is still running, so I can shut down the process safely after disposing the BuiltinHandlerActivator and call it a day. But since I have very little experience with Rebus, I wondered if there was a better way!

**Comment by mookid8000** [comment]
> it is my understanding that after the Bus has been disposed, no handler is still running, so I can shut down the process safely after disposing the BuiltinHandlerActivator and call it a day

Yes, definitely! Rebus defaults to waiting up to 1 minute for workers to finish their work when shutting down, and you can customize the timeout by calling something like
```csharp
Configure.With(...)
     .(...)
    .Options(o => o.SetWorkerShutdownTimeout(TimeSpan.FromMinutes(5))
    .Start();
```

So it's completely safe to shut it down, as long as you call `.Dispose()` (either on the container that hosts it, or directly on the bus or the built-in handler activator)

**Comment by meronz** [comment]
Got it! Thank you for the tips!
