### ISSUE TITLE
Cannot reply to message within transaction scope in Handle method

### ISSUE THREAD

**Issue by kewinbrand** [rebus-org/Rebus#980]
Hi,

I have some cases that a transaction scope is needed inside the handle method to transactionally publish the messages, but looks like Rebus does not support reply within the scope.

Below is a example of what I need to accomplish:

```csharp
public class MyMessageHandler : IHandleMessages<MyMessage>
{
    private readonly IBus _bus;

    public MyMessageHandler(IBus bus)
    {
        _bus = bus;
    }
    public async Task Handle(MyMessage message)
    {
        try
        {
            using (var scope = new RebusTransactionScope())
            {
                //I need all this messages to be transactional
                await _bus.Publish(new SomeOtherMessage());
                await _bus.Publish(new AnotherMessage());
               //!!! this throws the following exception
               //Attempted to reply, but could not get the current receive context - are you calling Reply outside of....
                await _bus.Reply(new ReplyToMyMessage {Status = StatusReply.Ok});
                
                await scope.CompleteAsync();
            }
        }
        catch (Exception)
        {
            await _bus.Reply(new ReplyToMyMessage {Status = StatusReply.Failed});
        }
    }
}
```

Any ideas on how to do it?

Thank you so far

**Comment by mookid8000** [comment]
I guess this is not a supported scenario.

Also, there is absolutely no reason to use `RebusTransactionScope` inside a Rebus handler, as all bus operations are enlisted in the handler's transaction context.

**Comment by kewinbrand** [comment]
Ok

How would I discard the published messages in my example and only send the reply? 
In my tests they are not discarded as the transaction is outside of the handle method

**Comment by mookid8000** [comment]
> How would I discard the published messages in my example and only send the reply?

With Rebus, you're pretty much encouraged to just send/publish/reply whatever you need, and then the bus takes care of sending the messages. If something fails during any of that, it will result in an exception, which in turn will cause the handling of the current message to be rolled back and retried.

Rebus maintains a strict "at least once"-delivery guarantee throughout.
