### ISSUE TITLE
Don't set rbs2-senttime when it is set explicitly

### ISSUE THREAD

**Issue by michielvoo** [rebus-org/Rebus#982]
In the [`AssignDefaultHeadersStep`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Pipeline/Send/AssignDefaultHeadersStep.cs) some of the default Rebus headers are only set if they are not explicitly set to something else. However, this is not the case for the `rbs2-senttime` header.

We have a scenario where we need to re-publish events, while keeping its original headers (we implemented the [outbox pattern](https://github.com/rebus-org/Rebus/issues/819)). We explicitly set `rbs2-msg-id` to the original value, but to ensure `rbs2-senttime` is set to the original value requires a pipeline step. It would be nice if it would not be set if we set it explicitly.

**Comment by mookid8000** [comment]
I guess you're right. The original reasoning behind this was that it should be possible to fake this particular header, but your scenario is a very good reason to do so!

Let me see what I can do 🙂

**Comment by mookid8000** [comment]
OK I've released Rebus 6.6.1, where this is fixed - could you try it and see if it behaves as expected? 🙂

**Comment by michielvoo** [comment]
Great, thanks!
