### ISSUE TITLE
Priority with two queues

### ISSUE THREAD

**Issue by kostazol** [rebus-org/Rebus#983]
Hello. I have two queues: with usually messages (tasks) and with priority messages (tasks). Every worker has special hardware for processing tasks, because of it I can't create many worker for every queue. Can I configurate Rebus with inputQueue priority?
For example, Rebus try to get messages from priority queue if it is empty, Rebus will get message from usually queue.

**Comment by kostazol** [comment]
Now I found only one solution in theory. 
I create two instances of Rebus using factory and Microsoft DI, set zero workers in two instances. After creating instances I set one worker, to instance wich work with priority queue. If it doesn't get message after some time (for example 30 seconds) I will set zero workers to this instance and set one worker to instance wich work with usually queue. After one message I restart this process.

**Comment by mookid8000** [comment]
As you've found out, Rebus only receives messages from one single queue (the "input queue") - so if you need to receive messages from two queues, you need two Rebus instances.

If you then have some kind of shared resource that can only be used by one process at a time, I would suggest you protect that using some kind of distributed lock. There's several ways to implement that, e.g. by using the nifty [DistributedLock](https://github.com/madelson/DistributedLock) library.

You can of course also do something like what you describe in your comment, but I would be worried that it would have pretty bad performance and be hard to make work in a reliable manner.

**Comment by kostazol** [comment]
If you can please write how I would use DistributedLock? As I know I would use it before getting messages from queue, but how can I pause Rebuse ?

**Comment by mookid8000** [comment]
You would not need to pause Rebus at all, you would simply need to add an appropriate 
```csharp
await using await myDistributedLock.AcquireAsync();

// do stuff here

```
to the relevant handlers.

**Comment by kostazol** [comment]
It is also solution, but this solution has two not good aspects: 
1. Queue usually has VisibilityTimeout and if I use DistributedLock in handler after some time message from usually handler will back to queue with error. 
2. Time of working with message will be very long and I will need to understand what is it (DistributedLock or errors in working)? 

Can I use DistributedLock before getting messages?

**Comment by mookid8000** [comment]
Are you using Azure Service Bus as the transport?

Rebus can automatically renew the peek lock in the background, meaning that a received message does NOT pop up to be consumed again, even though processing takes a long time:

```csharp
    Configure.With(...)
        .Transport(t => t.UseAzureServiceBus(connectionString, "queue")
                         .AutomaticallyRenewPeekLock())
        .(...)
```

You can read more about it here: https://github.com/rebus-org/Rebus/wiki/Azure-Service-Bus-transport#long-running-message-handlers

And no, Rebus does not readily provide hooks for doing stuff (e.g. grabbing a distributed lock) before receiving a message. Rebus is pretty extensible though, so it should be possible to hook into the transport's receive operation, if you really want to go down this path. You can read more about extensibility here: https://github.com/rebus-org/Rebus/wiki/Extensibility

**Comment by kostazol** [comment]
I use Amazon SQS. Does AutomaticallyRenewPeekLock work with AmazonSQS ? If I read information correct, it doesn't work.
Thank you for links, I will try to check extensibility solve my problem or not.
