### ISSUE TITLE
Adding support for distributed tracing

### ISSUE THREAD

**Issue by michielvoo** [rebus-org/Rebus#986]
Is there a plan to add support for distributed tracing in accordance with the [W3C Trace Context](https://www.w3.org/TR/trace-context/) recommendation, and if not, are the maintainers open to adding this to Rebus? 

I am planning to add this as a custom step in a project I am working on currently. On send it would start a `System.Diagnostics.Activity` of kind [`Producer`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activitykind?view=net-5.0) and add 1 or 2 headers (the trace parent and the trace state) to outgoing messages. On receive it would create an activity of kind `Consumer` and copy over the headers. That will enable other activities to be connected, for example an outgoing HTTP request that occurs as a consequence of consuming the message.

If all of that works well (based on collecting the activity using [the OpenTelemetry collector](https://www.nuget.org/packages/OpenTelemetry) and exporting it with a [vendor-specific exporter](https://www.nuget.org/packages/NewRelic.OpenTelemetry)), then I could generalize the code and create a pull request for it here so it would become a built-in feature of Rebus.

**Comment by mookid8000** [comment]
No concrete plans no, but it sounds pretty awesome to do so 🙂 

What NuGet references would it require to put this into Rebus? and/or which framework target(s) would it work for?

**Comment by michielvoo** [comment]
It would require only System.Diagnostics. But in .NET 5 they made it a bit easier to implement it by introducing [`ActivitySource`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activitysource?view=net-5.0).

**Comment by michielvoo** [comment]
I think these are the best starting points:

- [Activity improvements](https://github.com/dotnet/designs/blob/main/accepted/2020/diagnostics/activity-improvements.md)
- [Distributed tracing](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing)

The old way of doing things is also documented, but not as good, and it seems more awkward:

- [Activity user guide](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md)

**Comment by mookid8000** [comment]
Cool! If you cook something together, I'd be happy to accept a PR 🙂 

~But... would it have to go into Rebus core? I mean, to me it does not look like it requires a super-intimate~

I just realized that there's a repo called "Rebus.OpenTelemetry": https://github.com/rebus-org/Rebus.OpenTelemetry - isn't that exactly what we're talking about here? 😳

**Comment by michielvoo** [comment]
That looks exactly like it, thanks for pointing that out! Looking through the code it is mostly as I would expect it to be. I will definitely be using this package.
