### ISSUE TITLE
Question about "Saga without single initiator"

### ISSUE THREAD

**Issue by julealgon** [rebus-org/Rebus#987]
The example shown in [the saga wiki doc](https://github.com/rebus-org/Rebus/wiki/Coordinating-stuff-that-happens-over-time) showcases a common scenario where saving a customer triggers a saga which then awaits for 2 independent events to happen until it is completed.

How do I go about implementing something similar, but that doesn't have a "initiator" event? For instance, what if I have to listen for "a set of events to finish" before I can proceed with some processing?

Does Rebus allow you to model this requirement in some direct manner without needing an initiator message? Is it possible to "active a handler" only when 2 or more desired events have been "collected"?

The idea is similar to what you can do with an observable stream using for example Reactive Extensions. You can combine events from 2 unrelated streams and active a handler for every pair of event objects produced by the streams. With RX, you can:
- select the latest events from each stream every time one of the streams produces an event
- pair/combine each event from each source and broadcast the combination when they all become available
- pair/combine each event from each source and broadcast the combination as soon as one of them becomes available (send 'null' for the other ones or a default event)

It seems like saga can be useful to model scenarios like these but I'm not sure if it is currently possible to have a saga with "multiple initiators" or a similar concept that would allow for this type of communication.

Ideally, I'd love to be able to just have `IHandleMessages<Event1, Event2>` and then have the handler fired using some sort of configuration option to select the behavior as per the above (i.e. call this handler for every pair of such events in the order they are received).

**Comment by mookid8000** [comment]
> Does Rebus allow you to model this requirement in some direct manner without needing an initiator message? Is it possible to "active a handler" only when 2 or more desired events have been "collected"?

No 🙂 the thing is: You always receive and process one single message from the queue(*), But since you have a saga, it's easy to add multiple `IAmInitiatedBy<>` to it, e.g.

```csharp
public class YourSaga : Saga<YourSagaData>, IAmInitiatedBy<Event1>, IAmInitiatedBy<Event2>
{
    // ...
}
```
and then use the saga data to keep track of when you have received both events required for the flow to continue.

So to your question
> (...) what if I have to listen for "a set of events to finish" before I can proceed with some processing?

I can say: This is exactly the kind of correlation of related events a saga can help you implement. 🙂 


---
(*) Conceptually - in reality, you're probably receiving several in parallel, but in

**Comment by julealgon** [comment]
Very nice. I'd recommend updating the documentation to mention that `IAmInitiatedBy` can be implemented multiple times for the same Saga (that's not obvious from the text there).
