### ISSUE TITLE
Supporting pull-based workflows

### ISSUE THREAD

**Issue by julealgon** [rebus-org/Rebus#988]
Is there any way Rebus could support a pull-based strategy for retrieving messages, instead of relying on a background worker to simulate push-based events?

This week I went through a situation that caused me to reconsider Rebus as an alternative in one of our projects.

We have a scenario that has been running for quite a while that is using some custom abstractions to model queues, and it has 2 possible flows (i.e. implementations): 
- IBM-MQ flow for production
- MSMQ for local development

I wanted to leverage Rebus on this project since we are already using Rebus in another part of the system as a push for standardization in technologies and as a means to enable migration to NET Core (we intend to abandon the MSMQ path in favor of a more portable solution).

While I'm aware there is no built-in transport implementation for IBM-MQ, I figured I could try implementing that myself while basing the logic on other transports, like the MSMQ one. So far so good.

However, the biggest blocker for me was the change in how messages are handled in our current solution vs the way they are managed in Rebus. Our abstraction is done using a pull-based model, where code explicitly asks for messages in the queue and processes them. On the other hand, Rebus works as a push model, where messages are automatically received and pushed into handlers for processing.

This difference in interfaces made me hesitant to leverage Rebus in the project at this point, since adapting our interfaces to the new interfaces would mean considerable refactoring effort to change how our abstractions work.

As of now, I've postponed using Rebus and will investigate an incremental approach for allowing the migration in a smoother manner in the future. It would've been interesting if Rebus exposed a pull-based mechanism that I could use in the meantime that would allow me to start using the framework without requiring a complete redesign of the solution.

**Comment by mookid8000** [comment]
What does your code achieve by pulling the messages, and then handling them? I'm curious to hear why you wouldn't prefer to have messages handed to you... 🙂

**Comment by julealgon** [comment]
> What does your code achieve by pulling the messages, and then handling them? I'm curious to hear why you wouldn't prefer to have messages handed to you... 🙂

It is not a matter of preference at all. I _vastly_  prefer it push based whenever that's available.

The issue in this case is the migration effort. To change it, I'd have to change a _ton_ of code to transform from one into the other. It would be nice to have the option of doing this incrementally instead. At the end of the day, I'd still want to use the push-based approach, but I'd be able to make small changes towards it and be able to test those small increments. The fact that I am forced to do all of it in a single fell swoop is what complicates things.

**Comment by mookid8000** [comment]
This issue has been lying around for a long time, so I'm closing it now. 

If you want Rebus' help with a more pull-oriented way of receiving messages, I suggest you look at simply newing up one of Rebus' transports and call its `Receive` method.

But if the messages are non-Rebus messages, you'll probably get more resistance than you'll get help doing it like that.
