### ISSUE TITLE
Monitor service bus health using Rebus

### ISSUE THREAD

**Issue by smahapatra86** [rebus-org/Rebus#989]
Hi, 
This is not an issue, just trying to clarify one query.
I am using Rebus to send and receive messages from Azure service bus queue.
Wanted to check if there is a way on how we can do a health check on the service bus connection or service bus queue. This is to monitor the overall service bus health on Azure. Thanks in advance. :)

**Comment by mookid8000** [comment]
I don't know of any way to do that, besides using mechanisms built into Azure. It's easy e.g. to create dashboards in the Azure Portal showing various service bus metrics, which you could probably use to get an idea of whether things are working like they should.
