### ISSUE TITLE
Supporting cloudevents spec?

### ISSUE THREAD

**Issue by IlSocio** [rebus-org/Rebus#996]
Hello,
I'm wondering if there is any plan to introduce the support for the cloudevents specification in the future: https://cloudevents.io/

Thanks,
Marco.

**Comment by IlSocio** [comment]
to be honest, I'm not totally sure :)
currently, as part of my daily job, I'm looking for a way to improve interoperability across various services, which have been developed with different technologies and some of them defined a custom specification to encapsulate events.

By leveraging a common specification like cloudevents, we could improve interoperability across different libraries and technologies.
for instance, we could use nservicebus to publish an event on ASB and use rebus on the receiving side to handle it.
does it make sense to you?

**Comment by zejji** [comment]
This would certainly be an interesting as using a standard message envelope would allow for interoperability between .NET applications and applications written in other languages (or using other frameworks).

This article has quite a few useful examples: https://quarkus.io/blog/kafka-cloud-events/

**Comment by sabbadino** [comment]
If my memory doesn't fail .. the way rebus maps messages  can be easily mapped to a cloud event. (at least for asb, that's what I had a look into with as explorer)

**Comment by tystol** [comment]
Yeah I think this is just a custom implementation of [Rebus.Serialization.Json.ISerializer](https://github.com/rebus-org/Rebus/blob/master/Rebus/Serialization/Json/JsonSerializer.cs)

Should probably be a plugin, not core feature.

eg. Exact same thing here, but for MassTransit: 
https://github.com/riezebosch/MassTransit.CloudEvents

**Comment by glazkovalex** [comment]
> Hello, I'm wondering if there is any plan to introduce the support for the cloudevents specification in the future: https://cloudevents.io/
> 
> Thanks, Marco.

It seems to be implemented in the [CloudEventify](https://github.com/riezebosch/CloudEventify/tree/main) package.

**Comment by mookid8000** [comment]
If I understand correctly, [the CloudEventify package](https://github.com/riezebosch/CloudEventify) provides a Rebus serializer implementation that makes it possible to hook it up with CloudEvents - the [README](https://github.com/riezebosch/CloudEventify/blob/main/README.md) even has a nice example using Rebus.

Closing 🙂
